jina/executors/encoders/nlp/transformer.py
jina/executors/frameworks.py

resolves #387 
adapt the code blocks accordingly.

Docs executors code blocks 387

---

jina/executors/encoders/nlp/transformer.py
jina/executors/frameworks.py

resolves #389 
- make `_model`, `_tensor_func`, and `_sess_func` to lazy properties.

refactor(transformer): fix the potential troublemakers

---

jina/executors/crafters/nlp/split.py

doc(sentencizers): fix the docs

---

jina/executors/encoders/nlp/transformer.py

fix(encoders): fix the broken transformers

---

jina/drivers/helper.py

fix(drivers): fix the bug in handling empty chunks

---

jina/executors/__init__.py
jina/flow/__init__.py

fix(flow): fix the port_grpc bug

---

jina/executors/crafters/nlp/split.py

This wrong condition was showing a warning when the values were correct.

fix(executor): fix sign of condition

---

jina/executors/crafters/numeric/convert.py
jina/executors/crafters/numeric/io.py
tests/executors/crafters/numeric/convert.py
tests/executors/crafters/numeric/test_io.py

**Issue Link:** This commit does not refer to any issue or feature request
**Description:** In this commit, a numeric crafter is added to allow user to convert raw bytes into a numpy array, which is the input format for numeric encoder.

feat(executors): Add numeric crafter - ArrayConverter

---

.github/workflows/core-release.yml

Added on-release action for rebuilding and testing images

On-release action

---

.github/workflows/core-release.yml

Fixed ci dependencies after `--update-strategy` grid update.

ci: fix dependencies

---

jina/executors/encoders/image/bigtransfer.py

resolves #447 
commit [819902c](https://github.com/jina-ai/jina/commit/819902c45b528c0404114b4fab9419c9c0c307fa) has resolved this. This PR is only for the logging purpose.

feat(encoders): fix the bigtransfer encoders doc

---

jina/executors/crafters/nlp/split.py
jina/executors/crafters/numeric/io.py

According to jina.proto the length field of Chunk represents "the total number of chunks in the current document".

fix(crafters): fix numeric and jiebra crafters

---

jina/flow/__init__.py

fix(flow): update docstring in flow
resolves #481

fix(flow): update docstring in flow

---

docs/chapters/101/README.fr.md
docs/chapters/101/README.md
docs/chapters/flow/README.md

Please find some of my suggestions to improve the current documentation.

fix(docs): Updates in the 101 page and in the main flow documentation

---

docs/chapters/all_exec.md
jina/executors/crafters/nlp/split.py
tests/executors/crafters/nlp/split.py

I use this for pretty long text documents. Might be useful for others as well?

feat(crafters): add SlidingWindowSegmenter for nlp

---

jina/executors/encoders/audio/spectral.py
tests/executors/encoders/audio/test_spectral.py

MFCC and chromagram based audio encoders to extract timbral and harmonic features

feat(encoders): add spectral audio encoders

---

jina/__init__.py
jina/clients/python/grpc.py
jina/clients/python/io.py
jina/drivers/__init__.py
jina/drivers/control.py
jina/drivers/reduce.py
jina/excepts.py
jina/flow/__init__.py
jina/helper.py
jina/main/parser.py
jina/peapods/gateway.py
jina/peapods/pea.py
jina/peapods/pod.py
jina/peapods/zmq.py
jina/proto/jina.proto
jina/proto/jina_pb2.py
jina/resources/executors.base.all.yml
tests/executors/crafters/test_mime.py
tests/test_flow.py

second part of #504 
prep for #488

refactor: move num_part from args to proto

---

jina/logging/sse.py

This PR closes https://github.com/jina-ai/jina/issues/516 
Profile page is working now:

fix(logging): profile and log streams non-blocking

---

jina/executors/indexers/vector/faiss.py
jina/executors/indexers/vector/numpy.py

fix the bug in query with faiss

---

CHANGELOG.md
docs/chapters/101/README.md
jina/logging/sse.py

* New sections to give overview of WHAT Jina is and WHY neural search
* Rewrite of all content - improve English, add analogies
* Move YAML stuff to bottom - YAML only explains how to configure and not an "active agent" the way other things are
NOTE: I've put a few comments in bold: I need feedback on these from @hanxiao @nan-wang 
NEXT: Split into 101 (what, why, how get started) and 102 (how it all actually works)

docs(101): restructure, rewrite

---

jina/drivers/prune.py
tests/test_driver_prune.py
tests/yaml/test-prune-driver.yml

test(drivers): add test for prune driver

---

extra-requirements.txt
jina/executors/encoders/nlp/use.py
tests/executors/encoders/nlp/test_use.py

Added Google's Universal Sentence Encoder model to the nlp encoders.

feat(encoders): add universal sentence encoder

---

jina/executors/decorators.py
jina/executors/indexers/vector/faiss.py
tests/test_index_train.py

fix(indexer): is trained set on train call

---

jina/hubapi/docker.py
jina/main/parser.py
jina/peapods/pea.py
jina/peapods/pod.py
tests/test_flow.py
tests/test_hub.py

fix(driver): remove pub driver with post_hook

---

README.md

* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Grammatical and wording improvements for README, to make our initial user impression more professional
* **What is the current behavior?** (You can also link to an open issue here)
Some grammar and wording issues
* **What is the new behavior (if this is a feature change)?**
Better English
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
* **Other information**:
I have other (bigger) changes I want to make to the README, but let's get these fundamentals out of the way first

docs(readme): wording improvement

---

tests/test_gateway.py

Added a concurrency test for the REST gateway (https://github.com/jina-ai/jina/issues/573). Performance looks not too bad for me.

test(gateway): concurrency test for rest gateway

---

jina/helloworld/__init__.py
jina/helloworld/helper.py
jina/main/parser.py
tests/test_cli.py

The story began with a guy who ran the hello-world demo failed in the first three days. Support to those ones who are struggling to the unfriendly network.

feat(helloworld): add cli arg 'download-proxy'

---

docs/chapters/extend/mwu.rst

fix(docs): correct the mismatched parameter value

---

jina/executors/encoders/numeric/ica.py
tests/executors/encoders/numeric/test_ica.py

Added FastICA to numeric encoders
[https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html](url)

feat(encoder): add fastica to numeric encoders

---

README.md

updating banner with new slogan

chore: update readme gif banner

---

jina/flow/__init__.py

fix(flow): fix the mismatched arguments.
resolves #605

fix(flow): fix the mismatched arguments

---

Dockerfiles/pip.Dockerfile
tests/hub-mwu/Dockerfile
tests/mwu-encoder/Dockerfile
tests/test_container.py

Resolves https://github.com/jina-ai/jina/issues/608

test: use image built from pr in tests

---

jina/executors/encoders/image/customtfkeras.py
tests/executors/encoders/image/test_customtfkeras.py

Created a wrapper for any custom Keras models (image) which are not part of tensorflow.keras.applications : https://www.tensorflow.org/api_docs/python/tf/keras/applications

feat(executor): add image custom keras

---

jina/executors/encoders/nlp/transformer.py

Change for transformers >= 3.0.0

feat(encoder): transformers truncation strategy

---

tests/test_flow.py

I added tests for some endpoints. Stream endpoints are not yet covered, because its actually hard to test as they are hanging the connection

test(flow): improved log server tests

---

README.md

Just very minor tweaks from README on `master`. For larger changes I'll roll each change into a PR to make yes/no choices easier :)

docs(readme): small adjustments based on han's feedback

---

jina/drivers/encode.py
jina/flow/__init__.py
jina/helloworld/__init__.py
jina/helloworld/components.py

> Added **_UnaryEncoderDriver_**, inspired by **_UnarySegmentDriver_**. Useful for testing purposes and when no encoding is needed.
> Change name of method **_search_numpy_** to **search_ndarray** to match naming of the _**index_ndarray**_ counterpart
> Remove unused **_MySegmenter_** fro HelloWorld
These changes are needed to implement changes required for https://github.com/jina-ai/examples/pull/89

feat(examples): Add changes to implement Faiss Search examples

---

jina/executors/frameworks.py
jina/executors/indexers/vector/faiss.py

- Refactor how framework dependant executors set used devices
- Adda **BaseFaissExecutor**  to abstract how FAISS indexer can be moved to GPU

feat(frameworks): add faiss framework to be able to move index to gpu

---

jina/executors/indexers/vector/annoy.py
tests/executors/indexers/vector/test_annoy.py

Add search_k parameter to AnnoyIndexer

feat(indexer): add annoy search_k parameter

---

jina/executors/indexers/vector/ngt.py

Solves #657 
Make NGTIndexer inherit from BaseNumpyIndexer

refactor(ngt): make ngt inherit from basenumpyindexer

---

jina/drivers/control.py

I can't find where **PublishDriver** is used, if I am right and is not used, let's remove it

refactor(drivers): remove publishdriver

---

tests/unit/test_flow.py

Explicitly test that **flow** graphs have the expected configuration in terms of **socket types**.
**Warning**
Have not checked that the connections are the ones expected by the functional requirements. But this must help us to validate future changes that may break these configurations.

tests(flow): test socket configuration of pods and peas in flow

---

jina/executors/indexers/vector/milvus.py

Fixes #676. It imports **MilvusDBHandler** in **post_init** which is the one import **milvus** dependency

fix(milvus): move import milvusdbhandler which imports milvus

---

tests/unit/flow/test_flow.py
tests/unit/flow/test_flow_example_face.py
tests/unit/flow/test_flow_example_faiss.py
tests/unit/flow/test_flow_except.py
tests/unit/yaml/examples/faces/flow-index.yml
tests/unit/yaml/examples/faces/flow-query.yml
tests/unit/yaml/examples/faces/yaml/craft-flip.yml
tests/unit/yaml/examples/faces/yaml/craft-load.yml
tests/unit/yaml/examples/faces/yaml/craft-normalize.yml
tests/unit/yaml/examples/faces/yaml/customized_executors.py
tests/unit/yaml/examples/faces/yaml/encode.yml
tests/unit/yaml/examples/faces/yaml/index-chunk.yml
tests/unit/yaml/examples/faces/yaml/index-doc.yml
tests/unit/yaml/examples/faiss/flow-index.yml
tests/unit/yaml/examples/faiss/flow-query.yml
tests/unit/yaml/examples/faiss/yaml/craft.yml
tests/unit/yaml/examples/faiss/yaml/encode.yml
tests/unit/yaml/examples/faiss/yaml/index-chunk.yml
tests/unit/yaml/examples/faiss/yaml/index-doc.yml

Previous to #667 
Added tests checking the Flow structure of tests from face-db and faiss. No more tests have been added because of https://github.com/jina-ai/jina/pull/667#issuecomment-660881099.
The intention of this PR is to have better security that #667 does not break real use-cases

tests(flow): add flows from examples to test

---

jina/clients/python/io.py
jina/flow/__init__.py

Fixes #674 
Also improves docs a bit

fix(input_files): add error handling for bad reading mode, fix docs

---

docs/chapters/dashboard/index.md
docs/chapters/flow/index.md
docs/chapters/restapi/index.rst
jina/main/api.py
jina/main/parser.py
jina/resources/helloworld.flow.index.yml
jina/resources/helloworld.flow.query.yml
tests/unit/flow/test_flow_index.py

Solves #694 
It also changes that in api **flow(args)** should be called with --yaml-path

fix(api): api should use yaml path

---

docs/chapters/101/README.de.md

docs(101): fix german typo

---

jina/drivers/search.py
jina/executors/indexers/keyvalue/leveldb.py
jina/executors/indexers/keyvalue/proto.py
tests/unit/drivers/test_kv_search_driver.py
tests/unit/drivers/test_vector_search_driver.py

Add unittests for **VectorSearchDriver** and **KVSearchDriver**

test(drivers): add search driver tests

---

jina/drivers/craft.py
tests/unit/drivers/test_chunk2doc_rank_drivers.py
tests/unit/drivers/test_craft_driver.py
tests/unit/drivers/test_encoder_driver.py
tests/unit/drivers/test_kv_search_driver.py
tests/unit/drivers/test_vector_search_driver.py

Add unittest for **CraftDriver**

test(drivers): add test for craft driver

---

jina/clients/python/request.py
jina/counter.py
jina/drivers/craft.py
jina/executors/frameworks.py
jina/proto/jina.proto
tests/unit/drivers/test_segmenter_driver.py
tests/unit/test_client.py

Add unittests fro `SegmentDriver`

test(drivers): add test for segment driver

---

README.md
jina/drivers/reduce.py
jina/flow/__init__.py
jina/main/parser.py
jina/peapods/pod.py
jina/resources/executors._concat.yml
jina/resources/executors._pass.yml
jina/resources/helloworld.reduce.yml
tests/unit/drivers/test_concat_driver.py
tests/unit/drivers/test_reduce_all_driver.py
tests/unit/executors/crafters/test_mime.py
tests/unit/flow/test_flow.py
tests/unit/flow/test_flow_except.py
tests/unit/flow/test_flow_merge.py
tests/unit/test_client.py
tests/unit/test_container.py
tests/unit/test_driver_yaml.py
tests/unit/test_echostream.py
tests/unit/test_gateway.py
tests/unit/test_index.py
tests/unit/test_quant.py

**Changes**
- add `ConcatEmbedDriver` and its unittest
- `_pass` is an alias of `_forward`
- `Flow.join()` now support customized `name` and `uses`

feat(driver): add concat embedding driver

---

jina/executors/encoders/helper.py
jina/executors/encoders/nlp/transformer.py
jina/helper.py
jina/peapods/remote.py
tests/unit/executors/encoders/nlp/test_helper.py

add typing in some files, also created a test for jina.executors.encoders.helper class (only for reduce_mean function,since the return value in other functions in helper are the same)

feat: add typing in some functions with corresponding test

---

README.md

Fixing some wording issues in recent revisions to README

fix: wording

---

README.md

Allcontributors requires a **Contributors** section. I added it as a new section (since I don't know how destructive the allcontributors bot will be). Once I've used the bot to add a new contributor and can confirm it's all okay, I'll look into merging contributors/contributing sections

feat: contributors draft section

---

README.md

Vim somehow undid my section addition. I've re-added it here

fix: add missing section

---

tests/unit/drivers/querylang/test_querylang_drivers.py
tests/unit/drivers/querylang/test_slice_ql.py

Example on how to `test` a class without the use of `Flows`. 
Also introduce an example using a really complex `recursive document structure`

test: separate test for sliceql

---

jina/executors/crafters/image/flip.py
tests/unit/executors/crafters/image/test_flip.py

- Add support for horizontal flip and vertical flip of images in crafters.

feat(crafter): add flip image crafters

---

jina/helper.py
tests/unit/test_helper.py

cached_property decorator was not retrieving from the right key
skip

fix(helper): cached_property decorator fixed

---

jina/drivers/__init__.py
tests/unit/drivers/querylang/test_querylang_drivers.py
tests/unit/drivers/yaml/mockencoder-mode1.yml
tests/unit/drivers/yaml/mockencoder-mode2.yml
tests/unit/flow/test_flow.py
tests/unit/flow/yaml/mockencoder-mode1.yml
tests/unit/flow/yaml/mockencoder-mode2.yml
tests/unit/flow/yaml/numpy-indexer-1.yml
tests/unit/flow/yaml/numpy-indexer-2.yml

fix(drivers): fix the default value for depth_level 814

---

docs/chapters/flow/index.md

Just a few fixes for #812 to simplify wording and improve formatting.
@JoanFM Asking you to review, since you wrote it in the first place and you can see if I reworded wrongly :)

docs(flow): wording, formatting

---

jina/drivers/__init__.py
jina/drivers/convert.py
jina/drivers/craft.py
jina/drivers/encode.py
jina/drivers/index.py
jina/drivers/querylang/__init__.py
jina/drivers/querylang/filter.py
jina/drivers/querylang/reverse.py
jina/drivers/querylang/select.py
jina/drivers/querylang/slice.py
jina/drivers/querylang/sort.py
jina/drivers/rank.py
jina/drivers/reduce.py
jina/drivers/search.py
tests/unit/drivers/querylang/queryset/test_queryset.py
tests/unit/yaml/examples/faiss/yaml/encode.yml

- Added some docummentation for some classes
- Move test_queryset to its dedicated folder in tests/unit
- Enforce the usage of `_is_apply` and `_is_apply_all` to all Drivers

docs: improve documentation of query lang drivers

---

docs/chapters/helloworld/index.rst

update hello-world docs

---

README.md

Added my [new example](https://github.com/jina-ai/examples/tree/master/my-first-jina-app)

chore(readme): add new example

---

jina/executors/indexers/vector.py

fix: add key mappings to post init to avoid serialize

---

.github/workflows/cd.yml
.github/workflows/ci.yml
jina/counter.py
jina/docker/checker.py
jina/docker/hubio.py
jina/main/parser.py
tests/unit/hub-mwu-bad/bad-dockerfile/Dockerfile
tests/unit/hub-mwu-bad/bad-dockerfile/README.md
tests/unit/hub-mwu-bad/bad-dockerfile/manifest.yml
tests/unit/hub-mwu-bad/bad-dockerfile/mwu_encoder.py
tests/unit/hub-mwu-bad/bad-dockerfile/mwu_encoder.yml
tests/unit/hub-mwu-bad/bad-pythonfile/Dockerfile
tests/unit/hub-mwu-bad/bad-pythonfile/README.md
tests/unit/hub-mwu-bad/bad-pythonfile/manifest.yml
tests/unit/hub-mwu-bad/bad-pythonfile/mwu_encoder.py
tests/unit/hub-mwu-bad/bad-pythonfile/mwu_encoder.yml
tests/unit/hub-mwu-bad/missing-dockerfile/README.md
tests/unit/hub-mwu-bad/missing-dockerfile/manifest.yml
tests/unit/hub-mwu-bad/missing-dockerfile/mwu_encoder.py
tests/unit/hub-mwu-bad/missing-dockerfile/mwu_encoder.yml
tests/unit/hub-mwu-bad/missing-manifest/Dockerfile
tests/unit/hub-mwu-bad/missing-manifest/README.md
tests/unit/hub-mwu-bad/missing-manifest/mwu_encoder.py
tests/unit/hub-mwu-bad/missing-manifest/mwu_encoder.yml
tests/unit/test_docker.py
tests/unit/test_hub.py

fix(docker): fix the error checking

---

docs/chapters/yaml/yaml.rst
jina/drivers/craft.py
jina/executors/compound.py

docs(yaml): change doc for driver syntex

---

README.md

After speaking with @BingHo1013, I'm making a series of edits to the README. For the sake of convenience, I'm starting out with small stuff (which should be straightforward to approve) and when each PR is merged I'll start a new branch for the next round of (bigger) changes.
Since this is the first round of changes in Sep 2020, I've called the branch `fix-readme-2020-09a` - later branches will be tagged `b`, `c`, etc.
This PR just contains very small fixes and expands cookiecutter description

fix(README): wording, expand cookiecutter

---

jina/executors/encoders/helper.py

fix: changed index type in reduce code

---

tests/unit/executors/encoders/numeric/test_reduce.py

feat: added unit test cases to reduce code

---

docs/chapters/cli/exit.rst
docs/chapters/envs.rst
docs/chapters/faq/dev.rst
docs/chapters/helloworld/index.rst
docs/chapters/install/autocomplete.md
docs/chapters/install/upgrade.md
docs/chapters/install/via-docker.md
docs/chapters/install/via-pip.md
docs/index.rst

Clarification and fixes for English. Only other change was converting a markdown link to RST link in an RST file (I've never used RST before today, so may need to check that)

Docs english fixes

---

docs/chapters/helloworld/index.rst

External link was exposed due to syntax error.

docs: correct syntax issue in helloworld

---

extra-requirements.txt
jina/peapods/pea.py
tests/integration/issues/867/test_close_executor.py

It mocks Pea to have Old Behavior and asserts that it did not work properly

tests: improve issue 867 testing

---

docs/template/layout.html

sorry, the best I could do within quickfix limits.
https://github.com/jina-ai/jina/issues/895

docs: remove local floating navbar

---

jina/drivers/__init__.py
jina/drivers/search.py

Hey @maximilianwerk  may this idea solve the issue?

fix: add recur_on param back

---

jina/clients/python/request.py
jina/drivers/search.py
tests/integration/high_order_matches/test-adjacency-integrated.yml
tests/unit/drivers/querylang/test_querylang_reader.py
tests/unit/test_index.py

Not working because SearchRequest does not have `top_k`, so how do we interpeet the message from `jinabox`?
Fixes #942

fix: set request top_k, needed to be read by jinabox

---

docs/chapters/io/index.md

[opi.txt](https://github.com/jina-ai/jina/files/5215005/opi.txt)

fix(io-functions): wording

---

jina/peapods/pea.py

I spot a debugging message leftover

refactor: change error message if interrupting pea loop

---

jina/flow/__init__.py

Avoid having Flow locked just for problems in sse server. Let it finish independently

fix: set start_sse_server daemon to True

---

tests/unit/drivers/test_recursive_traversal.py

test(drivers): add tests for illustrating the issues

---

README.md

Updated the tutorial section to be in sync with the currently running examples. Hope I got the buzzwords right.

docs: update tutorial collection

---

jina/drivers/convert.py

Links to Jira:
https://jinaai.atlassian.net/browse/JINACORE-215
Adding `NdArray` to `URI` Driver.

feat: add ndarray to uri driver

---

jina/docker/database.py

- Improves documentation for `database.py`
- Adds functionality for `find_many` : retrieving multiple documents in MongoDB

fix: add database function find_many to mongodb

---

docs/chapters/io/index.md

docs: migrate flow intro from example to docs

---

jina/drivers/rank.py
tests/integration/level_depth/test_search_different_depths.py
tests/integration/level_depth/yaml/rank.yml
tests/unit/drivers/test_chunk2doc_rank_drivers.py
tests/unit/drivers/test_collect_matches_rank_driver.py
tests/unit/drivers/test_matches2doc_rank_drivers.py

feat: added tree traversal for ranker

---

jina/resources/helloworld.reduce.yml

Fix the not-running integration test.

fix: fixed double argument setting of use_tree_traversal

---

jina/drivers/index.py
tests/integration/level_depth/yaml/index-chunk.yml
tests/integration/level_depth/yaml/index-doc.yml
tests/unit/flow/test_flow_multimode.py
tests/unit/flow/yaml/numpy-indexer-1.yml
tests/unit/flow/yaml/numpy-indexer-2.yml

Switching to tree traversal for index driver.

feat: switched to tree traversal for index driver

---

jina/drivers/__init__.py
jina/drivers/querylang/sort.py
jina/drivers/rank.py
jina/drivers/reduce.py
jina/drivers/search.py
jina/resources/executors.requests.CompoundIndexer.yml
jina/resources/helloworld.reduce.yml
tests/integration/high_order_matches/test-adjacency-integrated.yml
tests/integration/high_order_matches/test-adjacency.yml
tests/integration/level_depth/yaml/index-chunk.yml
tests/unit/drivers/test_kv_search_driver.py

Tree traversal for search driver

feat: added tree traversal for search driver

---

jina/drivers/convert.py
jina/drivers/craft.py
jina/drivers/reduce.py
tests/unit/drivers/test_concat_driver.py

Converter, Crafter and Reducer use tree traversal now.

Feat tree traversal crafter

---

jina/drivers/encode.py
tests/unit/drivers/yaml/mockencoder-mode1.yml
tests/unit/drivers/yaml/mockencoder-mode2.yml
tests/unit/flow/yaml/mockencoder-mode1.yml
tests/unit/flow/yaml/mockencoder-mode2.yml

- Fix encode driver for `tree traversal`.
- `mode yaml` files for encoder unit tests

Fix encoder driver for tree traversal

---

tests/integration/incremental_indexing/docindexer.yml
tests/integration/incremental_indexing/test_incremental_indexing.py
tests/integration/incremental_indexing/vectorindexer.yml

TDD to have incremental indexing. These tests should pass (maybe the assertion can change and not assert on the `_size` of the indexers). Maybe other tests must be added.
The documents that are already present in the index should not be added.

tests: add skipped tests for incremental indexing

---

jina/drivers/rank.py
jina/executors/rankers/__init__.py
tests/unit/drivers/test_chunk2doc_rank_drivers.py
tests/unit/drivers/test_collect_matches_rank_driver.py
tests/unit/drivers/test_matches2doc_rank_drivers.py

Fixes the float int conversion error that happened for the new hashes.

fix: fixed the int float conversion collision between hash and idy

---

jina/__init__.py
jina/drivers/__init__.py
jina/drivers/convert.py
jina/drivers/craft.py
jina/drivers/encode.py
jina/drivers/index.py
jina/drivers/querylang/filter.py
jina/drivers/querylang/reverse.py
jina/drivers/querylang/select.py
jina/drivers/querylang/slice.py
jina/drivers/querylang/sort.py
jina/drivers/rank.py
jina/drivers/reduce.py
jina/drivers/search.py
jina/flow/__init__.py
tests/unit/drivers/test_recursive_traversal_tree.py

This is the final PR in the tree traversal task. After this the old traversal is completely removed.

refactor: removed old traversal

---

jina/drivers/cache.py
jina/drivers/index.py
jina/executors/indexers/__init__.py
jina/executors/indexers/cache.py
tests/unit/drivers/test_cache_driver.py

Bloom filter to test whether a doc is observed or not based on its ``doc.id``

feat(driver): add CacheIndexer and its Driver

---

jina/executors/encoders/frameworks.py

Following #1065 , this should be added for some executors in the hub to be able to be built (jina-ai/jina-hub#373)

fix: check existence of model path

---

tests/unit/clients/python/test_client.py

A bit clean up of the client test.

test: refactor python client test

---

README.pt_br.md

This PR adds Brazilian Portuguese translation for the README.md file. The issue for this is #1058

docs: add portuguese translation for readme

---

cli/autocomplete.py
jina/enums.py
jina/flow/__init__.py
jina/helper.py
jina/parser.py
tests/unit/flow/test_flow_eval_pod.py

- `.gather_inspect()` can be used to manually collect inspect pods
- `--inspect` is added to Flow CLI/API, allowing `HANG`, `REMOVE`, `COLLECT` three modes, 
- `HANG`: keep those pods where they are
- `REMOVE`: remove all pods before `.build()`
- `COLLECT`: all inspect pods are auto-collected via `.gather_inspect()` before `.build()`
```python
f = Flow(no_inspect=True).add(name='p1').add(name='p2', needs='gateway').inspect().needs(['p1', 'p2']).plot()
f = Flow().add(name='p1').add(name='p2', needs='gateway').inspect().needs(['p1', 'p2']).plot()
```
```python
f = Flow().add(name='p1').add(name='p2', needs='gateway').needs(['p1', 'p2']).inspect().plot()
```
```python
f = Flow().add(name='p1', parallel=3).inspect().add(name='p2', needs='gateway').needs(['p1', 'p2']).inspect().plot()
``` …

feat(flow): inspect pods are collected before gateway

---

jina/peapods/head_pea.py
jina/peapods/pea.py
jina/peapods/tail_pea.py

a test PR for testing codeowners and PR reviewers assignment

style: fix line space

---

jina/drivers/evaluate.py
jina/executors/evaluators/__init__.py
jina/executors/evaluators/craft/__init__.py
jina/executors/evaluators/craft/nlp/__init__.py
jina/executors/evaluators/craft/nlp/length.py
jina/executors/evaluators/encode/__init__.py
jina/executors/evaluators/encode/cosine.py
jina/executors/evaluators/encode/euclidean.py
jina/executors/evaluators/rank/__init__.py
jina/executors/evaluators/rank/precision.py
jina/executors/evaluators/rank/recall.py
jina/resources/executors.requests.BaseCraftingEvaluator.yml
jina/resources/executors.requests.BaseEncodingEvaluator.yml
tests/unit/drivers/test_craftevaluation_driver.py
tests/unit/drivers/test_encodingevaluation_driver.py
tests/unit/drivers/test_rankingevaluation_driver.py
tests/unit/executors/evaluators/craft/nlp/test_length.py
tests/unit/executors/evaluators/encode/test_cosine.py
tests/unit/executors/evaluators/encode/test_euclidean.py

- Added new `EncodeEvaluationDriver` and `CraftEvaluationDriver`
- Added new family of `BaseEncodingEvaluator` executors family with `CosineEvaluator` and `EuclideanEvaluator` (which sould be later moved to the `hub`)
- Added new family of `BaseCraftingEvaluator` executors family with `BaseNlpCraftingEvaluator` and `LengthStringEvaluator`  (which sould be later moved to the `hub`, or removed because it is just a dummy example)

feat: add evaluation encoder and crafter executors and drivers

---

tests/unit/docker/test_helper.py

Add missing tests [here](https://codecov.io/gh/jina-ai/jina/src/master/jina/docker/helper.py).

test: add docker helper test

---

jina/flow/__init__.py
jina/peapods/pod.py
tests/unit/flow/test_flow_before_after.py
tests/unit/flow/test_flow_visualization.py

- `plot` now support before & after
- `plot(img_type=)` is removed, `img_type` is inferred from the suffix of the filename
```python
f = Flow().add(uses_before='_pass', uses_after='_pass', name='p1',).plot()
```
```python
f = Flow().add(uses_before='_pass', name='p1',).plot()
```
```python
f = Flow().add(uses_after='_pass', name='p1',).plot()
```

feat(flow): add plot for uses before after

---

jina/docker/hubapi.py
jina/docker/hubio.py
jina/parser.py
tests/unit/docker/test_hub_build.py
tests/unit/docker/test_hub_list.py
tests/unit/docker/test_hubapi.py

refactor(hubio): remove the dependency of requests from list

---

tests/unit/proto/test_protobuf.py

A bit cleanup of `test_protobuf.py`.

test: take out jinatestcase from protobuf test

---

README.uk.md

docs: add ukrainian translation for readme

---

jina/docker/hubapi.py

feat(cli): show local version side by side

---

jina/drivers/evaluate.py
jina/executors/evaluators/rank/recall.py
tests/integration/evaluation/rank/test_evaluation.py
tests/unit/drivers/test_rankingevaluation_driver.py
tests/unit/executors/evaluators/rank/test_precision.py
tests/unit/executors/evaluators/rank/test_recall.py

That should fix #1123 . The for loop was mixed up.

Fix recall calculation

---

jina/drivers/rank.py

- Add some information in ranker drivers docstrings. 
- Change default `taversal_paths` of `Collect2Matches`

docs: change docstring of rank drivers

---

README.md

Added some communication in README for windows support as suggested in [https://github.com/jina-ai/examples/issues/246](url)

docs: add windows support communication to readme

---

CODEOWNERS

chore: add nan as the code owner

chore: add nan as the code owner

---

docs/chapters/prevent_duplicate_indexing/index.rst

docs: fix the format issues in `prevent_duplicate_indexing.rst`

docs: fix the format issues

---

jina/docker/hubio.py
jina/excepts.py
jina/executors/encoders/frameworks.py
jina/peapods/pea.py
tests/integration/hub_usage/dummyhub_pretrained/__init__.py
tests/unit/executors/encoders/test_frameworks.py
tests/unit/flow/test_flow_except.py

`cell` is the idiom in Mindspore context

refactor(encoder): change get_model to get_cell mindspore idiom

---

CODEOWNERS

@maximilianwerk @nan-wang I can remove you if you want as well

chore: remove Nan, Max and Joan as codeowners of modules

---

docs/chapters/prevent_duplicate_indexing/index.rst

docs: fix codeblock and filename highlights

docs: fix codeblock and filename highlights

---

CONTRIBUTING.md

Based on discussion in Slack group, adjusted testing section

fix(contributing): switch testing to pytest

---

jina/drivers/__init__.py
jina/drivers/control.py
jina/drivers/reduce.py
jina/executors/__init__.py
jina/executors/decorators.py
jina/proto/message/__init__.py
jina/resources/executors._concat.yml
jina/resources/executors._merge.yml
jina/resources/executors._merge_all.yml
jina/resources/executors._merge_eval.yml
tests/unit/drivers/test_concat_driver.py
tests/unit/drivers/test_reduce_all_driver.py
tests/unit/test_helper.py

WIP, otherwise `ReduceDriver` is orthogonal to all other Drivers.
also fixing `wrap_func` in `register_class`

refactor(driver): move reduce logic to BaseDriver

---

.github/workflows/cd.yml
.github/workflows/core-autocommit.yml
.github/workflows/release.yml

fix this: https://github.com/jina-ai/jina/runs/1362306125?check_suite_focus=true

ci: fix git pull and dev-bot msg

---

CONTRIBUTING.md

docs(test): improved documentation

---

tests/unit/test_index.py

Take out `JinaTestCase` from `test_index.py`.

test: take out jina test case from test index

---

README.md

Making coherence for brand slogan

chore: update readme slogan

---

.github/workflows/test-examples.yml

Adding the southpark distributed test to jina. The following needs to be done before merging:

test: southpark distributed

---

jina/drivers/__init__.py
jina/drivers/cache.py
jina/drivers/convert.py
jina/drivers/craft.py
jina/drivers/encode.py
jina/drivers/evaluate.py
jina/drivers/index.py
jina/drivers/multimodal.py
jina/drivers/predict.py
jina/drivers/querylang/filter.py
jina/drivers/querylang/queryset/lookup.py
jina/drivers/querylang/reverse.py
jina/drivers/querylang/select.py
jina/drivers/querylang/slice.py
jina/drivers/querylang/sort.py
jina/drivers/rank.py
jina/drivers/reduce.py
jina/drivers/search.py

feat: replace iterable with sequence as hints

---

jina/__init__.py
jina/checker.py
jina/clients/python/grpc.py
jina/clients/python/helper.py
jina/docker/hubio.py
jina/executors/__init__.py
jina/executors/compound.py
jina/executors/decorators.py
jina/executors/requests.py
jina/flow/__init__.py
jina/flow/builder.py
jina/helper.py
jina/logging/profile.py
jina/parser.py
jina/peapods/pea.py
jina/peapods/zmq.py
jina/proto/message/__init__.py
setup.py
tests/unit/docker/hub-mwu-bad/bad-dockerfile/mwu_encoder.py
tests/unit/docker/hub-mwu-bad/bad-pythonfile/mwu_encoder.py
tests/unit/docker/hub-mwu-bad/fail-to-start/mwu_encoder.py
tests/unit/docker/hub-mwu-bad/missing-dockerfile/mwu_encoder.py
tests/unit/docker/hub-mwu-bad/missing-manifest/mwu_encoder.py
tests/unit/docker/hub-mwu/mwu_encoder.py
tests/unit/test_index.py
tests/unit/test_index_remote.py
tests/unit/test_yamlparser.py

Closes #1240 
- tested by running various examples
- used PyCharm automatic replace f-string. This worked in most cases. Some required manual rewriting

style: use f-strings instead of %s-formatting

---

tests/unit/test_index.py
tests/unit/test_index_remote.py
tests/unit/test_yamlparser.py
tests/unit/yaml/test-index-remote.yml

@bwanglzu I found some random errors

test: refactor test index test

---

docs/chapters/flow/index.md

Closes #1255 
Short overview of the "score" field based on those discussions and a look through the code

docs: add note on 'score' field

---

tests/integration/test_helloworld.py

Removed `JinaTestCase` and added tmpdir in tests.

test: helloworld without JinaTestCase and local directories

---

tests/unit/executors/indexers/test_binary_indexer.py
tests/unit/peapods/test_container.py

test: remove duplicated random_docs

test: remove duplicated random_docs

---

.github/workflows/tag.yml
.github/workflows/update_hub.yml
scripts/jina-hub-update.py

* add new step to `tag` flow that
* clones jina hub
* attempts to bump version of jina to current
* opens PR to jina hub
* performs checks
* if checks pass commit with new version
* bumps minor version of hub module too
Need input on 
* how should we test the workflow from this PR? The workflow is only triggered on a `tag` or if it's part of master? It works locally using [https://github.com/nektos/act](https://github.com/nektos/act) @deepankarm

Ci update hub

---

README.md

Revamp of README learn section 
- updated the title to Learn,
- completed the description of each links
- added one line with links to our Blog & Han's blog when people are up for more reading 
- restructured the Documentation section (remove links since it's already in Learn)

docs readme learn revamp

---

.github/workflows/cd.yml
.github/workflows/nightly.yml
.github/workflows/tag.yml

ci: changing env vars for gh action

---

docs/chapters/remote/run-remote-pod-console.md
docs/chapters/remote/run-remote-pod-flow.md
docs/chapters/remote/run-remote-pod-jina.md

docs(remote): fix the dead links

docs(remote): fix the dead links

---

jina/drivers/multimodal.py
jina/types/document/__init__.py
jina/types/document/helper.py
tests/unit/drivers/test_kv_search_driver.py
tests/unit/drivers/test_multimodal_driver.py
tests/unit/drivers/test_segmenter_driver.py
tests/unit/types/test_document.py

- Adapt for **test_kv_search_driver.py**
- Adapt **test_segment_driver.py** and add weights property to document primitive type 
- Fix **test_rankingevaluation_driver.py** as per get back assert
- Fix **test_multimodal_driver.py**

test: help fix kv search driver test

---

docs/chapters/extend/executor.rst
docs/chapters/install/on-wsl.md

docs: add docs for the classifier, evaluator, and the windows installation

docs: add classifier wsl

---

docs/chapters/hub/build-pod-image.md
docs/chapters/hub/use-your-pod.md
jina/resources/hub-builder-success/index.html

Replace unsupported `--image` argument with `--uses`.

fix: replace image with uses

---

docs/chapters/install/on-x.md
docs/chapters/install/via-pip.md
docs/index.rst

docs: fix wsl

---

tests/integration/evaluation/rank/test_evaluation.py
tests/integration/evaluation/test_evaluation_from_file.py

refactor: refactor the test for evaluation

refactor: refactor the test for evaluation

---

jina/clients/python/request.py
tests/integration/issues/github_976/test_topk_rest_api.py

fix: topk priority

---

README.md

1. import the numpy
2. fix the "TypeError: 'builtin_function_or_method' object is not subscriptable"

docs: fix the type error

---

jina/executors/decorators.py
jina/executors/indexers/vector.py
tests/integration/issues/github_1229/test_sharding_empty_index.py
tests/integration/issues/github_1229/vectorindexer.yml
tests/unit/executors/indexers/test_numpyindexer.py

Fixes https://github.com/jina-ai/jina/issues/1229

fix: handle empty shards

---

tests/__init__.py
tests/unit/__init__.py
tests/unit/clients/python/test_io.py
tests/unit/docker/test_helper.py
tests/unit/docker/test_hub_build.py
tests/unit/drivers/querylang/queryset/test_queryset.py
tests/unit/drivers/test_cache_driver.py
tests/unit/drivers/test_concat_driver.py
tests/unit/drivers/test_recursive_traversal_tree.py
tests/unit/drivers/test_reduce_all_driver.py
tests/unit/executors/indexers/test_numpyindexer.py
tests/unit/executors/test_comp_exec.py
tests/unit/executors/test_decorators.py
tests/unit/executors/test_route_exec.py
tests/unit/flow/test_flow.py
tests/unit/flow/test_flow_example_face.py
tests/unit/flow/test_flow_example_faiss.py
tests/unit/flow/test_flow_index.py
tests/unit/flow/test_flow_merge.py
tests/unit/flow/test_flow_multimode.py
tests/unit/flow/test_flow_visualization.py
tests/unit/logging/test_logging.py
tests/unit/peapods/remote/test_jinad.py
tests/unit/peapods/test_container.py
tests/unit/test_driver_yaml.py
tests/unit/test_exectype.py
tests/unit/test_index.py
tests/unit/test_index_remote.py
tests/unit/test_workspace.py
tests/unit/test_yamlparser.py

Issue: https://github.com/jina-ai/jina/issues/1349

chore: use pathlib instead of os.path in all unit tests

---

tests/integration/eval_flow/test_flow_eval_pod.py
tests/integration/evaluation/rank/test_evaluation.py
tests/integration/evaluation/test_evaluation_from_file.py
tests/integration/gateway_non_blocking/test_gateway_non_blocking.py
tests/integration/high_order_matches/test_adjacency.py
tests/integration/issues/github_1072/test_queryset.py
tests/integration/issues/github_1229/test_sharding_empty_index.py
tests/integration/issues/github_929/test_shelfindexer.py
tests/integration/issues/github_969/test_messages_different_types.py
tests/integration/issues/github_976/test_topk.py
tests/unit/clients/python/test_on_err.py
tests/unit/drivers/querylang/test_querylang_drivers.py
tests/unit/drivers/querylang/test_querylang_reader.py
tests/unit/drivers/test_concat_driver.py
tests/unit/drivers/test_eval_collect_driver.py
tests/unit/drivers/test_reduce_all_driver.py
tests/unit/executors/indexers/test_binary_indexer.py
tests/unit/flow/test_flow.py
tests/unit/flow/test_flow_except.py
tests/unit/flow/test_flow_merge.py
tests/unit/flow/test_flow_skip.py
tests/unit/test_gateway.py
tests/unit/test_index.py

refactor: ensure callback called in tests

---

jina/helper.py
jina/peapods/peas/gateway/grpc/async_call.py

fix: jupyter asyncio

---

jina/executors/indexers/__init__.py
jina/executors/indexers/vector.py
tests/unit/executors/indexers/test_numpyindexer.py

Adding update & delete ops to NumpyIndexer
- Faiss and Annoy use masking process --> separate PRs once this is merged https://github.com/jina-ai/jina-hub/pull/1280
- more testing?

feat: numpy indexer update/delete

---

docs/_static/main.css
docs/template/footer.html

docs: add footer to docs

---

.github/workflows/ci.yml
.github/workflows/commit-lint.yml
.github/workflows/label-pr.yml
.github/workflows/latency-tracking.yml

upstream problem: https://github.com/wagoid/commitlint-github-action/issues/66

ci: revert ci commit lint on pull_request_target

---

docs/index.rst

Polishing section names. Additional work will be done after docs meeting later in week

docs(index): improve section names

---

jina/docker/hubapi.py
tests/unit/docker/test_hubapi.py

refactor unit tests in  hubapi

refactor unit tests in  hubapi

---

jina/types/document/__init__.py
jina/types/document/multimodal.py
tests/unit/types/document/test_document.py

refactor: doc content hash

---

jina/types/document/__init__.py
tests/unit/types/document/test_document.py

refactor(tests): refactor unit tests for document hashing

refactor(tests): refactor unit tests for document hashing

---

daemon/__init__.py
daemon/api/endpoints/__init__.py
daemon/api/endpoints/flow.py
daemon/api/endpoints/pea.py
daemon/api/endpoints/pod.py
tests/conftest.py
tests/jinad/unit/api/endpoints/test_flow.py
tests/jinad/unit/api/endpoints/test_pea.py
tests/jinad/unit/api/endpoints/test_pod.py

feat(daemon): endpoints for params expose and logging public address

---

jina/docker/hubapi/local.py
jina/docker/hubapi/remote.py
jina/docker/hubio.py
jina/resources/hubapi.yml
tests/integration/test_helloworld.py
tests/unit/docker/test_hub_list.py
tests/unit/docker/test_hubapi.py

Changes done according to https://github.com/jina-ai/cloud-ops/issues/67
Fixes https://github.com/jina-ai/jina/issues/1585 and https://github.com/jina-ai/cloud-ops/issues/27

fix(hubapi): cli changes for new get images invocation

---

jina/executors/__init__.py
tests/unit/test_exectype.py

fix: register class should not only depend on name

---

docs/chapters/flow/index.md
docs/chapters/hub/publish-your-pod-image.md
docs/chapters/remote/create-remote-flow.md
docs/chapters/remote/create-remote-pod-console-jinad.md
docs/chapters/remote/create-remote-pod-flow.md
docs/chapters/remote/run-remote-pod-console.md

Some minor fixes I did while reading a bit through the docs

docs: some cleanup

---

README.md

docs: fix a bug in code blocks on README

docs: fix a bug in code blocks on README

---

README.md
jina/excepts.py
jina/parsers/__init__.py
jina/parsers/base.py
jina/parsers/check.py
jina/parsers/client.py
jina/parsers/export_api.py
jina/parsers/flow.py
jina/parsers/helloworld.py
jina/parsers/helper.py
jina/parsers/hub/build.py
jina/parsers/hub/list.py
jina/parsers/hub/login.py
jina/parsers/hub/new.py
jina/parsers/hub/pushpull.py
jina/parsers/logger.py
jina/parsers/peapods/base.py
jina/parsers/peapods/pea.py
jina/parsers/peapods/pod.py
jina/parsers/peapods/runtimes/container.py
jina/parsers/peapods/runtimes/distributed.py
jina/parsers/peapods/runtimes/remote.py
jina/parsers/peapods/runtimes/zed.py
jina/parsers/peapods/runtimes/zmq.py
jina/parsers/ping.py
jina/peapods/peas/__init__.py
jina/peapods/runtimes/zmq/zed.py
jina/peapods/zmq/__init__.py

feat(parser): improve flexi parser to allow bullet list newline

---

jina/optimizers/__init__.py
tests/integration/optimizers/pods/dummy_evaluate.py
tests/integration/optimizers/test_optimizer.py

move params from optimize_flow to OptunaOptimizer __init__

refactor(optimizer): optimizer parameters

---

jina/flow/__init__.py
jina/optimizers/__init__.py
jina/optimizers/flow_runner.py
tests/integration/optimizers/test_optimizer.py
tests/unit/optimizers/test_optimizers.py

Refactored `ResultProcessor` and changed some naming to the final Jina 1.0 versions. Added docstrings. to be continued...

feat: code cleanup and docstrings added

---

tests/unit/logging/test_logging.py

Test the logging level with os variable 'JINA_LOG_LEVEL' setting.
Related to https://github.com/jina-ai/jina/pull/1744.

test: logging level

---

jina/docker/hubio.py
tests/unit/docker/test_hub_build.py

This reverts commit 54b07ace04ab8acdac72526805ceb212fb415094.

fix(revert): revert fix label insertion into dockerfile (#1732)"

---

docs/chapters/101/README.ar.md
docs/chapters/101/README.de.md
docs/chapters/101/README.fr.md
docs/chapters/101/README.gr.md
docs/chapters/101/README.ja.md
docs/chapters/101/README.md
docs/chapters/101/README.ru.md
docs/chapters/101/README.zh.md

I added a Greek translation to 101 chapter. Also added the Greek menu option to all `README.*.md`
I will also translate the main README.md in Greek this weekend.

docs(101): added greek translation to 101 chapter

---

jina/jaml/parsers/executor/legacy.py
tests/unit/jaml/parsers/executors/test_legacy.py

Currently when a jina app is executed it might read from a YAML file that specifies an encoder. If an argument from the encoder is misspelled (or does not exist) the code crashes but no error or Warning is presented to the user.

feat: check yaml definition matches instanciated class in LegacyParser

---

docs/chapters/crud/index.md
docs/index.rst

Please leave feedback and suggestions
Waiting for all PR and tasks related to CRUD to be implemented and finalized before expanding this.
Relevant PRs/issues to be mentioned in here

docs: crud

---

tests/integration/crud/simple/flow.yml
tests/integration/crud/simple/flow_kv.yml
tests/integration/crud/simple/flow_vector.yml
tests/integration/crud_corrupted_docs/flow-parallel.yml
tests/integration/crud_corrupted_docs/flow.yml
tests/integration/docidcache/crud_cache_flow_index.yml
tests/integration/docidcache/crud_cache_flow_query.yml
tests/integration/evaluation/flow-evaluate-from-file-parallel.yml
tests/integration/evaluation/flow-evaluate-from-file.yml
tests/integration/evaluation/flow-index-gt-parallel.yml
tests/integration/evaluation/flow-index-gt.yml
tests/integration/evaluation/flow-parallel-evaluate-from-file-parallel.yml
tests/integration/evaluation/rank/flow-evaluate.yml
tests/integration/evaluation/rank/flow-index.yml
tests/integration/gateway_non_blocking/flow.yml
tests/integration/issues/github_1468/flow.yml
tests/integration/issues/github_1684/flow.yml
tests/integration/issues/github_976/flow.yml
tests/integration/level_depth/flow-index.yml
tests/integration/level_depth/flow-query.yml
tests/integration/multimodal/flow-embedding-multimodal-parallel.yml
tests/integration/multimodal/flow-multimodal-all-types-parallel.yml
tests/integration/optimizers/optimizer_conf.yml
tests/integration/ref_indexer/compound-index.yml
tests/integration/ref_indexer/compound-query.yml
tests/integration/ref_indexer/index.yml
tests/integration/ref_indexer/query.yml

Update integration test with flow v1 api.

test: use flow v1 in integration test

---

tests/unit/drivers/querylang/queryset/test_lookup.py

test(drivers): add lookupnode tests

---

README.md

Updating copyright time range.

chore: update readme copyright

---

jina/peapods/runtimes/jinad/client.py
tests/distributed/test_against_external_daemon/delayed_executor.py
tests/distributed/test_against_external_daemon/delayed_executor.yml
tests/distributed/test_against_external_daemon/test_single_instance.py

fix(daemon): set client timeout to args timeout_ready

---

jina/optimizers/__init__.py
jina/optimizers/flow_runner.py
jina/optimizers/parameters.py

Cleanup of optimizer docstrings according to sphinx style.

docs: updated optimizer docstrings

---

jina/logging/formatter.py
jina/logging/logger.py
jina/logging/pipe.py
jina/logging/profile.py

Update docstrings of logging with https://docs.jina.ai/chapters/docstring/docstring.html

docs(logging): update logging docstrings

---

jina/docker/hubapi/local.py

feat(hub): expose jina version in hub list cli #1885

---

daemon/__init__.py
jina/peapods/runtimes/asyncio/rest/app.py
scripts/get-gateway-openapi.py

docs(rest): add jina logo to redoc

---

jina/helper.py

Update the docstrings of public functions and classes in helper

docs(helper): update helper docstrings

---

jina/importer.py

docs(importer): update importer docstring

---

jina/types/ndarray/__init__.py
jina/types/ndarray/dense/numpy.py
jina/types/ndarray/sparse/__init__.py
jina/types/ndarray/sparse/numpy.py
jina/types/ndarray/sparse/pytorch.py
jina/types/ndarray/sparse/scipy.py
jina/types/ndarray/sparse/tensorflow.py

Mainly reformatted to fit the docstring guide.

docs(ndarray): update docstring for ndarray

---

jina/drivers/search.py
tests/unit/types/document/test_document.py

DON'T MERGE!!!
This is a test PR for checking how many tests would fail. Might anyhow still go into 1.0
DON'T MERGE!!!

fix: more useful default

---

.github/workflows/ci.yml
jina/drivers/search.py
jina/resources/executors.requests.CompoundIndexer.yml
jina/types/document/__init__.py
tests/integration/crud/advanced/yaml/index-chunk.yml
tests/integration/crud/advanced/yaml/index-doc.yml
tests/integration/crud/simple/test_curd_readme.py
tests/integration/doccache/kv.yml
tests/integration/level_depth/yaml/index-chunk.yml
tests/integration/level_depth/yaml/index-doc.yml
tests/integration/sharding/yaml/index_kv.yml
tests/integration/sharding/yaml/index_kv_simple.yml
tests/unit/executors/indexers/binarypb.yml
tests/unit/types/document/test_document.py

feat(types): add update method to document types

---

.pre-commit-config.yaml
CONTRIBUTING.md

feat: precommit hooks for docstrings

---

README.md

Fix link to southpark -> link to wikipedia example
autoremoving of trailing whitespace via the IDE.

fix: wrong link

---

README.md

- Remove South Park (bc moved to legacy)
- Add Wikipedia sentence search
- Add Wikipedia incremental indexing
- Remove Object Search (broken last time tested, Jina version unspecified in reqs.txt)

fix(readme): fix example links

---

jina/types/document/__init__.py
jina/types/document/converters.py
jina/types/document/helper.py
jina/types/document/multimodal.py
jina/types/message/__init__.py
jina/types/message/common.py
jina/types/mixin.py
jina/types/ndarray/dense/__init__.py
jina/types/ndarray/dense/numpy.py
jina/types/ndarray/generic.py
jina/types/ndarray/sparse/__init__.py
jina/types/ndarray/sparse/numpy.py
jina/types/ndarray/sparse/pytorch.py
jina/types/ndarray/sparse/scipy.py
jina/types/ndarray/sparse/tensorflow.py
jina/types/querylang/__init__.py
jina/types/request/__init__.py
jina/types/request/common.py
jina/types/request/control.py
jina/types/request/delete.py
jina/types/request/index.py
jina/types/request/mixin.py
jina/types/request/search.py
jina/types/request/train.py
jina/types/request/update.py
jina/types/score/__init__.py
jina/types/sets/document.py
jina/types/sets/querylang.py

docs(types): add missing docstrings 

---

jina/drivers/__init__.py
jina/drivers/encode.py
jina/drivers/evaluate.py
jina/drivers/index.py
jina/drivers/predict.py
jina/drivers/search.py
jina/types/sets/document.py
tests/integration/encode_driver_batching/test_encode_driver_batching.py
tests/unit/drivers/test_encoder_driver.py
tests/unit/types/document/test_document_traverse.py

this is the continuation of #1937 to solve #1932 
I've already layout the new implementation of `RecursiveDriver`, please continue on

refactor(driver): use traverse from document type

---

jina/drivers/__init__.py
jina/drivers/control.py
jina/drivers/encode.py
jina/drivers/evaluate.py
jina/drivers/predict.py
jina/drivers/querylang/select.py
jina/flow/base.py
jina/flow/builder.py
jina/jaml/__init__.py
jina/jaml/helper.py
jina/jaml/parsers/__init__.py
jina/jaml/parsers/base.py
jina/parsers/helper.py

Adding two dots and two blank lines will fix the issue, tested locally, please checkout `dump` function in the screenshot:
[img](https://user-images.githubusercontent.com/9794489/108195254-cea46980-7117-11eb-9267-06398df3c1e2.png)

docs: ignore noqa in docstring

---

jina/peapods/runtimes/asyncio/rest/app.py
jina/peapods/runtimes/asyncio/rest/models.py

fix(rest): openapi rendering for crud

---

jina/logging/logger.py
jina/parsers/peapods/base.py
jina/peapods/peas/__init__.py
jina/peapods/pods/__init__.py
jina/resources/logging.quiet.yml
tests/unit/logging/test_logging.py

feat(logging): add --quiet option

---

jina/importer.py

These three functions seem not used at the moment. If we want to keep them, I will close this or and add unit tests accordingly.

refactor(importer): remove dead code

---

tests/unit/test_helper.py

Add test to cover touch_dir and random_port

test(helper): add tests

---

.github/workflows/cd.yml
.github/workflows/ci.yml

I see tests taking more than 250 s, so let's increase timeout

ci: increase timeout

---

jina/executors/indexers/keyvalue.py
tests/integration/crud/advanced/yaml/index-doc.yml
tests/integration/crud/rest/yaml/index.yml
tests/integration/crud/rest/yaml/index_kv.yml
tests/integration/crud/rest/yaml/index_vector.yml
tests/integration/crud/simple/chunks/yaml/index_kv.yml
tests/integration/crud/simple/yaml/index.yml
tests/integration/crud/simple/yaml/index_kv.yml
tests/integration/issues/github_929/binarypb.yml

test: add delete on dump to more

---

tests/integration/crud/simple/test_crud_readme.py

#2105 is partially fixed with this PR.

test: remove folder after test

---

tests/unit/types/document/test_document.py

PR commit to #2227 , not for master branch.

test: clean up sparse document test

---

jina/parsers/peapods/pod.py
jina/peapods/pods/helper.py
tests/distributed/test_index_query_with_shards/flow_distributed_peas_in_pod.yml
tests/distributed/test_simple_distributed_with_shards/flow_distributed_peas_in_pod.yml
tests/unit/peapods/pods/test_pods.py

fix: use list instead of dictionary for peas-hosts

---

RELEASE.md

**Context**: Following discussions with team leads / product / CTO. The following changes were agreed upon and need to be communicated to the team/community.

feat: add info for release cycle and breaking changes

---

jina/peapods/pods/compoundpod.py
tests/unit/peapods/pods/test_compound_pods.py

I think these changes make CompoundPods semantically more similar to Pod. The host and the port now refer to the headPea which is what the Flow may be interested in

refactor: small changes to compound pod

---

jina/executors/crafters/__init__.py
jina/executors/encoders/__init__.py
jina/executors/encoders/numeric/__init__.py
jina/executors/segmenters/__init__.py

when draft training, discovered a lot of unused imports in executors.

fix: remove unused imports

---

jina/peapods/runtimes/zmq/zed.py
tests/integration/v2_api/test_returns.py

Comparison `r_docs != self.request.docs` did not work as expected and left request empty.

fix: comparison doc array

---

tests/integration/inspect_pods_flow/test_inspect_pods_flow.py

This PR adapts the tests from 'eval_flow' from v1 to v2.

test: inspect flows

---

tests/integration/ranker_training/offline/test_offline_training.py

chore: update docstrings

---

README.md

chore: fix broken links

---

.github/2.0/cookbooks/Executor.md

minor improvement and typo fix to the cookbook of Executor

minor improvement and typo fix to the cookbook of Executor

---

.github/2.0/cookbooks/Executor.md
.github/2.0/cookbooks/Flow.md
tests/unit/helloworld/multimodal/conftest.py
tests/unit/helloworld/multimodal/test_executors.py

add unit tests for helloworld multimodal executors. This PR setup the test and add first Executor test.

test: add helloworld multimodal 2.0 segmenter test

---

.github/2.0/cookbooks/Executor.md
jina/types/arrays/chunk.py
jina/types/document/__init__.py
tests/unit/types/document/test_document.py
tests/unit/types/score/test_score.py

enable the shortcut such as `doc.score = 1.2`

feat: add score value shortcut

---

jina/helloworld/multimodal/app.py

Check if the people image dataset exist, if true no need to download the data again, for easier debugging.

fix: check if data exist

---

jina/peapods/zmq/__init__.py
tests/integration/dump/test_dump_reload.py

This PR fixed the hanging pods bug. It also reintroduces the integration test for dump reload and demonstrate its usage.

fix: fixed hanging pod termination

---

.github/2.0/cookbooks/Executor.md

feat: add code snippets for using paddle in cookbooks

feat: add code snippets for using paddle in cookbooks

---

.github/2.0/cookbooks/Executor.md

This adds another example Executor to the cookbook. It is using Keras/Tensorflow and built in MobileNet.
In a real world case one would pass certain parameters as args to the Executor (like image dimensions). 
Also I am assuming here that the content is stored in the _buffer_ field, but one could also argue that should be _blob_. I am using _buffer_ because `DocumentArray.from_files()` will set _buffer_ and not _blob_.
The example was tested with this flow:
```
if __name__ == '__main__':
from jina import Flow, DocumentArray
f = Flow().add(uses=TfMobileNetEncoder)
with f:
f.post(on='/index', inputs=DocumentArray(DocumentArray.from_files('/some/path/*.png', read_mode='rb')))
```

feat: add example for executor using tensorflow

---

tests/__init__.py
tests/integration/crud/__init__.py
tests/integration/crud/simple/flow.yml
tests/integration/crud/simple/test_crud.py

Add basic crud integration tests

test: add basic crud integration

---

.github/2.0/cookbooks/Executor.md

With a slightly practical example and descriptions.

feat: update 2.0 executor cookbook

---

jina/helloworld/multimodal/executors.py

with #2465 merged, we switch to `update`.

fix: use update instead of MergeFrom

---

daemon/__init__.py

small fix: Create the root workspace directory on startup of jinad.

fix(daemon): create root workspace dir

---

jina/flow/base.py
jina/peapods/pods/__init__.py
jina/peapods/pods/compound.py

Add the option to show the Flow with replicas and shards

fix: fix flow show with replicas

---

tests/integration/v2_api/test_func_routing.py

Modified a test to check for groundtruths routing.

test: added groundtruths routing

---

README.md
cli/autocomplete.py
jina/flow/builder.py
jina/parsers/peapods/pod.py
jina/parsers/peapods/runtimes/zed.py
jina/peapods/pods/__init__.py

fix: cli args help text

---

tests/unit/types/arrays/test_documentarray.py

Part of https://github.com/jina-ai/jina/issues/2479

test: docarray filter

---

jina/types/arrays/document.py
tests/unit/types/arrays/test_documentarray.py

Background:
https://github.com/jina-ai/jina/issues/2540

fix(documentarray): fix save binary

---

tests/unit/flow/test_slow_executor_shutdown.py

Part of https://github.com/jina-ai/jina/issues/2479

test: slow shutdown

---

.github/pages/hello-world.md
jina/helloworld/chatbot/executors.py
jina/helloworld/multimodal/executors.py
tests/system/chatbot/test_chatbot.py

Updated helloworld models in order to reach better quality.

feat: update example models for better running versions

---

jina/peapods/pods/__init__.py
jina/peapods/pods/compound.py
tests/unit/peapods/pods/test_compound_pods.py
tests/unit/peapods/pods/test_pods.py

Intended to fix #2363 
This is a 3nd, cleaner try at #2382 and #2418 lol
cc: @cristianmtr  @maximilianwerk  @JoanFM

fix: naming of peas replicas in logs

---

daemon/api/endpoints/logs.py

This fixes the problem that jinad continues to stream logs to disconnected clients. Before we just ran forever in a while True loop. This PR fixes that behaviour.
I checked that the existing tests still success and manually that the old problem behaviour is gone. I could not easily test this in the existing test setup as it does not have access to those internal state information. If we want tests here I would need to write new tests for the connection manager

fix(daemon): fix log stream clients disconnecting

---

jina/types/document/graph.py

Change default_logger call to use less resources.

refactor: update logger to debug

---

jina/types/document/graph.py
tests/unit/types/document/test_graph_document.py

This PR Fixes iteration over graphs with no edges

fix: graph iteration in case it has no edges

---

daemon/api/endpoints/workspaces.py
daemon/files.py
daemon/stores/base.py
daemon/stores/workspaces.py
tests/daemon/unit/models/good_ws/.jinad
tests/daemon/unit/models/test_jinad_file.py
tests/distributed/helpers.py
tests/distributed/test_against_external_daemon/flow_app_ws/.jinad
tests/distributed/test_against_external_daemon/flow_app_ws/app.py
tests/distributed/test_against_external_daemon/test_remote_workspaces.py

Remove quotes/spaces at the start and end of a run command

fix(daemon): remove quotes around run command

---

.github/workflows/cd.yml
.github/workflows/tag.yml
docs/conf.py
jina/types/request/__init__.py

fix: Response class as alias of Request class

---

.github/workflows/latency-tracking.yml

As for the unexpected err: [check run here](https://github.com/jina-ai/jina/pull/2621/checks?check_run_id=2826860463#step:6:8), add a necessary blank in the command line.

fix(latency-tracking): add a necessary blank

---

.github/2.0/cookbooks/Flow.md

This fixes two issues with the flow cookbook example (missing on keyword and missing kwargs)

fix(cookbook): fix example in flow cookbook

---

.github/2.0/cookbooks/Flow.md
jina/clients/base.py
jina/flow/base.py
jina/helloworld/chatbot/app.py
jina/peapods/runtimes/asyncio/rest/app.py
jina/types/request/__init__.py
tests/system/chatbot/test_chatbot.py

fix: clarify typehint for callback function

---

jina/flow/base.py
tests/integration/rolling_update/test_dump.py

same as https://github.com/jina-ai/jina/pull/2657 but against daemon-2.0

feat(daemon): dump flow wrapper

---

jina/hubble/hubio.py
jina/parsers/hubble/push.py
tests/unit/parsers/hubble/test_pushpull.py

**CREATE operation at first time:**
- jina hub push . -> public or private, either is okey with me
- jina hub push --public . -> public
- jina hub push --private . -> private
**UPDATE operation using --force option:**
- jina hub push --force UUID --secret SECRET .  -> don't change visibility
- jina hub push --private --force UUID --secret SECRET . -> change to private
- jina hub push --public --force UUID --secret SECRET . -> change to public

Modify the behavior of public and private

---

.github/workflows/ci.yml
daemon/api/endpoints/partial/flow.py
daemon/api/endpoints/partial/pea.py
daemon/stores/flows.py
daemon/stores/partial.py
daemon/stores/workspaces.py
tests/conftest.py
tests/daemon/unit/api/endpoints/partial/test_flow.py
tests/daemon/unit/api/endpoints/test_common.py
tests/daemon/unit/api/endpoints/test_logs.py
tests/daemon/unit/stores/test_flowstore.py
tests/daemon/unit/stores/test_partialstore.py
tests/daemon/unit/stores/test_peapodstore.py
tests/daemon/unit/stores/test_workspacestore.py
tests/daemon/unit/test_files.py

WIP (fix store unit tests, clean up flow store/endpoint create function params)
**TODO**: I copied local workspace creation in the tests around, need to move this in some test helper.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200490924153885) by [Unito](https://www.unito.io)

fix(daemon): store unit tests

---

.github/2.0/cookbooks/Flow.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200495197127121) by [Unito](https://www.unito.io)

docs: remove use gateway

---

extra-requirements.txt
jina/clients/http.py
jina/clients/request/__init__.py
jina/excepts.py
jina/peapods/runtimes/asyncio/http/app.py
jina/peapods/runtimes/asyncio/http/models.py
tests/integration/hub_usage/test_hub_usage.py
tests/jinahub/test_integration.sh
tests/unit/clients/python/test_client.py
tests/unit/flow/test_flow_change_gateway.py
tests/unit/flow/test_flow_http_extend.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200497204346921) by [Unito](https://www.unito.io)

fix(http): fix http request response model

---

cli/api.py
tests/unit/mwu-encoder/Dockerfile
tests/unit/peapods/runtimes/container/test_container_runtime.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200498452413401) by [Unito](https://www.unito.io)

fix: change alias to pea

---

tests/integration/override_executor_specific_params/test_specific_params.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200503147147975) by [Unito](https://www.unito.io)

test: add more tests

---

jina/peapods/peas/__init__.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200504141884406) by [Unito](https://www.unito.io)

perf: hide zmq.asyncio import to speedup import

---

jina/clients/http.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200506242540071) by [Unito](https://www.unito.io)

perf: http client is now fully async

---

.github/2.0/cookbooks/Serving.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200507932557152) by [Unito](https://www.unito.io)

fix: typo in cookbook

---

jina/hubble/helper.py
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/peapods/pods/__init__.py
tests/integration/hub_usage/test_hub_usage.py
tests/unit/hubble/test_hubio.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200509828168837) by [Unito](https://www.unito.io)

feat(hubble): support alias name

---

.github/workflows/cd.yml

copied core-test from ci.yml to cd.yml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200511980994890) by [Unito](https://www.unito.io)

ci: fix cd testbed

---

jina/hubble/helper.py
jina/hubble/hubio.py
jina/resources/Python.gitignore
tests/integration/hub_usage/test_hub_usage.py
tests/unit/hubble/test_hubio.py

* fix 1: put `metas` and `envs` in request header
* fix 2: add request_id in request header
* fix 3: use local gitignore pattern
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200515138427558) by [Unito](https://www.unito.io)

fix(hubble): put `metas` and `envs` in request header

---

.github/2.0/cookbooks/Serving.md
docs/index.rst
jina/parsers/__init__.py
jina/parsers/peapods/runtimes/remote.py
jina/peapods/zmq/__init__.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200520535765373) by [Unito](https://www.unito.io)

refactor: create task in async zmqlet

---

jina/helper.py
jina/peapods/pods/__init__.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200521016950704) by [Unito](https://www.unito.io)

refactor: get public ip

---

jina/clients/base/grpc.py
jina/clients/base/websocket.py
jina/flow/base.py
jina/jaml/parsers/executor/legacy.py
jina/peapods/peas/__init__.py
jina/peapods/pods/__init__.py
jina/peapods/runtimes/asyncio/grpc/__init__.py
jina/peapods/runtimes/asyncio/http/__init__.py
jina/peapods/runtimes/asyncio/prefetch.py
jina/peapods/runtimes/asyncio/websocket/__init__.py
jina/peapods/runtimes/base.py
jina/peapods/runtimes/zmq/zed.py
jina/peapods/zmq/__init__.py
tests/unit/peapods/peas/test_pea.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200522605342166) by [Unito](https://www.unito.io)

fix: double join invoke from Pod

---

jina/peapods/runtimes/gateway/http/app.py
tests/unit/flow/test_flow_http_extend.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200526471225971) by [Unito](https://www.unito.io)

fix(http): change default endpoints methods to post

---

.github/2.0/cookbooks/Flow.md

A rather enormous change :slightly_smiling_face:.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200527199355817) by [Unito](https://www.unito.io)

docs(cookbook): fix typo in Flow.md

---

jina/hubble/helper.py
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/hubble/progress_bar.py
tests/unit/test_helper.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200528431353124) by [Unito](https://www.unito.io)

refactor(hub): get hub url from api.jina.ai

---

.github/2.0/cookbooks/Hubble.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200529274574161) by [Unito](https://www.unito.io)

docs(cookbook): update Hubble.md

---

cli/autocomplete.py
jina/hubble/helper.py
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/parsers/hubble/pull.py
jina/resources/Python.gitignore

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200529751805307) by [Unito](https://www.unito.io)

fix(hubble): add --install-deps argument

---

cli/__init__.py
cli/autocomplete.py
jina/peapods/runtimes/container/__init__.py
scripts/devbot.sh
scripts/inject-cli-as-overload.py
scripts/update-autocomplete-cli.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200535038524742) by [Unito](https://www.unito.io)

feat(cli): call version check in another thread

---

jina/hubble/hubio.py
jina/logging/formatter.py
jina/logging/logger.py

fix(logging): fix log formatter

---

jina/helloworld/chatbot/app.py

I have tried simple hello-world chatbot command and this did not work. 
I found CORS was not set.
I also find CORS error on helloworld-mulit-modal. It works different from chat, I could not fix it. I think this also need set CORS true. (Is it possible to set cors on yml?)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200535300693002) by [Unito](https://www.unito.io)

fix: set cors for helloworld-chatbot

---

jina/helloworld/multimodal/flow-search.yml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200535800531292) by [Unito](https://www.unito.io)

fix(demo): open cors for multimodal

---

.github/2.0/cookbooks/Executor.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200531210636278) by [Unito](https://www.unito.io)

docs: add cookbook about params

---

.github/2.0/cookbooks/Hubble.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200536087441892) by [Unito](https://www.unito.io)

docs: add documentation override

---

jina/hubble/hubapi.py
jina/hubble/hubio.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200536430571114) by [Unito](https://www.unito.io)

feat: hubble streaming logging

---

jina/enums.py
jina/flow/base.py
jina/parsers/peapods/runtimes/zed.py
jina/parsers/peapods/runtimes/zmq.py
jina/peapods/networking.py
jina/peapods/pods/__init__.py
jina/peapods/zmq/__init__.py
jina/proto/jina.proto
jina/proto/jina_pb2.py
jina/types/routing/table.py
tests/integration/external_pod/test_external_pod.py
tests/integration/rolling_update/test_rolling_update.py
tests/unit/flow/test_flow.py
tests/unit/flow/test_flow_example_face.py
tests/unit/flow/test_flow_example_faiss.py
tests/unit/flow/test_remote_orchestrate.py
tests/unit/peapods/pods/test_compound_pods.py
tests/unit/peapods/pods/test_networking.py
tests/unit/peapods/zmq/test_dynamic_routing.py
tests/unit/types/test_routing_graph.py

This PR will enable the support of a `remote -> local` connection via `remote == router bind` and`local == router connect`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200535447686606) by [Unito](https://www.unito.io)

feat: added remote local support

---

jina/flow/base.py
jina/parsers/flow.py

revert: telemetry on flow creation

---

jina/hubble/hubio.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200538213478340) by [Unito](https://www.unito.io)

fix(hubble): missed error message

---

jina/peapods/peas/__init__.py

Apparently hanging pea close was not fixed by https://github.com/jina-ai/jina/commit/e7b7c830bb5ddd3309665f5f7a28d04cde73777d
As we still see it: https://github.com/jina-ai/jina/runs/2963363204

fix(core): add sleep after terminate

---

jina/hubble/hubio.py

fix the clustered UI when displaying alias

fix: fix the clustered UI when displaying alias

---

jina/logging/formatter.py

fix(logger): change debug level color to purple

---

tests/unit/flow/test_flow.py

This adds a test to verify that https://github.com/jina-ai/jina/issues/2500 got fixed as a side effect of dynamic routing (https://github.com/jina-ai/jina/pull/2551).
Not sure we need this test actually as part of the test suite, but I was writing it anyway to verify the behaviour and I think there are no other tests doing this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200517178620445) by [Unito](https://www.unito.io)

fix(core): add complex test for routing list

---

.github/workflows/latency-tracking.yml

**Changes:**
- enabled latency-tracking CI job on push & PR

feat: enabled latency-tracking CI job on push & PR

---

jina/helloworld/multimodal/flow-index.yml
jina/helloworld/multimodal/flow-search.yml
jina/helloworld/multimodal/my_executors.py
jina/helloworld/multimodal/static/index.html

Changes to make it ready to adapt to use `jinahub+docker`

refactor: hello multimodal refactor

---

README.md

Just a few small wording tweaks to tighten things up

chore: polish wording

---

.github/workflows/latency-tracking.yml

chore: disable the latency tracking

chore: disable the latency tracking

---

jina/clients/mixin.py
jina/peapods/runtimes/zmq/zed.py
tests/integration/issues/github_2910/test_flow.py
tests/integration/v2_api/test_func_routing.py

- resolved #2910 
- fixed a bug in matching `target_peapod`

fix: fix #2910

---

tests/unit/flow/test_flow_yaml_parser.py

The PR adds a test to test Flow's `load_config` method with `override_with` parameter on `protocol`.

test: test flow.load_config with override_with on protocol

---

extra-requirements.txt
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/resources/extra-requirements.txt

add a file lock to make the `pulling` thread-safe

feat(hubble): add filelock while installing executor from hubble

---

.github/images/eah.svg
README.md

@hanxiao isn't here so asking you to review Nan! This will go up each month, a week before our EAH. After that it'll be taken down until a week before the next EAH
- docs(readme): add eah banner
- chore: polish wording

docs readme event banner

---

README.md

chore: remove the meetup banner

---

.github/images/eah.svg
README.md

Commenting out event banner until next time we need it
- chore: polish wording
- chore: comment out event banner til next time
- Revert "chore: comment out event banner til next time"
- chore: comment out event banner til next time

chore remove event banner

---

.github/2.0/cookbooks/CleanCode.md

docs(cookbook): add document creation clean code

---

README.md
jina/helloworld/chatbot/my_executors.py
jina/helloworld/fashion/my_executors.py
jina/helloworld/multimodal/my_executors.py

This PR updates the hello world examples leveraging the `DocumentArray.match` functionality.
Note that the user experience in the 3 examples is exactly the same.

refactor: update hello examples

---

cli/__init__.py
cli/api.py
cli/autocomplete.py
cli/export.py
cli/lookup.py
jina/parsers/__init__.py
tests/unit/test_cli.py

feat(cli): add jina help cli for quick arg lookup

---

.github/images/meetup.svg
README.md

Will keep this up until the event. In future will activate banner a week prior to meetups/EAH

feat: add meetup banner

---

.github/2.0/cookbooks/Document.md
jina/types/arrays/document.py
jina/types/arrays/memmap.py
jina/types/arrays/search_ops.py
tests/unit/types/arrays/test_search_ops.py

Allow users to find Documents in a  DocumentArray that match several regular expressions per tag

feat: find method for DocumentArray

---

jina/flow/base.py

feat(flow): add uses on flow plot

---

.github/2.0/cookbooks/Document.md
jina/types/arrays/document.py
jina/types/arrays/search_ops.py
tests/unit/types/arrays/test_documentarray.py
tests/unit/types/arrays/test_memmap.py

feat: add sample method to document array

---

.github/2.0/cookbooks/Document.md
README.md
jina/helloworld/chatbot/my_executors.py
jina/helloworld/fashion/my_executors.py
jina/helloworld/multimodal/my_executors.py
jina/math/helper.py
jina/types/arrays/neural_ops.py
tests/unit/types/arrays/test_neural_ops.py

improve `.match` by
- allowing scipy metric
- allowing 2-arity function
- allowing min-max normalization

feat(types): allow scipy metric in match and add minmax normalization

---

.github/2.0/cookbooks/Document.md
jina/types/arrays/search_ops.py
tests/unit/types/arrays/test_documentarray.py
tests/unit/types/arrays/test_memmap.py

add shuffle to document array, it's implemented as sample the entire document array.

feat: add shuffle to documentarray

---

.github/workflows/latency-tracking.yml
scripts/latency-tracking/app.py

- fix: latency tracking long-running issue
- fix: added dependent job to lt
- fix: fixed lt annotation error
- fix: fixed step error
- fix: fixed ci lt mkdir permission issue
- chore: changed lt output filename
- feat: updated LT ci
- fix: fixed can't open file 'merge_outputs.py error
- feat: renamed batch.sh to track.sh

fix: latency tracking long running issue

---

jina/flow/base.py
jina/parsers/peapods/runtimes/container.py

fix minor grammar issues in gpu description

refactor(parser): clarify gpu argument description

---

.github/workflows/ci.yml
.pre-commit-config.yaml
cli/__init__.py
cli/autocomplete.py
cli/export.py
jina/hubble/hubio.py
jina/parsers/hubble/__init__.py
jina/resources/executor-template/README.md
jina/resources/executor-template/config.yml
jina/resources/executor-template/executor.py
jina/resources/executor-template/manifest.yml
scripts/black.sh
scripts/docstrings_lint.sh

feat(hub): add new command to jina hub CLI

---

jina/helloworld/fashion/helper.py

Fixes the image representation that contained a bug created when the image was represented as a 3d array

fix: fashion hello world fix 

---

.github/2.0/cookbooks/Document.md
jina/math/distance.py
jina/math/helper.py
jina/types/arrays/neural_ops.py
tests/unit/math/test_distance.py
tests/unit/math/test_helper.py
tests/unit/types/arrays/test_neural_ops.py

Add sparse support to distances and neural_ops

fix: add sparse support

---

jina/types/document/__init__.py

Improve the code a bit and improve the docstring.

refactor: improve document update method

---

.github/2.0/cookbooks/Flow.md
tests/distributed/test_local_flow_use_remote_executor/test_integration.py

This enriches the Cookbook with information about commonly used `add` parameters. It is still work in progress. Solves #3013

docs: added add method configs

---

.github/2.0/cookbooks/Document.md
jina/types/arrays/memmap.py
jina/types/arrays/search_ops.py
tests/unit/types/arrays/test_memmap.py

same as #3119 but merging into #3002

perf(dam): cache mmap object targeting #3002

---

jina/types/document/__init__.py
scripts/devbot.sh
scripts/inject-document-props-as-overload.py

closes https://github.com/jina-ai/internal-tasks/issues/144

ci: inject Document overload during CI

---

.github/pages/hello-world.md
README.md
extra-requirements.txt
jina/parsers/helloworld.py
jina/resources/extra-requirements.txt

This merges `chatbot` and `multimodal` extra dependencies into a single one - `demo`

chore: merge demo dependencies

---

jina/types/arrays/document.py
jina/types/arrays/memmap.py
jina/types/arrays/traversable.py
tests/unit/types/document/test_document_traverse.py

closes https://github.com/jina-ai/jina/issues/3068

fix: traverse chunk match

---

jina/types/arrays/memmap.py
jina/types/arrays/neural_ops.py

add `embeddings` property similar as DA to DAM, use  cache if exist, otherwise build and cache it.

perf: use embeddings property in cache

---

.github/workflows/cla.yml
.github/workflows/commit-lint.yml
.github/workflows/hacktoberfest.yml
.github/workflows/label-pr.yml

- feat: changed pull_request_target to pull_request

feat: enabled workflows for external contributors

---

setup.py

fix(setup): add core deps to perf deps

---

.github/workflows/cla.yml

add jina-bot to the cla whitelist

fix: add jina-bot to the cla whitelist

---

.github/workflows/cla.yml
.github/workflows/commit-lint.yml
.github/workflows/hacktoberfest.yml
.github/workflows/label-pr.yml

ci: revert "feat: enabled workflows for external contributors"

---

jina/hubble/hubio.py
jina/resources/executor-template/manifest.yml

feat(hubio): modify fields of manifest produced by jina hub new

---

README.md

update the number of slack members
reopen #3163

docs: update the number of slack members

---

cli/autocomplete.py
jina/__init__.py
jina/helloworld/fashion/app.py
jina/helloworld/fashion/helper.py
jina/logging/profile.py
jina/parsers/helloworld.py
jina/peapods/grpc/__init__.py
scripts/latency-tracking/app.py
tests/unit/test_progress_bar.py

perf(helloworld): optimize the performance of hello fashion

---

.github/workflows/benchmark.yml
jina/resources/extra-requirements.txt

- fix(ci): fixed benchmark ci error

fix(ci): fixed benchmark ci error

---

jina/types/arrays/memmap.py

address https://github.com/jina-ai/jina/issues/3260

fix(dam): warning truncate doc id

---

.github/workflows/benchmark.yml
.github/workflows/cd.yml

fix(ci): fixed benchmark CI

---

jina/helloworld/multimodal/static/index.html

https://github.com/jina-ai/jina/issues/3090

feat: disable button and search animation

---

docs/fundamentals/document/documentarray-api.md
jina/flow/base.py

Remove typo and minor rewrite for clarity

fix: remove typo and small rewrite of match explanation

---

conda/meta.yaml
scripts/create-conda-recipe.py

Changes that were requested by conda-forge team

fix: small changes to conda script

---

jina/peapods/pods/k8slib/kubernetes_tools.py

Enable K8s config loading from within a K8s cluster. I need this for the connection pooling

feat(k8s): client access from within the cluster

---

jina/peapods/pods/k8slib/kubernetes_deployment.py

Useful information for shards to know which virtual shard to pick.

feat: k8s parallel for shards

---

jina/peapods/pods/k8s.py
tests/unit/peapods/pods/test_k8s_pod.py

Add unit test coverage to the https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8s.py module.
Issue: https://github.com/jina-ai/jina/issues/3293

test: pods k8s parse args unit test

---

jina/peapods/pods/k8slib/kubernetes_tools.py
tests/k8s/test_custom_resource_dir.py
tests/unit/peapods/pods/k8slib/test_kubernetes_tools.py
tests/unit/peapods/pods/test_k8s_pod.py

Add unit test coverage to the https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8slib/kubernetes_tools.py module.
Issue: https://github.com/jina-ai/jina/issues/3293

test(k8s): unit test tools

---

docs/advanced/experimental/Kubernetes.md
docs/advanced/experimental/index.md
docs/advanced/experimental/kubernetes.md

Add a description of how the Kubernetes feature can be used.

docs: kubernetes cook book

---

jina/hubble/hubio.py

- sorting the rows in the table output of `jina hub new` by the filename
- some clean-up of description

fix: clean-up and re-ordering of `hub new` table

---

daemon/dockerize.py

Closes https://github.com/jina-ai/jina/issues/3377

fix: fix typo on daemon dockerize

---

scripts/docstrings_lint.sh

Updating dead link to pre-commit hook setup

ci: pre commit hook

---

cli/autocomplete.py
docs/advanced/experimental/compound_executors.md
docs/fundamentals/document/documentarray-api.md
jina/flow/base.py
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/parsers/__init__.py
jina/parsers/hubble/pull.py
jina/parsers/hubble/push.py
jina/parsers/peapods/pod.py
jina/peapods/peas/helper.py
tests/unit/hubble/test_hubapi.py
tests/unit/hubble/test_hubio.py
tests/unit/parsers/hubble/test_pushpull.py

This PR sets the behavior that by default `uses='jinahub://'`or `uses='jinahub+docker://'` will **not** pull if they are locally available already.

feat(hubio): do not pull latest version by default

---

jina/logging/profile.py

built-in progress bar now has a spinner `thread` to show long halting progress

feat(helper): progressbar now has a spinner

---

jina/hubble/helper.py
jina/hubble/hubio.py
tests/integration/hub_usage/test_hub_usage.py
tests/unit/hubble/test_helper.py
tests/unit/hubble/test_hubio.py

feat: get fetch metas only when using --force, otherwise, default to local cache

feat: new image force

---

jina/types/arrays/traversable.py
tests/unit/types/arrays/test_batching.py

fix: batching for multi-valued blobs and embeddings

---

jina/types/arrays/memmap.py
tests/unit/types/arrays/test_memmap.py

use `memmap.path` replace `memmap._path` in finetuner

feat: expose path as getter for finetuner

---

README.md

Just some minor spit and polish to fix grammar

docs(readme): small polishing

---

docs/fundamentals/executor/executor-api.md

https://jina-ai.slack.com/archives/C0169V26ATY/p1632331692319800

docs: more explicit naming

---

jina/flow/base.py

fix: fix get address table k8s

---

docs/advanced/experimental/indexers.md

Fixing typos from [here](https://github.com/jina-ai/jina/pull/3486#pullrequestreview-764358949)

docs: minor typos in indexers

---

docs/advanced/experimental/kubernetes.md

- some console output to let the user know what the expected outcome is

docs: k8s console output

---

jina/hubble/hubio.py
jina/parsers/hubble/__init__.py
jina/parsers/hubble/new.py
tests/unit/hubble/test_hubio.py
tests/unit/parsers/hubble/test_new.py

This PR aims at resolving #3393.
Resolution:
- A new.py file is added to add a parser to Jina hub new.
- added arguments in test_new of test_hubio.py
- Updated hubio.py to make use of command-line arguments.

feat: add parser to jina hub new

---

README.md
docs/conf.py
jina/types/arrays/document.py
tests/unit/types/arrays/test_documentarray.py
tests/unit/types/document/test_converters.py

closes: https://github.com/jina-ai/internal-tasks/issues/193

fix: fix test_da_csv_write on windows

---

README.md
docs/conf.py
jina/types/arrays/document.py
tests/unit/types/arrays/test_documentarray.py
tests/unit/types/document/test_converters.py

test: xfail only parameter with x-python

test: xfail only parameter with x-python

---

docs/advanced/experimental/indexers.md
docs/advanced/experimental/kubernetes.md

Fix link to renamed `FaissPSQLIndexer`

docs: update link to indexer

---

conda/meta.yaml
scripts/create-conda-recipe.py

This updates conda requirements, due to addition of `kubernetes` requirement

fix: conda requirements

---

jina/types/arrays/document.py
jina/types/arrays/memmap.py
tests/unit/types/arrays/test_documentarray.py
tests/unit/types/arrays/test_memmap.py

feat: add buffers getter setter

---

CONTRIBUTING.md

docs: fix a typo

---

.github/workflows/cla.yml

ci: fix cla

---

.github/workflows/cla.yml

ci: fix cla bugs

---

jina/peapods/grpc/__init__.py
jina/peapods/networking.py

* expose polling type via grpclet and connection pool
* change arguments to prepare for removal of port_in
* inject connection pool to the grpclet, so its connections can be managed externally

feat(grpc): refactor grpclet interface

---

README.md

chore: logo change

---

jina/helloworld/chatbot/my_executors.py
jina/helloworld/multimodal/my_executors.py

minor refactoring discovered while doing book review.

refactor(helloworld): use inference mode

---

jina/peapods/networking.py
jina/peapods/runtimes/gateway/graph/topology_graph.py
jina/peapods/runtimes/head/__init__.py
tests/integration/runtimes/test_runtimes.py

Adds a bunch of integration tests, testing the new star routing runtimes.
Also doing a small change in the topology graph to send all messages on merging and not just the last.

feat(tests): star routing runtime integration tests

---

docs/_static/iframe.js
docs/_static/main.css
docs/_templates/page.html
docs/conf.py

I'll merge this once I test embedding this in learning portal

docs: add configurations to hide sidebar and nav when loaded in iframe

---

daemon/api/dependencies.py
jina/enums.py
jina/parsers/peapods/pea.py
jina/peapods/peas/__init__.py
jina/peapods/peas/helper.py
jina/peapods/pods/__init__.py
tests/integration/peas/test_pea.py
tests/unit/peapods/pods/test_compound_pods.py

This closes https://github.com/jina-ai/internal-tasks/issues/265
This adds integration tests for peas (basically the same as for runtimes, just with peas).
I am also changing the PeaRoleType enum. I think the new definition is clearer.

feat(tests): integration tests for peas

---

jina/types/arrays/mixins/traverse.py

closes https://github.com/jina-ai/jina/issues/3947

fix: check traversal_paths once

---

docs/_static/docbot.css
docs/_static/docbot.js
docs/_templates/docbot.html

Fix doc-bot style broken before load.
Fix potential issue that may cause doc-bot fail to load.

docs: fix doc-bot style during load

---

jina/hubble/helper.py

adding filelock for hubio's `disk_cache.db` to resolve issue #3617

fix: hubio disk cache for multithreading

---

docs/_static/docbot.css
docs/_static/docbot.js

This fixes a bug in the previous patch that the doc-bot grows infinitely upon multiple questions and won't trigger a scroller.
Fixes the automatic scroll-to-bottom position.
Fixes multiple concurrent query when enter is pressed multiple times.

fix: docbot overflow and scrolling

---

docs/advanced/hub/executor-best-practices.md

To address https://github.com/jina-ai/example-video-search/issues/4

docs: executor best practice regarding docker resource

---

docs/Makefile
docs/_templates/sidebar/brand.html
docs/conf.py
docs/makedoc.sh

A bit ugly. But this allows one to build docs locally without adding to any git branch -- `bash makedocs.sh local-only`

docs: allow local branch only

---

docs/advanced/experimental/indexers.md

Some clean-up / updates of indexers page in docs, before writing the benchmark section

docs: refactor indexers page

---

docs/advanced/hub/use-hub-executor.md
docs/fundamentals/document/document-api.md
docs/fundamentals/document/documentarray-api.md
jina/clients/base/helper.py
jina/clients/base/http.py
jina/flow/base.py
jina/helper.py
jina/peapods/runtimes/gateway/http/models.py
jina/peapods/runtimes/gateway/websocket/app.py
jina/peapods/runtimes/request_handlers/data_request_handler.py
jina/types/arrays/memmap/__init__.py
jina/types/arrays/mixins/io/csv.py
jina/types/arrays/mixins/io/json.py
jina/types/arrays/mixins/magic.py
jina/types/document/__init__.py
jina/types/document/mixins/attribute.py
jina/types/document/mixins/audio.py
jina/types/document/mixins/buffer.py
jina/types/document/mixins/content.py
jina/types/document/mixins/helper.py
jina/types/document/mixins/image.py
jina/types/document/mixins/mesh.py
jina/types/document/mixins/text.py
jina/types/document/mixins/video.py
jina/types/mixin.py
jina/types/ndarray/__init__.py
jina/types/struct.py
tests/unit/peapods/runtimes/gateway/http/test_models.py
tests/unit/types/ndarray/test_ndarray.py
tests/unit/types/ndarray/test_ndarray_dict_json.py

```python
from jina import Document
d1 = Document(embedding=[1, 2, 3])
d2 = Document(embedding=[4, 5, 6], blob=np.random.random([10, 3]))
d2.chunks.append(d1)
print(d2.to_json())
d3 = Document(d2.to_json())
print(d3)
```
```
/Users/hanxiao/.pyenv/versions/3.7.9/bin/python /Users/hanxiao/Documents/jina/toy5.py
{
"blob": [
[
0.9649817331679378,
0.4739374784564643,
0.793891170344934
],
[
0.9872954579820935,
0.5629163343819901,
0.7021878651613199
],
[
0.7152901390747485,
0.36303204955404234,
0.930047251966927
],
[
0.414375563135602,
0.30867051665386813,
0.5833177354426033
],
[
0.5241172697590948,
0.8345834336081983,
0.9778800984498491
],
[
0.6992921278999543,
0.6894755026694135,
0.04010049047652431
],
[
0.8241683614537004,
0.6069184211285863,
0.3969301351287311
],
[ …
```

feat(types): add dict json printer parser to ndarray proto

---

README.md

Small tweaks to improve wording on updated README

docs: polish readme

---

docs/tutorials/question-answering-bot.md

This PR fixes bugs in the question-answering bot tutorial.

docs: updates docqa tutorial after community feedback

---

.github/workflows/label-pr.yml
docs/fundamentals/flow/remarks.md
docs/makedoc.sh

fix https://github.com/jina-ai/internal-tasks/issues/352

fix: use custom protoc doc generator image

---

jina/peapods/peas/factory.py
tests/unit/peapods/peas/test_pea_factory.py

closes: https://github.com/jina-ai/jina/issues/4090

fix: fix Flow uses executor from jinahub+docker 

---

jina/helloworld/multimodal/my_executors.py

reported by @Shubhamsaboo too many warnings shown up

refactor(helloworld): suppress warnings of traversal flat

---

jina/peapods/networking.py

Dont process non jina resources in the K8sConnectionPool. These resources will not have Jina metadata and are causing errors at the moment.

fix: ignore non jina resources

---

docs/fundamentals/executor/executor-api.md
jina/executors/__init__.py
jina/executors/decorators.py
jina/helper.py
jina/peapods/runtimes/request_handlers/data_request_handler.py
jina/peapods/runtimes/worker/__init__.py
jina/types/mixin.py
tests/unit/executors/test_decorators.py
tests/unit/executors/test_executor.py
tests/unit/peapods/runtimes/request_handlers/test_data_request_handlers.py
tests/unit/peapods/runtimes/worker/test_worker_runtime.py

Based on the work here https://github.com/jina-ai/jina/pull/4027
See more extensive description in the base PR
Closes https://github.com/jina-ai/internal-tasks/issues/357
The previous PR was extended by these items:

feat(executor): enable async executors

---

docs/tutorials/master-executor.md

docs(tutorial): typo

---

docs/fundamentals/document/documentarray-api.md
docs/fundamentals/executor/executor-api.md

fix minor typos in documentation

docs: fix typos

---

daemon/api/endpoints/partial/flow.py
daemon/stores/partial.py
jina/flow/base.py
jina/parsers/peapods/base.py
jina/peapods/peas/__init__.py
jina/peapods/pods/__init__.py
scripts/get-all-test-paths.sh
tests/daemon/unit/api/endpoints/partial/test_flow.py
tests/daemon/unit/api/test_dependencies.py
tests/daemon/unit/stores/test_partialstore.py
tests/distributed/test_local_flow_use_remote_executor/docker-compose-shards.yml
tests/distributed/test_local_flow_use_remote_executor/docker-compose.yml
tests/distributed/test_local_flow_use_remote_executor/test_integration.py
tests/distributed/test_remote_flow_dump_rolling_update/flow_query.yml
tests/distributed/test_rolling_update_container_runtime/docker-compose.yml
tests/distributed/test_rolling_update_container_runtime/flow_query.yml
tests/distributed/test_rolling_update_container_runtime/test_rolling_update.py
tests/distributed/test_scale_remote_executors/test_remote_executors.py
tests/distributed/test_workspaces/test_cache_validate.py

enable more daemon tests again
TODO: create follow up task to remove cancel event setting

feat: enable daemon tests again

---

tests/integration/peas/test_pea.py

make sure all processes are forked before grpc communication starts

fix: improve pea tests reliability

---

.github/workflows/cd.yml
.github/workflows/ci.yml

closes https://github.com/jina-ai/jina/issues/4151
This applies changes done to CI, to CD as well.
Also I found the comment in CI to be not correct, lets see if tests pass now

fix: fix cd failing

---

docs/datatype/image/image2image.md

+ Pre-requisite for successful running
+ Added colab link for reference
Issue posted in the Slack [community channel](https://jina-ai.slack.com/archives/C0169V26ATY/p1641979583044400)

docs: update pre-requisite
