docs/conf.py

Also adding polyfill for text-fragments.

feat(docs): bump qabot 0.3

---

jina/peapods/peas/__init__.py
jina/peapods/peas/helper.py

refactor: set name of process where runtimes run

---

docs/advanced/experimental/index.md
docs/advanced/experimental/sandbox.md
jina/flow/base.py
jina/hubble/helper.py
jina/hubble/hubio.py
jina/peapods/networking.py
jina/peapods/pods/__init__.py
tests/unit/flow-construct/test_flow.py
tests/unit/flow-example/test_flow_examples.py
tests/unit/hubble/test_helper.py
tests/unit/peapods/test_networking.py
tests/unit/test_helper.py

@jacobowitz @JoanFM 
I drafted this PR based on the discussion we have yesterday. Please tell me if I missed something. 
---
Close: https://github.com/jina-ai/hubble/issues/245

feat: support jinahub+sandbox

---

.github/DOCSTRINGS.rst
CONTRIBUTING.md

- add back the docstring guide
- fix link in CONTRIBUTING.md

docs: add back guide to docstrings

---

docs/conf.py

docs: use new docsqa server address

---

jina/orchestrate/deployments/__init__.py

fix: fix flow plot

---

docs/how-to/docker-compose.md
docs/how-to/kubernetes.md

Docs3 0 warning k8s docker compose

---

jina/hubble/hubio.py
tests/unit/hubble/test_hubio.py

Ref: https://github.com/jina-ai/hubble/issues/211

feat(hubble): upgrade to api v2

---

jina/hubble/hubio.py
tests/unit/hubble/test_hubio.py

feat(sandbox): using given port

---

docs/fundamentals/flow/create-flow.md
docs/fundamentals/flow/index.md

* fix some examples
* explain some more methods

docs: fix examples

---

docs/conf.py

remove the out-of-date announcement for EAH-2022.02.08

chore: remove the eah announcement

---

docs/how-to/gpu-executor.md
docs/how-to/kubernetes.md
docs/how-to/sandbox.md

docs: minor clean up on 3.0 branch

---

docs/get-started/migrate.md

docs: migration attributes

---

docs/fundamentals/executor/index.md

Minimum working example for Executor, analogous to the one given for Flow here: https://docs3_0--jina-docs.netlify.app/fundamentals/flow/#minimum-working-example

docs: add minimum working example to executor

---

docs/fundamentals/architecture-overview.md
docs/fundamentals/concepts.md
docs/fundamentals/executor/executor-api.md
docs/fundamentals/executor/index.md
docs/fundamentals/flow/flow-api.md

docs: fix inconsistent definition for executor and flow

---

docs/get-started/install.md

remove jinad from the install section

docs: remove jinad from install section

---

jina/__init__.py

ci: bump version to 2.7

---

docs/fundamentals/executor/containerize-executor.md
docs/fundamentals/executor/executor-in-flow.md
docs/fundamentals/executor/hub/use-hub-executor.md
docs/fundamentals/flow/create-flow.md
docs/how-to/docker-compose.md
docs/how-to/gpu-executor.md
docs/how-to/kubernetes.md
docs/how-to/sandbox.md

docs: remove return_results

---

cli/__init__.py
extra-requirements.txt
jina/resources/extra-requirements.txt

Closes https://github.com/jina-ai/jina/issues/4361

refactor(cli): replace distuils with packaging

---

extra-requirements.txt
jina/resources/extra-requirements.txt
tests/distributed/test_scale_remote_executors/executors.py
tests/integration/v2_api/test_func_routing.py
tests/unit/clients/python/test_request.py

fix failing tests associated with recent docarray upgrade

fix: fix docarray version

---

jina/hubble/hubio.py

Fixes some improper wording in strings. See [here](https://jinaai.slack.com/archives/C018JCT47PV/p1645102286301999?thread_ts=1645102133.028709&cid=C018JCT47PV)

fix(strings): sandbox wording

---

jina/serve/runtimes/base.py
tests/unit/serve/stream/test_stream.py

remove duplicate codes in the unit tests for streaming

refactor: remove duplicate codes in the unit tests for streaming

---

docs/conf.py

fix: docsqa to new url

---

jina/parsers/__init__.py
jina/parsers/create.py
jina/types/request/__init__.py

chore: clean up docstrings and imports

chore: clean up docstrings and imports

---

jina/helloworld/chatbot/app.py
jina/helloworld/fashion/helper.py
jina/helloworld/multimodal/app.py

clean up helloworld imports requests from dev-rel.

refactor: use docarray import and sorting in helloworld

---

jina/excepts.py

chore: clean up unused exceptions

---

docs/_templates/page.html
docs/conf.py

docs: update qa-bot to v0.4

---

docs/fundamentals/flow/flow-api.md

docs: fix docs on k8s and docker compose

---

jina/hubble/hubio.py
jina/orchestrate/deployments/__init__.py
tests/unit/hubble/test_hubio.py

Ref https://github.com/jina-ai/hubble/issues/289

feat(sandbox): send all arguments to hubble

---

extra-requirements.txt
jina/resources/extra-requirements.txt

ci: unpin uvicorn version

---

jina/orchestrate/deployments/config/k8s.py
tests/unit/orchestrate/deploymens/config/test_k8s_deployment_config.py

fix(k8s): do not pass gpu to head

---

jina/hubble/hubio.py
tests/unit/hubble/test_hubio.py

**Before**
`IndexError: list index out of range`
**After**
`Exception: No image found for executor "...", tag: ..., commit: ..., session_id: ...`
**Before**
`Exception: 42202`
**After**
`Exception: Executor name has been taken by others, please provide another name. session_id: ...`
-----------
Ref links:
https://jinaai.slack.com/archives/C023A7RAPGR/p1646060403505149?thread_ts=1645890087.560159&cid=C023A7RAPGR
https://jinaai.slack.com/archives/C023A7RAPGR/p1645722090809509

fix(hubble): show helpful error message

---

docs/fundamentals/executor/executor-in-flow.md
docs/fundamentals/flow/client.md
jina/clients/base/grpc.py
jina/clients/base/http.py
jina/clients/base/websocket.py
jina/clients/helper.py
jina/clients/mixin.py
jina/excepts.py
tests/unit/clients/python/test_on_err.py
tests/unit/orchestrate/flow/flow-construct/test_flow_except.py
tests/unit/orchestrate/flow/flow-construct/test_flow_skip.py
tests/unit/orchestrate/flow/flow-orchestrate/test_flow_docarray_return.py
tests/unit/serve/runtimes/gateway/http/test_app.py

fixing https://github.com/jina-ai/jina/issues/4391
New behavior:
if an exception is raised then :

fix: fix client error 4391

---

jina/clients/mixin.py
jina/orchestrate/flow/base.py
tests/integration/graphql/test_graphql.py

feat: graphql async client

---

docs/fundamentals/flow/access-flow-api.md
docs/fundamentals/flow/create-flow.md
docs/fundamentals/flow/flow-api.md
docs/fundamentals/flow/index.md

Improve the docs page on Flow API, to include some of the content that has been dropped.
Also addressing some assumptions that endpoints should be thought of as CRUD endpoints.
Needs more work
Done with @samsja and @JohannesMessner

docs: flow api improvements

---

docs/fundamentals/executor/executor-api.md
jina/serve/executors/__init__.py

fixing https://github.com/jina-ai/jina/issues/4406

docs: Document Executor from hub

---

jina/helper.py
jina/orchestrate/flow/base.py
jina/serve/runtimes/gateway/http/app.py

fix: disable graphql featues if docarray version does not support it

---

jina/helloworld/multimodal/my_executors.py
tests/unit/clients/python/test_request.py
tests/unit/helloworld/multimodal/test_executors.py
tests/unit/types/request/test_request.py

test: fix tests failing after new docarray patch

---

jina/helloworld/multimodal/my_executors.py
tests/unit/clients/python/test_request.py
tests/unit/helloworld/multimodal/test_executors.py

test: fix tests failures caused by docarray

---

jina/clients/grpc.py
jina/clients/mixin.py

update docstrings for `jina/clients`

docs(clients): update docstrings

---

scripts/latency-tracking/requirements.txt

chore: update requirement of pillow for latency tracking

---

jina/clients/mixin.py
tests/unit/orchestrate/flow/flow-async/test_asyncflow.py

fix: fix asyncclient return

---

cli/autocomplete.py
docs/fundamentals/flow/create-flow.md
docs/how-to/flow-switch.md
jina/orchestrate/flow/base.py
jina/parsers/orchestrate/deployment.py
tests/integration/conditions_feature/flow.yml
tests/integration/conditions_feature/test_condition_behavior.py

refactor: rename switch feature

---

docs/fundamentals/flow/client.md
jina/clients/mixin.py

refactor: return_responses to post

---

docs/fundamentals/flow/access-flow-api.md
jina/clients/base/helper.py
jina/enums.py
jina/serve/runtimes/gateway/websocket/app.py
tests/integration/websocket_gateway/test_subprotocols.py

Support for streaming json using websocket

feat(websocket): json/bytes support

---

jina/serve/runtimes/gateway/websocket/app.py

fix: move import in websocket app

---

jina/serve/runtimes/gateway/websocket/app.py

chore: small refactor

---

jina/clients/mixin.py
jina/orchestrate/flow/base.py

refactor(client): simplify logics in client post

---

jina/enums.py
jina/orchestrate/flow/base.py

FIx the issue with the printing of our BetterEnum 
Before : 
After :

Fix better enum formatting

---

docs/fundamentals/flow/flow-yaml.md
docs/fundamentals/flow/index.md

Add documentation for configuring Flows with YAML files
Closes #4415

docs: add docs for configuring flow

---

cli/autocomplete.py
jina/clients/__init__.py
jina/orchestrate/flow/base.py
jina/parsers/deprecated.py
jina/parsers/helper.py
jina/parsers/orchestrate/runtimes/remote.py

fixing https://github.com/jina-ai/jina/issues/4533

fix: deprecation of https

---

jina/orchestrate/deployments/__init__.py
jina/serve/networking.py
tests/integration/issues/github_4488/test_deployment_protocol.py

return correct protocol when calling `.protocol` on a deployment.
Fixes https://github.com/jina-ai/jina/issues/4488

fix: deployment protocol

---

docs/fundamentals/flow/client.md
docs/fundamentals/flow/flow-api.md

docs: explain https support

---

.pre-commit-config.yaml
extra-requirements.txt
jina/helloworld/chatbot/my_executors.py
jina/orchestrate/deployments/__init__.py
jina/resources/extra-requirements.txt
jina/serve/runtimes/head/__init__.py
jina/serve/runtimes/request_handlers/data_request_handler.py
jina/serve/runtimes/worker/__init__.py
jina/types/request/data.py
scripts/black.sh

We need to pin black to a new version [due this upstream issue](https://github.com/psf/black/pull/2966)

fix: pin black version

---

docs/fundamentals/flow/access-flow-api.md
docs/fundamentals/flow/client.md
docs/fundamentals/flow/flow-api.md

To follow the structure in https://github.com/jina-ai/internal-tasks/issues/401

docs: refactor access flow page

---

cli/autocomplete.py
jina/hubble/hubio.py
jina/parsers/hubble/push.py
tests/unit/hubble/test_hubio.py
tests/unit/parsers/hubble/test_pushpull.py

Ref: https://github.com/jina-ai/hubble/issues/372
Related: https://github.com/jina-ai/hubble/pull/382

feat(hub): add `--no-cache` option to "jina hub push" CLI

---

jina/orchestrate/flow/base.py
tests/unit/orchestrate/flow/flow-construct/test_flow_visualization.py

fix: do not copy flow if already built

---

jina/__init__.py

chore: bump version

---

extra-requirements.txt
jina/resources/extra-requirements.txt

fix: prometheus client requirements to match conda package

---

docs/how-to/kubernetes.md

This extends the kubernetes how a bit by mentioning that the Gateway scan be scaled as well.
Closes [# (issue)](https://github.com/jina-ai/jina/issues/4601)

docs: mention scaling of gateway

---

jina/helper.py

fixing https://github.com/jina-ai/jina/issues/4612

fix: remove force interactive in rich console

---

docs/api.md

Clean up description of Python API page.
Closes https://github.com/jina-ai/jina/issues/4615

docs: remove needless python api page

---

.github/Jina.postman_collection.json
docs/fundamentals/flow/access-flow-api.md
scripts/black.sh

Add Postman collection. Contributed by Jonathan Rowley in [community Slack](https://jina-ai.slack.com/archives/C0169V26ATY/p1649689443888779?thread_ts=1649428823.420879&cid=C0169V26ATY)
Closes https://github.com/jina-ai/internal-tasks/issues/407

docs: add postman collection

---

docs/how-to/sandbox.md

Sandbox won't be deleted if there is no traffic but scale down to 0.

docs(sandbox): sandbox is serverless now

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py

By using " " mermaid allows to show invalid characters

fix: fix flow plot with private executor

---

docs/fundamentals/flow/access-flow-api.md

fixing hint box in access flow

docs: fix admonition in access flow page

---

docs/fundamentals/executor/executor-api.md
docs/fundamentals/flow/access-flow-api.md
docs/fundamentals/flow/client.md
docs/how-to/async-executors.md
docs/how-to/debug-executor.md
docs/how-to/external-executor.md
docs/how-to/flow-switch.md
docs/how-to/gpu-executor.md
docs/how-to/kubernetes.md

docs: normalize usage of admonition boxes

---

CONTRIBUTING.md
tests/k8s/test_k8s.py

Small update to the contributing guidelines so that user can run the k8s tests

feat: add linkerd details in contributing

---

jina/hubble/helper.py
jina/hubble/hubio.py

Goals:
- Allow Hubble errors to be overridden from jina core level to provide a better experience.
- Recognize Hubble errors by status codes instead of finding matches in messages.

fix(hubio): improve error message from hubble

---

cli/__init__.py

fix: use warnings and threading

---

jina/clients/base/http.py
jina/clients/base/websocket.py
jina/helloworld/fashion/app.py
jina/helloworld/fashion/my_executors.py
jina/hubble/hubapi.py
jina/hubble/hubio.py
jina/jaml/__init__.py
jina/jaml/parsers/__init__.py
jina/orchestrate/deployments/__init__.py
jina/orchestrate/deployments/config/k8slib/kubernetes_deployment.py
jina/orchestrate/flow/asyncio.py
jina/orchestrate/flow/base.py
jina/orchestrate/pods/helper.py
jina/parsers/flow.py
jina/parsers/helloworld.py
jina/parsers/orchestrate/base.py
jina/parsers/orchestrate/runtimes/distributed.py
jina/serve/executors/decorators.py
jina/serve/networking.py
jina/serve/runtimes/head/__init__.py
jina/serve/runtimes/worker/__init__.py
jina/serve/stream/__init__.py
jina/types/request/__init__.py
jina/types/request/control.py

style: sort and optimize imports

---

.github/workflows/cd.yml

fix: the cd

---

jina/orchestrate/deployments/config/docker_compose.py
tests/unit/orchestrate/flow/flow-construct/test_flow_to_docker_compose_yaml.py

fix: add resource layer in docker compose gpu

---

cli/autocomplete.py
docs/fundamentals/executor/hub/push-executor.md
jina/hubble/hubio.py
jina/parsers/hubble/push.py

Goals:
- Rename immutable-tag to protected-tag as discussed in https://github.com/jina-ai/jina/pull/4676

fix: rename immutable-tag to protected-tag

---

jina/__init__.py

Goals:
Allow jina now to unset the jina check version.
FYI @florian-hoenicke !

feat: allow jina now to unset jina_check_version

---

jina/helloworld/fashion/helper.py
jina/hubble/hubio.py
jina/orchestrate/flow/base.py

fix(flow): early stop at flow start

---

extra-requirements.txt
jina/resources/extra-requirements.txt

build: grpc version>=1.46.0

---

.github/workflows/cd.yml

fix: fix cd

---

jina/orchestrate/flow/base.py

feat: display all of the prometheus endpoint in ui

---

docs/_static/source-in-links.js
docs/conf.py

Goals:
- fix script that adds utm_source query param to links

docs(tracking): update refer links to other docs with utm_source

---

.github/workflows/cd.yml

ci: fix k8s test in cd

---

.github/workflows/ci.yml
jina/__init__.py

Goals:
- fixes https://github.com/jina-ai/jina/issues/4771

fix: import all from jina

---

docs/_templates/sidebar/navigation.html

add link and logo for jina NOW to docs page

docs: add jina now logo

---

jina/orchestrate/flow/base.py

we need to deactivate the logs in jina now

refactor: logging no print

---

docs/_static/source-in-links.js

docs(tracking): fix utm source

---

jina/__init__.py
jina/hubble/helper.py
jina/hubble/hubio.py
tests/unit/hubble/test_hubio.py

Ref https://github.com/jina-ai/hubble/issues/355

feat(hubble): executor push/pull user integration

---

jina/hubble/hubio.py
tests/unit/hubble/test_hubio.py

Ref https://github.com/jina-ai/hubble/issues/423

fix(sandbox): send secret in the request

---

jina/orchestrate/flow/base.py

refactor(flow): improve success box

---

tests/unit/hubble/test_hubio.py

Goals:
- fix failing hubble unit test

test(hubble): fix failing test

---

jina/orchestrate/deployments/__init__.py
tests/unit/orchestrate/deployments/test_cuda_assignment.py

feat(deployment): add roundrobin cuda device assignment

---

docs/fundamentals/flow/monitoring-flow.md
jina/serve/runtimes/gateway/request_handling.py
jina/serve/runtimes/request_handlers/data_request_handler.py
tests/integration/monitoring/test_monitoring.py

This pr is to try the rebase and merge strategy instead of squash for this pr https://github.com/jina-ai/jina/pull/4805

Feat new metrics test

---

jina/clients/base/websocket.py
jina/helper.py

refactor: simplify event loop usage

---

jina/helper.py
jina/serve/runtimes/gateway/http/app.py
tests/integration/gateway_clients/test_streaming.py
tests/integration/streaming/test_clients_streaming.py

fix: avoid closing loop at fork time

---

docs/fundamentals/flow/create-flow.md
docs/proto/docs.md

Add docs for the round robin cuda features

docs: round robin gpu scheduling 

---

docs/fundamentals/flow/flow-api.md

docs: fix Flow docs typo

---

jina/serve/executors/__init__.py

feat(executor): add self logger to executor

---

cli/__init__.py
extra-requirements.txt
jina/__init__.py
jina/orchestrate/flow/base.py
jina/proto/serializer.py
jina/resources/extra-requirements.txt
jina/resources/project-template/app.py
jina/resources/project-template/flow.yml
tests/integration/external_deployment/test_external_deployment.py
tests/integration/issues/github_2910/test_flow.py
tests/unit/orchestrate/flow/flow-orchestrate/test_flow_change_gateway.py

general code review of the core

fix: code review

---

.github/workflows/create-release.yml
.github/workflows/force-docker-build.yml
.github/workflows/tag.yml

Signed-off-by: mrtrkmn <mr.turkmen@icloud.com>
Goals:
- fixes #4748

ci: add create-release.yml

---

jina/orchestrate/deployments/__init__.py

fix: cuda visible device

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py

fix: do not deploy sandbox on init

---

docs/fundamentals/flow/client.md

This pr add docs for the default port client

docs: add default port client

---

jina/__init__.py
jina/hubble/helper.py
jina/serve/executors/__init__.py
jina/serve/executors/decorators.py
tests/integration/high_order_matches/test_document.py

feat: avoid concurrent init for replicas in same machine

---

README.md
cli/autocomplete.py
docs/fundamentals/executor/executor-api.md
docs/fundamentals/flow/flow-api.md
docs/fundamentals/flow/index.md
docs/fundamentals/flow/when-things-go-wrong.md
docs/how-to/kubernetes.md
docs/how-to/monitoring.md
jina/clients/base/grpc.py
jina/orchestrate/deployments/config/k8s.py
jina/orchestrate/flow/base.py
jina/parsers/orchestrate/runtimes/head.py
jina/parsers/orchestrate/runtimes/remote.py
jina/resources/executor-template/README.md
jina/resources/project-template/app.py
jina/serve/executors/__init__.py
jina/serve/networking.py
jina/serve/runtimes/gateway/http/app.py
jina/serve/runtimes/gateway/http/models.py
jina/serve/runtimes/request_handlers/data_request_handler.py
tests/integration/test_grpc_compression/test_grpc_compression.py
tests/k8s/test_graceful_request_handling.py
tests/k8s/test_k8s.py
tests/k8s/test_k8s_failures.py
tests/unit/orchestrate/deployments/config/test_k8s_deployment_config.py
tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
tests/unit/serve/executors/test_executor.py
tests/unit/serve/runtimes/gateway/http/test_app.py

refactor: remove unnecessary code

---

Dockerfiles/debianx.Dockerfile
README.md
cli/export.py
conda/meta.yaml
docs/_templates/page.html
docs/conf.py
scripts/create-conda-recipe.py
scripts/get-all-test-paths.sh
setup.py

ci: update test path findings

---

.github/pages/hello-world.md

chore: remove pages from .github folder

---

docs/fundamentals/flow/yaml-spec.md

docs: correct header indention

---

docs/fundamentals/flow/executor-args.md
docs/fundamentals/flow/flow-args.md
docs/fundamentals/flow/gateway-args.md
docs/fundamentals/flow/yaml-spec.md
scripts/devbot.sh
scripts/generate-list-args.py

docs: add arg list to flow yaml 

---

docs/fundamentals/flow/yaml-spec.md
jina/schemas/flow.py
jina/schemas/helper.py

fix: JSON schema generation

---

docs/fundamentals/architecture-overview.md
docs/get-started/create-app.md

minor update on the get-started section

docs: minor documenation updates on the get started section

---

docs/_templates/page.html

Goals:
The current title, description, and default questions are about DocArray in the qabot, correct them to jina.

fix(doc): update the description and default questions for qabot

---

jina/clients/__init__.py
jina/clients/grpc.py
jina/clients/http.py
jina/clients/websocket.py
jina/orchestrate/flow/asyncio.py
jina/orchestrate/flow/base.py
jina/serve/executors/__init__.py
jina/serve/executors/decorators.py

Goals:
Add examples to the most important docstrings

docs: examples in docstrings

---

docs/fundamentals/jcloud/advanced.md

docs: add wolf annotations document

---

docs/fundamentals/jcloud/advanced.md

docs: undo wolf document updates

---

docs/envs/index.md
docs/get-started/migrate.md

Goals:
Explain how to pass env vars to individual executors

docs: explanation how to set env vars

---

jina/clients/grpc.py
jina/clients/http.py
jina/clients/mixin.py
jina/clients/websocket.py
tests/integration/runtimes/test_gateway_dry_run.py

fix: add async dry run method

---

docs/fundamentals/flow/executor-args.md
docs/fundamentals/flow/gateway-args.md
docs/fundamentals/jcloud/basic.md
jina/hubble/helper.py
jina/orchestrate/flow/base.py
jina/parsers/orchestrate/runtimes/worker.py

fix: replace broken executor files docs link

---

jina/orchestrate/flow/base.py

feat: improve ui after flow success

---

tests/unit/orchestrate/flow/flow-construct/test_flow_except.py

refactor: change exec name in test

---

jina/serve/runtimes/gateway/request_handling.py
tests/integration/monitoring/test_monitoring.py

Goals:
When requests fail due to connection errors, the metrics related do not get updated

fix: fix monitoring update of metrics on exception

---

tests/conftest.py

Goals:
Try to identify flakiness source

test: set GRPC_ENABLE_FORK_SUPPORT=False for tests

---

docs/fundamentals/jcloud/advanced.md
docs/fundamentals/jcloud/faq.md

docs(jcloud): refactor faq section

---

docs/fundamentals/jcloud/faq.md

[Preview](https://github.com/jina-ai/jina/blob/jcloud-log/docs/fundamentals/jcloud/faq.md)

docs(jcloud): expand faq section

---

docs/how-to/docker-compose.md
docs/how-to/scale-out.md

PQlite was renamed ANNlite  and we need to renamed all of the references in our documentation

docs: change pqlite reference to annlite in docs

---

jina/serve/executors/__init__.py
tests/unit/clients/test_helper.py

test: have BaseExecutor bind default endpoint

---

jina/orchestrate/flow/base.py

feat: disable deploy sandbox when plotting

---

jina/serve/networking.py
jina/serve/runtimes/gateway/graph/topology_graph.py
jina/serve/runtimes/gateway/request_handling.py
tests/integration/gateway_clients/test_clients_gateways.py
tests/integration/gateway_clients/test_streaming.py
tests/integration/runtimes/test_network_failures.py
tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py

fix: fix endpoint discovery tries

---

.github/workflows/cd.yml

fixes: https://github.com/jina-ai/jina/issues/5018

chore: update action to update dockerhub description

---

jina/__init__.py

chore: bump jina version

---

jina/serve/networking.py
jina/serve/runtimes/gateway/grpc/__init__.py
jina/serve/runtimes/gateway/http/__init__.py
jina/serve/runtimes/gateway/http/app.py
jina/serve/runtimes/gateway/websocket/__init__.py
jina/serve/runtimes/gateway/websocket/app.py
jina/serve/runtimes/head/__init__.py

refactor: small refactor on streamer

---

scripts/get-openapi-schemas.py

fix: fix get openapi schemas

---

jina/serve/runtimes/asyncio.py

fix: fix the name of the event from runtimes

---

docs/fundamentals/jcloud/resources.md

Goals:
- Add genral CPU type and GPU type.

docs: add CPU and GPU type

---

docs/fundamentals/jcloud/advanced.md
docs/fundamentals/jcloud/resources.md

- Added docs for Gateway customization.
- Fixed docs for Gateway ingress type.

docs(jcloud): doc for gateway customization

---

docs/fundamentals/jcloud/advanced.md
docs/fundamentals/jcloud/resources.md

Goals:
- Add gateway timeout setting
- Update new shared gpu pods number for each node and memory notes

docs: add gateway timeout and update shared gpu

---

.github/pull_request_template.md

Goals:
Remind everyone of a policy that we agreed upon in a past retro. PRs without description will not be reviewed!

chore: update pr template with reminder to add a description

---

docs/fundamentals/jcloud/yaml-spec.md

**Goals:**
- remove alb/kong from jcloud gateway tab to avoid confusion.
- correct some GPU notes

docs: remove kong/alb from jcloud document

---

jina/serve/runtimes/gateway/request_handling.py

The behavior of the `receiving_request_seconds` is not perfect atm since it record the time for failed request as well.

refactor: refactor data request handler monitoring

---

.github/workflows/ci.yml

ci: cleanup pip install

---

docs/fundamentals/jcloud/index.md

**Goals:**
- correct `retention-days` faq

docs: correct jcloud retention days

---

.github/workflows/ci.yml
extra-requirements.txt
jina/resources/extra-requirements.txt
jina/serve/runtimes/gateway/http/models.py

CI is currently failing, it looks like a type changed in the protbuf library, so a type check we did fails.
This fixes the issue by just seeing if the needed attribute is there, regardless of the type, so this issue should not happen anymore in the future.

fix: update to protobuf 4.21 new types

---

docs/fundamentals/jcloud/yaml-spec.md

The example given in the modified section wasn't accurate enough, this PR is to fix it.

docs(jcloud): fix docs for gateway resource customization

---

.github/workflows/cd.yml

**Goals:**
Pin linkerd version in CD

fix: linkerd cd

---

tests/integration/monitoring/test_manual_flow.py

**Goals:**
Increase wait time for test_pending_request to ensure request is actually pending

test: increase wait time

---

tests/unit/serve/runtimes/worker/test_worker_runtime.py

This test has been skipped on CI for a while, and is now outdated on top of not working in the first place. So we are removing it.

test: remove outdated test

---

jina/helper.py
tests/unit/orchestrate/flow/flow-orchestrate/test_flow_complex_topology.py

- Pass internal flag to determine if CI is from jina-ai org

feat: pass internal flag to telemetry

---

jina/helper.py
tests/unit/test_helper.py

fix: fix parsing empty list

---

docs/fundamentals/jcloud/yaml-spec.md

**Goals:**
- Add docs about how to pass `labels` in the Flow yaml with JCloud deployments.

docs(jcloud): labels in flow yaml

---

.github/workflows/cd.yml
.github/workflows/ci.yml
tests/unit/hubble/test_hubio.py

ci: add jina auth token

---

jina/hubble/hubio.py

**Description**
This PR enables displaying warning messages from Hubble API when using `jina hub push`.
**Goals:**
- resolves #5112 
_How warning messages are displayed_

feat(hubio): display warning messages from hubble request (jina hub push)

---

scripts/get-openapi-schemas.py

update usage of `get_fastapi_app` in `get-openapi-schemas` to fix script

fix: fix get-openapi-schemas script

---

scripts/get-openapi-schemas.py

fix: fix get openapi schema script

fix: fix get openapi schema script

---

docs/fundamentals/executor/containerize-executor.md

**Goals**
Improve awareness of changing default config.yml file name in custom docker image.

docs: improve warning about config file in custom docker

---

docs/fundamentals/flow/topologies.md
jina/orchestrate/deployments/__init__.py
tests/unit/orchestrate/deployments/test_cuda_assignment.py

Add the chance to do round-robin by passing list of devices instead of slice

feat: support list-like syntax to round robin CUDA devices

---

docs/get-started/what-is-cross-modal-multi-modal.md

**Goals:**
* Make reading comprehension easier
* Maintain professional image for company content

docs(what-is-modality): fix grammar, punctuation

---

docs/get-started/what-is-jina.md

**Goals:**
- Improve readability
- Ensure professional content quality

docs(what-is-jina): fix grammar, wording, punctuation

---

docs/index.md

**Goals**
Step-by-step following of installation instructions do not work on Docker

docs: fix install instructions docker

---

docs/fundamentals/gateway/index.md

docs: mention prefetch in python and yaml code

---

docs/fundamentals/flow/health-check.md

**Goals:**
- change `os.setenv` to `os.environ` (I think the former is used in Go but not in Python)

docs: change setenv into environ

---

docs/fundamentals/executor/executor-methods.md

docs(executor): add missing request numbers in sample code

---

docs/how-to/docker-compose.md
docs/how-to/kubernetes.md

**Goals:**
Add note about the best practice of keeping same jina versions accross microservices

docs: add note about keeping same jina versions

---

README.md
docs/fundamentals/architecture-overview.md
docs/fundamentals/executor/containerize-executor.md
docs/fundamentals/executor/executor-api.md
docs/fundamentals/executor/executor-files.md
docs/fundamentals/executor/executor-methods.md
docs/fundamentals/executor/executor-run.md
docs/fundamentals/executor/executor-serve.md
docs/fundamentals/executor/monitoring-executor.md
docs/fundamentals/executor/yaml-spec.md
docs/get-started/create-app.md
docs/get-started/install/apple-silicon-m1-m2.md
docs/how-to/index.md
docs/index.md

Cleaning up docs under:
- Get started
- User guides > Basic concepts
- User guides > Executor (excl Hub)
Cleanup work involves:
- Fixing some imports in example code
- Changing tense to present simple tense
- Changing perspective to "you" (rather than one or we)
- Changing from passive (an Executor can be fooed) to active voice (you can foo an Executor)
- Spelling
- Grammar
- Capitalization
This probably doesn't catch every issue, but it cleans things and makes things more consistent.
---
- docs(index): polish
- docs(readme): slack link, polish
- docs(apple): update macos capitalization to be in line with apple's website
- docs(apple): polish
- docs(how-to): rm learning portal
- docs(how-to): prune back flowery/markety text
- docs(get-started): consistent pronouns, polish
- …

docs: polish (2022/10/04)

---

jina/orchestrate/flow/base.py

**Goals:**
- Enable [grpc fork support](https://github.com/grpc/grpc/issues/18321) to correctly clean up grpc usage in parent and child processes.

fix(orchestrate): enable grpc fork support

---

jina/serve/runtimes/head/__init__.py
tests/integration/instrumentation/test_flow_instrumentation.py

feat: add default tracing interceptors to Head grpc connection pool

---

docs/how-to/realtime-streaming.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix typo in realtime-streaming

---

jina/__init__.py

Bump release version in order to release 3.11.0.

chore(version): bump version to 3.11.0

---

.github/workflows/force-docker-build.yml
.github/workflows/force-docs-build.yml
.github/workflows/force-release.yml
.github/workflows/update-announcement.yml

**Goals:**
Fix check of release token

ci: fix proper check release token

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/force-docker-build.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: fix proper buildx version

---

docs/_templates/sidebar/brand.html

- resolves https://github.com/jina-ai/docarray/issues/690

docs: fix version selector state out of sync when entering on url

---

docs/fundamentals/client/third-party-client.md

**Goals:**
- Thank contributor
- Clean up language

docs: add contributor acknowledgement, clean up language

---

docs/fundamentals/k8s.md

- Fix English bugs
- Fix JCloud box link
- Move JCloud section to top
**Goals:**
- Fix bugs
- Make JCloud more visible

docs(k8s): fix box link; mv jcloud to top; small language fixes

---

docs/fundamentals/jcloud/index.md

**Goals:**
Have some common wording to Jina AI Cloud

docs: renaming to Jina AI Cloud

---

pyproject.toml
setup.py

chore: move setup requirements from setup.py to pyproject.toml

---

jina/checker.py
jina/orchestrate/flow/base.py
jina/orchestrate/flow/builder.py
jina/orchestrate/pods/container.py
jina/orchestrate/pods/factory.py
jina/orchestrate/pods/helper.py
jina/parsers/create.py
jina/parsers/flow.py
jina/parsers/helper.py
jina/parsers/orchestrate/deployment.py
jina/parsers/orchestrate/pod.py
jina/parsers/orchestrate/runtimes/head.py
jina/parsers/orchestrate/runtimes/runtime.py
jina/parsers/orchestrate/runtimes/worker.py
jina/parsers/ping.py
jina/serve/executors/decorators.py
jina/serve/gateway.py
jina/serve/runtimes/asyncio.py
jina/serve/runtimes/gateway/__init__.py
jina/serve/runtimes/gateway/graph/topology_graph.py
jina/serve/runtimes/head/__init__.py
jina/serve/stream/__init__.py

**Goals:**
Remove unneeded imports

chore: remove unneeded imports

---

jina/serve/networking.py
tests/unit/serve/instrumentation/conftest.py
tests/unit/serve/instrumentation/test_gateway_metric_labels.py
tests/unit/serve/instrumentation/test_instrumentation.py

fix: missing recording logic in connection stub metrics

---

docs/fundamentals/flow/create-flow.md
docs/fundamentals/flow/index.md
docs/fundamentals/flow/remarks.md
docs/get-started/install/windows.md

docs: fix link to multiprocessing spawn section and highlight entrypoint protection

docs: fix link to multiprocessing spawn section and highlight entrypoint protection

---

conda/meta.yaml
extra-requirements.txt
jina/helper.py
jina/resources/extra-requirements.txt
scripts/create-conda-recipe.py

Update conda recipe to remove those packages that do not have a conda recipe

chore: update conda recipe script

---

jina/types/request/data.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove useless print

---

extra-requirements.txt
jina/resources/extra-requirements.txt

**Goals:**
Bump up to newest jina-hubble-sdk that supports Conda

chore: bump hubble sdk

---

docs/fundamentals/client/third-party-client.md

Add reference to Kotlin client provided by community

docs: add reference to kotlin client by community

---

tests/unit/serve/gateway/test_gateway.py
tests/unit/test_gateway.py

**Goals:**
- ...
- ...
- ...
- ...

test: refactor test

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: fix hub-integration parameter

---

.github/workflows/force-release.yml

- Backport ci: fix hub-integration parameter

backport `ci: fix hub-integration parameter` to hotfix-hubble-sdk-version

---

jina/serve/runtimes/gateway/graph/topology_graph.py
jina/serve/stream/__init__.py
jina/serve/streamer.py

**Goals:**
Add more prints of Exceptions to see if we are missing some handling

chore: add more prints of exceptions

---

jina/orchestrate/deployments/config/k8slib/kubernetes_tools.py

**Goals:**
Dump env vars as str so that Kubernetes does not complain

fix: dump env vars as str to k8s

---

tests/k8s/test_k8s.py
tests/k8s/test_k8s_failures.py

**Goals:**
Print exceptions raised to see if we can improve k8s tests in the future

test: print exceptions raised

---

extra-requirements.txt
jina/resources/extra-requirements.txt

Signed-off-by: Sami Jaghouar <sami.jaghouar@hotmail.fr>
testing whereas we need crypto dependenc

chore: test ci without crypto dependency

---

jina/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: update jina version

---

extra-requirements.txt
jina/resources/extra-requirements.txt

**Goals:**
Remove otel-semantic-convention to avoid `jina[devel]` install problem

ci: remove otel-semantic-convention

---

docs/correct_some_requirements.sh

chore: fix old docs script

---

jina/serve/networking.py
tests/integration/runtimes/test_network_failures.py

**Goals:**
Try to add more information to ease debugging

refactor: add more debug info to prints

---

docs/envs/index.md
jina/__init__.py
jina/serve/gateway.py
jina/serve/streamer.py
tests/unit/orchestrate/flow/flow-construct/test_flow_custom_gateway.py
tests/unit/serve/gateway/test_gateway.py
tests/unit/yaml/dummy_gateway_get_streamer.py

Add get_streamer helper function

feat: add get_streamer helper and inject streamer info

---

Dockerfiles/pip-perf.Dockerfile
jina/clients/__init__.py
jina/orchestrate/flow/base.py

feat: create new Dockerfile with perf tools

---

jina/serve/stream/__init__.py

chore: change type hint

---

docs/correct_some_requirements.sh

**Goals:**
- fixes broken build https://github.com/jina-ai/jina/actions/runs/3694047527/jobs/6254804772

ci: fix old docs build opentelemetry sdk pin

---

docs/concepts/executor/dynamic-batching.md

docs: fix dynamic batching example

docs: fix dynamic batching example

---

jina/clients/mixin.py
jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py
jina/orchestrate/pods/__init__.py
jina/orchestrate/pods/container.py
jina/serve/executors/__init__.py
tests/integration/flow_dry_run/test_flow_dry_run.py
tests/integration/override_config_params/worker/flow.yml

**Goals:**
Avoid using threads to wait for ready because they do grpc checks. GRPCIO does not play well with threads and processes

refactor: do the flow readiness check async and not in thread

---

.github/workflows/cd.yml
.github/workflows/ci.yml
setup.py

**Goals:**
- resolves #5525 
Limitations
- The flow currently has a bug where it sometimes will hang when using grpcio versions above 1.49.0

fix: support python 3.11

---

Dockerfiles/debianx.Dockerfile
Dockerfiles/pip-perf.Dockerfile
Dockerfiles/pip.Dockerfile

Fix docker builds for python 3.11

fix: add gcc-c++ and python devel for python 3.11

---

jina/serve/stream/__init__.py
tests/integration/issues/github_5543/test_reentrant_flows.py

**Goals:**
Fix the problem when Flow is  started multiple times in same process, should improve the CI stability

fix: do not raise exception to end iteration

---

docs/cloud-nativeness/k8s.md
docs/concepts/client/third-party-clients.md
docs/concepts/flow/basics.md
docs/concepts/flow/index.md
docs/concepts/gateway/index.md

**Goals:**
- The reference link to the `gateway` is not set properly.

docs: fix the reference to gateway

---

tests/unit/orchestrate/flow/flow-async/test_asyncflow.py

**Goals:**
Cover tests of Async Client and stream False option

test: add tests for stream false and async flow

---

jina/orchestrate/deployments/install_requirements_helper.py

**Goals:**
Remove unwanted warning

fix: remove unwanted warning

---

jina/clients/request/helper.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: removing seemingly useless line

---

jina/clients/request/__init__.py
jina/clients/request/asyncio.py
jina/clients/request/helper.py
tests/integration/v2_api/test_func_routing.py
tests/unit/clients/test_asyncio.py
tests/unit/clients/test_helper.py

refactor: remove dead code, improve test coverage and fix convoluted client code

---

setup.py

add python 3.11 classifier to setup.py

chore: add python 3.11 classifier to setup.py

---

docs/concepts/flow/index.md

**Goals:**
- clarifies issue in #5596

docs: caution users about exceptions inside Flow context

---

tests/integration/runtimes/test_network_failures.py

Signed-off-by: Johannes Messner <messnerjo@gmail.com>
**Goals:**
there was a failing test on master that relied on wolf and was affected by a wolf server side change. this PR makes this test independent of wolf, fixing the issue

test: fix test by not relying on wolf

---

jina/orchestrate/flow/base.py

**Goals:**
Avoid problems of concurrency with `urllib`

refactor: no need to run summary in thread

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Signed-off-by: samsja <sami.jaghouar@hotmail.fr>
this pr fix the cd for docarray v2 test

ci: add docarray v two in cd

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py
jina/orchestrate/orchestrator.py

chore: add telemetry start and stop events for deployment

chore: add telemetry start and stop events for deployment

---

jina/orchestrate/flow/base.py

**Goals:**
Try to fix CI segfaults

refactor: handle rich and threads differently

---

docs/concepts/executor/hub/push-executor.md
docs/concepts/executor/hub/use-hub-executor.md

**Goals:**
- This PR aims to document about the arm64 architecture support of jina hub docker images.

docs(hub): document about arm64 architecture support

---

docs/cloud-nativeness/opentelemetry.md
docs/concepts/client/instrumentation.md

**Goals:**
- provide a more concrete local example for the confusion in https://github.com/jina-ai/example-grafana-prometheus/issues/4

docs: refactor example code for experimenting with Otel

---

jina/serve/executors/__init__.py

closes: https://github.com/jina-ai/jina/issues/5626

chore: deprecate executor serve and to_kubernetes_yaml methods

---

docs/concepts/gateway/customization.md

docs: fix jina base image required for custom gateway

docs: fix jina base image required for custom gateway

---

docs/concepts/executor/serve.md
jina/exporter.py
jina/orchestrate/deployments/__init__.py
jina/orchestrate/deployments/config/docker_compose.py
jina/orchestrate/flow/base.py
jina/serve/executors/__init__.py
tests/docker_compose/conftest.py
tests/docker_compose/test_deployment_docker_compose.py
tests/docker_compose/test_flow_docker_compose.py

**Goals:**
- ...
- ...
- ...
- ...

feat: add `to_docker_compose_yaml` to Deployment

---

docs/api-rst.rst

docs: add deployment to python api docs

docs: add deployment to python api docs

---

docs/concepts/executor/deployment-yaml-spec.md
docs/concepts/executor/serve.md
docs/concepts/flow/yaml-spec.md
docs/concepts/flow/yaml-vars.md

closes: https://github.com/jina-ai/jina/issues/5658 https://github.com/jina-ai/jina/issues/5627

docs: deployment yaml

---

docs/concepts/jcloud/yaml-spec.md

**Goals:**
- ...
- ...
- ...
- ...

docs(jcloud): fix storage kind

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py
tests/integration/deployments/test_deployment.py

minor revisions to the code base

chore: minor revisions

---

jina/orchestrate/flow/base.py

feat: add survey placeholder

---

tests/integration/hub_usage/test_hub_usage.py
tests/unit/orchestrate/deployments/config/test_docker_compose_pod_config.py
tests/unit/orchestrate/deployments/config/test_helper.py
tests/unit/orchestrate/deployments/config/test_k8s_deployment_config.py

**Goals:**
- Make `_mock_fetch` more general so it's less likely to break next time when the signature of the fetch function changes again.

test(hub): make less signature assumptions in _mock_fetch

---

jina/orchestrate/flow/base.py

fix: fix survey message

---

docs/concepts/jcloud/yaml-spec.md

**Goals:**
- add docs for https://github.com/jina-ai/jina-operator/pull/263

docs: add traces support document

---

jina/serve/runtimes/asyncio.py

**Goals:**
- ...
- ...
- ...
- ...

chore: add SIGSEGV handler to runtimes

---

tests/integration/docarray_v2/test_v2.py

fix a tiny potential bug in the tests of docarray v2

test: fix tests v2

---

README.md

Various fixes:
- Wording
- Styling
- Make code more readable

docs(readme): alex fixes

---

jina/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: update version

---

.github/workflows/ci.yml
jina/proto/build-proto.sh
jina/proto/pb/jina_pb2.py

closes: https://github.com/jina-ai/jina/issues/5701

fix: docarray v2 support with protobuf 4

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py

**Goals:**
Avoid known warnings appearing in colab where async coroutines are never awaited.

fix: hide known warnings in google colab

---

README.md

docs: add warning about cleaning up the flow

docs: add warning about cleaning up the flow

---

.github/workflows/cd.yml
.github/workflows/ci.yml
jina/orchestrate/deployments/__init__.py
jina/orchestrate/deployments/config/k8s.py
jina/orchestrate/flow/base.py
jina/proto/build-proto.sh
jina/proto/pb/jina_pb2.py
tests/k8s/test_k8s_deployment.py
tests/unit/orchestrate/deployments/test_deployments.py

**Goals:**
Fix replicas deployment and connect to the proper Worker

fix: fix deployment replication and host respecting

---

docs/concepts/gateway/customization.md

Cleaning up English and markdown formatting.
This page is still Flow-centric - will wait for Orchestration changes before fixing that aspect

docs(custom-gateway): polish english

---

extra-requirements.txt
jina/resources/extra-requirements.txt

test: limit portforward version

---

jina/serve/runtimes/head/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: health check ready after starting server

---

README.md
jina/orchestrate/pods/__init__.py
jina/serve/networking/utils.py
jina/serve/runtimes/asyncio.py
tests/integration/runtimes/test_warmup.py
tests/unit/orchestrate/deployments/test_deployments.py

feat: use grpc health checks to wait for pods to ready

feat: use grpc health check to wait for ready

---

jina_cli/api.py

**Goals:**
Change to adapt to latest refactor

chore: change how to assign name

---

README.md
docs/index.md

fix readme link
closes: https://github.com/jina-ai/jina/issues/5737

docs: add readme link

---

docs/concepts/executor/docarray-v2.md
tests/integration/docarray_v2/test_v2.py

fix: adapt to docarray v2 update

fix: adapt to docarray v2 update

---

docs/_templates/page.html
docs/conf.py

docs: remove docs qa

---

jina/serve/networking/utils.py

**Goals:**
Revert default grpc options.
- resolves #5748

fix: revert grpc default options

---

README.md

closes https://github.com/jina-ai/jina/issues/5757

docs: fix notebook colab link

---

scripts/get-openapi-schemas.py

**Goals:**
Fix openAPI schema generation for cd

cd: fix get openapi schemas

---

.github/workflows/ci.yml
jina/_docarray.py
tests/integration/docarray_v2/test_v2.py

fix docarray v2 issue after renaming

fix: fix docarray v2 issue

---

jina/orchestrate/flow/base.py

**Goals:**
- ...
- ...
- ...
- ...

chore: hide survey if env is set

---

jina/serve/runtimes/servers/composite.py

**Goals:**
- ...
- ...
- ...
- ...

chore: add backwards compatibility

---

.github/workflows/stateful-build-wheels.yml

fix: build and publish wheels in ci

fix: build and publish wheels in ci

---

docs/how-to/gpu-executor.md
docs/makedoc.sh

fix docs building post proto refactorization

fix: fix docs building post proto refactor

---

README.md

add transformers and sentencepiece in pip install commands
add import line in example python file:
from translate_executor import Translator

chore: update README.md to handle problems during step by step learning

---

jina/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: bump version for release

---

docs/concepts/preliminaries/index.md
docs/concepts/serving/executor/create.md
docs/tutorials/deploy-model.md

**Goals:**
- ...
- ...
- ...
- ...

docs: point to legacy documentarray docs

---

jina/serve/helper.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

test: fix docarray v2 comp tests

---

jina/serve/runtimes/head/request_handling.py
tests/integration/instrumentation/test_container_instrumentation.py
tests/integration/instrumentation/test_flow_instrumentation.py
tests/unit/orchestrate/flow/flow-construct/test_flow_except.py

**Goals:**
- ...
- ...
- ...
- ...

test: fix some tests in CI

---

docs/concepts/serving/executor/hub/hub-portal.md
docs/concepts/serving/executor/hub/index.md
docs/concepts/serving/executor/hub/sandbox.md
docs/jina-ai-cloud/index.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix broken links

---

.github/workflows/ci.yml
jina/clients/base/helper.py
jina/clients/base/http.py
jina/orchestrate/deployments/__init__.py
jina/serve/executors/__init__.py
jina/serve/runtimes/gateway/health_model.py
jina/serve/runtimes/gateway/models.py
jina/serve/runtimes/worker/http_fastapi_app.py
jina/types/request/data.py
tests/integration/deployment_http_composite/test_deployment_http_composite_docarray_v2.py

**Goals:**
- ...
- ...
- ...
- ...

feat: add support to HTTP and Composite Deployment with docarray v2

---

jina/orchestrate/flow/base.py

**Goals:**
- ...
- ...
- ...
- ...

chore: fix link to survey

---

extra-requirements.txt
jina/resources/extra-requirements.txt

Fix CI problems cause by https://github.com/docker/docker-py/issues/3113

chore: pin urllib

---

tests/unit/orchestrate/deployments/test_deployments.py
tests/unit/serve/executors/test_executor.py

**Goals:**
- ...
- ...
- ...
- ...

test: fix test private exec

---

jina/orchestrate/deployments/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove non-existing property

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix link to docs for Http

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: try to fix CD

---

.github/workflows/cd.yml
.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci:  fix cd

---

.github/workflows/cd.yml
.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: small fix in cd

---

.github/workflows/cd.yml
.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: small cd fix

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: fix cd

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: fix fetch depth to get right num commits

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: try to fetch inside the step

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/force-release.yml
docs/concepts/orchestration/scale-out.md
setup.py

**Goals:**
- ...
- ...
- ...
- ...

ci: fix prerelease

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: try to fix build wheels on mac archs

---

docs/concepts/orchestration/scale-out.md
jina/orchestrate/deployments/__init__.py
jina/serve/executors/decorators.py

**Goals:**
- ...
- ...
- ...
- ...

chore: change docstring of write decorator

---

docs/concepts/orchestration/scale-out.md

**Goals:**
- ...
- ...
- ...
- ...

chore: fix link in stateful

---

jina/orchestrate/deployments/__init__.py
jina/orchestrate/flow/base.py

fix: fix link to docs and redocs

---

jina/orchestrate/flow/base.py
jina_cli/autocomplete.py
tests/integration/flow_dry_run/test_flow_dry_run.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix disallow list of arguments

---

docs/yaml-spec.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix links in yaml specs

---

extra-requirements.txt
jina/clients/request/asyncio.py
jina/resources/extra-requirements.txt
jina/serve/stream/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove aiostream dependency

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

chore: try to fix force release

---

jina/serve/executors/decorators.py
tests/unit/serve/executors/test_executor.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix instantiate of Executor with `write` decorator

---

jina/__init__.py
jina/helper.py

**Goals:**
- ...
- ...
- ...
- ...

chore: try fix setting start method

---

jina/serve/consensus/jina_raft/rpc.go
jina/serve/networking/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove annoying message for debug

---

jina_cli/autocomplete.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

test: add test with shaped ndarray

---

jina/serve/runtimes/head/request_handling.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix isse in head missmatch endpoint

---

jina/orchestrate/deployments/__init__.py
jina/serve/runtimes/worker/request_handling.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: ensure closing Executor at shutdown in HTTP Deployment

---

docs/jina-ai-cloud/index.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix links in docs

---

jina/serve/runtimes/helper.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix tags doc schema

---

Dockerfiles/debianx.Dockerfile

**Goals:**
- ...
- ...
- ...
- ...

ci: fix debianx Dockerfile

---

jina/orchestrate/deployments/config/k8s.py
tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py

**Goals:**
- ...
- ...
- ...
- ...

fix: consider env from secrets in gateway

---

tests/unit/clients/python/test_request.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove bad tests

---

jina/serve/runtimes/asyncio.py

**Goals:**
- ...
- ...
- ...
- ...

chore: change reported name

---

jina/serve/runtimes/worker/request_handling.py
tests/integration/hot_reload/exec4/config.yml
tests/integration/hot_reload/exec4/my_executor4.py
tests/integration/hot_reload/my_executor_4_new.py
tests/integration/hot_reload/test_hot_reload.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix reloading Executor when is loaded from `config.yml`

---

jina/orchestrate/deployments/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: head and gateway start later

---

jina/orchestrate/deployments/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove daemon

---

jina/orchestrate/deployments/__init__.py
jina/serve/networking/__init__.py
jina/serve/runtimes/gateway/graph/topology_graph.py
jina/serve/stream/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove daemon from add voter

---

jina/serve/consensus/jraft.go

**Goals:**
- ...
- ...
- ...
- ...

chore: remove AddVoterError unused object

---

jina/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: upgrade version to 3.18.0

---

jina/orchestrate/flow/base.py

Something changes in the upstream that made our `plot` fail. This PR fixes it

fix: fix plot of Flows

---

extra-requirements.txt
jina/resources/extra-requirements.txt

Silence `Dependabot` security alert

chore: change urllib minimal requirement

---

CONTRIBUTING.md

**Goals:**
- ...
- ...
- ...
- ...

docs: dummy commit to pre release

---

.github/workflows/cd.yml
jina/serve/stream/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

ci: fix update schema in CD

---

extra-requirements.txt
jina/resources/extra-requirements.txt

**Goals:**
- ...
- ...
- ...
- ...

ci: limit pydantic version

---

jina/helper.py
tests/unit/test_helper.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix is generator detection

---

jina/clients/mixin.py

**Goals:**
- ...
- ...
- ...
- ...

fix: apply return_type also when return responses

---

jina/serve/runtimes/gateway/graph/topology_graph.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix validation with default endpoint

---

jina/orchestrate/flow/base.py
jina/serve/executors/__init__.py
jina/serve/runtimes/asyncio.py
tests/integration/docarray_v2/test_v2.py
tests/integration/docarray_v2/wrong_schema_executor.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fail fast when no valid schemas

---

jina/serve/runtimes/worker/batch_queue.py
jina/serve/runtimes/worker/request_handling.py
tests/integration/docarray_v2/test_v2.py
tests/unit/serve/dynamic_batching/test_batch_queue.py

**Goals:**
- ...
- ...
- ...
- ...

fix: dynamic batching with new docarray

---

.github/workflows/force-release.yml

**Goals:**
- fix hub-integration workflow

ci: bump up python version to 3.8

---

docs/concepts/jcloud/configuration.md

**Goals:**
- Add docs for jcloud horizontal pod autoscale

docs: add docs for jcloud horizontal pod autoscale

---

jina/helper.py
jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix example shown in SwaggerUI for Flow with HTTP

---

jina/serve/runtimes/servers/__init__.py
jina/serve/runtimes/servers/composite.py

**Goals:**
- ...
- ...
- ...
- ...

chore: refactor CompositeServer for better extendability

---

jina/serve/runtimes/servers/grpc.py

**Goals:**
- ...
- ...
- ...
- ...

chore: remove useless import

---

jina/serve/runtimes/worker/request_handling.py

fixes the validation error message

fix: fix streaming validation error message

---

README.md

**Goals:**
- ...
- ...
- ...
- ...

docs: remove include gateway arg

---

jina/clients/base/helper.py
jina/clients/base/http.py
jina/serve/runtimes/gateway/graph/topology_graph.py
jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
jina/serve/runtimes/gateway/streamer.py
jina/serve/runtimes/worker/http_fastapi_app.py
jina/serve/stream/__init__.py
jina/types/request/data.py
tests/integration/docarray_v2/test_streaming.py

**Goals:**
- ...
- ...
- ...
- ...

feat: support streaming in Flow with one Executor

---

jina/serve/runtimes/worker/request_handling.py

**Goals:**
- ...
- ...
- ...
- ...

fix: respect req-id from client

---

docs/concepts/serving/executor/add-endpoints.md

**Goals:**
- ...
- ...
- ...
- ...

docs: add note about flow with one executor supported

---

jina/serve/runtimes/helper.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

feat: expose richer OpenAPI.json from Flow with HTTP

---

extra-requirements.txt

**Goals:**
- ...
- ...
- ...
- ...

chore: fix uvicorn version to avoid breaking test

---

jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
jina/serve/runtimes/worker/http_fastapi_app.py

**Goals:**
- ...
- ...
- ...
- ...

fix: show examples in SwaggerUI

---

jina/serve/runtimes/gateway/graph/topology_graph.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix caching models from all endpoints, inputs and outputs

---

docs/concepts/preliminaries/index.md
docs/get-started/create-app.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix errors in getting started and preliminaries

---

docs/get-started/create-app.md

docs: remove an extra backtick in create-app.md

---

README.md

**Goals:**
- ...
- ...
- ...
- ...

chore: update tag to add model serving

---

.github/workflows/ci.yml
extra-requirements.txt
jina/resources/extra-requirements.txt
tests/k8s/conftest.py
tests/k8s/test_k8s_failures.py
tests/k8s/test_k8s_flow.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix install issue

---

setup.py

In the setup.py file there are some constant text that are hardcoded into the file, in this PR those hardcode text are converted into constants for better code readability

refactor: refactor the setup.py file

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: enable prerelease

---

jina/serve/runtimes/gateway/graph/topology_graph.py

**Goals:**
- ...
- ...
- ...
- ...

chore: make message more explicit to see error

---

jina/serve/consensus/run.go

**Goals:**
- ...
- ...
- ...
- ...

fix(consensus): free more cstrings

---

.github/workflows/force-release.yml

**Goals:**
Remove hub-integration test

ci: remove hub integration test

---

docs/concepts/serving/executor/dynamic-batching.md

**Goals:**
There was an incorrect line where dynamic batching configs are explaining, resulting in the feature not working.

docs: fix line explaining dynamic batching in yaml

---

README.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix readme code

---

docs/_templates/page.html

**Goals:**
- resolves issue #6089
- so I have changed twitter logo to the latest one. Before we were getting twitter logo from fabawsome.com I just found the latest logo there and changed it to that 
- ...
- ...
- ...

 Upated Twitter logo: solved issue #6089

---

README.md

chore: fixed spelling error in README

---

docs/_templates/page.html

**Goals:**
- ...
- ...
- ...
- ...

chore: revert twitter logo change

---

.github/workflows/cd.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: disable prerelease

---

jina/serve/runtimes/worker/request_handling.py
tests/conftest.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: call extend rest interface in worker

---

jina/orchestrate/pods/container.py
jina/serve/networking/__init__.py
jina/serve/runtimes/asyncio.py
jina/serve/runtimes/gateway/request_handling.py
jina/serve/runtimes/gateway/streamer.py
jina/serve/runtimes/head/request_handling.py
jina/serve/runtimes/servers/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: use asyncio Events over threading Events

---

jina/serve/executors/run.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: fix run stateful in docker

---

jina/serve/runtimes/worker/batch_queue.py
tests/integration/docarray_v2/test_v2.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: small timer refactor

---

docs/concepts/orchestration/flow.md

**Goals:**
- ...
- ...
- ...
- ...

docs: fix topology documentation

---

jina/serve/runtimes/helper.py
tests/unit/serve/runtimes/test_helper.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix issue with float

---

jina/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

chore: upgrade ver

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/force-release.yml
jina/__init__.py
setup.py

**Goals:**
- ...
- ...
- ...
- ...

ci: test ci

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

fix: update force-release.yml

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: update force-release.yml

---

jina/serve/executors/__init__.py
jina/serve/runtimes/worker/request_handling.py
tests/integration/docarray_v2/csp/SampleExecutor/executor.py
tests/integration/docarray_v2/csp/test_sagemaker_embedding.py

**Goals:**
- ...
- ...
- ...
- ...

test: test CSP parameters

---

jina/serve/runtimes/worker/batch_queue.py
tests/integration/dynamic_batching/test_dynamic_batching.py
tests/unit/serve/dynamic_batching/test_batch_queue.py

**Goals:**
- ...
- ...
- ...
- ...

feat: avoid need data lock in batch queue

---

CHANGELOG.md
jina/resources/logging.plain.yml

**Goals:**
- ...
- ...
- ...
- ...

fix: add plain handler

---

jina/serve/runtimes/worker/batch_queue.py
jina/serve/runtimes/worker/request_handling.py
tests/integration/dynamic_batching/test_dynamic_batching.py
tests/unit/serve/dynamic_batching/test_batch_queue.py

**Goals:**
- ...
- ...
- ...
- ...

refactor: slight change in dyn batch queue

---

jina/clients/base/http.py

**Goals:**
- ...
- ...
- ...
- ...

fix: readd timeout

---

jina/clients/base/http.py

**Goals:**
- ...
- ...
- ...
- ...

fix: pass params to iolet

---

jina/serve/executors/__init__.py

**Goals:**
- ...
- ...
- ...
- ...

fix: rewrite compatible

---

tests/jinahub/test_integration.sh

**Goals:**
- ...
- ...
- ...
- ...

fix: test hubapp hubpods fix

---

jina/serve/runtimes/worker/request_handling.py

**Goals:**
- ...
- ...
- ...
- ...

fix: fix req handling sagemaker

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

cI: change build

---

.github/workflows/force-release.yml

**Goals:**
- ...
- ...
- ...
- ...

ci: pdate force-release.yml

---

extra-requirements.txt

**Goals:**
- ...
- ...
- ...
- ...

ci: test uvicorn non standard install
