jina-ai/serve

.github/workflows/ci.yml, .github/workflows/cla.yml, jina/executors/encoders/image/customtorchvision.py, jina/executors/encoders/image/torchvision.py, tests/executors/encoders/image/test_customtorchvision.py
**Issue Link**: This commit does not refer to any issue or feature request
**Description:** This commits adds the possibility to the user to use any custom saved torch models.
So far, torchvision encoders can use pretrained models from pytorch (mobilenet, alexnet , resnet and all their flavours) but it can be interested to be able to use custom models trained for a specific purpose and being able to extract feature maps from any of the layers.
Future work could imply creating a hub example on how to deploy your model as document indexer in Jina.
=> feat(executors): Add custom torch vision encoder

jina/executors/crafters/nlp/split.py, tests/executors/crafters/nlp/split.py
The Sententicizer is now 2.5 times faster.
Instead of replacing separators by a '\n' character and splitting later by the new line character, this improved version does that with one regex and using the `findall` method.
The complexity of the new algorithm is also linear but with a low constant time because it uses only one pass over the input string.
The regex also ignores spaces at the beginning and end of the sentences so no `strip` needed.
Adding two tests that show examples of questionable results of the Sentencizer.
If that is the expected behaviour, then it is good to keep those tests here to show that it is not considered a bug.
Those test are:
* Splitting by separators that appear in common constructions like floating point numbers.
* Splitting by the '\n' character. In this …
=> perf(executor): improving Sentencizer by a factor of 2.5

README.de.md, README.fr.md, README.ja.md, README.md, README.ru.md, README.zh.md, docs/chapters/101/README.fr.md, docs/chapters/101/README.ja.md, docs/chapters/101/README.md, docs/chapters/101/README.pt.md, docs/chapters/101/README.ru.md, docs/chapters/101/README.zh.md
This commit adds support to the Portuguese language on the multilingual Jina's 101 documentation.
Note that, similarly to what was done for other languages, the key Jina concepts (Document, Chunk, Executor, Pea, etc.) are not translated.
This commit supersedes PR#462.
=> docs: added support to the Portuguese language for 101

docs/chapters/io/main.md
Small typo fix and whitespace issue recognized in the **io chapter** while reading the documentation.
=> docs: remove whitespace and fix typo chapter io

jina/main/parser.py
Running the dashboard with server IP set to 0.0.0.0 does not work for me. 
The only way that I managed to get it up and running was changing from 0.0.0.0 to 127.0.0.1.
Following the instructions from the [dashboard page](https://github.com/jina-ai/dashboard), it would be useful to be able to change the server IP with a logserver config file.
I would also like to update the [dashboard documentation](https://github.com/jina-ai/dashboard#2-connect-the-dashboard-to-your-log-server) and other related documentation to say that a potential problem is the server IP, but when running:
```bash
> bash make-doc.sh server 8080
```
I got this following error:
```bash
+ docker run --rm -v /home/palotti/github/jina-ai/jina/docs/chapters/proto:/out -v /home/palotti/github/jina-ai/jina/jina/proto:/protos …
```
=> feat(helloworld): Added the option to configure the logserver via .yml

jina/clients/__init__.py, jina/clients/python/__init__.py, jina/clients/python/grpc.py, jina/clients/python/io.py, jina/clients/python/request.py
fix typos,
\*xx\* is interpreted as italic(xx), use \\* to output as \*,
delete empty :return:,
delete invalid :param args:,
:cmd: is invalid, change it to :command: in __init__.py,
":command:`jina client --help`" will appear to be bold(jina client --help) without hyperlink in html, is that the effect we want?
resolves #495
=> fix(clients): update docstring in clients

jina/flow/__init__.py
While i made my way through the flow api code, i recognized that the build function has a `inplace` param, while e.g. `add` method exposes the `copy_flow` variable. I thought it might make more sense to have just one variable name. I am not sure about backwards compatibility, as this build method should be used just internally?
=> refactor(flow): refactor build inplace param

jina/drivers/__init__.py, jina/drivers/convert.py, jina/drivers/craft.py, jina/drivers/encode.py, jina/drivers/filter.py, jina/drivers/helper.py, jina/drivers/index.py, jina/drivers/prune.py, jina/drivers/reduce.py, jina/drivers/score.py, jina/drivers/search.py, jina/executors/indexers/keyvalue/proto.py, tests/test_driver_if.py, tests/yaml/test-if-encode1.yml, tests/yaml/test-if-encode2.yml, tests/yaml/test-if-flow.yml, tests/yaml/test-ifdriver1.yml, tests/yaml/test-ifdriver2.yml
`if` expression is added to `BaseDriver` to allow user filter docs/chunks by a *single expression*.
Examples:
only encode MIME `text/*`
```yaml
!Encode1
requests:
on:
IndexRequest:
- !EncodeDriver
if: doc.mime_type.startswith('text')
```
One can also use it in Python:
only prune docs with even `doc_id`
```python
class PruneEvenDriver(PruneDriver):
if_expression = 'doc.doc_id % 2 ==0'
def __init__(self, pruned=('text',), level='doc', *args, **kwargs):
super().__init__(pruned, level, *args, **kwargs)
```
- Does not work with "compositional expression":
- Like the `lambda` function, `if` supports the **single expression** only: https://docs.python.org/3/reference/expressions.html
- Can not filter `docs` AND `chunks` at the same time, e.g. `doc.doc_id % 2 == 0 && chunk.chunk_id % 2 == 0` does …
=> feat: add `if` expression to BaseDriver

jina/executors/encoders/audio/fairseq.py, tests/executors/encoders/audio/test_fairseq.py
Wav2vec is trained and designed for 16 kHz sampling rate. The resampling of the input audio signal to 16 kHz should improve embedding quality.
=> feat(encoder): improve wav2vec encoder with signal resampling

CONTRIBUTING.md
Rewrite to improve community engagement and have all info in one place (previously duplicated in pinned issue and prior CONTRIBUTING doc)
I've also included my own basic contact info in there, since the doc is all about onboarding, and that's what I'm here for
=> docs(contributing): make more developer friendly

jina/__init__.py, jina/hubapi/docker.py, jina/main/parser.py, release.sh
doesn't work with token though https://github.com/peter-evans/dockerhub-description/issues/10
=> feat(hub): add docker readme push

CODE_OF_CONDUCT.md
To enhance our [community profile](https://github.com/jina-ai/jina/community) and show we're welcoming to new contributors, GitHub recommends adding a code of conduct. I took this one from GitHub's [recommended source](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
=> docs(code-of-conduct): initial commit

jina/peapods/zmq.py
https://github.com/jina-ai/jina/issues/622
https://github.com/zeromq/pyzmq/blob/60e0744e1aed9bebee376268c954582e3b2e393e/zmq/eventloop/zmqstream.py#L452
receives a `None` message and as sockets are already closed the warning is logged.
=> fix(peapods): got events closed stream

jina/executors/encoders/helper.py, jina/executors/encoders/nlp/transformer.py, tests/executors/encoders/nlp/test_transformer.py
**Issue link**
https://github.com/jina-ai/examples/issues/90
**Description**
Small indexing error when trying to create the prune mask if cls_pos is 'tail' as in the case of model xlnet-base-cased.
Fix the indexing issue, add a couple of tests with the required model in the issue.
Identified another issue while running tests that some models do not implement _resize_token_embeddings_
=> fix(encoders): fix mask prune creation

jina/drivers/craft.py, jina/executors/crafters/audio/io.py, jina/executors/crafters/image/io.py, jina/executors/crafters/numeric/io.py, tests/executors/crafters/image/test_io.py, tests/executors/crafters/numeric/test_io.py
PR implementing proposal from #620. Linked PR in examples: https://github.com/jina-ai/examples/pull/92
- ImageReader inherits from BaseDocCrafter and returns one document and not chunks. 
- ArrayReader and AudioReader return a document dict, so no offset provided.
- Add tests of image reading from buffer, since often pod may not have the images in a local uri.
- Use CopyFrom in DocCraftDriver to pass blob message field. Avoid error: **_assignment not allowed to field in protocol message object_**
=> refactor(crafters): io crafters should craft documents

docs/chapters/101/README.md
Just added a link to the top of 101 to our [blog post](https://medium.com/@jina_ai/what-is-jina-and-neural-search-7a9e166608ab) explaining neural search and Jina. Currently linking to Medium since blog not up on our own website yet. When we have our own blog I'll change the link
=> docs(101): add link to explain basics of neural search

jina/executors/indexers/vector/sptag.py, tests/executors/indexers/keyvalue/test_leveldb.py, tests/executors/indexers/vector/test_faiss.py, tests/executors/indexers/vector/test_nmslib.py, tests/executors/indexers/vector/test_numpy.py
- Add FaissIndexer tests
- Split vector indexer tests
- Use context manager from executor to avoid closing file handles explicitly. This pattern may save some headaches in the future since some may forget to close.
=> test(indexers) split indexer tests  and add faiss indexer test

jina/executors/indexers/vector/faiss.py
Ass nprobe parameter to FAISS Indexer. NProbe controls at search time, how many clusters are considered to search for NN in FAISS.
**Discussion**
@nan-wang 
I added the parameters in FaissIndexer constructor, but since it is a parameter that is only used at search time, seems not to be the place, because the user then would need to fix this when indexing and not being able to change it when it is serialized.
If I add nprobe to post_init, can I pass it as a constructor when loading FaissIndexer from disk?
=> feat(executors): add nprobe parameter to faiss indexer

jina/executors/indexers/vector/numpy.py, tests/executors/indexers/vector/test_annoy.py, tests/executors/indexers/vector/test_faiss.py, tests/executors/indexers/vector/test_nmslib.py, tests/executors/indexers/vector/test_numpy.py
When sorting chunks and obtaining top_k values, argsort sorts entire array. with argpartition, it guarantees that the **kth** element is in the sorted position, and the indexes before it are smaller and viceversa. Besides that no other ordering is guaranteed, but since it is later the job of **Rankers** to sort the documents at the end, it is not necessary.
=> perf(indexer): change sort method to argpartition, not sort all the array

docs/index.rst
[Flow API](https://docs.jina.ai/chapters/flow/index.html) section is not visible in the Table of Contents. I suppose there's a typo in `index.rst`. This PR fixes it, so TOC look like this.
=> fix(toc): add flow api section to table of contents

jina/executors/indexers/vector/milvusdb/milvusdbhandler.py
Closes #668 
Make **MilvusIndexer** more robust.
- Check **connection** status so to avoid calling connect multiple times.
- Hesitating if we should check **index_status** before building index, expecting further input from https://github.com/milvus-io/pymilvus/issues/236
=> refactor(milvus): check connectivity status before connecting

docs/_static/main.css, docs/template/layout.html, docs/template/searchbox.html
**Describe the feature**
Users will have a better experience using the documentation if they can easily access the search input without using their mouse.
**Your proposal**
I have implemented a feature that adds focus to the search input when a user presses the "/" key.
=> docs(search-input): focus on the search input when "/" is pressed

jina/flow/__init__.py, tests/unit/test_index.py
Running in local `pytest tests/unit/test_index.py -k 'test_two_client_route_replicas'`, found an issue in the optimization code.
It solves what was not properly covered by #667
=> fix(flow): fix access to pod edges, consider IGNORE_GATEWAY optimization should not try to optimize gateway connections

jina/__init__.py
We are excited to release Jina 0.4.0. Jina is the easier way to do neural search on the cloud. Highlights of this release include fallbacks if GPU is unavailable, FaissIndexer on GPU, and switching indexers during querying.
- Add a new value for the `on_gpu` field. Setting `on_gpu: auto` in the yaml configure will first check if a GPU device is available and fallback to CPUs when no GPU is found. #617
- Improve the accessibility of `jina helloworld`. We add a CLI argument to enable downloading via the proxy. If you are using a proxy to speed up your internet, try `jina helloworld --download-proxy http://127.0.0.1:1087`. Just replace the ip and port with your proxy settings. #595
- Support to switching between different `Indexers` during querying. A new argument, `ref_indexer`, is added …
=> 🎉 release v0.4.0

jina/peapods/pea.py, tests/unit/peapods/test_peapods.py
Changes introduced
I observed that when using multiple replicas in a pod using a docker image, docker cannot run more than one due to name collision.
Also peapods directory under unit tests has been created
Problem introduced by e437c69#diff-5c6a3cdc3670c601c655fdd1b5c76bec
=> fix(peas): fix pea names with replicas

jina/executors/encoders/helper.py, jina/executors/encoders/nlp/transformer.py, tests/unit/executors/encoders/nlp/test_mock_transformer.py, tests/unit/executors/encoders/nlp/test_transformer.py
Resolves #691
Main change:
* all models from https://huggingface.co/models are now available. It can be done via `AutoModelForPreTraining`
Other changes
* Fixed bug in `prune_mask`
* Added a heuristic for automatic creation sequence embedding from its tokens (if BERT-like, use first token, else last)
* Used `batch_encode_plus` to simplify batching
* `max_length` is set to `None` - so batches will be padded to largest sequence. I think user should determine this parameter based on the task
* Re-implemented saving logic. I got lost in fields like `raw_model_path`, `tmp_model_path`, so instead I just added `model_save_path` field. 
* Added unit tests that are using mock transformer model. The reason is that they can be run relatively (tokenizer is still downloaded) quickly as huge amount of …
=> Support more pre-trained models for Transformer Encoder

tests/unit/drivers/querylang/queryset/test_lookup.py, tests/unit/drivers/querylang/test_filterql_driver.py
Add tests for `LookupLeaf` which is a key component of the `QueryLanguageDrivers`. Tests for FilterQL have been disabled because I have no clear vision of the expected output, it calls `del doc` in document, which is not clear what it does, maybe it should return a boolean, and in case the boolean is true, that document must be cleared from the document in the `protobuf` syntax?
=> tests(querylang): add lookup and filterql tests

.github/workflows/cd.yml, .github/workflows/ci.yml
Runs tests and coverage reports when merge on master happens, intentds to solve #711 
I would like to know if I can abstract these [`unit-test, integration-test. codecov`] steps into its own single `.yml `file to be called from any workflow.
=> feat(ci): add tests and coverage when push on master

jina/flow/__init__.py, jina/helper.py, jina/resources/executors._merge_all.yml, tests/unit/flow/test_flow_merge.py
@JoanFM are these two unittests describing what you mentioned in the Slack?
`test_this_will_fail` will fail, the log shows it waits for 4 parts. This is because we construct the Flow from one direction and `num_parts` is set by counting the number of emissions. 
```
r1@39041[I]:collected 1/4 parts of IndexRequest
r2@39044[I]:collected 1/4 parts of IndexRequest
r1@39041[I]:received "index" from gateway▸a12▸⚐
r2@39044[I]:received "index" from gateway▸a22▸⚐
r2@39044[I]:collected 2/4 parts of IndexRequest
r1@39041[I]:collected 2/4 parts of IndexRequest
```
=> test(flow): add test for double merging pathways

jina/executors/indexers/__init__.py, jina/executors/indexers/vector/milvus.py, jina/executors/indexers/vector/ngt.py
Some changes suggested by the usage of `mypy` as static type checker for jina.
Usage: 
```bash
pip install mypy
mypy --ignore-missing-imports jina
```
This PR solves:
```bash
jina/executors/indexers/vector/ngt.py:21: error: Incompatible default for argument "epsilon" (default has type "float", argument has type "int")
jina/executors/indexers/vector/ngt.py:47: error: Signature of "query" incompatible with supertype "BaseIndexer"
jina/executors/indexers/vector/ngt.py:58: error: "append" of "list" does not return a value
```
=> refactor(indexer): changes detected by using mypy static type checker

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/cla.yml, .github/workflows/tag.yml, tests/unit/drivers/test_concat_driver.py
```
Collecting docutils<0.16,>=0.10
Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
paddlepaddle from https://files.pythonhosted.org/packages/7a/f5/34dad6d2aaf9ffaf78b64728fae8b968841090a2a00300fffd227b903a62/paddlepaddle-1.8.3-cp37-cp37m-manylinux1_x86_64.whl#sha256=290b3ec2c421571a5fd8293971e314aae1323834e8cddc05d7053b94c2f1999b (from jina==0.4.2):
Expected sha256 290b3ec2c421571a5fd8293971e314aae1323834e8cddc05d7053b94c2f1999b
Got        8424b42549292ca4205f10d299a7e55a6c2abf4314fd6a15bd402c65ee21d4aa
##[error]Process completed with exit code 1.
``` …
=> fix(cicd): fix pip cache problem

jina/executors/crafters/image/crop.py, tests/unit/executors/crafters/image/__init__.py, tests/unit/executors/crafters/image/test_crop.py, tests/unit/executors/crafters/image/test_io.py, tests/unit/executors/crafters/image/test_normalize.py, tests/unit/executors/crafters/image/test_resize.py
- Spotted an issue when calling cropping, we were not respecting that `_crop_image` expects dimensions in format (height, width). Issue was not spotted because tests were done with `square` shaped images.
- Add some test with different dimensions
**WARNING - QUESTIONS**
- Qualitatively I have checked the crop, but for `precision` issues that seem to happen when saving by `PIL` cannot test the perfect reconstruction of the `crop`. Any idea how to fix this?
=> fix(crafters): fix crop dimension

jina/clients/python/request.py, jina/helper.py
To avoid compiling the url regular expression at every `is_url` call, move it outside and do it only once.
=> fix: have url regex pattern compiled just once

jina/executors/encoders/nlp/transformer.py, tests/unit/executors/encoders/nlp/test_mock_transformer.py
- Assign properly `pad` and `eos` tokens. Transformer tests are working now (tested locally by setting env variable `JINA_TEST_PRETRAINED`
- Following https://github.com/huggingface/transformers/blob/6028ed92bd9e5471e6f8a1d23cfd95a3a63018fb/src/transformers/tokenization_utils_base.py#L1985. `pad_to_max_length=True` is enough to guarantee max length padding. It guarantees backward compatibility with older versions. This fixed some tests also for `XLNet` tests
Closes #773
=> fix: fix eos token error from transformers

.github/workflows/ci.yml
Since trying to integrate All Contributors bot, several PR will be added that just update `README.md` and `allcontributorssrc`. These patterns can safely skip `unit-test` and `integration-test` to allow faster integration of these changes.
@alexcg1
=> ci: skip ci if changes only affect README and allcontributorssrc

docs/_static/main.css, docs/template/layout.html
Added a function to minimize and maximize the Table of Contents, and canceled the scroll bar on the code in Edge Browser.
Issue Link: https://github.com/jina-ai/jina/issues/772
resolved #772 
**1.  Screenshot: init page**
**2.  Screenshot: minimize Table of Contents**
=> fix(docs): fix navigation bar hidden problem in docs

.github/workflows/ci.yml
Until found a solution, `all-contributors` PR won't be merged if these conditions are kept
=> fix: disable ci skipping

jina/executors/encoders/nlp/transformer.py, tests/unit/executors/encoders/nlp/__init__.py, tests/unit/executors/encoders/nlp/test_mock_transformer.py, tests/unit/executors/encoders/nlp/test_transformer.py
Transformers are not extracting embeddings, but a complete prob distribution over the vocabulary. 
Key finding in https://huggingface.co/transformers/model_doc/bert.html#transformers.BertModel.forward (see hidden_states in output of `forward`) 
Now `transformers test` run in local, you are welcome to try yourself
=> fix: transformers are extracting prob distrib over vocab

docs/chapters/flow/index.md
@alexcg1 @hanxiao 
We have a task to add some documentation about `jina best practices` or `patterns`. Here I showcase the schema I want to introduce and the place. Do you think is good way? Is it the right place in the docs to place it? Are we missing some common pattern that might deserve a little explanation for a user to grasp?
It would be good to review the content @hanxiao, @nan-wang, it may not be so accurate?
=> docs: add docs about common jina practices

extra-requirements.txt, setup.py
previous `pip install jina` = current `pip install jina[core]`
current `pip install jina` = previous `pip install jina[perf]`
in other words, `perf` is installed by default unless otherwise specified.
previously, without `perf`, `jina hello-world` can still run but with red warnings all over the places, bad experience
=> refactor: move base_deps from setup to extra

jina/executors/indexers/__init__.py, jina/executors/indexers/vector/__init__.py, tests/unit/executors/indexers/vector/test_numpy.py
related to #767 
one (naive) way to implement filter-then-query.
=> feat(indexer): add query by ids to BaseNumpyIndexer

jina/executors/crafters/image/normalize.py, jina/executors/encoders/image/torchvision.py, tests/unit/executors/indexers/vector/test_annoy.py, tests/unit/executors/indexers/vector/test_faiss.py, tests/unit/executors/indexers/vector/test_milvus.py, tests/unit/executors/indexers/vector/test_ngt.py, tests/unit/executors/indexers/vector/test_nmslib.py, tests/unit/executors/indexers/vector/test_numpy.py
- Change naming of VectorIndexer tests, plus remove unittest and some small refactoring
- Add check of instance when loading from `save_abspath`
=> test: refactor indexer tests and check instance type

tests/unit/executors/encoders/nlp/test_mock_transformer.py
Remove np.asarray when inputting to encoder method, no functional change, but it is less confusing when seeing this test as reference on how the encode method for nlp is used
=> test: no need of np asarray

jina/executors/indexers/vector.py
Until a new way of Ranking is introduced, for some cases as `faiss indexer` where a flat document structure is indexed and queried, we need to fully go back to sorting the elements by distance. 
Currently we cannot assume that a Ranker will do the sorting afterwards.
Linked to https://github.com/jina-ai/examples/pull/166
=> fix: go back to old sorting

README.md
Removing broken example link for my-first-jina-app, since cookiecutter doesn't work with latest Jina version
=> fix(readme): remove broken example

.github/labeler.yml, .github/workflows/cd.yml, .github/workflows/nightly.yml, .github/workflows/tag.yml, jina/drivers/__init__.py, jina/enums.py, jina/executors/__init__.py, tests/unit/test_exectype.py
- do not include hub component when building docker
- add `force_register` to `BaseExecutor` and `BaseDriver` for easing debug
=> fix(executor): add force register for easy debug

README.md
* Remove extraneous badges (things like `Jina loves open source` - I mean we're on the GitHub repo already, so that should be clear. And also badges for stuff we already have in the README like docs)
* Move docs out of tutorials and into docs
* Reorder tutorials and swap columns. Now it looks a lot emptier, but we'll re-add `my-first-jina-app` soon
* Collapse extra details under hello world
=> Fix readme 2020 09c

tests/integration/issues/867/test_close_executor.py
Simple test that spins a Pod with an Executor that `sleeps` when pickling. 
Now it passes, I want to ensure that it does not pass previous to #907 
Confirmed! This test does not work on previous versions!
=> test: add tests with executor that sleeps on save

jina/main/api.py
A follow-up on commit a53185d5bb20d84b26dd5fd6b01e61f8b9b33c6d which forgets to change `uses` to `yaml_path` in one place.
=> fix(api): change uses to yaml_path

jina/drivers/rank.py, jina/executors/rankers/__init__.py, tests/unit/drivers/test_matches2doc_rank_drivers.py
This is a suggested implementation for #891. Missing:
Open questions: 
- Rename `Match2DocRanker` to `Match2DocScorer`, since effectively only scores are provided?
- Fix allowed adjacency depth to 0, meaning only the direct matches of a document are re-scored?
- Any obvious design error when thinking about the neural search use case?
Thanks a lot for your feedback already!
=> feat: added Matches2DocRankDriver

CONTRIBUTING.md
- Code skeleton of the wizard generated using `jina hub new` command - moving this to cookiecutter README
=> fix: moving hub new template readme to cookiecutter

jina/resources/executors.requests.CompoundIndexer.yml
Keeps the text, blob and buffer in the matches after doing the retrieval from the vectorindexter
=> fix: keep text, blob and buffer after vectorsearch

extra-requirements.txt, jina/docker/checker.py, jina/docker/database.py, jina/docker/helper.py, jina/docker/hubio.py, jina/excepts.py
- Enabled `jina hub build --push` & `jina hub push` flows to update summaries to Mongodb Atlas.
- Currently reads the database credentials from `os.environ`
- Uses the following env variables 
- db_username
- db_password
- db_hostname
- db_name
- db_collection
Doing `jina hub build` - builds the docker & writes the summary json to a local file.
Doing `jina hub push` - pushed the docker to docker hub. Tries reading the json from local disk. If unable, builds its summary (without build data). writes the summary to mongo collection.
Doing `jina hub build --push` - builds the docker, pushes it to docker hub, writes the summary from build to mongo collection.
Pending - 
- Enable hub-builder to push the image too
- Enable CD in jina-hub via updated hub-builder
- Unit tests for DB related …
=> Bookkeeping for jina hub push flows

jina/docker/hubio.py, jina/helper.py
This is related to `jina hub build --test-uses`. We add a `random_name` which has `-` instead of `_`, hence we get the below error
`something wrong but it is probably not your fault. ValueError('name: empty-order is invalid, please follow the python variable name conventions')`
Also had an issue in `raises_error` to pop the right argument, when build fails & we raise error.
https://github.com/jina-ai/jina-hub/runs/1133291527?check_suite_focus=true
=> fix: issue with hyphen in random name and raise_error

tests/unit/drivers/test_recursive_traversal_tree.py
This is a new adaption of the traversal tests to do a test-driven development of the new traversal proposal. Furthermore, this allows us to decide whether this is the functionality, we want to achieve.
I choose `traversal_paths=['cmc', 'mcm']` over `traversal_paths=[['c', 'm', 'c'], ['m', 'c', 'm']`, since it easier to read, and especially in the `.yml` files it is much easier to write a list of strings instead of a list of lists of strings.
Furthermore, I added the root identifier `r` to also be able to apply a function to the roots of the trees.
=> test: proposal for the new flow traversal

jina/executors/__init__.py, tests/integration/issues/github_867/test_close_executor.py, tests/integration/issues/github_867/yaml/slowexecutor.yml, tests/unit/executors/test_set_metas.py
Without these changes, can't override `NumpyIndexer` batch_size
=> fix: fix set metas overriding default from client

jina/drivers/__init__.py, jina/drivers/craft.py, jina/drivers/querylang/select.py, jina/drivers/querylang/slice.py, jina/drivers/querylang/sort.py, jina/drivers/rank.py, jina/drivers/reduce.py, jina/drivers/search.py, jina/resources/executors._merge_all.yml, jina/resources/executors.requests.BaseRanker.yml, jina/resources/executors.requests.CompoundIndexer.yml, jina/resources/helloworld.reduce.yml, tests/unit/drivers/test_recursive_traversal_tree.py, tests/unit/drivers/test_reduce_all_driver.py
This enables traversal via explicit tree path definition. The following changes happened:
- added tree traversal itself
-- no need for `granulartiy_range`, `adjacency_range`, `recur_on` or `recursion_order` with the new approach
- added feature toggle to switch between old traversal and new traversal
-- toggle is settable globally or on a per-driver level
- hello-world runs with mixed versions: for most parts use the old traversal, for the reduce functions use the new one.
- refactored `ReduceAllDriver` in order to be more explicit about what happens and have no internal state to reduce idling memory foodprint (and be stateless).
=> feat: new tree traversal structure

jina/drivers/querylang/filter.py, jina/drivers/querylang/slice.py, jina/drivers/querylang/sort.py, jina/resources/executors.requests.BaseRanker.yml, tests/unit/drivers/querylang/test_querylang_drivers.py
This PR should demonstrate, how the adaptation of the traversal will happen. `test_querylang_drivers.py` demonstrates nicely, how things become better understandable. `use_tree_traversal=True` should be set for now, since the tree traversal is not the default, yet. The overwrite of the default `traversal_paths` should only happen, if `['c', 'r']` is not a reasonable default.
=> feat: tree traversal default for SliceQL

jina/clients/python/io.py, tests/unit/clients/python/test_client.py, tests/unit/clients/python/test_io.py
A fix for a subtle bug introduced here: https://github.com/jina-ai/jina/pull/1009/files#diff-e47ef1c2a309b9935e22d5ff1e58d7dcR30
Beforehand, only the iterator was returned and thus the file closed. Since the iterator has not iterated the file yet, it would fail in the moment it starts iterating. With the `yield` solution, the file remains open.
@Arrrlex :)
=> fix: no early file closing

jina/drivers/querylang/filter.py
There is no need to set a special default for `FilterQL`.`['c', 'r']` is perfectly fine.
=> fix: no special default for filter ql

CHANGELOG.md, CONTRIBUTING.md, release.sh
This PR fixes issue #1030.
Before, the markdown links worked fine on GitHub and the ones in the documentation did not. I tried using a different format to identify markdown anchors, but then links did not work on GitHub and did work in the documentation. I kept the latter ones, because I found them easier to read (feel free to point out if you would like me to revert back to the old markdown anchor identifiers). And to make it work I manually inserted html hyperlink tags with matching names/identifiers (i.e. `<a name=...></a>`).
- fixes existing markdown links in `CHANGELOG.md` and `CONTRIBUTING.md`
- adjusts `realase.sh` script to add hyperlink tag when adding a "realease note" to `CHANGELOG.md`
=> docs: fix markdown links in CHANGELOG.md and CONTRIBUTING.md

CHANGELOG.md, CONTRIBUTING.md
Fixes issue #1030 and markdown html link names described in #1032 to match with the ones generated by https://github.com/technote-space/toc-generator in the GitHub action defined by [contributors.yml](https://github.com/jina-ai/jina/blob/master/.github/workflows/contributors.yml).
This anchor naming convention might be ambigious - e.g. `release-note-0111` might match be a heading with version `0.11.1` as well as `0.1.11`. This should be mitigated by appending `-1`, `-2`, ... to the anchor identifiers for the subsequent headings with the same anchor identifier. I tried it on a private repository and it seems that `toc-generator` generates those links correctly - i.e. it would be `release-note-0111`, `release-note-0111-1`, `release-note-0111-2`...
=> docs: fix markdown html link names

jina/drivers/__init__.py, jina/drivers/convert.py, jina/drivers/craft.py, jina/drivers/encode.py, jina/drivers/index.py, jina/drivers/querylang/filter.py, jina/drivers/querylang/reverse.py, jina/drivers/querylang/select.py, jina/drivers/querylang/slice.py, jina/drivers/querylang/sort.py, jina/drivers/rank.py, jina/drivers/reduce.py, jina/drivers/search.py, tests/unit/drivers/test_concat_driver.py, tests/unit/drivers/test_craft_driver.py, tests/unit/drivers/test_recursive_traversal_tree.py, tests/unit/drivers/test_segmenter_driver.py
This removes the `_apply` function from jina, since there is no real use-case anymore for it. All straight-forward, except the refactoring of `ConcatEmbedDriver`.
=> refactor: remove apply function

tests/integration/level_depth/test_search_different_depths.py
This test was broken due to the `id/hash` refactoring. It should work now again. The removed `assert` does not make any sense.
=> test: added back level depth test

CONTRIBUTING.md, README.md
Based on feedback during devrel call, make Slack more prominent and instruct users to post to #general channel specifically
=> feat: emphasise slack, link direct to general channel

jina/clients/python/io.py, tests/unit/clients/python/test_io.py
The `input_lines` function must work as an iterator and not return an iterator.
=> fix: inputlines should always yield

jina/clients/python/request.py, jina/drivers/index.py, jina/drivers/search.py, jina/executors/indexers/keyvalue.py, tests/unit/drivers/test_kv_search_driver.py, tests/unit/executors/indexers/test_binary_indexer.py, tests/unit/flow/test_flow_index.py, tests/unit/flow/test_flow_multimode.py, tests/unit/test_workspace.py
- Changed invocation of `exec_fn` for `KVIndexDriver` & `KVSearchDriver`
- Test changes
=> Avoid passing whole doc to executor for BinaryPbIndexer

codecov.yml
A follow-up PR for #1054 , in 1054 coverage has back to 80% while the coverage not being updated on master branch. This one force codecov ignore `jina/hub` folder.
=> test: force ignore hub directory in config

jina/drivers/cache.py, jina/drivers/index.py, jina/drivers/querylang/queryset/dunderkey.py, jina/executors/indexers/cache.py, jina/logging/formatter.py, jina/resources/executors._unique.yml, tests/integration/incremental_indexing/inc_docindexer.yml, tests/integration/incremental_indexing/inc_vectorindexer.yml, tests/integration/incremental_indexing/test_incremental_indexing.py, tests/unit/drivers/querylang/queryset/test_dunderkeys.py, tests/unit/drivers/test_cache_driver.py, tests/unit/executors/test_route_exec.py, tests/unit/executors/yaml/route.yml
this PR is an improvement & replacement for #1062 
#1070 takes the tests from #1062 and improves this PR on the following aspects:
- #1070 does not change Protobuf, instead, it uses `tags` in our Protobuf schema
- #1070 does not change `KVIndexDriver` and `VectorIndexDriver` to unselect hit-cache-docs, instead, it uses `FilterQL` and add it to the YAML level.
- #1070 adds `DocIdCache(KVIndexer)` and `BaseCacheDriver(BaseIndexDriver)`
- shortcut executor `_unique` is introduced, one can use it in `--uses-before` when indexing to prevent repeated indexing
#1068 test code is included in this PR but the problem is not solved. #1068 wrongly diagnosed the problem, real issue is posted in #1071
=> feat: check whether a document has been already indexed

CONTRIBUTING.md, README.md
Previously I changed Slack link to redirect straight to our #general channel. However, that meant folks couldn't sign up (since they didn't have an invite)
I've now changed it back to an invite link to fix this
=> fix: slack links

jina/drivers/cache.py, jina/drivers/convert.py, jina/executors/indexers/__init__.py, jina/executors/indexers/cache.py, jina/executors/indexers/keyvalue.py, jina/resources/executors.requests.UniquePbIndexer.yml, jina/resources/executors.requests.UniqueVectorIndexer.yml, tests/integration/incremental_indexing/test_unique_indexing.py, tests/integration/incremental_indexing/uniq_docindexer.yml, tests/integration/incremental_indexing/uniq_vectorindexer.yml, tests/unit/drivers/test_cache_driver.py
Two shortcuts are added in respond to #1062 TODO 1
>  Avoid the differences of using DuplicateChecker between single-shard and multi-shards usages. For the single-shard usage, one needs to construct a CompoundIndexer consist of DuplicateChecker and the VectorIndexer/KVIndexer. While for the multi-shards, one needs to put DuplicateChecker into the uses_before. This is because the uses_before does not play any role when shards==1.
- `UniquePbIndexer`, can be directly used via
```yaml
!UniquePbIndexer
components:
- !DocIDCache {}
- !BinaryPbIndexer
with:
index_filename: doc.gz
metas:
workspace: $JINA_TEST_INCREMENTAL_INDEX_WORKSPACE
name: doc_idx
metas:
name: inc_docindexer
workspace: $JINA_TEST_INCREMENTAL_INDEX_WORKSPACE
```
- `UniqueVectorIndexer`:
```yaml
!UniqueVectorIndexer
components: …
```
=> refactor(indexer): refactor cache index add shortcuts

jina/enums.py, jina/flow/__init__.py, jina/flow/builder.py, jina/peapods/pod.py, tests/unit/flow/test_flow_eval_pod.py, tests/unit/flow/test_flow_index.py
`.eval()` will add an empty hanging Pod to the flow. No evaluation-related logic is implemented in this PR.
Examples:
```python
f = Flow().add(name='p1').add(name='p2', needs='gateway').needs(['p1', 'p2']).eval().plot(build=True)
```
```python
f = Flow().add(name='p1', parallel=3).eval().add(name='p2', needs='gateway').needs(['p1', 'p2']).eval().plot(build=True)
```
```python
f = Flow().add().eval().add().eval().add().eval().plot()
```
=> feat(flow): add eval() interface generates hanging pod

jina/executors/decorators.py, tests/unit/executors/test_decorators.py
From a bug found in `NmsLibIndexer` I found that some indexers may not only need to have `batched` data but also would need information about which `ordinal` indexers correspond to each data in a batch.
This PR tries to enable https://github.com/jina-ai/jina-hub/pull/458
**Extra change**
I have not seen where the `label` is used in the `batching` decorator and therefore I try to remove it since it results in a lot of `if - else` logic. @hanxiao @nan-wang do you know in which context it is used?
=> feat: potentially add argument of ordered indexes from batch

jina/executors/indexers/vector.py, tests/unit/executors/indexers/test_numpyindexer.py
Hi, I have recently read your great blog article on your numpy indexer (https://hanxiao.io/2020/09/21/Numpy-Tricks-and-A-Strong-Baseline-for-Vector-Index/) and saw that at query time you do a full sort on the distances to retrieve the top k candidates.
This PR suggests using numpy's partial sort implementation `np.argpartition` which runs in O(n) versus O(n * log(n)) for `np.argsort`. 
With this code change the query method does not return the top k candidates ordered like with full sort before, but it seems the system is not relying on the top k candidates being ordered, at least the docstring does not imply it.
This little example illustrates the difference, the speedup for top 10 retrieval from a 100k array is around 12 fold
```python
top_k = 10
dist = …
```
=> perf: numpy indexer use partial sort at query time

jina/enums.py, jina/parser.py, jina/peapods/pea.py, jina/peapods/pod.py
Fixes #1013 
- Edited `pea.py` to rename argument `replica_id` to `pea_id`.
- Updated `PeaRoleType`, and changed `PeaRoleType.REPLICA` to `PeaRoleType.PARALLEL` wherever it was used.
=> fix: Renamed pea replica_id to pea_id

jina/drivers/control.py, jina/peapods/pod.py, tests/integration/incremental_indexing/test_incremental_indexing.py, tests/integration/incremental_indexing/test_unique_indexing.py, tests/unit/flow/test_flow_before_after.py, tests/unit/yaml/examples/faces/flow-query.yml
- Pod context manager now allows `--uses-before` and `--uses-after` when `--parallel = 1`. Previously `uses-before` and `uses-after` are only respected when `parallel > 1`.
With this new feature, you can build a sequential (microservice-like) quote `CompoundExecutor` unquote (`before -> exec -> after`)  simply via:
```python
f = Flow().add(uses_before='before.yml', uses_after='after.yml', uses='exec.yml')
with f:
f.index(docs)
```
Another usage is to solve the `todo1` mentioned in #1062: 
> avoid the differences of using DuplicateChecker between single-shard and multi-shards usages. ...
This can now be implemented as 
```python
f = Flow().add(uses=os.path.join(cur_dir, 'docindexer.yml'), uses_before='_unique')
```
See `tests/integration/incremental_indexing/test_unique_indexing.py` for …
=> feat(pod): allow uses-before/after on single pea

CODEOWNERS
I added me as owner for `jina/drivers`. Am I right, that @bwanglzu should be the owner for `tests` instead of `jina/tests`, since the latter does not exist?
=> chore: add maximilianwerk as codeowner for drivers

.github/workflows/ci.yml
- docker `pip install .` in fresh enviroment without `devel` deps, and then `docker run hello-world`. This make sure fresh pip install always work. this to check issue such as #1122
=> test: add docker hello-world with no devel install

extra-requirements.txt
Adding `packaging` as requirement for the `hub` so that https://github.com/jina-ai/jina-hub/pull/460 can pass.
It would affect any other `hub` build
=> chore: add packaging in extra requirements

.github/workflows/code-formatting.yml
Seems like later steps are only triggered, if `failure()` is explicitly in the `if` statement.
=> style: added failure

.github/workflows/code-formatting.yml
Sorry for the first try in a row. But `failure()` is not combinable @JoanFM . Anyhow, if any step before the `black --check...` fails, the last one will fail as well and nothing bad will be committed.
=> fix: failure not combinable

.github/workflows/ci.yml, Dockerfiles/alpinex.Dockerfile, Dockerfiles/debianx.Dockerfile
Describe the bug
All of our hub docker containers contain pip cache which increases its size. This cache is useless.
Describe how you solve it
Add these to our jina dockerfiles. This will lead to smaller jina and hub images especially those with big dependencies like tensorflow and torch. This way we don't need to use flag `--no-cache-dir` in pip installs everywhere.
I also suggest disabling pip version check.
```
ENV PIP_NO_CACHE_DIR=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
```
resolved #1167
=> fix: disabled pip cache in docker

jina/drivers/evaluate.py, jina/executors/evaluators/rank/precision.py, tests/integration/evaluation/rank/yaml/evaluate.yml, tests/unit/drivers/test_rankingevaluation_driver.py
Inheriting `RankEvaluateDriver` from `FieldEvaluateDriver` makes it more flexible and specially allows the user to evaluate based on `score__value` field that is filled by the `Search` and `Rank` drivers. (See NDCG Evaluator for instance)
=> refactor: ranking evaluator inherit from field evaluator

.github/workflows/cd.yml, .github/workflows/nightly.yml
`devel` image is generated in two places:
- `cd.yml` on master merging, building x64 image
- `nightly.yml` midnight on building multi-arch devel images
Fixing these two places solves #1171
=> fix(docker): include submodule when building devel images

jina/flow/__init__.py, tests/unit/flow/test_flow.py
The explicitly defined values on pod level should have higher priority, then the ones on flow level.
=> fix: pod argument overriden by flow

jina/executors/compound.py, tests/unit/test_workspace.py
During testing, discovered error in `CompoundExecutor` not saving it's ~components~ and itself to `filename`.
1. Take out `JinaTestCase` from `test_workspace`
2. Clean up `test_workspace`
3. Save `CompoundExecutor` itself to `filename`, as it's base class (if `filename` exist).
=> test: refactor workspace test

docs/chapters/io/index.md
BaseDocCrafter was removed in #652. Now we use BaseCrafter.
=> docs(io): use new crafter base class

jina/peapods/container.py, jina/peapods/pea.py, jina/peapods/pod.py, tests/unit/peapods/test_container.py
Instead of relying on reading messages from the logs to set ready signal to the Pod, it relies in network connection with the Pea running inside docker.
To ensure that the PretrainedModelException is properly passed when building executors in the hub, we are still basing ourselves on reading log messages. Not sure if there is a solution for it
**Discussion**
Since there are 2 processes where the `ContainerPea` lives right now, if we start the `docker` container in a `detach=False` way, we may have better control on how its resources are used, and maybe we can avoid all this inner communication? I am not an expert but in non-detached mode we may be able to extract exceptions and errors?
=> fix: rely on control request to set ready docker pea

jina/executors/__init__.py, jina/executors/compound.py, jina/executors/metas.py, jina/logging/logger.py, jina/resources/executors.metas.default.yml, tests/unit/drivers/test_collect_matches_rank_driver.py, tests/unit/test_workspace.py, tests/unit/test_yamlparser.py, tests/unit/yaml/test-expand3.yml, tests/unit/yaml/test-workspace.yml
Changes `replica_id` to `pea_id` and `replica_workspace` to `pea_workspace`
=> refactor: remove replica naming

README.md
Code of conduct got moved to `.github` so was invisible. I've added a link under community
=> Docs readme code conduct

jina/drivers/control.py, jina/drivers/querylang/queryset/dunderkey.py
Since #1210 the `LogInfoDriver` is broken and here I fix it and allow to extract the wanted fields of a message via `dunder_get`
=> fix: adapt log info after lazy reading

jina/enums.py, jina/parser.py, jina/peapods/__init__.py, jina/peapods/container.py, jina/peapods/pea.py, jina/peapods/pod.py, jina/peapods/ssh.py, jina/peapods/zmq.py, tests/unit/peapods/test_ssh_remote.py, tests/unit/test_zmq_addr.py
Reason for this PR:
- we can have multiple remote access methods
- having an SSH-based remote peapod requires no extra dependency, long-term: ssh peapod is a poorman solution for novice
- help us to design better RemotePea/Pod lifecycle
Not trying to overengineer anything at the moment.
=> feat(remote): add ssh remote peapod

jina/clients/python/request.py, tests/unit/clients/python/test_request.py
To be able to receive complex `json-like` or `dict` representing documents (for instance from `jinabox`) we need to be able to interpret `dict` or `json-like str` directly into parsed documents.
=> feat: parse dict as document

.github/workflows/tag.yml, .github/workflows/update_hub.yml, scripts/jina-hub-update.py
Fixing difference between local run (via `act`) and GH environment.
**EDIT** Finished, workflow passed.
=> fix: ci hub update missing python3-setuptools

jina/parser.py
I think the remote default should be jinad.
SSHRemote does not handle proper closure of `pod` and executors, just finished the `ssh` connection ?
=> refactor: remote default should be jinad

jina/helper.py
Making the random port range configurable via environment variables. I did not add tests, since this is heavily tested in a lot of integration tests and just testing the setting of environment variables is a bit shallow.
=> feat: random port ranges are configurable

jina/peapods/pod.py, tests/unit/flow/test_remote_orchestrate.py
Without the change, in the test `assert f['pod1'].host_out == remote2` fails because it is None
=> fix: remote host_out None

.github/workflows/test-jinad.yml, jina/peapods/pod.py, tests/integration/jinad/test_simple_distributed/Dockerfile, tests/integration/jinad/test_simple_distributed/docker-compose.yml, tests/integration/jinad/test_simple_distributed/requirements.txt
@rutujasurve94 I hope this one helps:
- Use test-pip image and build it in the yaml.
- Install jinad requirements avoiding it installing jina again.
- Remove requirements installation from jina since it uses the jina:test-pip image.
- To try locally, please build jina:test-pip locally by running in the jina root:
`docker build --build-arg PIP_TAG="[devel]" -f Dockerfiles/pip.Dockerfile -t jinaai/jina:test-pip .`
After that, u can run the bash or test manually to adapt properly the asserts
=> test: help jinad integration

CHANGELOG.md, README.md, tests/unit/drivers/querylang/queryset/test_lookup.py, tests/unit/drivers/querylang/queryset/test_queryset.py
Refactor queryset unittest with new api and document type. #1329
=> test: refactor queryset with primitive type

.github/workflows/tag.yml, .github/workflows/update_hub.yml, scripts/jina-hub-update.py
**v2**
- don't bump Jina version, as it's not used by the builder
- bump _dummy_ field of **timestamp**
- check if combination of module version + jina version have been tested before (by looking up PR name)
- only open Draft PRs
- only open issues if the checks fail
- close PRs
**v1**
- traverse list of modules
- remove those that have opened issues
- try to open PR to bump version and add new jina version
- wait for PR checks to finish
- if they fail, open issue in hub
- allow for more configuration of workflow (for future separation into its own Marketplace action)
This will be submitted **as-is**, and the work for the GitHub Action hub builder will be another PR.
=> ci: automatic testing/building of hub images on new release

jina/peapods/remote.py
Send terminate signal to every Pea in remote
Will be properly tested in #1317
=> fix: send terminate to every Pea

jina/clients/python/__init__.py, tests/integration/gateway_non_blocking/flow.yml, tests/integration/gateway_non_blocking/test_gateway_non_blocking.py, tests/integration/gateway_non_blocking/yaml/fast_slow.yml, tests/integration/gateway_non_blocking/yaml/fast_slow_driver.py
Add test showing that when parallel is larger than 1, the gateway is non blocking and faster requests can be returned. Also shown that this does not happen when parallel is 1
=> test: add integ test about non blocking gateway

jina/docker/checker.py, jina/docker/hubio.py, tests/integration/hub_usage/test_hub_usage.py
- Add jina version to hub image name. Required for https://github.com/jina-ai/jina/pull/1298
- Fix unnecessary `-` being replaced with `--`
=> fix: add jina version info to docker image name

docs/chapters/flow/index.md, tests/integration/evaluation/rank/test_evaluation.py, tests/integration/evaluation/test_evaluation_from_file.py, tests/integration/issues/github_976/test_topk.py, tests/integration/level_depth/test_search_different_depths.py
Since `load_config` is a `classmethod`, we don't need to call it on a Flow object. Instead we can call the `classmethod` directly.
=> chore(flow): no constructor for class method needed

jina/helper.py, tests/unit/test_helper.py
When running `f = Flow.load_config('flow-index.yml')`, I received the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/Library/TeX/texbin/flow-index.yml'`
This is because the file `flow-index.yml` did not exist. However, the error message tells me that the file does not exist in my LaTeX folder, which is weird.
It turned out that the current helper function takes the last path in the `PATH` variable as default. For sure, this is not intended.
I changed the implementation to fire an exception instead of taking the last path as default.
=> fix(helper): search file error handling

.github/i18n/README.kr.md
This is another account of rabbits99 team. Sorry for making confuse again.
This file is new version of readme-korean.
I hope that it works well. 
Thank you
I have read the CLA Document and I hereby sign the CLA
=> fix(readme): update korean readme

jina/types/sets/chunk_set.py, jina/types/sets/match_set.py, tests/__init__.py, tests/unit/types/test_chunkset.py, tests/unit/types/test_documentset.py, tests/unit/types/test_matchset.py
blocking #1368 .
When refactoring `traverse_apply`, need a lot of chunk level test cases. While `ChunkSet.append` is not working when append document on `Sequence[Document]`. 
Why?
`docs_proto` was defined as `Union['RepeatedCompositeContainer', Sequence['Document']]`, the current implementation does not support operations on sequence of documents.
What has been changed?
1. Refactored `MatchSet` and `ChunkSet` , allow `append` operation on a list of document.
2. Add tests.
Didn't add unit test case to initialise a `DocumentSet` or `MatchSet` when `self._docs_proto`  is `RepeatedCompositeContainer`. (I was not able to initialise `RepeatedCompositeContainer` manually, while it has been covered when testing a driver).
=> refactor chunkset and matchset append method

CONTRIBUTING.md
Otherwise in github the link doesn't work: [https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#commit-message](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#commit-message)
After the fix the link works: [https://github.com/serge-m/jina/blob/docs-contributing-patch/CONTRIBUTING.md#writing-your-commit-message](https://github.com/serge-m/jina/blob/docs-contributing-patch/CONTRIBUTING.md#writing-your-commit-message)
=> docs(contributing): fix link to commit style

jina/docker/hubapi.py, jina/docker/hubio.py, tests/unit/docker/test_hub_build.py
:construction: 
As part of the Hub Updater, we want to make sure NOT to overwrite images with the same name.
=> fix: dont overwrite docker image names

jina/executors/__init__.py
We want to allow setting of `workspace` in Indexers without name. 
Brought up in #1380 , when tried setting `meta={'workspace': tmpdir}` but I get an error
like so
```    
with BinaryPbIndexer('pbdix.bin', metas={'workspace': tmpdir.strpath}) as idxer:
```
```
(<class 'AttributeError'>, AttributeError("'BinaryPbIndexer' object has no attribute 'warn_unnamed'"), <traceback object at 0x7f243731fec0>)
```
Copying the approach from here worked https://github.com/jina-ai/jina/blob/008638d3e61c20c585b376ea003be712123a6eb2/tests/unit/executors/indexers/test_numpyindexer.py#L39
```    
metas = {
'is_trained': False,
'is_updated': False,
'batch_size': None,
'workspace': f'{tmpdir}',
'name': None,
'on_gpu': False,
'warn_unnamed': False,
'max_snapshot': 0,
'py_modules': None,
'pea_id': …
```
=> fix: allow indexers to have workspace

jina/drivers/encode.py, jina/drivers/index.py, jina/drivers/predict.py, jina/drivers/search.py, jina/types/document/helper.py, jina/types/sets/document_set.py, tests/unit/drivers/test_encoder_driver.py, tests/unit/drivers/test_helper.py, tests/unit/drivers/test_predict_mock_driver.py
Note: `__str__` and `__repr__` on Jina types are out of scope of this PR
=> refactor(types): move extract embeddings and contents into docset

jina/executors/indexers/vector.py, jina/resources/helloworld.indexer.yml, tests/integration/high_order_matches/test-adjacency-integrated.yml, tests/integration/high_order_matches/test-adjacency.yml, tests/integration/incremental_indexing/uniq_vectorindexer.yml, tests/integration/incremental_indexing/vectorindexer.yml, tests/integration/jinad/test_index_query/pods/index.yml, tests/integration/jinad/test_index_query_with_shards/pods/index.yml, tests/unit/executors/indexers/test_numpyindexer.py, tests/unit/executors/yaml/npvec.yml, tests/unit/flow/yaml/numpy-indexer-1.yml, tests/unit/flow/yaml/numpy-indexer-2.yml, tests/unit/peapods/remote/yamls/indexer.yml, tests/unit/yaml/dummy_exec1.yml, tests/unit/yaml/test-compound-indexer2.yml, tests/unit/yaml/test-index-remote.yml, tests/unit/yaml/test-index.yml, tests/unit/yaml/test-joint-wrap.yml, tests/unit/yaml/test-joint.yml, tests/unit/yaml/test-multifield-indexer-2.yml, tests/unit/yaml/test-multifield-indexer.yml, tests/unit/yaml/test-query.yml
Changed default `NumpyIndexer` metric to `cosine` for better `default`
=> fix: change numpy metric cosine

jina/docker/hubio.py, jina/excepts.py, jina/parser.py, tests/unit/docker/test_hub_build.py, tests/unit/executors/indexers/test_binary_indexer.py
+ Add `--no-overwrite` option to not allow pushing image with same module version and jina version
=> fix: check jina version in hub modules when pushing

docs/chapters/101/README.zh.md
fix: redundant translation in readme Chinese
=> fix: redundant translation in readme Chinese

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/latency-tracking.yml, .github/workflows/test-hubapp-hubpods.yml, .github/workflows/test-jinad.yml
🔴 changes in https://github.com/jina-ai/jina/pull/1348 seem to make https://github.com/jina-ai/latency-tracking unusable, which implies breaking changes that were not discovered.
=> ci: add latency tracking

jina/types/request/__init__.py, tests/unit/types/request/test_common.py, tests/unit/types/request/test_request.py
Add missing tests for `types.Request`.
=> test: refactor request test

jina/flow/__init__.py, jina/flow/yaml_parser/v1.py, jina/helper.py, jina/parser.py, jina/peapods/peas/__init__.py, tests/unit/flow/test_flow.py, tests/unit/flow/yaml/flow-with-envs.yml, tests/unit/peapods/test_pods.py, tests/unit/test_cli.py
- `env` add for Flow and Pod level
- available from CLI and YAML
YAML usage:
```yaml
!Flow
version: '1'
env:
key_parent: value3  # all pods share this env var
pods:
- uses: EnvChecker1
env:
key1: value1
key2: value2
- uses: EnvChecker2
```
CLI usage: `jina pod --env key1=value1 key2=value2`
could be useful to #1414
=> feat: add `env` to pea, pod, flow cli

jina/helloworld/__init__.py, jina/helloworld/components.py, jina/helloworld/helper.py, jina/parser.py, jina/resources/helloworld.evaluator.yml, jina/resources/helloworld.flow.evaluate.yml, jina/resources/helloworld.html, jina/resources/helloworld.merge-evaluate.yml
Add Evaluation value to helllo world html
=> feat: helloworld evaluate html

jina/clients/sugary_io.py, jina/flow/__init__.py, jina/flow/asyncio.py, tests/integration/test_helloworld.py, tests/unit/clients/python/test_client.py, tests/unit/clients/python/test_io.py
fix problem in master also the test failure in #1426
=> fix(io): fix input_files/lines data_type

.github/workflows/ci.yml, .github/workflows/latency-tracking.yml
no need to reply commit lint problem manually
=> ci: add commit lint feedback

jina/executors/devices.py
I improved the `TorchDevice` docs, namely:
- set `torch.set_grad_enabled(False)` as the example does not include any training/gradients - this is good practice as it saves memory and increases performance
- `_input` tensor created using `as_tensor` with the `device` parameter - no need to explicitly check for GPU, as if only CPU is available no in-memory copy will be made
-  `_output` tensor now calls the `cpu()` method without checking for GPU - as before, if there is no GPU, then this operation is a noop, i.e. no in-memory copy will be made.
=> docs(devices): improve TorchDevice docstring

cli/autocomplete.py, jina/__init__.py, jina/clients/__init__.py, jina/clients/asyncio.py, jina/clients/base.py, jina/clients/helper.py, jina/flow/__init__.py, jina/flow/asyncio.py, jina/parser.py, jina/proto/serializer.py, jina/types/request/__init__.py, tests/integration/hub_usage/test_hub_usage.py, tests/unit/flow/test_flow.py, tests/unit/types/request/test_request.py
add `return_results` (by default = `False`) in client CLI, so that when turning on, results are returned as a list. Can be used with `Flow` and `AsyncFlow`, e.g.
`AsyncFlow`:
```python
with AsyncFlow(return_results=True).add() as f:
r = await f.index_ndarray(np.random.random([10, 2]))
assert isinstance(r, list)
assert isinstance(r[0], Response)
```
SyncFlow
```python
with Flow(return_results=True).add() as f:
r = f.index_ndarray(np.random.random([10, 2]))
assert isinstance(r, list)
assert isinstance(r[0], Response)
```
Design decision:
- dropping asyncio generator. Complicated, can not unify the Sync & AsyncFlow interface in short time.
- people who wants to use this function is more likely to fetch all result at once, otherwise, `on_done` callback is sufficient.
- complicated usage e.g. …
=> feat: return result from flow and client

jina/executors/__init__.py, jina/executors/metas.py, jina/jaml/__init__.py, tests/integration/issues/github_1545/test_executor_metas.py
Add test proving the problem with #1545
=> test: add test for 1545

tests/__init__.py, tests/unit/__init__.py, tests/unit/clients/python/test_io.py, tests/unit/docker/test_hub_build.py, tests/unit/drivers/test_cache_driver.py, tests/unit/drivers/test_reduce_all_driver.py, tests/unit/executors/indexers/test_numpyindexer.py, tests/unit/executors/test_comp_exec.py, tests/unit/executors/test_decorators.py, tests/unit/executors/test_route_exec.py, tests/unit/flow/test_flow.py, tests/unit/flow/test_flow_example_face.py, tests/unit/flow/test_flow_example_faiss.py, tests/unit/flow/test_flow_index.py, tests/unit/flow/test_flow_multimode.py, tests/unit/flow/test_flow_visualization.py, tests/unit/logging/test_logging.py, tests/unit/peapods/runtimes/container/test_container_runtime.py, tests/unit/peapods/runtimes/remote/jinad/test_api.py, tests/unit/test_driver_yaml.py, tests/unit/test_exectype.py, tests/unit/test_index.py, tests/unit/test_index_remote.py, tests/unit/test_workspace.py, tests/unit/test_yamlparser.py
Revert #1400 in #1349
Reason:
> please do not do any pathlib refactoring anymore. Not worth it, as none of our methods accepts Path-like object as arg. As a consequence, I observe this pattern str->Path->str in a lot of places in the tests. What's the purpose of doing this if you eventually have to convert it into str? for just saving +'/'+?
=> feat: revert pathlib changes

tests/integration/hub_usage/test_hub_usage.py
- fixes the error `TypeError("'str' object is not callable")` in `test_hub_usage`
=> fix: test hub usage github token

tests/unit/drivers/querylang/queryset/test_dunderkeys.py, tests/unit/drivers/querylang/queryset/test_lookup.py, tests/unit/drivers/test_concat_driver.py, tests/unit/drivers/test_craft_driver.py, tests/unit/drivers/test_encoder_driver.py, tests/unit/drivers/test_helper.py, tests/unit/drivers/test_kv_index_driver.py, tests/unit/drivers/test_kv_search_driver.py, tests/unit/drivers/test_multimodal_driver.py, tests/unit/drivers/test_reduce_all_driver.py, tests/unit/drivers/test_segmenter_driver.py, tests/unit/drivers/test_vector_fill_driver.py, tests/unit/drivers/test_vector_search_driver.py
More test refactoring on driver module:
1. Replace protobuf with primitive data types.
2. More decoupling on entity creation using pytest fixtures from test cases.
3. Some minor changes, such as optimize imports, remove unused code.
=> test: clean up driver test

jina/flow/base.py
=> fix: fix visualization in notebook

jina/peapods/peas/gateway/rest/__init__.py
I was not able to connect form jinabox.js to my local machine running a REST endpoint (as given in the multires-lyrics-search example) on MacOS.
This fixes it by adding CORS flags that are recommended by fastAPI.
=> fix: fixes CORS behavior for REST API

jina/jaml/__init__.py, jina/jaml/helper.py, tests/unit/flow/test_flow_yaml_parser.py, tests/unit/test_yamlparser.py
Enables loading config from dict. The class name must be labeled with the keyword `__cls`
```python
class DummyEncoder(BaseEncoder):
pass
d1 = {'__cls': 'DummyEncoder',
'metas': {'name': 'dummy1'}}
with Flow().add(uses=d1):
pass
```
```python
d1 = {
'__cls': 'BaseEncoder',
'metas': {'name': '${{BE_TEST_NAME}}',
'batch_size': '${{BATCH_SIZE}}',
'pea_id': '${{pea_id}}',
'workspace': '${{this.name}} -${{this.batch_size}}'}
}
d = {'BE_TEST_NAME': 'hello123', 'BATCH_SIZE': 256}
b1 = BaseExecutor.load_config(d1, context=d)
```
- Variable substitution works when loading from `dict`
- CompoundExecutor dict also works, e.g.
```python
d2 = {
'__cls': 'CompoundExecutor',
'components':
[
{
'__cls': 'BinaryPbIndexer',
'with': {'index_filename': 'tmp1'},
'metas': {'name': 'test1'}
},
{
'__cls': …
```
=> feat(jaml): enables loading config from dict

jina/parsers/__init__.py
This is a tiny PR to fix a typo in the parser help menu
=> docs(cli): Fix small typo in cli parser

extra-requirements.txt, jina/peapods/pods/__init__.py, jina/peapods/runtimes/jinad/__init__.py, jina/peapods/runtimes/jinad/api.py, jina/peapods/runtimes/ssh/__init__.py, tests/integration/jinad/Dockerfiles/Dockerfile, tests/unit/peapods/pods/test_pods.py
This needs to be fixed to make https://github.com/jina-ai/jinad/pull/78 work. `jinad` checks will still fail with this PR.
=> fix(remote): remote type check and pod invocation

jina/types/sets/querylang.py, tests/unit/types/sets/test_querylangset.py
Add unit tests for QueryLangSet and minor bug fixing.
**What has been fixed**:
1. `__setitem__` expect set, not return
2. `self._docs_map` is not a valid variable in `QueryLangSet`.
3. `QueryLangProto` does not have an id field, while calling `build`.
Question: do we really need `build` method in `QueryLangSet`? the docstring was copied from `Document`
=> test: add querylang set test

jina/docker/checker.py, jina/docker/hubio.py, tests/unit/docker/test_hub_build.py
Freeze jina version to the core version that builds the hub image
=> feat: freeze jina version in hub build

jina/parsers/peapods/runtimes/container.py, jina/peapods/runtimes/container/__init__.py, tests/unit/mwu-encoder/mwu_encoder_volume_change.yml, tests/unit/peapods/runtimes/container/test_container_runtime.py
Iteration to fix #1438 
It allows to have volumes mapped to arbitrary path in the container. This combined with #1595  can allow using `ref_indexer` inside Docker
=> feat: volumes can be mapped to arbitrary path in container

jina/executors/indexers/vector.py, tests/integration/ref_indexer/index.yml, tests/integration/ref_indexer/pods/indexer.yml, tests/integration/ref_indexer/pods/indexer_with_ref.yml, tests/integration/ref_indexer/query.yml, tests/integration/ref_indexer/test_numpy_indexer_with_ref_indexer.py, tests/unit/executors/indexers/test_numpyindexer.py
Avoid inheriting from `ref_indexer` the `index_abspath` to avoid the inflexibility of moving workspaces into containers
One of the iterations in the direction of fixing #1438
=> feat: ref indexer avoid getting abspath

tests/unit/peapods/pods/test_pods.py, tests/unit/peapods/runtimes/container/test_container_runtime.py, tests/unit/peapods/runtimes/test_runtimes.py
these two flaky tests slow us down. the reason of flaky remains unknown
=> test: skip flaky tests

.github/workflows/test-jinad.yml, jina/peapods/runtimes/jinad/__init__.py, jina/peapods/runtimes/jinad/api.py
jinadruntime seems not need `dict` for `__init__(args)`
=> style: fix jinadruntime styling

docs/conf.py
Add cross-reference checker for sphinx.
with this PR, several options have been offered to make docstring more robust:
1. `make html` will show warnings if the internal referenced link is incorrect.
2. `make linkcheck` same as above, without generating html pages.
3. `make coverage` check the docstring coverage.
Some basic statistics:
**broken links**: Found 2724 broken links, ~2550 were broken links in CHANGELOG.md.
**coverage**:  ~40 undocumented methods & classes.
**warnings**: 2721 warnings, mostly are class or method reference not found.
=> docs: add reference check while build docs

CONTRIBUTING.md
In the contributing.md file, there is a broken link that needs to be changed:
I will just change which link jina-101 is referring to: from "./101/README.html" to  "https://github.com/jina-ai/jina/tree/master/docs/chapters/101"
=> docs(contributing): fix a broken link

jina/types/document/uid.py, tests/unit/types/document/test_document.py
Test added was failing before the change introduced in the hashing method
=> fix: content hash should not depend on chunks

CONTRIBUTING.md, docs/conf.py
This PR should fix all the deadlinks in docs:
1. Ignore unused links in `CHANGELOG.md`.
2. Ignore several local URIs, such as `0.0.0.0:[PORT]`.
3. Fix unreachable links.
=> docs: fix deadlinks

jina/types/document/__init__.py, jina/types/document/multimodal.py, jina/types/document/uid.py, tests/unit/test_helper.py
=> refactor: doc content hash

jina/executors/__init__.py
When issuing the `NoDriverForRequest` exception I think it would be useful to also include the name of the executor
Looking in the log and just seeing that is not enough to track it down
https://github.com/jina-ai/jina/blob/9b81559dadb624a3d5230614fef1d38539aa0226/jina/executors/__init__.py#L429 becomes:
```            raise NoDriverForRequest(f'{req_type} for {self}')
```
And then the log becomes:
```
inc_doc/ZEDRuntime@274989[E]:NoDriverForRequest('DeleteRequest for UniqueVectorIndexer')
inc_vec/ZEDRuntime@274997[I]:recv DeleteRequest  from gateway▸inc_doc/ZEDRuntime✖▸inc_vec/ZEDRuntime▸⚐
inc_vec/ZEDRuntime@274997[I]:#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 2.0 KB
inc_vec/ZEDRuntime@274997[E]:NoDriverForRequest('DeleteRequest for UniquePbIndexer')
```
instead of
``` …
```
=> fix: log executor on nodriverforreq

tests/unit/docker/test_hub_build_level.py, tests/unit/docker/yaml/test-joint.yml
Fix for #1575 using `docker image` object instead of `string` argument for `test_build` in `hubio`
=> fix: test for hubio test build

README.md
A user copying and pasting the existing sample will hit the following error. 
```
NameError: name 'numpy' is not defined
```
This is avoidable by including import numpy in the example.
=> fix: example requires numpy to be imported

.gitignore, jina/executors/indexers/__init__.py, jina/executors/indexers/cache.py, jina/executors/indexers/keyvalue.py, jina/executors/indexers/vector.py, jina/helper.py, tests/unit/drivers/test_cache_driver.py, tests/unit/executors/indexers/test_binary_indexer.py, tests/unit/executors/indexers/test_numpyindexer.py
This will be required for the CRUD integration tests suite
- handling of missing keys should not `Raise`
- missing keys are filtered out of the request
- we do log a `warning` - up to the user to interpret if that's expected or not
=> fix: rewrite handling of missing keys for indexers

jina/types/document/__init__.py
Stumbled upon this while working on #1613
=> fix: ignore parent id in content hash

tests/integration/crud/test_crud.py
To clarify what the `9` means for the EAH presentation (12 January)
=> fix: use topk in crud tests

jina/peapods/pods/__init__.py
In case we have a separated workspace and set shards to 1, search does not work.
We get rid of this case by forcing to have `separated_workspace=False` if `parallel==1`
=> fix: conditional args

jina/drivers/control.py
I found this more useful when debugging. I can just copy-paste the output into a JSON tree viewer, and collapse/expand as needed during inspection.
=> feat: support json print in loginfo

daemon/models/custom.py, jina/flow/base.py, jina/parsers/helper.py, jina/parsers/peapods/runtimes/container.py, jina/peapods/runtimes/container/__init__.py, tests/unit/parsers/peapods/runtimes/test_runtime_parser.py, tests/unit/peapods/runtimes/container/flow.yml, tests/unit/peapods/runtimes/container/test_container_runtime.py
As requested in #1671 , adding arbitrary parameters can be useful to get custom behavior or options for the docker images supporting Peas living in Docker images
=> feat: pass arbitrary kwargs to docker sdk

jina/drivers/search.py, tests/integration/level_depth/yaml/index-chunk.yml, tests/integration/level_depth/yaml/index-doc.yml
This is to prevent duplicating the embedding and raising the reshaping error in Document (`ValueError: cannot reshape array of size 10 into shape (10,10)`)
A more robust solution should be discussed in the future
=> fix: KVSearchDriver `is_merge` should be `False` by default

jina/drivers/search.py, tests/integration/level_depth/yaml/index-chunk.yml, tests/integration/level_depth/yaml/index-doc.yml
Reverts jina-ai/jina#1701 due to #1705
=> revert: "fix: KVSearchDriver `is_merge` should be `False` by default"

jina/parsers/peapods/pods/base.py, jina/peapods/pods/__init__.py, tests/unit/peapods/pods/test_pods.py
Right now if we use `uses_before` or `uses_after` it is added even when parallel is 1. Although it can be desired to have a `uses_after` or `uses_before` it is more common to only want it when there are multiple Peas inside a Pod.
Add an option to disable them if parallel is 1. Like this one can keep the same `Flow` structure for `sharding` and no `sharding` and just parametrize the number of parallels or other options while not wasting CPU and network hops by these extra Peas
=> refactor: optional disable uses_b/a if parallel is 1

README.md
The old example of `.add(uses='docker://jinahub/pretrained-cnn:latest') ` is outdated since pretrained-cnn:latest doesn't exist in jinahub and will cause error. 
Change it with the most downloaded image `.add(uses='docker://jinahub/pod.encoder.dummy_mwu_encoder:0.0.6-0.9.3')`.
=> chore: update add() use case in readme

docs/chapters/flow/index.md
Add a docker example for Flow API `uses` to address https://github.com/jina-ai/jina/issues/1698. This is consistent with https://github.com/jina-ai/jina/blob/master/README.md
=> docs(flow): add docker example for Flow API `uses`

jina/jaml/parsers/executor/legacy.py, tests/unit/test_workspace.py, tests/unit/yaml/test-kvindexer-workspace.yml
After refactoring in #1722, it seems that there was a bug when indexers are moved to docker.
The problem is that when the executor is loaded from the `mapped volume` in docker, the workspace is still in the `.bin` and although is capable of recreating itself, it tries to fetch the data from the old workspace.
**Solution**
I propose to have the workspace switched to the `workspace` folder from where is it loaded as it indicates that it has been "moved" or "mapped into the `docker` system".
In the long term, I would suggest to get rid of `.bin` and have a single source of configuration from YAML and have every executor know what to expect
=> fix: workspace from dump may not match the one from yaml

jina/optimizers/__init__.py, jina/optimizers/parameters.py, tests/unit/optimizers/parameters.yml, tests/unit/optimizers/test_optimizers.py, tests/unit/optimizers/test_parameters.py
Removed `FloatParameter` since `suggest_float` in `optuna` is anyhow just a wrapper around the three float sampling algorithms and I'd rather not forward this "hack".
Furthermore, added docstrings.
=> docs: added docstring for paramters

README.md, cli/api.py, daemon/api/endpoints/__init__.py, jina/clients/__init__.py, jina/clients/asyncio.py, jina/clients/base.py, jina/clients/websocket.py, jina/flow/asyncio.py, jina/peapods/runtimes/asyncio/rest/app.py, jina/peapods/runtimes/asyncio/rest/models.py, tests/unit/clients/python/test_client.py, tests/unit/flow/test_asyncflow.py
This is a breaking change to AsyncFlow API #1606 
- as a continuation of #1543 , this PR introduces return of an AsyncFlow as async generator (PEP525);
- now AsyncFlow are "fully async" in the sense that both `input_fn` and return are now async, (the flow itself is intrinsically async as well)
- note, this reverts the #1540, as `return` can not be used inside an `async generator`. Also keeping all results in a list is pretty trivial and users can do it themselves by looping over the async generator.
=> feat(async): AsyncClient & AsyncFlow's return is async generator

.github/workflows/tag.yml
Problem definition: Jina runs `make-docs.sh` when release in `tag.yml` -> `on push tags`. We want to let `docs` repo "know" Jina is releasing. To achieve this, while jina is releasing:
1. Jina Docs [tag workflow](https://github.com/jina-ai/docs/blob/docs-migration/.github/workflows/tag.yml) monitors release event.
2. When release, Jina Core [tag workflow](https://github.com/jina-ai/jina/blob/master/.github/workflows/tag.yml#L53) send a customized `jina-release-event`.
3. Jina Docs tag workflow receive `jina-release-event` and performs all the steps defined in [tags.yml](https://github.com/jina-ai/docs/blob/docs-migration/.github/workflows/tag.yml), on `docs-migration` branch.
4. Jina Docs workflow push the updated docs to `gh-pages` branch.
=> docs: add repo dispatch event when release

jina/parsers/peapods/base.py, jina/peapods/peas/__init__.py, jina/peapods/runtimes/zmq/zed.py
Productivity boost to capture faster exceptions and problems when defining problems. Also easier for the community to see the problems and to have better reporting.
@cristianmtr
=> fix: show exc info by default

jina/clients/__init__.py, jina/clients/asyncio.py, jina/drivers/delete.py, jina/drivers/index.py, jina/drivers/search.py, jina/executors/__init__.py, jina/executors/indexers/__init__.py, jina/executors/indexers/vector.py, jina/flow/__init__.py, jina/flow/asyncio.py, jina/types/document/__init__.py, jina/types/document/converters.py, jina/types/document/uid.py, tests/integration/memmap/test_mmap.py, tests/unit/drivers/test_vector_fill_driver.py, tests/unit/drivers/test_vector_index_driver.py, tests/unit/drivers/test_vector_search_driver.py, tests/unit/executors/indexers/test_numpyindexer.py, tests/unit/executors/indexers/test_numpyindexer_batching.py, tests/unit/types/document/test_document.py
`keys` inside the `NumpyIndexer` are not always of type `str`. I am not sure, whether it should be `Iterator[str]`, `Iterable[str]`, `Sequence[str]` or simply `List[str]` though. Input would be highly appreciated.
`query_by_id` => `query_by_key` to keep consistency.
`def query(keys:...`=> `def query(query_vectors, ...`
Furthermore, I changed the interface of the `delete` function to also use `str` instead of `int`. Not sure about this change as well.
Quite a few hub changes must be done after this PR is merged in order to keep all hub indexer in sync with this PR.
=> fix: vector indexer only uses str as keys

jina/optimizers/__init__.py
Better to take current local as default instead of `/` implicitly
=> fix: default value of workspace dir

.github/workflows/cd.yml, .github/workflows/tag.yml
Tested with a workflow in cloud-ops repo: https://github.com/jina-ai/cloud-ops/blob/master/.github/workflows/test-checkout.yml
Run: https://github.com/jina-ai/cloud-ops/runs/1830403348?check_suite_focus=true
Docs with test run: https://api.jina.ai/rest/master.html
=> ci(rest): added redoc docs for rest gateway

jina/drivers/search.py, jina/resources/helloworld.indexer.yml, tests/integration/crud/advanced/yaml/index-chunk.yml, tests/integration/crud/advanced/yaml/index-doc.yml, tests/integration/level_depth/yaml/index-chunk.yml, tests/integration/level_depth/yaml/index-doc.yml
As agreed, `is_merge` should be `False` by default. See https://github.com/jina-ai/jina/issues/1705#issuecomment-762079812
=> fix: is_merge should be False by default

jina/peapods/pods/__init__.py, tests/daemon/unit/stores/test_flowstore.py, tests/integration/issues/github_1861/test_pea_closing.py
Right now when a Pea fails to start, the rest of the already started Peas will be left alive
=> fix: close already started Peas when one of them fail to start

.github/workflows/tag.yml
workflow on dashboard repo: https://github.com/jina-ai/dashboard/blob/master/.github/workflows/sync-version-with-jina.yml
test workflow that triggers version update workflow in dashboard: https://github.com/jina-ai/cloud-ops/blob/master/.github/workflows/test-dashboard-version.yml
sample successful test run: https://github.com/jina-ai/cloud-ops/runs/1833504891?check_suite_focus=true
=> ci(dashboard): send event for version update

jina/drivers/index.py, jina/executors/indexers/__init__.py, jina/executors/indexers/keyvalue.py, jina/executors/indexers/vector.py
- uuid1 (default doc_id) is 36, therefore default_length needs to be 36
- no need do property for simple get/set
- move check to driver
=> refactor(driver): set default len 36, move check to driver

jina/resources/executors.requests.CompoundIndexer.yml
without `is_merge=True`, all scored info is lost due to copy override
=> fix(driver): compoundindexer should turn on is_merge

.github/workflows/tag.yml
There's an issue with workflow_dispatch in GH - ([link1](https://github.community/t/error-in-docs-or-misunderstanding-for-workflow-dispatch-event/125066/2), [link2](https://github.community/t/workflow-dispatch-cant-set-ref-to-commit-sha/138132)), which means `ref` cannot point to a commit sha. And for some reason, it is not able to pick the latest tag that triggered the event too, Hence hardcoding to `refs/heads/master` 
[Here's](https://github.com/jina-ai/cloud-ops/runs/1849186307?check_suite_focus=true) an example that got triggered by a `tag push` in `cloud-ops` repo.
=> ci: add fixed ref for workflow dispatch event

jina/executors/indexers/vector.py, tests/unit/executors/indexers/test_numpyindexer.py
Before this change, a mismatch between vector and key shapes during the very first `add` call would not have raised the `ValueError`.
=> fix: size assertion for first add call

jina/drivers/__init__.py, jina/types/sets/document.py, tests/unit/types/document/test_document_traverse.py
Note that this PR is the first step of #1932, no driver is refactored yet. The recursive driver needs to be refactored to use this feature.
The scope of this PR is to implement my comment here https://github.com/jina-ai/jina/issues/1932#issuecomment-778371142
- `DocumentSet.traverse` gives a high performant generator, allowing iterating over it in one-shot
- it supports current traverse grammar, such as `r`, `c`, `cm`, `mc`, and the combination of them
- one can do batching over it, see `test_batching_traverse`
=> feat(types): traverse is a method of document set

jina/drivers/rank/aggregate/__init__.py
docs(drivers): remove the legacy docstring
=> docs(drivers): remove the legacy docstring

CONTRIBUTING.md
docs: fix the typos and add links
=> docs: fix the typos and add links

README.md
Max and I both added the wiki example so it got added twice! This PR:
- removes Max's entry
- expands title of my own to include "NLP" for better explanation
=> docs(readme): rm duplicate wikipedia example

.darglint
This will ignore docstrings that don't cover exception info. We agreed we would ignore these
=> docs: add darglint config

jina/executors/__init__.py, jina/resources/executors._eval_pr.yml, jina/resources/executors._merge_matches_topk.yml, jina/resources/executors.requests.BaseRanker.yml, jina/resources/executors.requests.BaseRankingEvaluator.yml, jina/resources/executors.requests.BinaryPbIndexer.yml, jina/resources/helloworld.reduce.yml, tests/unit/executors/test_set_requests.py
- add `use_default` keyword under the `requests` field. If set, then missing request types and its drivers are auto-filled according to MRO.
- add `with` keyword under each request type. If set, then all drivers under that request type will have the share that `kwargs.
- when `with` is set under request type, then `drivers` keyword must be used to contain the list of drivers.
For example,
<table>
<tr>
<td>
Before</td>
<td>After</td>
</tr>
<tr>
<td>
```python
!ImageNormalizer
requests:
on:
ControlRequest:
- !ControlReqDriver {}
[IndexRequest, SearchRequest]:
- !FilterQL
with:
lookups:
mime_type: image/jpeg
traversal_paths: ['c']
- !URI2Blob
with:
traversal_paths: ['c']
- !CraftDriver
with:
traversal_paths: ['c']
```
</td><td>
```python
!ImageNormalizer
requests:
use_default: true  # for …
```
=> feat(executor): add use_default and with to requests field

jina/drivers/__init__.py, jina/drivers/control.py, jina/drivers/encode.py, jina/drivers/evaluate.py, jina/drivers/predict.py, jina/drivers/querylang/select.py, jina/flow/base.py, jina/flow/builder.py, jina/jaml/__init__.py, jina/jaml/helper.py, jina/jaml/parsers/__init__.py, jina/jaml/parsers/base.py, jina/parsers/helper.py
problem: noqa has been added as a part of docstring, and sphinx can not ignore it.
workaround found [here](https://github.com/terrencepreilly/darglint/issues/21#issuecomment-498850025), adding two dots before noqa should ignore it.
=> docs: ignore noqa in docstring

CONTRIBUTING.md, README.md
Also removed multilingual 101 links since that's [deprecated](https://jinaai.slack.com/archives/C018QCARHNG/p1612451976206900?thread_ts=1612449397.203800&cid=C018QCARHNG) (and files are gone)
=> fix(contributing, readme): all 101 links go to 101.jina.ai

jina/drivers/rank/aggregate/__init__.py, jina/executors/rankers/__init__.py, tests/unit/drivers/rank/aggregate/test_aggregate_matches_rank_driver.py, tests/unit/drivers/rank/aggregate/test_chunk2doc_rank_drivers.py
- column naming was wrong
- the usage of `np.object` is deprecated
- breaking changes introduced, hub-side PR is here:
=> fix(ranker): correct column names in ranker score matrix

.github/workflows/ci.yml
The CI was successfull and I was allowed to merge even with failing tests.
According to this issue in github runner https://github.com/actions/runner/issues/777 and documentation on github runners I believe this is the way to go
=> fix: CI should never skip last step

tests/unit/types/document/test_document.py
During example creation I came across an error that was fixed by Han relating the setting attributes of a document. I could not found an example testing the extraction of numpy arrays from a doc with `get_attr` in unit test.
=> test: add test get_attr with np.ndarray

README.md
Original binder link resulted in 404 error. 
The name of the jupyter notebook was wrong. Now fixed.
=> fix(docs): binder link was incorrect

jina/drivers/predict.py, tests/unit/drivers/test_predict_mock_driver.py
https://github.com/jina-ai/jina-hub/issues/3068#issuecomment-778720794
Current implementation of `BasePredictDriver` does not allow to use content of `Document` to predict tags. Methods like Zero shot classification might require a feature extraction pipeline totally independent from the embeddings from encoder and hence can have their own model for predicting tags based on the content.
=> feat(driver): add param to use content to predict tags

tests/unit/logging/test_logging_profile.py
The previous test may fail, so change it to make sure it could pass and meanwhile illustrate the functionality.
=> test(logging): add profiling test

jina/clients/base.py, jina/executors/indexers/keyvalue.py, jina/flow/base.py, jina/helloworld/chatbot/__init__.py, jina/helloworld/helper.py, jina/helloworld/multimodal/__init__.py, jina/logging/logger.py, jina/logging/profile.py, jina/optimizers/__init__.py, jina/optimizers/discovery.py, jina/optimizers/flow_runner.py, jina/resources/fashion/components.py, jina/resources/multimodal/pods/segmenter.py, jina/resources/multimodal/pods/weighted_ranker.py, jina/types/document/converters.py
Improve the docstring coverage in Jina core to 100% 🥳 .
=> docs: add missing docstrings for core

jina/jaml/__init__.py, tests/unit/flow/test_flow_yaml_parser.py, tests/unit/jaml/test_type_parse.py, tests/unit/test_yamlparser.py
- we will be slowly migrating from `!YAMLTag` to `jtype: YAMLTag`, this PR is a starting point
- the rationale behind this is we want to enable [JSONSchema](https://www.schemastore.org/json/) (FYI, YAML is a superset of JSON) for IDE-level of validation and autocompletion, as we heavily rely on YAML configs.
- the current problem is that those customized tags are not compatible to JSONschema, but also creates problem during internal/external-integration. (@BastinJafari on dashboard)
- in general, we want the maximum compatibility of our YAML file, to get broader support from the Schema ecosystem.
- the old way of `{"__cls": "SomeExecutor" }` to construct executor from JSON is now replaced by `{"jtype": "SomeExecutor"}`
Other alternatives to realize this but dropped: …
=> feat(jaml): add keyword jtype to represent YAML tag

.gitignore, jina/executors/indexers/vector.py, jina/resources/executors._index.yml, tests/integration/crud/advanced/test_crud_advanced_example.py, tests/integration/crud/advanced/yaml/index-chunk.yml, tests/integration/crud/simple/chunks/yaml/index_vector.yml, tests/integration/crud/simple/yaml/index_vector.yml, tests/integration/doccache/vector.yml, tests/unit/drivers/test_cache_driver.py, tests/unit/executors/indexers/test_numpyindexer.py
Delete invalid entries when saving
---
Benchmark code (no point in adding it to CI):
```python
@pytest.mark.parametrize('save', [False, True])
def test_scipy_indexer_known_big_benchmark_save(save, test_metas):
"""Let's try to have some real test. We will have an index with 10k vectors of random values between 5 and 10.
We will change tweak some specific vectors that we expect to be retrieved at query time. We will tweak vector
at index [0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000], this will also be the query vectors.
Then the keys will be assigned shifted to test the proper usage of `int2ext_id` and `ext2int_id`
"""
vectors = np.random.uniform(low=5.0, high=10.0, size=(100000, 1024))
keys = np.arange(0, len(vectors)).astype(np.str_)
print(f'benchmarking delete_on_save with …
```
=> fix: delete invalid entries before dumping NpIndexer

jina/executors/indexers/keyvalue.py, tests/unit/executors/indexers/test_binary_indexer.py
---
Benchmark
delete_on_dump=True, entries=100000. took 1.7688062191009521 seconds
delete_on_dump=False, entries=100000. took 0.001649618148803711 seconds
Code: 
```python
@pytest.mark.skipif('GITHUB_WORKFLOW' in os.environ, reason='skip the network test on github workflow')
@pytest.mark.parametrize('delete_on_dump', [True, False])
def test_binarypb_benchmark(test_metas, delete_on_dump):
entries = 100000
nr_to_update = 10000
keys = np.arange(entries)
values = np.random.randint(0, 10, size=entries).astype(bytes)
with BinaryPbIndexer(metas=test_metas, delete_on_dump=delete_on_dump) as idxer:
idxer.add(keys, values)
idxer.save()
assert idxer.size == entries
save_abspath = idxer.save_abspath
new_values = np.random.randint(0, 10, size=nr_to_update).astype(bytes)
with …
```
=> feat(binarypb): delete on dump

jina/optimizers/__init__.py
This is needed in order to use the dynamic workspace for the indexers.
=> fix: expose env variable for workspace

jina/parsers/peapods/runtimes/container.py
minor fix on type, it has been used in `KEY: VALUE` format.
=> fix: metavar for docker args

jina/logging/formatter.py, jina/logging/logger.py, jina/optimizers/__init__.py, jina/optimizers/parameters.py, jina/types/querylang/queryset/dunderkey.py, jina/types/score/__init__.py, tests/unit/types/sets/test_querylangset.py
A small correction for the docstrings.
We had cases where we were using `:returns:` in the docstring, but it has to be `:return:`
Resolves https://github.com/jina-ai/jina/issues/2149
=> refactor: returns to return

jina/executors/indexers/keyvalue.py, jina/executors/indexers/vector.py, jina/helper.py, tests/unit/executors/indexers/test_binary_indexer.py
NOTE
@florian-hoenicke @JoanFM @maximilianwerk 
Closing the query_handler is now coherent, but makes the update and delete ops slower. This is a trade-off we need to discuss perhaps.
Before, we were only closing the qhandler's body but still relying on its header to get the keys. That was a bit of smell due to the design of the Write/ReadHandlers in BinaryPb. Once we call close we shouldn't be able to access it, but we are. 
Do we want to keep the old way (less readable, but more efficient), or this way (more readable, less efficient)?
=> fix: add delete() for cached property

jina/executors/indexers/keyvalue.py, jina/types/document/multimodal.py
The parent class had a different function interface compared to the overridden method.
resolves https://github.com/jina-ai/jina/issues/2161
=> refactor: match parent method

jina/drivers/search.py
discovered while writing docs.
=> docs: fix docstring in search driver

.coveragerc, .github/codecov.yml
resources folder has some python scripts, while most of them are `yml`, should not be included in pytest and codecov.
=> test: ignore resources folder for pytest and codecov

README.md
Two times in the README.md, a file is opened as `fp` and used as `fp1`. This PR corrects this.
=> docs: fix fp1 typo in readme

tests/unit/docker/test_hub_build_level.py
This is a test PR from the forked repo.
For PRs from fork repo, tests/unit/docker/test_hub_build_level.py will fail. The direct reason is that the list is empty. 
`image_name = list(filter(lambda image: _filter_repo_tag(image), images))[0]`
This issue needs to dig deeper. This means that for PR from fork repo, before this test there are no images in the testing environment, but for our PRs, there are images in env. 
Then there must be some other tests not working as expected, take this for example: 
https://github.com/jina-ai/jina/blob/4578fd65c4b5477f1fd2ddf723aaa7a7e9cbc22d/tests/unit/docker/test_hub_build.py#L12
This test is not asserted so we won't know even it fails. If it **fails to pull the images**, the test of this PR will fail for sure.
=> fix: hub_build_level  test

scripts/docstrings_lint.sh
generated files from the protobuf definition should not be checked in the linter
The problem got revealed when updating the proto definition in https://github.com/jina-ai/jina/pull/2198
resolves https://github.com/jina-ai/jina/issues/2200
=> fix: linter ignore generated files

scripts/black.sh
in https://github.com/jina-ai/jina/pull/2199 we ignored generated protobuf files for docstring matching.
In this pr, we need to ignore the reformatting as well.
=> fix: black exclude reformat

tests/unit/flow/test_flow.py
Test expects all `.py` files in its dir to have contents. Ensure they all do, and ensure it always checks the same files, no matter where you're running it from
=> fix: test expects file with contents

tests/integration/crud/simple/test_crud.py
(The previous [branch](https://github.com/jina-ai/jina/pull/2219) had a mess while rebasing master. This is the same but the updated master will prevents the other tests in CI to fail)
As discussed [here](https://github.com/jina-ai/jina/pull/2213) right now there is no way to access the embedding. They are being excluded by default during query time. 
It refers to this [issue](https://github.com/jina-ai/jina/issues/2069)
=> test: assert there are no embeddings by default

extra-requirements.txt, tests/system/chatbot/test_chatbot.py
Given a system under test, `test_chatbot` depends on the `index` flow to be fired. While `f.block` blocked the process. I did some search and find the official plugin: [pytest-xprocess](https://github.com/pytest-dev/pytest-xprocess)
> pytest plugin for managing processes across test runs.
This plugin:
1. Bootstrap `hello_world` example in another process.
2. Monitor system logs to check if it is ready to test using `pattern matching`.
3. Run the test.
4. Kill the process.
This PR completes regression tests for three examples.
=> test: add regression for chatbot

tests/unit/peapods/zmq/test_zmq_addr.py
this pr should completes unit tests for `ZMQManyRuntime `.
=> test: add zmq runtime test

jina/drivers/search.py
the default value should be a `tuple` instead of a `str`
```
Python 3.7.5 (default, Feb 15 2020, 23:39:06)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: a = ('m')
In [2]: type(a)
Out[2]: str
```
=> fix: fix the bug in the default value

README.md
=> fix: fix script in README

jina/helper.py
- fetching external ip is slow in china because of the network issue. 
- the original implementation fetch IP sequentially, called twice
- **with timeout at 1, in China mainland it takes (1+1+1)*2 = 6s to start at Flow!**
- change it to async and smaller timeout
=> fix(helper): fetching external ip is extremely slow

README.md
With GitHub's new table of contents feature, our current examples show up twice each, because we're wrapping both the emoji and the example title in header tags (because they're in different table cells so can't use single tag).
This PR converts the examples into a list. As a side-effect it'll *probably* look better on mobile too
Fixes #2263
=> fix(readme): example headers display

jina/__init__.py, jina/types/document/__init__.py
This PR:
- Avoids warning users of external packages with specific arrays that are allowed in documents
- Refactors `update_ndarray` code making it more compact
- fixes `protbuff_updater` mispelled variable names to `protbuf_updater`
=> fix: import warnings verbose off by default

jina/clients/request/__init__.py, jina/clients/request/asyncio.py
`Flow.index(Document())` gives this single Document `doc.siblings=100` (as 100 is the default `request_size`), this logic is wrong.
One may argue not setting it (i.e. implicit 0) is also wrong, but given not-set and 100 are both wrong, I would choose not-set.
=> fix(client): remove sibling setting in client

jina/types/message/__init__.py, tests/integration/dump/test_dump_dbms.py
Fix dumprequest not being propagated to the send ctrl message
Baseline:
```
```
Dump / Reload
```
```
The reason indexing is slower for the DBMSBinaryPb vs Baseline BinaryPb is because we need to pickle both the vector and the metadata before storing them in the underlying KV data structure the BinaryPb uses:
```
def add(
self, ids: List[str], vecs: List[np.array], metas: List[bytes], *args, **kwargs
):
"""Add to the DBMS Indexer, both vectors and metadata
:param ids: the ids of the documents
:param vecs: the vectors
:param metas: the metadata, in binary format
:param args: not used
:param kwargs: not used
"""
if not any(ids):
return
vecs_metas = [pickle.dumps((vec, meta)) for vec, meta in zip(vecs, metas)]
self._add(ids, vecs_metas)
```
=> fix: benchmark dump test

jina/executors/indexers/dbms/keyvalue.py, jina/executors/indexers/dump.py
@theUnkownName Rebase your PSQL PR when this is merged, as it provides better type hints for the dumping
=> refactor(dump): type annotations and refactor

extra-requirements.txt
Fix scipy version to a modern one
=> fix: scipy version

.github/pages/snippets.md
Adding optimization to the snippets. This is also runnable on google colab via: https://colab.research.google.com/github/jina-ai/jupyter-notebooks/blob/main/basic-optimizer/basic-optimizer.ipynb
Closes https://github.com/jina-ai/jina/issues/2077
=> Docs snippets optimizer

jina/enums.py, jina/parsers/peapods/pod.py, jina/peapods/pods/__init__.py, jina/peapods/pods/compoundpod.py, tests/integration/rolling_update/test_rolling_update.py, tests/unit/peapods/pods/test_compound_pods.py
closes https://github.com/jina-ai/jina/issues/2339
=> feat: hosts for replicas

jina/peapods/runtimes/zmq/zed.py, jina/peapods/zmq/__init__.py
=> fix: avoid flush when kbinterrupt

jina/clients/websocket.py, tests/unit/clients/python/test_client.py
This fixes https://github.com/jina-ai/jina/issues/2367
I am basically just checking if we enter the for loop which is generating the actual requests to Jina. If this is not the case I will gracefully disconnect (close the websocket) again. This stops the waiting for a server response and the client unblocks.
There are no tests for our clients unfortunately, but I checked the new code manually with a local stress test and it behaves as expected: If a caller passes in an exhausted input generator, the client will just disconnect without any error and the caller can continue its business. Before this change we blocked the caller indefinetely.
=> fix(websocket-client): fix blocking on empty requests

scripts/get-all-test-paths.sh
add `system` into codecov, to fix the error:
=> ci: add system path to get all test paths

jina/executors/indexers/dump.py
Found issue while working on https://github.com/jina-ai/examples/pull/573
=> fix: ensure same precision in dump

cli/autocomplete.py, jina/clients/base.py, jina/clients/mixin.py, jina/clients/request/__init__.py, jina/clients/request/asyncio.py, jina/clients/request/helper.py, jina/helloworld/fashion/flow.yml, jina/parsers/client.py, jina/peapods/runtimes/zmq/zed.py, tests/unit/flow/test_asyncflow.py, tests/unit/flow/test_flow.py, tests/unit/peapods/runtimes/remote/jinad/yamls/flow-index.yaml
allowing no `inptus` data request, `f.post('/hello', parameters={'foo': 'bar'})`. This is useful for sending pure commands to executors
=> feat: allow empty data req

jina/helloworld/multimodal/executors.py
Align channel axis in `Crafter`, remove channel permute in `Encoder`.
=> fix: channel axis in normaliser

.github/2.0/cookbooks/Document.md, jina/types/document/__init__.py, tests/unit/types/document/test_document.py
**Problem:**
There is an inconsistency in the document _cookbook_ and potentially in the implementation of the `Document` constructor.
The cookbook explains that the document content fields are mutually exclusive (buffer/text/blob/uri) and that they are all `content`.
So a `Document` can only have one content, not a `uri` AND a `text` etc.
In the current example of the _cookbook_ this is actually the case: It creates a `Document` which has a content and a different uri. That does not happen with the actual implementation, it will always take the last content parameter.
This behavior of the code is also debatable. It is not really incorrect, but it is a bit confusing that the implementation just takes the last value in the `kwargs` list. I think it might be better to raise a `ValueError` …
=> fix: exclusivity doccontent

cli/autocomplete.py, jina/clients/request/helper.py, jina/helloworld/chatbot/app.py, jina/parsers/hub/build.py, jina/parsers/peapods/pea.py, jina/peapods/runtimes/zmq/zed.py, jina/types/document/__init__.py, jina/types/request/__init__.py, jina/types/struct.py, tests/system/multimodal/test_multimodal.py, tests/unit/peapods/runtimes/asyncio/rest/test_models.py, tests/unit/proto/test_pb_struct_tags.py, tests/unit/types/document/test_document.py
this PR enables a Python organic dict view of `Protobuf.Struct`, useful in `doc.tags`, `request.parameters`
=> feat: add pythonic dict view for pb struct

.github/2.0/cookbooks/Executor.md
This adds a small description to the Tensorflow Executor in the cookbook. One could add potentially how that can or should not be used in a search context, but I think its a bit too much detail at this point.
=> feat: Add description for tf executor example

.github/2.0/cookbooks/Executor.md
In the `MyExector` example above, there is no additional parameters of
`__init__` method, which is why we should remove `with` property.
Otherwise, people will get an error here.
=> docs(cookbooks): remove `with` property in minimum yml example

daemon/models/base.py, tests/daemon/unit/stores/test_basestore.py
This adds a simple test for serialization of the `BaseStore`. The test just stores and loads some dummy store (inheriting from `BaseStore`) and checks if the stores before and after are equal.
The PR also makes two code changes:
1. For the empty dict one should specify the factory I believe and not use the mutable `{}`
2. In `set_size()` I am checking for the existence of 'items'. Without this check my test fails as the function gets called once without items in the dict. Not sure why this happens.
=> feat: add test for store serialization

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/force-docker-build.yml, .github/workflows/tag.yml, Dockerfiles/debianx.Dockerfile, README.md, RELEASE.md, jina/__init__.py, jina/clients/request/helper.py, jina/executors/decorators.py, jina/helloworld/fashion/app.py, jina/types/arrays/document.py, jina/types/document/generators.py
It's a strange bug caused `import grpc`, yet i'm not sure it is really the upstream problem.
As mentioned in #2447 , running `jina -v` on armv8 throws the exception immediately:
```
free(): invalid pointer
Aborted
```
After some inspections, I found the cause is `import grpc`. To reproduce, **(only on armv8)**, 
-  adding `import grpc` _before_ these lines of `jina/__init__.py`
```python
from jina.types.document import Document
from jina.types.arrays.document import DocumentArray
``` 
passes.
-  adding `import grpc` _after_ these lines of `jina/__init__.py`
```python
from jina.types.document import Document
from jina.types.arrays.document import DocumentArray
``` 
fails.
Unfortunately, I don't have time to dig in on this, but this PR at least figured out this issue and fix #2447
=> fix: fail to import on armv8 

daemon/models/base.py, daemon/models/workspaces.py, daemon/stores/base.py, daemon/stores/workspaces.py, tests/daemon/unit/stores/test_workspacestore.py
sorry for the large diff, the black prehook did the formatting.
relevant changes are:
- https://github.com/jina-ai/jina/pull/2505/files#diff-37ce282b4c82b8fba0f0fa251dcd66a6800e19984e046661f523ccacc95dbe91R185
- https://github.com/jina-ai/jina/pull/2505/files#diff-37ce282b4c82b8fba0f0fa251dcd66a6800e19984e046661f523ccacc95dbe91R206
- https://github.com/jina-ai/jina/pull/2505/files#diff-eb700ccf4382124005490360e31674bb156310e0a5bf05c607777b2f0f00e72dR86
- https://github.com/jina-ai/jina/pull/2505/files#diff-eb700ccf4382124005490360e31674bb156310e0a5bf05c607777b2f0f00e72dR98
- 
What this PR actually changes:
- fix empty requirements (before it failed because we expect a list in the pydantic model but it was space separated string)
- fix some metadata for the workflow store (size)
- add some …
=> fix(daemon): handle empty requirements

jina/optimizers/__init__.py, jina/optimizers/flow_runner.py, tests/integration/optimizers/data.jsonlines, tests/integration/optimizers/flow.yml, tests/integration/optimizers/optimizer_conf.yml, tests/integration/optimizers/parameter.yml, tests/integration/optimizers/pods/craft.yml, tests/integration/optimizers/pods/dummy_crafter.py, tests/integration/optimizers/pods/dummy_evaluate.py, tests/integration/optimizers/pods/evaluate.yml, tests/integration/optimizers/test_discovery.py, tests/integration/optimizers/test_optimizer.py
PR for adding back the optimizer test and adopt the optimizer to the 2.0 API.
=> test: added optimizer integration test back

daemon/dockerize.py, daemon/models/containers.py, daemon/models/workspaces.py, daemon/stores/base.py
This adds a feature to jinad to manage the subnetworks assigned to the Docker networks on image creation.
Now JinaD assigns subnetworks in the 10.0.0/8 private address space (as its larger than the docker default one which is 192.168.0.0/16). Each subnet is a /22 network so we can have 1024 hosts in a flow, which should be enough for now I think.
We have now room for 16384 networks in jinad, which is the maximum number of workspaces we can create concurrently now.
Some meta data about the IP assignment gets persisted in the workspace store.
I also fixed some minor other thing (wrong store status model being created on first time creation without pickle).
=> feat: add ip range management

daemon/stores/base.py
Before we were setting the fields in the base status model individually. That does not work if child classes (like workspace status) add new fields.
=> fix(daemon): use all state fields for status loading

tests/integration/crud/flow.yml, tests/integration/crud/test_crud.py
Part of https://github.com/jina-ai/jina/issues/2479
=> test: crud rest

tests/unit/types/document/test_converters.py
Part of https://github.com/jina-ai/jina/issues/2479
=> test: add asserts for mime types

tests/unit/flow/test_flow_except.py
This tests previous issues/github_1861 which checked, that a Flow is not hanging, when an Executor crashes during startup.
=> test: added test for startup exception

tests/integration/high_order_matches/test_document.py
Adopted high-order-matches test in order to test configurable `traversal_paths` again. Cleaned up some unused code.
=> test: make high order matches useful agian

daemon/dockerize.py
This works locally on my ubuntu 20.04 and fix the hanging tests for parallel > 1
Not sure if that breaks anything on Windows or Mac
=> fix(daemon): docker host internal on linux

jina/types/document/generators.py, tests/unit/clients/python/test_io.py
A clone PR from https://github.com/jina-ai/jina/pull/2492
=> fix: missing sampling args in generator of from_lines

.github/2.0/cookbooks/Document.md, jina/types/document/__init__.py, tests/unit/types/document/test_document.py
**Changes introcduced**
Try to have pretty dict printing for `Document`. At the same time we need to be able to build the `Document` back from a pretty dict like this.
Same would apply for `json`.
=> feat: add pretty print for embedding and blob

tests/integration/issues/github_1546/bad1/crafter.yml, tests/integration/issues/github_1546/bad1/custom_crafter.py, tests/integration/issues/github_1546/bad1/helper.py, tests/integration/issues/github_1546/good1/crafter.yml, tests/integration/issues/github_1546/good1/custom_crafter.py, tests/integration/issues/github_1546/good1/helper.py, tests/integration/issues/github_1546/good2/__init__.py, tests/integration/issues/github_1546/good2/crafter.yml, tests/integration/issues/github_1546/good2/helper.py, tests/integration/issues/github_1546/good3/__init__.py, tests/integration/issues/github_1546/good3/config.yml, tests/integration/issues/github_1546/good3/helper.py, tests/integration/issues/github_1546/test_pymodules_import.py
adding integration test for pymodules back. One is not needed anymore, since full module discovery works, when `__init__.py` is added to `pymodules`
=> test: added pymodules import test back

scripts/black.sh, tests/integration/v2_api/test_docs_matrix_tail_pea.py
This is a test showcasing, how a `MatchMerger` in a TailPea could look like. Beware, that replica/sharding for `(1,2)` and `(2,1)` are broken. That needs to be fixed before 2.0 release.
=> test: added a test for docmatrix in the tail pea

.pre-commit-config.yaml, jina/proto/jina.proto, jina/proto/jina_pb2.py, jina/types/document/__init__.py, tests/unit/types/document/test_document.py
I suggest, we remove sibbling from the jina.proto and the Document itself. The sibblings field is used only for very specific Executors (e.g. `BiMatchRanker`) and should thus become a field in `tags`, in my opinion.
This is especially true, since we don't (and most probably can't consistently) provide an automated way of computing the number of siblings.
=> refactor: remove sibbling from protobuf

tests/unit/test_cli.py
`--shards` and `--parallel` can be used as synonyms by the user. However internally, only `args.parallel` works. This is good for now and this test should just showcase it.
In the future, we might change the internal representation from `.parallel` to `.shards`, since it is the semantically correct way. Anyhow, since `replicas` do not work correctly without shards (this is a bug(!)), I would keep the old naming yet.
=> test: added a test to showcase how shards and parallel are synonyms

jina/clients/websocket.py
This is a bug that we encountered in the delphai eap project.
We get this error every time at some point in the middle of indexing our data:
```
WebSocketClient@9113[E]:Got following error while streaming requests via websocket: ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')
```
The indexing then crashes and the rest of the data is not indexed.
I fixed the error in this PR by introducing an argument `ping_interval=None` to the websocket connection call, which fixes the problem.
I am not entirely sure if this argument has any implications on other code, what it does is basically skipping the ping step on the websocket.
The solution was found here: [Stackoverflow](https://stackoverflow.com/questions/54101923/1006-connection-closed-abnormally-error-w …
=> fix: websocket crashing

jina/parsers/peapods/runtimes/zed.py
Seems that parsing a class inherited from jina.executor in CLI is not supported
=> remove the zed runtime argument option of class inherited from jina.executor

.github/CODE_OF_CONDUCT.md
Added email in place of placeholder
=> fix(coc-2569): code of conduct missing placeholders

daemon/__init__.py, daemon/api/endpoints/flows.py, daemon/api/endpoints/partial/flow.py, daemon/api/endpoints/partial/pea.py, daemon/api/endpoints/partial/pod.py, daemon/api/endpoints/peas.py, daemon/api/endpoints/pods.py, daemon/dockerize.py, daemon/models/containers.py, daemon/parser.py, daemon/stores/containers.py, daemon/stores/partial.py, setup.py
This is a draft for the introduction of 'mini' (partial) jinad instances. These instances start one of pod/pea/flow and the necessary store and API.
The main jinad process runs new docker containers with the partial (mini) jinad as the entrypoint. The --mode argument defines the appropriate type (pea/pod/flow). Mini Jinad will then start a partial store and the appropriate API.
As an example I also added the rolling update command to the (partial) Pod API. It can be triggered from main jinad, which will basically forward the incoming request. I did not test this as I could not manage yet to create Pods correctly.
The implementation is kind of hacky in the sense the partial stores/api feel a bit akward, especially those stores dont at too much value I think.
TODO:
=> Feat demon jinad runtime remote

README.md
Had to switch to using calendar links instead of event links because Google doesn't like sharing individual events
=> fix(eah): new calendar link

daemon/api/endpoints/logs.py, daemon/helper.py, daemon/stores/__init__.py, tests/daemon/unit/api/endpoints/test_logs.py
This remove the workspace_id as a parameter from the log requests. The workspace id is found automatically by checking the entity id and then looking up the workspace in the correct store.
=> feat(daemon): remove workspace id from logging requests

jina/flow/base.py, scripts/docstrings_lint.sh, scripts/inject-cli-as-overload.py
- [background: `@overload`](https://www.python.org/dev/peps/pep-3124/)
- [usage in Python](https://github.com/search?l=Python&q=org%3Apython+%27%40overload%27&type=Code)
- adding `@overload` method gives nice code-completion and intellisense, help users to onboard much quicker, see images below.
- `Flow.__init__` and `Flow.add()` are two popular user-facing methods; also `Client.__init__` (but this is blocked by #2565 )
=> feat: inject cli args as overload function 

jina/proto/jina.proto, jina/proto/jina_pb2.py, jina/types/document/graph.py, tests/integration/issues/github_2103/test_search_attributes.py, tests/unit/peapods/runtimes/asyncio/rest/test_models.py, tests/unit/types/document/test_graph_document.py
Move `graph_info` to `content` in a `Document`.
**Benefits**
As suggested by @maximilianwerk this enforces the design ot a root `Document` **BEING** a graph and not only containing graph information
**Drawbacks**
Potentially there may be cases where one would also like to have some content in the root graph (I am not sure this is true as I did not find any case for this)
**Open questions**
Should we add the ability to traverse on `nodes` as synonim for `chunks`? Should this be only for `GraphDocument`?
=> feat: put graph as one of content

jina/types/arrays/chunk.py, jina/types/arrays/document.py, jina/types/arrays/match.py, tests/unit/types/arrays/test_chunkarray.py, tests/unit/types/arrays/test_matcharray.py
**Changes introcued**
Calling `_docs_proto` leads to think that these are `protobuf` objects, but they are actually different type of `DocumentViews`
=> refactor: rename _docs_proto from DocumentArray

daemon/api/endpoints/workspaces.py, daemon/dockerize.py, daemon/files.py, daemon/models/workspaces.py, daemon/stores/workspaces.py, daemon/tasks.py, tests/daemon/unit/models/good_ws/.jinad, tests/daemon/unit/models/good_ws_filename/sample.jinad, tests/daemon/unit/models/good_ws_multiple_files/.jinad, tests/daemon/unit/models/good_ws_multiple_files/sample.jinad, tests/daemon/unit/models/good_ws_wrong_values/sample.jinad, tests/daemon/unit/models/test_jinad_file.py, tests/distributed/test_against_external_daemon/no_run.jinad, tests/distributed/test_against_external_daemon/test_single_instance.py, tests/distributed/test_against_external_daemon/test_single_instance_custom_container.py
Draft PR for showcasing custom container creation on workspace creation.
With this PR jinad will start a container with workspace creation if a jinad file is used with a run command.
Missing in this PR:
=> feat: daemon custom container

jina/types/document/__init__.py, tests/unit/types/document/test_document.py
=> fix: document update with fields do not have support setter

.github/2.0/cookbooks/Flow.md, jina/__init__.py, jina/flow/asyncio.py, tests/unit/flow/test_asyncflow.py
- bring `AsyncFlow` class back
- sugary syntax `Flow(asyncio=True)` swallows the IDE type hint on `async`, therefore it is not really the best practice. 
- the unified interface is still required if user care more about consistency rather than type hint
=> revert: bring explicit AsyncFlow class back

jina/peapods/runtimes/asyncio/rest/__init__.py
When creating custom REST endpoints, we get not any logs. Also, exceptions are silently ignored.
Having the logs helps debugging the application.
Example:
```
INFO:     127.0.0.1:51113 - "POST /search_docs HTTP/1.1" 200 OK
```
=> feat: info loglevel rest

jina/helloworld/multimodal/my_executors.py
found this unused property when pairing with @niuzs-alan , since now we start to use `DocumentArrayMemmap`.
=> refactor: remove unused property in indexer

daemon/api/endpoints/workspaces.py, daemon/files.py, daemon/tasks.py, tests/distributed/test_against_external_daemon/blocking.jinad, tests/distributed/test_against_external_daemon/test_single_instance_custom_container.py
This reworks the workspace update endpoint. Now its possible to call PUT with a list of files which will update the workspace.
This means the requirements are updated (old and new merged), file are placed, docker image rebuild and if necessary the custom container is restarted.
I added a simple tests.
There are some ugly code parts I want to improve, but it generally should work.
=> feat(daemon): update workspace

daemon/stores/flows.py, daemon/stores/partial.py
This exposes the dump/rolling_update commands on a flow via jinad api.
This depends on this PR: https://github.com/jina-ai/jina/pull/2657 - This one is actually against master, maybe we change it to daemon-2.0 as well? Otherwise this PR will be incomplete until we merge with master.
I did not add any tests yet as they would fail until we have the master changes anyway.
Also there is an existing test case for this: https://github.com/jina-ai/jina/blob/master/tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
=> feat(daemon): expose rolling update for flow

daemon/models/workspaces.py, daemon/stores/containers.py, daemon/stores/workspaces.py, tests/distributed/helpers.py, tests/distributed/test_remote_flow_dump_rolling_update/docker-compose.yml, tests/distributed/test_remote_flow_dump_rolling_update/pods/indexer_query.yml, tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
This PR fixes two things in daemon 2.0:
- Delete flow/pod/pea when workspaces are deleted
- Adjust the existing integration test for rolling update so that it passes with all the changes. (tests/distributed/test_remote_flow_dump_rolling_update/)
=> fix: rolling update test

.github/workflows/latency-tracking.yml
let's ignore the tracking temporally to avoid the delay for core's pr.
Then I shall fix the`ZeroDivsionError` immediately and open the tracking again.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200497144939499) by [Unito](https://www.unito.io)
=> Ci latency tracking zerodivisionerror

jina/types/arrays/traversable.py, tests/unit/types/arrays/test_documentarray.py, tests/unit/types/arrays/test_memmap.py
Consequence of discussion [here](https://jinaai.slack.com/archives/C0183GCN8AK/p1624358262177400)
We want to enforce `traversal_paths` always being `List[str]` and not `Union[List[str],str]`.
1. Easier to reason and catch
1. Easier to teach. New users don't need to understand both cases of traversing.
1. The type annotation is never actually checked, and it might fail silently, because you can traverse characters in a `str`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200504913520864) by [Unito](https://www.unito.io)
=> feat: enforce trav paths being iterable of str

jina/clients/base/__init__.py, jina/clients/base/grpc.py, jina/clients/base/http.py, jina/clients/base/websocket.py, jina/flow/base.py, jina/helloworld/chatbot/app.py, jina/helloworld/fashion/helper.py, jina/helloworld/multimodal/app.py, jina/logging/profile.py, jina/peapods/peas/__init__.py, jina/peapods/runtimes/asyncio/prefetch.py, jina/peapods/runtimes/base.py, jina/peapods/runtimes/jinad/client.py, jina/peapods/runtimes/zmq/zed.py, jina/peapods/zmq/__init__.py
> https://jinaai.slack.com/archives/C018F60RBL5/p1624635344068600
_There are too many information on the screen as Jina running,_ it creates the following problems:
Very scary to new users.
Feel heavy. To be honest, every program (even assembly) feel super heavy if you print every line on the screen.
Too loud, belittle user. As a framework, loud log outputs gives user a impression that, "what you are building & output is insignificant, because I'm emitting a looot and they are more important! So please read my output and good luck of finding your output."
In the screenshot below (readme code snippet), the user own log output is in the redbox, take a look at the ratio there. All the other lines in the screenshot are emitted from Jina. Don't you think it is completely overwhelming?
Another …
=> feat: mute many log.info and log.success

extra-requirements.txt, jina/types/document/__init__.py, jina/types/document/converters.py, tests/unit/types/document/test_converters.py
> can we stop guess_mime from request when creating a document with uri ? it makes document creation slow and fragile [here](https://github.com/jina-ai/jina/blob/88ac3a9776a7af47cfe0716be5a8d36dde90b5db/jina/types/document/converters.py#L148)  In a EAP, I have all chunks with url field and a lot Http 404 error generated
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200523505424299) by [Unito](https://www.unito.io)
=> refactor: remove mime type guess from remote url

jina/hubble/hubio.py, tests/unit/hubble/test_hubio.py
1. Add ATTENTION words for secret
1. Add alias field
1. Remove image field. We don't want users to care about the actual docker image, which may be private and untouchable directly in the future.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200534256250580) by [Unito](https://www.unito.io)
=> feat(hubble): optimize display when create executor

tests/unit/peapods/zmq/test_dynamic_routing.py
These ports are the reason for random failure in CI. Forgot to remove them after debugging in the dynamic routing PR.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200534751263065) by [Unito](https://www.unito.io)
=> fix: removed debug port

daemon/dockerize.py, tests/unit/test_helper.py
Fixes randomly failing tests, because of missing refactoring of `JINA_RANDOM_PORTS`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200535947272228) by [Unito](https://www.unito.io)
=> fix: environment usage

jina/jaml/__init__.py, tests/integration/override_config_params/zed/test_override_config_params.py, tests/integration/override_executor_specific_params/test_specific_params.py
Override_with and override_metas could not work when `uses` is called on a class or without `with` or `metas` config
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200537376904538) by [Unito](https://www.unito.io)
=> fix: fix override_with or override_metas

extra-requirements.txt, jina/hubble/helper.py, jina/hubble/hubio.py, jina/hubble/progress_bar.py
Create a new implementation of `ProgressBar` and `Spinner`. The original `jina.logging.profile.ProgressBar` is designed for `jina.Client`, that would not be suitable for download/uploading file.
The progress bar for uploading is show as following:
As the head request of S3 url does not contains `Content-Length`. That means we cannot get the size of download ahead. So, we use a spinner instead of progress bar for downloading
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200540369414310) by [Unito](https://www.unito.io)
Close #2754
=> refactor: add progress bar while push/pull

jina/peapods/pods/__init__.py
**Why this change**
JinaD calls close of the object which actually is another way of closing the ExitStack. (Removing this makes it clear that `Flows` and `Pods` behave the same way from JinaD perspective
=> refactor: remove unneeded func

jina/peapods/peas/__init__.py
We noticed that this [test](https://github.com/jina-ai/jina/blob/master/tests/daemon/unit/api/endpoints/test_common.py#L159) was failing a lot (but randomly) in [ci](https://github.com/jina-ai/jina/pull/2799/checks?check_run_id=2950566069)
I was running this test locally a lot and saw it less often, but it happened as well occasionally. The reason for the failure is that the flow closing hangs, which does so because the Pea closing hangs.
After discussion with @JoanFM we decided to remove the alive check the process as it seems to be unnecessary and was just added recently and may be the reason for the issue.
Another possible workaround was a `time.sleep() `after terminating a Pea, but we would rather try to avoid this.
I was running this changed version locally hundreds of time and did …
=> fix(core): prevent peas from hanging on close

.github/workflows/cd.yml, .github/workflows/ci.yml, daemon/dockerize.py, tests/conftest.py, tests/daemon/unit/models/good_ws/.jinad, tests/daemon/unit/test_files.py, tests/distributed/test_against_external_daemon/docker-compose.yml, tests/distributed/test_against_external_daemon/test_remote_workspaces.py, tests/distributed/test_remote_flow_dump_rolling_update/docker-compose.yml
This fixes https://github.com/jina-ai/jina/issues/2768
It also fixes an issue with CI setting for jinad. We need to set some environment variable `JINA_DAEMON_BUILD` to `DEVEL` to make sure CI builds docker from the code in the PR and not from dockerhub release version. Before this was incorrect, because appending to the github env file only takes effect in the next step. We actually need it in the current step there.
JinaD now basically checks the host directory used for mounting its root workspace and will use the correct one when creating child containers (flow/peads/pods/.jinad). Before we were always mounting /tmp/jinad, which can be wrong if the user changes it.
I've added a test for this using docker compose, because I cant use the regular jinad instance as I need to control the …
=> fix(daemon): fix flexible root workspace mount in docker

.github/workflows/ci.yml
docker build tests are failing due to missing env vars in CI. copied them from CD.
Some failure atm: https://github.com/jina-ai/jina/pull/2828/checks?check_run_id=2964672841
=> fix(ci): add env vars for docker test to ci

jina/excepts.py, jina/helper.py, jina/peapods/peas/__init__.py, jina/peapods/runtimes/base.py, jina/peapods/runtimes/container/__init__.py, jina/peapods/runtimes/gateway/grpc/__init__.py, jina/peapods/runtimes/gateway/http/__init__.py, jina/peapods/runtimes/gateway/websocket/__init__.py, jina/peapods/runtimes/jinad/__init__.py, jina/peapods/runtimes/zmq/base.py, jina/peapods/runtimes/zmq/zed.py, jina/peapods/zmq/__init__.py, tests/unit/peapods/peas/test_pea.py, tests/unit/peapods/runtimes/container/test_container_runtime.py, tests/unit/peapods/zmq/test_dynamic_routing.py, tests/unit/peapods/zmq/test_zmq_addr.py
We are currently setting `is_ready` before the runtime is actually really ready to handle traffic. This PR gives the responsability to set `is_ready` flag to the `runtime` and tries to make sure that `is_ready` is more meaningful.
It also allows us to avoid the need to call `terminate` and have a potentially more grateful shutdown
=> refactor: refactor is ready

jina/flow/base.py
The edge label is not needed anymore, since it will always be `ROUTER-ROUTER` with dynamic routing. Makes much nicer and leaner plots.
=> fix: removed edge label from flow plot

jina/hubble/hubio.py
As mentioned by @alexcg1 , the usages of `.add(uses=jinahub://dummy_executor)` cannot work in docker container.
=> fix: make hubble executor work in container

jina/peapods/zmq/__init__.py, tests/unit/peapods/zmq/test_dynamic_routing.py, tests/unit/test_echostream.py
This adds a test for sending data from remote back to local via the `remote: ROUTER-BIND` and `local: ROUTER-CONNECT`, where the remote sends data via the bounded sockets.
It also fixes a remaining bug, where the empty frame way removed by accident.
This closes #2782
=> test: added remote local test

tests/integration/rolling_update/test_rolling_update.py
This PR removes the hard coded ports in the rolling update test. We can not do it as it was before as it might conflict with arbitrary other ports.
I am not sure why we set it like this before though.
=> fix(tests): remove hard coded ports in rolling update test

jina/logging/logger.py, jina/peapods/runtimes/gateway/prefetch.py, jina/peapods/runtimes/zmq/zed.py
When processing data requests (which is a quite frequent task) we construct some log messages in every case for debug logging purpose. This happens even when debug logging is disabled. I think that is wasteful and should be avoided. 
The easiest way to avoid this is to check for the log level and only construct the log message if necessary. This is also recommended in the [Python documentation](https://docs.python.org/3/howto/logging.html#optimization).
The idea for this came up in this pr: https://github.com/jina-ai/jina/pull/2865
I only changed it for a few cases in this PR which happen quite often and should inflict the most costs for us. Other cases (Initialization and control messages) should not happen often enough that its worth to introduce this check there, I think.
=> feat(logging): skip unnecessary log message constructions

jina/hubble/hubio.py, tests/unit/hubble/test_hubio.py
Fix that when error occurs, the exit code still be 0. It makes tests confusing and hard to detect whether it's successful or not.
```
❯ JINA_HUBBLE_REGISTRY=http://localhost:3000 jina hub push case9; echo $?
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM …
```
=> fix(hubio): when error occurs, exit code should be set to non-zero

README.md
doc: declare cors in `Get Started` 's FLow
=> doc: declare cors in `Get Started` 's FLow

jina/parsers/peapods/runtimes/zmq.py, tests/conftest.py, tests/integration/rolling_update/test_rolling_update.py, tests/integration/v2_api/test_docs_matrix_tail_pea.py, tests/unit/clients/python/test_client.py
I thin the reason for most of our CI timeouts is because TERMINATE is not properly sent in the first attempt and having TIMEOUT_CTRL at such a large value and have short `mark.timeout` makes the ratio of timeouts very high without having any inherent bug
=> test: timeout control adjusting for ci

Dockerfiles/debianx.Dockerfile
During cleanup we were uninstalling ruby, hence fluentd was not working in jinad container. This PR fixes it
=> ci: fix fluentd with jinad image

Dockerfiles/debianx.Dockerfile
pypi dependencies can include setup.py files from git, that would need `git` cli to be installed. Currently, jinad doesn't support adding custom commands during workspace building, hence there's no other way to install `git` cli except including it in the base docker image (only for `-daemon`)
=> ci: add git to jinad docker image

jina/peapods/runtimes/zmq/zed.py, tests/unit/peapods/peas/test_pea.py
Skip sending responses to IDLE and CANCEL requests.
The test only tests IDLE unfortunately, but CANCEL actually impacts the tested pod so I could not use that one.
Fixes https://github.com/jina-ai/jina/issues/2930
=> fix(core): dont respond to cancel and idle

jina/hubble/helper.py, jina/hubble/hubio.py, tests/conftest.py, tests/unit/hubble/test_helper.py, tests/unit/hubble/test_hubio.py
- default to disk cache when fetching hubble executor meta information if there's no internet connection
- skip pulling the docker image if there's no internet connection and the docker image was already pulled
=> feat: support offline executors

.github/workflows/ci.yml
Using [this](https://github.com/jitterbit/get-changed-files/issues/19#issuecomment-854657729) action could check changed files for docstring/black without rebase/merge master back to feature brnach.
> The head commit for this push event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.
=> fix(ci): fix head commit ahead base commit

jina/helper.py, tests/integration/issues/github_2992/test_flow.py, tests/unit/test_helper.py
fixes the following example:
```
from jina.helper import batch_iterator
from jina import Document
from jina.types.arrays.memmap import DocumentArrayMemmap
dam = DocumentArrayMemmap("test_dam")
dam.append(Document())
bi = batch_iterator(dam, 3)
for batch in bi:
for doc in batch:
print(doc)
```
=> fix: apply islice on iterator object of data in batch iterator

.github/workflows/ci.yml, .github/workflows/latency-tracking.yml
Added steps (styfle/cancel-workflow-action@0.9.0) to cancel runs from previous commits in a PR for `docker-image-test`, `hub-test`, `core-test`, `latency-tracking`
=> ci: cancel prev runs for tests

jina/importer.py, jina/jaml/__init__.py
This PR aims at fixing the (internal) extra dependency issues in our hub . 
For instance, base on the executor from  https://github.com/jina-ai/executor-audio-VGGishEncoder/tree/fix-module-not-found , i found some weird observations. 
```
from jina import Executor, Flow
from jina.executors import BaseExecutor
import threading
encoder = BaseExecutor.load_config('config.yml')
```
All of the use cases above work perfectly. However, if we want to use `jina executor/pod/pea`  cli to load executor, we will get errors:
```
jina executor --uses config.yml   # => Failed, throw exception: `vggish` module cannot be found
```
=> fix(importer): add custom sys meta path finder

jina/types/document/__init__.py
with this change, we could speed up `match` and Document creation with `copy` with almost 45% of the time
```shell
py-spy> Sampling process 100 times a second. Press Control-C to exit.
0:00:23.514182
py-spy> Stopped sampling because process exitted
py-spy> Wrote flamegraph data to 'profile.svg'. Samples: 2446 Errors: 0
(venv) jina|refactor-copy-without-hash⚡ ⇒ sudo py-spy record -o profile1.svg -- python test.py
py-spy> Sampling process 100 times a second. Press Control-C to exit.
0:00:14.911232
py-spy> Stopped sampling because process exitted
py-spy> Wrote flamegraph data to 'profile1.svg'. Samples: 1639 Errors: 0
```
=> refactor(document): do not hash content if copy is true

jina/types/arrays/neural_ops.py, jina/types/document/__init__.py, tests/unit/types/arrays/test_neural_ops.py
for #3034 , I would not say it's a bug, it's a side effect. Calling match on same document does not really make sense. But here is a workaround. not a perfect solution, but works. Feel free to close this if there is a better solution
before: 
after:
=> fix: match with same documents

jina/types/document/__init__.py, jina/types/document/multimodal.py, tests/unit/types/document/test_document.py
the idea:
1. when calling `update_content_hash`, we actually never change parameters, so `include_fields` never being used except test. We also get rid of the mutually exclusive check.
2. maybe this is a better solution for hashing, we don’t specify `exclude_fields` ,but specify `fields`  necessary for hashing, safer
2. `CopyFrom` and `FieldMask` is expensive, we manage to only use `FieldMask` without creating the `empty_proto`
3. `SerializeToString ` = `SerializePartialToString ` + check if message is initialised, we initialise the pb message in the first line of the method, so checking is unnecessary please refer to [here](https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.SerializePartialToString).
=> refactor: try to speed up update content hash

jina/types/arrays/document.py, jina/types/arrays/match.py, jina/types/arrays/neural_ops.py, jina/types/document/__init__.py
minor improvement on the efficiency of `.match`
master (https://github.com/jina-ai/jina/commit/63d59edca82003a07093016ee7c2aabfc925eac9):
```
➜  jina git:(master) ✗ python toy36.py
--- 12.913429542000001 seconds ---
➜  jina git:(master) ✗ python toy36.py
--- 13.194746499999999 seconds ---
➜  jina git:(master) ✗ python toy36.py
--- 14.238623624999999 seconds ---
```
this PR:
```
➜  jina git:(perf-minor-improve-match) ✗ python toy36.py
--- 6.968042625000001 seconds ---
➜  jina git:(perf-minor-improve-match) ✗ python toy36.py
--- 7.192200333000001 seconds ---
➜  jina git:(perf-minor-improve-match) ✗ python toy36.py
--- 6.7111269170000005 seconds ---
```
---
`toy36.py` grabbed from #3055 
```python
import time
from jina import DocumentArray, Document
def main_func():
da1 = …
```
=> perf(types): remove redundant copy in match function

CONTRIBUTING.md, jina/__init__.py, jina/types/arrays/neural_ops.py, tests/__init__.py, tests/conftest.py, tests/unit/test_cli.py
related to #2957 #2514
a new Jina Environment variable `JINA_MP_START_METHOD` is added to allow changing `multiprocessing` start method **_before_** loading Jina package.
this should fix Paddle on GPU problem caused by `fork`.
To reproduce:
`toy1.py`
```python
from jina import Flow, Executor, requests
import paddlehub as hub
class PaddleHubExecutor(Executor):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.model = hub.Module(name='ernie')
print(f' \n\n\n SUCCESS in loading model \n\n\n')
@requests
def encode(self, docs, **kwargs):
print(f' here I would encode')
if __name__ == '__main__':
f = Flow().add(uses=PaddleHubExecutor)
with f:
pass
```
```console
JINA_MP_START_METHOD='spawn' python toy1.py
```
```console
UserWarning: multiprocessing start method is set …
```
=> feat: add env JINA_MP_START_METHOD for changing mp start_method

jina/peapods/runtimes/gateway/grpc/__init__.py, jina/peapods/runtimes/gateway/http/__init__.py, jina/peapods/runtimes/gateway/websocket/__init__.py
This PR introduces the following change:
For all runtimes, the gateway will bind to all inbound connections on the localhost, i.e. `0.0.0.0` instead of the parameter `args.host`. 
This change is motivated by a use-case from kubernetes where the gateway host deployment is hidden behind a kubernetes service with corresponding dns (this is a typical kubernetes pattern). 
Clients can reach the gateway via this dns from the outside but the host cannot bind to this address as it is the IP of the service not the deployment where the gateway runs.
=> refactor: change bind to all inbound

.github/2.0/cookbooks/Executor.md
Edit minor typos (missing word) in the [Executor documentation](https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Executor.md#method-returns).
=> docs(Executor.md): Minor typos

.github/workflows/force-docker-build.yml, Dockerfiles/debianx.Dockerfile, README.md, RELEASE.md, setup.py
`pip install jina` now corresponds to old `pip install "jina[standard]"`
Note "decremental" extras is not supported by pypi as [discussion here](https://jinaai.slack.com/archives/C018QC7Q4CU/p1626703322033300?thread_ts=1626697209.032200&cid=C018QC7Q4CU)
so this PR uses env var to enable a minimum installation of Jina
```bash
JINA_PIP_INSTALL_CORE=1 pip install jina  # => old pip install jina
JINA_PIP_INSTALL_PERF=1 pip install jina  # => old pip install jina[perf]
```
=> refactor(setup): make standard deps as the default deps

extra-requirements.txt, jina/resources/extra-requirements.txt
The DGL version on `extra-requirements.txt` is hardcoded and more modern versions can be used.
=> fix: allow more versions of dgl

jina/types/arrays/chunk.py, jina/types/arrays/match.py, jina/types/arrays/neural_ops.py
Regading how `append` to Matches behave, I do not see any point on offering `copy` option. I think is better to add it to the list, and then edit afterwards
=> refactor: no copy on append

jina/types/document/__init__.py
There is no need to create a `dict_keys` object for either iterating over the keys of a dict or for generating a set of keys for a dict.
Generating `dict_keys` only slows down code if the object is only used to check if another object is there (or for iterating over keys):
```
%timeit set({'a':23}.keys())
233 ns ± 31.4 ns per loop 
%timeit set({'a':23})
127 ns ± 0.243 ns per loop 
```
=> refactor: remove dict keys creation

.github/2.0/cookbooks/Document.md, jina/types/arrays/neural_ops.py, tests/unit/types/arrays/test_neural_ops.py
This PR adds a `.embeddings` property for faster acces to the embeddings of a `DocumentArray` or a `DocumentArrayMemmap` . This is done iterating over the bytes of the embeddings at proto level avoiding the creation of intermediate Python obejcts. 
This PR also provides
- A speed up of 3x on the current `.match` implementation
- A speed up of 2x on the current `.match` implementation with minibatches
```
from jina import Document, DocumentArray
d = Document(embedding=np.random.random(128))
docarray = DocumentArray([d for _ in range(100_000)])
```
Using `get_attributes`
```
%timeit np.vstack(docarray.get_attributes('embedding'))
```
```
1.65 s ± 95.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Using  `.embeddings`
```
%timeit docarray.embeddings
```
```
649 …
```
=> feat: add efficient access to embeddings

jina/types/arrays/document.py, jina/types/arrays/memmap.py, jina/types/arrays/neural_ops.py, tests/unit/types/arrays/test_documentarray.py, tests/unit/types/arrays/test_memmap.py, tests/unit/types/arrays/test_neural_ops.py
Allow setting  in `.embeddings` at `DocumentArray` level
=> feat: add setter to embeddings

cli/__init__.py, jina/flow/base.py, jina/helper.py, jina/jaml/parsers/flow/v1.py, jina/parsers/helper.py, tests/unit/parsers/test_warnings.py
This will log a warning, when an unknown argument is used via the JAML syntax inside the Pod arguments. See the tests for examples with warnings.
I am not sure if `warn_unknown_args` and `DEPRECATED_ARGS_MAPPING` belongs into `jina/parsers/helper.py`. Happy about other suggestions
=> feat: unknown args loggin

jina/types/document/__init__.py, tests/unit/clients/python/test_request.py
background: https://github.com/jina-ai/jina/pull/3193#pullrequestreview-731999252
close #3193 
```
➜  jina git:(master) ✗ python toy39.py
get embedding ...	get embedding takes 4 seconds (4.49s)
➜  jina git:(perf-rm-warn-logic) ✗ python toy39.py
get embedding ...	get embedding takes 3 seconds (3.99s)
```
=> perf(types): remove warning logic in binary doc construction

jina/types/ndarray/dense/numpy.py
This PR removes runtime environment variable read for DenseNDarray creation
- Before this PR
```
%timeit aux = jina.types.ndarray.dense.numpy.DenseNdArray()
2.81 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
- After this PR
```
%timeit aux = jina.types.ndarray.dense.numpy.DenseNdArray()
1.48 µs ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
=> perf: remove environment variable reading from init

daemon/clients/base.py, daemon/clients/flows.py, daemon/clients/peas.py, daemon/clients/pods.py, daemon/dockerize.py, jina/peapods/runtimes/jinad/__init__.py, tests/daemon/unit/clients/test_clients.py
This PR adds 3 things:
- Adds timeout for JinaDClient
- Sets `/workspace` to `$HOME` in all partial-jinad based containers. 
- Adds `jinahub+docker://Executor` and `jinahub://Executor` schemes to jinadruntime.
=> feat(daemon): add timeout to client

cli/__init__.py, jina/flow/base.py, jina/helper.py, jina/parsers/__init__.py, jina/parsers/deprecated.py, jina/parsers/helper.py, tests/unit/parsers/test_warnings.py, tests/unit/peapods/runtimes/gateway/http/test_app.py, tests/unit/test_cli.py
=> fix(helper): fix bad warning message on unknown cli

jina/peapods/grpc/__init__.py, jina/peapods/runtimes/gateway/http/app.py, jina/peapods/runtimes/gateway/websocket/app.py, jina/peapods/runtimes/grpc/__init__.py, tests/unit/flow/test_flow_dynamic_routing.py, tests/unit/peapods/runtimes/gateway/http/test_app.py
This PR enables the GRPCDataRuntime to be run with HTTP and Websocket Flows. Before those were ignoring `grpc_data_requests` and always starting an AsyncZmqlet.
This fixes https://github.com/jina-ai/jina/issues/3243
=> fix(grpc): enable grpc runtime for http and websocket gateway

.github/2.0/cookbooks/Daemon.md, daemon/api/dependencies.py, daemon/api/endpoints/flows.py, daemon/api/endpoints/peas.py, daemon/api/endpoints/pods.py, daemon/clients/flows.py, daemon/clients/peas.py, daemon/dockerize.py, daemon/helper.py, daemon/stores/containers.py, tests/daemon/unit/api/flow1.yml, tests/daemon/unit/api/test_dependencies.py, tests/distributed/test_workspaces/envvars_ws/executor.py, tests/distributed/test_workspaces/envvars_ws/executor.yml, tests/distributed/test_workspaces/envvars_ws/flow.yml, tests/distributed/test_workspaces/test_envvars.py, tests/distributed/test_workspaces/test_remote_workspaces.py
A lot of times, we have Flow/Executor yamls that have env vars that need to be set while starting the Flow. This PR adds the support to do the same. The user journey remains the same.
1. Create a workspace with all your files. These files might use env var syntax like `${{VAR_NAME}}` or `$VAR_NAME`.
2. Create a Flow in the above workspace. The change in this PR comes in this step. 
- We add a new query param `envs`. It supports passing multiple strings, in `key=value` format.
- These env vars are parsed & set while starting the containers in JinaD.
- JAML already supports env var substitution, which gets used inside the container, while starting Flow/Executor.
```python
from daemon.clients import JinaDClient
client = JinaDClient(host=HOST, port=PORT) …
```
=> feat(daemon): support envvars

.github/2.0/cookbooks/Flow.md, jina/clients/mixin.py, jina/clients/request/__init__.py, jina/clients/request/asyncio.py, jina/helloworld/multimodal/flow-search.yml, jina/peapods/pods/compound.py, jina/peapods/runtimes/request_handlers/data_request_handler.py, tests/integration/crud/flow.yml, tests/integration/external_pod/test_external_pod.py, tests/integration/inspect_pods_flow/test_inspect_pods_flow.py, tests/integration/v2_api/test_func_routing.py, tests/jinahub/flow.yml
The expected behavior from Executor side should be:
```
if Documents are returned:
forward them to next Pod
else:
forward whatever the docs object contains after Executor execution to next Pod
```
Subtasks
=> feat: make docs behavior consistent :boom: 

jina/jaml/parsers/flow/v1.py, tests/unit/flow/test_flow_yaml_parser.py, tests/unit/flow/yaml/flow-gateway.yml
<table>
<tr>
<td align="center">Before</td> <td align="center">After</td>
</tr>
<tr>
<td> 
```python
from jina.jaml import JAML
f = Flow.load_config('''
jtype: Flow
version: 1
with:
port_expose: 9000
protocol: http
executors:
- name: executor1
port_in: 45678
''')
print(JAML.dump(f))
"""
!Flow
version: '1'
executors:
- name: executor1
workspace: /home/ubuntu//jina/
zmq_identity: 7309d5e9-b0e3-41ff-93ba-892e2eb1f786
port_ctrl: 57077
port_in: 45678
port_out: 60949
socket_in: "ROUTER_BIND"
socket_out: "ROUTER_BIND"
port_expose: 9000
upload_files: []
"""
```
</td>
<td>
```python
from jina.jaml import JAML
f = Flow.load_config('''
jtype: Flow
version: 1
with:
name: abc
port_expose: 9000
protocol: http
abc: def
executors:
- name: executor1
port_in: …
```
=> fix: read with args in flow.save_config

jina/flow/base.py
As discussed with @jacobowitz, we can not see any benefit of resolving the host. We rather lose information by converting the URL to an IP. 
In addition, the flow context can not know the actual IP when the pod is orchestrated by another system like k8s.
=> Refactor don't resolve host

.coveragerc, .github/codecov.yml, docs/fundamentals/flow/flow-as-a-service.md, docs/fundamentals/flow/index.md, pytest.ini, tests/integration/crud/__init__.py, tests/integration/v2_api/test_returns.py, tests/unit/clients/python/test_client.py
1. fixed all clients in docs from `port_expose` to `port`.
2. minor test change, test client `test_independent_client` is not testing client, it's testing flow.
3. remove `coverage.rc` since not used anymore, remove `jina/hub` from test config since hub is not a submodule of jina anymore. Added `pytest.ini` to ignore `pytest.mark.slow` warnings.
=> docs: use port replace port expose in client

jina/peapods/runtimes/request_handlers/data_request_handler.py, tests/unit/peapods/runtimes/request_handlers/test_data_request_handlers.py
This allows Executor to return any `AbstractDocumentArray`, thus leverage the `DocumentArrayMemmap`.
=> fix: dam can be returned by an executor

jina/types/arrays/document.py, jina/types/document/__init__.py
This speeds up DocumentArray.__iter__ heavily since Document constructor becomes much faster
Consequently, all methods that use __iter__ become faster.
When developing this, we had to set mermaid_id efficiently. A similar issue was raised before: https://github.com/jina-ai/jina/issues/2582
To solve it, we used a class attribute counter (to make mermaid_id unique based on document id which is already unique)
results:
|    |      master      |  perf-document-fast-init ( ff87e72 ) | perf-document-fast-init (ec5961d) | perf-document-fast-init (latest) |
|----------|:-------------:|------:|------:|------:|
| document array iter |  1.16 s | 0.32 s | 0.50 s | 0.36 s |
| document array get_attributes('text') |    1.32 s   |   0.42 s | 0.61 s | 0.43 s |
| document array get_attributes('text', …
=> perf: document fast init

docs/fundamentals/document/document-api.md, docs/fundamentals/executor/executor-built-in-features.md
=> docs: add note to warn users about int data type in doc.tags and parameters

jina/jaml/parsers/executor/legacy.py
`runtime_args.name` can be `None` in some tests, and we don't want to make tests require more scaffolding
Ex https://github.com/jina-ai/executors/runs/3534309301#step:4:781
=> fix: name can be None in args

jina/types/arrays/document.py, tests/unit/flow-example/test_flow_empty_request.py, tests/unit/types/arrays/test_documentarray.py
Dont fail if DocumentArray.extend() is called with `None`. Just do nothing.
=> fix(types): allow da extend with None

README.md
Remove Deprecated Link to Neural Search Cookbook
=> docs(readme): remove deprecated link

jina/helloworld/fashion/app.py
We already implement the conversion logic in [MyEncoder](https://github.com/jina-ai/jina/blob/4c4f69b150bc1f7103f31aea8ceade1f36081a7e/jina/helloworld/fashion/my_executors.py#L69). Thus there is no need to import it.
BTW, should we remove the definition of `MyConverter` from my_executors.py?
=> fix: Remove unused class MyConverter

jina/hubble/hubio.py
Clickable Jina Hub url in terminal!
=> fix(hub): replace docker hub url with jina hub url, and it is clickable

jina/flow/base.py, jina/jaml/__init__.py, jina/peapods/peas/__init__.py, tests/integration/multiprocessing_spawn/modules/main_jaml.py, tests/integration/multiprocessing_spawn/test_spawn.py
This reverts the hacks added in #3380 and #3404 and passes all `JAMLCompatible` classes registered in main process to the `run` method in Peas.
=> fix(spawn): reregister all jaml classes

jina/flow/base.py, jina/peapods/peas/__init__.py
An interesting problem. At first, it looks like a simple UI thing, but digging deeper reveals the flaw of the current readiness-check logic. This PR changes the readiness check on Flow start from "blocking-style" to "rotating polling-style", which overall fits better to microservice architecture like Jina.
Let's first see this example:
```python
import time
from jina import Flow, Executor
class SlowExecutor(Executor):
def __init__(self, wait, **kwargs):
super().__init__(**kwargs)
time.sleep(wait)
f = (
Flow()
.add(uses=SlowExecutor, uses_with={'wait': 4})
.add(uses=SlowExecutor, uses_with={'wait': 3})
.add(uses=SlowExecutor, uses_with={'wait': 2})
.add(uses=SlowExecutor, uses_with={'wait': 1})
)
with f:
pass
```
In current master (3ba5ec18586671c3b8fd59a1150883607e77100c), it behaves as …
=> feat: flow polls ready status from every pod 🍾 

jina/flow/base.py, tests/unit/flow-construct/test_flow.py
Fixes Issue: #3197
Expected Behavior: `Flow(grpc_data_requests=True).add(shards=2)` should raise an error.
Implemented Behavior:
```python
>>> Flow(grpc_data_requests=True).add(shards=2)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/workspaces/jina/jina/flow/builder.py", line 33, in arg_wrapper
return func(self, *args, **kwargs)
File "/workspaces/jina/jina/flow/base.py", line 716, in add
raise NotImplementedError("GRPC data runtime does not support sharding")
NotImplementedError: GRPC data runtime does not support sharding
>>> Flow(grpc_data_requests=True).add(shards=None)
<jina.flow.base.Flow object at 0x7fb19e5c8b80>
>>> Flow(grpc_data_requests=True).add()
<jina.flow.base.Flow object at 0x7fb19e5c8b80>
```
=> fix(flow): raise error when using grpc data runtime with shards

daemon/clients/peas.py
minor improvement of error logging for 422. When pydantic validation fails also include the invalid field name
=> fix(daemon): improve error logging

docs/advanced/experimental/kubernetes.md
https://github.com/jina-ai/jina/compare/master...gaocegege:typo?expand=1#diff-2b5818fa7aa948f44308441b2bc44d8c208025cdffbdbb2cc1058bf6febb9669R53
We are using index-flow namespace below, thus here is a typo. This PR is to fix it.
=> docs(k8s): fix the wrong namespace in the kubernetes example

jina/peapods/pods/k8s.py, jina/peapods/pods/k8slib/kubernetes_deployment.py, tests/unit/peapods/pods/k8slib/test_kubernetes_deployment.py, tests/unit/peapods/pods/test_k8s_pod.py
It is not recommended to hard code service FQDN. 
Ref https://github.com/kubernetes/dns/blob/master/docs/specification.md
The cluster domain can be configured by the CoreDNS/KubeDNS, and it can be run without the FQDN.
=> fix(k8s): Do not hard code the FQDN

jina/peapods/pods/k8s.py, jina/peapods/pods/k8slib/kubernetes_deployment.py, jina/peapods/pods/k8slib/kubernetes_tools.py
Before the PR:
```
exists already
deploy_pod0@95791[I]:🔋     Create Service for "pod0" with image "pod0" pulling from "jinahub/0hnlmu3q:v33-2.1.0"
exists already
deploy_pod0@95791[I]:🐳     Create Deployment for "jinahub/0hnlmu3q:v33-2.1.0" with replicas 1 and init_container False
exists already
exists already
deploy_gateway@95791[I]:🔋     Create Service for "gateway" with image "gateway" pulling from "jinaai/jina:master-py38-standard"
exists already
deploy_gateway@95791[I]:🐳     Create Deployment for "jinaai/jina:master-py38-standard" with replicas 1 and init_container False
exists already
test-flow@95791[I]:🎉 Kubernetes Flow is ready to use!
test-flow@95791[I]:
🔗 Protocol:            HTTP
🔒 Private network:     10.73.114.107:8080
💬 Swagger UI:          http://localhost:8080/docs
📚 Redoc: …
```
=> chore(pods): Print logs with JinaLogger and add logs for k8s namespace creation

.github/workflows/docs-netlify.yml
Used the [same workflow](https://github.com/deepankarm/jina/runs/3664811034?check_suite_focus=true) in my fork to deploy from the [feat-windows-beta](https://github.com/jina-ai/jina/pull/3290) branch - https://feat-windows-beta--jina-docs.netlify.app/
We can probably enable this workflow for all PRs with label `area/docs`
=> ci(docs): deploy docs from any branch

docs/advanced/experimental/index.md, docs/advanced/experimental/indexers-cheat-sheet.md, docs/advanced/experimental/indexers.md, docs/advanced/experimental/kubernetes.md, docs/advanced/experimental/scaling.md
First draft for indexer cheat sheet. 
- I have not included graphics for shards & replicas, since the graphics we generate via `.plot()` are not in sync with what is actually deployed in k8s.
- links might be broken. have to play around to see how to make them work. Will fix this.
picture of the table itself, since we don't pre-build the docs:
=> docs: first indexer cheat sheet version

daemon/api/endpoints/peas.py, daemon/api/endpoints/pods.py, daemon/api/endpoints/workspaces.py, daemon/clients/workspaces.py, daemon/helper.py, daemon/stores/partial.py, jina/flow/base.py, jina/peapods/runtimes/jinad/__init__.py, tests/distributed/test_topologies/test_topologies.py, tests/distributed/test_workspaces/cache_validator.py, tests/distributed/test_workspaces/flow_cache_validator.yml, tests/distributed/test_workspaces/test_cache_validate.py
If a remote `Executor` downloads a pre-trained model, we want to make sure, during the next run the Executor can reload from the previously downloaded model (from disk). This can be done by reusing the previous workspace. This PR adds tests to show how it can be used & fixes few bugs related to the same.
=> perf(daemon): reload files across flows/executors

jina/peapods/pods/k8slib/kubernetes_deployment.py
This PR is to:
- change the log output about service since v1/service resource on Kubernetes does not need the image
- change the log output about deployment since we confuse the name and image name
=> fix(kubernetes): Fix the service and deployment log

docs/advanced/experimental/indexers.md
This is required in order to explain what a Storage vs Searcher implements (generally).
=> docs: add explanation on crud usage

.github/workflows/ci.yml
This PR skips the complete step for `code-injection` and would unblock https://github.com/jina-ai/jina/pull/3448. 
There's still an issue with this step. Whenever there's a commit added by `jina-dev-bot` the CI run gets stuck. It starts again onlly if the PR is reopened.
=> ci: skip code injection for forks

jina/logging/profile.py
The current progress bar overwrites the last log line printed before the bar starts. Old behavior:
```
PASSED                                                                                              
PASSED                                                                                            
PASSED                                                                                              
PASSED                                                                                              
⠴   CANCELED ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00 8.7 step/s FAILED            
```
New behavior:
```
tests/unit/test_bla.py:my_test1
PASSED
tests/unit/test_bla.py:my_test2
PASSED
tests/unit/test_bla.py:my_test3
PASSED
tests/unit/test_bla.py:my_test4
PASSED …
```
=> fix: progress bar overwrite other logs

docs/advanced/experimental/indexers.md
Not true at the moment. Restricting it to just "Indexers" is both correct and safe for any possible deviations for the time being.
=> docs: fix reference to fill_embedding

daemon/api/dependencies.py, daemon/api/endpoints/flows.py, daemon/api/endpoints/peas.py, daemon/api/endpoints/pods.py, daemon/dockerize.py, daemon/stores/containers.py, jina/peapods/runtimes/container/__init__.py, jina/peapods/runtimes/container/helper.py, jina/peapods/runtimes/jinad/__init__.py, tests/distributed/test_topologies/test_topologies.py, tests/unit/peapods/runtimes/container/test_container_runtime.py
This PR
1. Enables any remote Executors to set `gpus` argument with `Flow` syntax. This argument was only valid for local + dockerized Executors. Since all remote Executors are dockerized, this enables setting up `docker devices` on any remote containers.
2. All remote Flows are by default started with `gpus: all` devices set, as we don't have `gpus` arg for Flows. If needed and used, we can enable it later.
Note: If on remote, docker cannot access the device passed, we reset the device & start the container again. 
Usage with remote Executor
----
```python
f = Flow().add(
uses='CustomExecutor',
host=CLOUDHOST,
port_jinad=8000,
py_modules=['/path/to/pymodule.py'],
upload_files=['/path/to/requirements.txt'],
gpus='all'
)
```
=> feat(daemon): allow gpus arg for remote Executors

docs/advanced/hub/push-executor.md, jina/parsers/hubble/pull.py, jina/parsers/hubble/push.py
As `UUID` is hidden from the user, it should be replaced with `NAME`
=> docs: replace UUID with NAME

jina/logging/profile.py
adding `print()` in the constructor is not a good solution
=> fix(helper): fix progressbar print to flush

extra-requirements.txt, jina/resources/extra-requirements.txt
fixes #3536
Perf is needed so that the requirement is actually part of all hubble built docker images.
=> fix(kubernetes): add kubernetes dep to perf

.github/workflows/cd.yml
> Error when evaluating 'strategy' for job 'core-test'. (Line: 137, Col: 20): Error reading JToken from JsonReader. Path '',
the error pop up after [this pr](https://github.com/jina-ai/jina/commit/4769b336bb0ff55cb65eb15466d4bacdd0bfc70f).
Hypothesis:
`pre-testbed` failed to generate outputs, thus produce empty output matrix (`core-test` needs `pre-testbed`). And in `core-test`:
```yaml
strategy:
fail-fast: false
matrix:
python-version: [3.7]
test-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
```
`fromJson` get an empty string.
Previously, `pre-testbed` has 2 needs: `update-schema` and `update-doc`. `update-doc` has been removed in #3526. 
this should be related to env settings. so I added env back to this PR. also some minor clean up such as remove unused `tests` in the bash …
=> ci: fix cd

.github/workflows/cla.yml
Instead of using our fork, this pr switches to the latest upstream version at https://github.com/cla-assistant/github-action
=> ci: fix cla

docs/_templates/page.html, docs/conf.py
This PR includes three fixes:
- Use prod Vue (size drops to 1/3 of the dev version, [read more](https://vuejs.org/v2/guide/installation.html#Development-vs-Production-Mode))
- Add `aria-label` to social button anchors since their content is an icon and can't be read by screen readers
- Add `noreferrer` to social button anchors, [read more](https://web.dev/external-anchors-use-rel-noopener/)
=> fix(docs): performance and a11y

jina/types/document/__init__.py
- had this issue today
- Can be reproduced by https://github.com/jina-ai/executor-pptxloader/commit/cab04bf0ef29b12d682bdfc92a85205a82a18da0
=> fix: scipy sparse import

jina/proto/jina.proto, jina/proto/jina_pb2.py, jina/proto/jina_pb2_grpc.py
This PR makes the necessary changes to our protobuf models for star routing:
1. Remove the RoutingTable completely from the message. This will be an object kept at the gateway locally in the Future.
2. Remove the routes object from the Envelope. Thats not needed anymore as the Gateway can keep track of this locally and add the routes only in the end to the response to the Client.
3. Adjust the CommandMessage: A lot of them are not needed anymore, but ACTIVATE/DEACTIVATE will be used in the future to add/remove peas from a head. Thus we need the networking information to send alongside.
4. Change the gRPC service model to return a Message as the response, instead of the empty workaround
closes https://github.com/jina-ai/internal-tasks/issues/238
=> feat(proto): adjust proto for star routing

jina/jaml/__init__.py, jina/jaml/helper.py, tests/unit/jaml/test_type_parse.py
should fix warnings as was mentioned in #3770
=> fix(jaml): remove duplicate py_modules while parsing yaml

docs/fundamentals/document/documentarray-api.md
Wrong document: https://docs.jina.ai//fundamentals/document/documentarray-api/?highlight=traverse#split-elements-by-tags
I believe it's kind of legacy from `.rst` file?
=> docs(fundamentals): remove useless `:class:` literal in documentarray docs

jina/executors/__init__.py, jina/helper.py, jina/jaml/__init__.py, tests/unit/executors/test_executor.py
Not going to lie, this is really one of my favorite features recently.
```python
from jina import Executor, DocumentArray, Document
exec = Executor.from_hub('jinahub://DummyHubExecutor')
da = DocumentArray([Document()])
exec.foo(da)
assert da.texts == ['hello']
```
=> feat(executor): Executor.from_hub now accepts jinahub scheme 🍾 

docs/advanced/experimental/kubernetes.md, jina/clients/mixin.py, jina/flow/base.py, tests/k8s/conftest.py, tests/k8s/test_connection_pool.py, tests/k8s/test_custom_resource_dir.py, tests/k8s/test_graceful_request_handling.py, tests/k8s/test_k8s.py
When deploying with `K8S`, we expect `k8s_namespace` sent to `Flow`, as namespace. Otherwise use default `Flow` name as namespace.
=> refactor: separate k8s namespace from flow name

cli/api.py, jina/peapods/networking.py, jina/peapods/runtimes/__init__.py, jina/peapods/runtimes/request_handlers/data_request_handler.py, jina/peapods/runtimes/worker/__init__.py, jina/types/message/__init__.py, tests/unit/peapods/runtimes/worker/test_grpc_data_runtime.py, tests/unit/peapods/runtimes/worker/test_worker_runtime.py, tests/unit/peapods/test_networking.py
With star routing the grpc data runtime becomes very simpel (receive messages and forward to data request handler).
This PR is refactoring the runtime (now WorkerRuntime) and also removes the partial message logic from the data request handler. In the future this is done before it hits this handler.
=> feat: star routing - refactor grpc data runtime

.github/workflows/ci-no-code-related.yml, .github/workflows/ci.yml
Two main changes in this PR:
1. Don't run `core-test` or any other test when just changing the docs. This will save a lot of time and resources.
2. Remove *adding-comment when commit lint fails* function because it won't work if the PR is raised by external contributors(in other words, the source branch of the PR comes from a forked repo). That means the value is very limited, and considering the complexity it adds, I would say it's a nice move to remove this functionality. So that this change won't increase a lot modulization concerns, because they are so simple.
=> ci: only run commit lint when only changing docs folder

jina/peapods/runtimes/worker/__init__.py, jina/proto/jina.proto, jina/proto/jina_pb2.py, jina/proto/jina_pb2_grpc.py, jina/proto/serializer.py
This enables sending mulitple partial requests in a single grpc call by introducing the `MessageListProto` wrapper and a fairly hacky serializer implementation to hide it again from the user.
I think this should work (I adapted the worker runtime and checked the test), but is not ideal:
- We actually only need multiple requests and not multiple messages, this adds unnecessary overhead
- There is too much message/messageProto conversion back and forth with this implementation
I created a follow up issue to implement this better, but this will be significant more work: https://github.com/jina-ai/internal-tasks/issues/259
=> feat(proto): enable sending multiple messages in a list

jina/types/arrays/memmap/__init__.py, jina/types/arrays/mixins/content.py, jina/types/ndarray/__init__.py, tests/unit/types/ndarray/test_ndarray.py
add full scipy support to ravel/unravel, now ravel setter/getter supports scipy sparse matrix perfectly.
```python
import scipy.sparse
import torch
import tensorflow
tensorflow.enable_eager_execution()
from jina import DocumentArray
sp_embed = np.random.random([10, 7])
sp_embed[sp_embed > 0.5] = 0
da = DocumentArray.empty(10)
da.embeddings = sp_embed
print(type(da.embeddings), type(da[0].embedding))
da.embeddings = torch.from_numpy(sp_embed)
print(type(da.embeddings), type(da[0].embedding))
da.embeddings = tensorflow.constant(sp_embed)
print(type(da.embeddings), type(da[0].embedding))
da.embeddings = torch.tensor(sp_embed).to_sparse()
print(type(da.embeddings), type(da[0].embedding))
da.embeddings = scipy.sparse.coo_matrix(sp_embed)
print(type(da.embeddings), …
```
=> feat(types): add scipy sparse to ravel/unravel

jina/peapods/networking.py, jina/peapods/runtimes/request_handlers/data_request_handler.py, jina/peapods/runtimes/worker/__init__.py, tests/unit/peapods/runtimes/request_handlers/test_data_request_handlers.py, tests/unit/peapods/runtimes/worker/test_worker_runtime.py
This closes https://github.com/jina-ai/internal-tasks/issues/264
One can see the disadvantage of the multi message approach here. The DataRequestHandler gets multiple messages and we arbitrarily manipulate the first message and return it.
Ideally this should be multiple requests and we always return the only existing message (to preserve meta information)
=> feat(worker): merge docs in worker runtime

.github/workflows/ci-no-code-related.yml
We enable GitHub status check for these two jobs: lint-flake-8 and success-all-test. So we need to fake these two jobs, otherwise the PR will infinitely wait for success of these two nonexistent jobs. e.g. https://github.com/jina-ai/jina/pull/3886
=> ci: fake two required jobs for ci-no-code-related workflow

docs/tutorials/quesion-answering-bot.md, jina/Untitled.ipynb
Adds a tutorial for a question answering bot that uses doc2query
=> docs: create tutorial for qa bot

.github/workflows/ci-no-code-related.yml, .github/workflows/ci.yml
This reverts commit db10582899a11a09a25f45f15c2a9ef70b5428a9.
**Since we already made some changes about GitHub Actions' configuration, this hack is no longer needed.**
=> ci: remove hack to ci-no-code-related workflow (#3914)

docs/fundamentals/document/document-api.md, docs/fundamentals/document/documentarray-api.md, docs/fundamentals/document/documentarraymemmap-api.md
- docs(fundamentals): polish document api
- docs(fundamentals): polish documentarray api
- docs(fundamentals): polish documentmemmaparray api
=> docs(fundamentals): more polishing

docs/fundamentals/document/documentarray-api.md, jina/types/arrays/mixins/traverse.py, tests/unit/types/arrays/mixins/test_traverse.py
Based on the considerations:
- less nested-structure in argument
- `numpy.einsum`'s subscript https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
=> refactor(types): traversal_paths is now a comma-sep string

jina/types/arrays/document.py, jina/types/document/graph.py, tests/unit/types/arrays/documentarray/test_documentarray.py
closes https://github.com/jina-ai/internal-tasks/issues/279
results:
```python
from jina import Document
from jina.logging.profile import TimeContext
doc = Document()
with TimeContext('appending chunks'):
for _ in range(10000):
doc.chunks.append(
Document(
text='hey',
offset=0,
weight=1.0 ,
location=[1, 2],
)
)
```
on master:
```
appending chunks ...	appending chunks takes 31 seconds (31.40s)
```
on feature branch:
```
appending chunks ...	appending chunks takes 0 seconds (0.64s)
```
=> perf: create DocumentArray index map lazily

jina/peapods/networking.py, jina/peapods/pods/__init__.py, jina/peapods/runtimes/gateway/__init__.py, jina/peapods/runtimes/head/__init__.py, scripts/get-all-test-paths.sh, tests/integration/peas/test_pea.py, tests/integration/pods/test_pod.py, tests/integration/runtimes/test_runtimes.py, tests/unit/peapods/runtimes/worker/test_worker_runtime.py
This closes https://github.com/jina-ai/internal-tasks/issues/266
This changes:
- Some small improvement with the logger for the connection pool (use same logger as pea to have more readable log config)
- use injected port_in in Pods for the head and dont generate random ones. (this needs to be extended for scaling the heads)
- add integration tests for pods
- make tests less flaky by retrying grpc calls 3 times and avoiding throwing with assertions before we clean up ressources (otherwise retries might get messed up)
=> feat(tests): add pod integration tests

daemon/models/id.py, jina/helper.py, jina/types/document/__init__.py
test settings: 1 million documents generation:
```python
from jina import Document
[Document() for _ in range(1000000)]
```
feature branch: 21239777 function calls (21233402 primitive calls) in 16.524 seconds
master branch: 23239839 function calls (23233463 primitive calls) in 19.815 seconds
we saved 2million function calls and roughly 17% time saving.
old & new uuid looks a bit different:
=> perf: small improve on uuid generation in doc

jina/types/arrays/chunk.py, jina/types/arrays/match.py, tests/unit/types/arrays/documentarray/test_chunkarray.py, tests/unit/types/arrays/documentarray/test_matcharray.py, tests/unit/types/document/test_document.py
closes https://github.com/jina-ai/jina/issues/3971
=> feat: no return in ChunkArray/MatchArray append

docs/_static/docbot.css, docs/_templates/docbot.html
This fixes the feedback tooltip broken issue when the answer is too short.
From:
To:
=> fix(docbot): feedback tooltip ui style

docs/fundamentals/document/documentarray-api.md, docs/fundamentals/document/fluent-interface.md, jina/types/arrays/mixins/__init__.py, jina/types/arrays/mixins/parallel.py, jina/types/document/__init__.py, jina/types/document/mixins/attribute.py, jina/types/document/mixins/image.py, jina/types/list.py, jina/types/mixin.py, jina/types/ndarray/__init__.py, jina/types/request/__init__.py, jina/types/routing/table.py, jina/types/score/__init__.py, jina/types/struct.py, tests/unit/types/arrays/mixins/test_parallel.py, tests/unit/types/document/test_converters.py, tests/unit/types/test_pickle.py
```python
from jina import DocumentArray
from jina.logging.profile import TimeContext
docs = DocumentArray.from_files('/Users/hanxiao/Downloads/left/*.jpg')
def foo(d):
return (d.load_uri_to_image_blob()
.set_image_blob_normalization()
.set_image_blob_channel_axis(-1, 0))
with TimeContext('map-process'):
for d in docs.map(foo, backend='process'):
pass
with TimeContext('map-thread'):
for d in docs.map(foo, backend='thread'):
pass
with TimeContext('for-loop'):
for d in docs:
foo(d)
```
```text
map-process ...	map-process takes 5 seconds (5.55s)
map-thread ...	map-thread takes 10 seconds (10.28s)
foo-loop ...	foo-loop takes 18 seconds (18.52s)
```
=> docs(types): add parallel map to documentarray-like objects

jina/types/arrays/mixins/embed.py, jina/types/arrays/mixins/parallel.py, jina/types/document/mixins/sugar.py
```python
import onnxruntime
model = onnxruntime.InferenceSession('resnet.onnx')
from jina import DocumentArray, Document
def pre_proc(d: Document):
return (
d.load_uri_to_image_blob()
.set_image_blob_shape((224, 224))
.set_image_blob_normalization()
.set_image_blob_channel_axis(-1, 0)
)
def post_proc(d: Document):
return d.set_image_blob_channel_axis(0, -1).set_image_blob_inv_normalization()
def embed(da):
return da.embed(model)
(
DocumentArray.from_files('/Users/hanxiao/Downloads/left/*.jpg')[:1000]
.apply(pre_proc)
.apply_batch(embed, batch_size=16)
.apply(post_proc)
.plot_embeddings(image_sprites=True)
)
```
=> feat(types): make apply and apply_batch self-returning

docs/fundamentals/document/documentarray-api.md, extra-requirements.txt, jina/resources/extra-requirements.txt, jina/types/arrays/mixins/match.py, jina/types/arrays/mixins/parallel.py, jina/types/document/mixins/sugar.py, tests/unit/types/arrays/mixins/test_parallel.py
```python
import onnxruntime
from jina import DocumentArray, Document
model = onnxruntime.InferenceSession('resnet.onnx')
pre_proc = lambda d: (
d.load_uri_to_image_blob()
.set_image_blob_shape((224, 224))
.set_image_blob_normalization()
.set_image_blob_channel_axis(-1, 0)
)
def post_proc(d: Document):
return d.set_image_blob_channel_axis(0, -1).set_image_blob_inv_normalization()
docs = (
DocumentArray.from_files('/Users/hanxiao/Downloads/left/*.jpg')[:1000]
.apply(pre_proc)
.apply_batch(lambda d: d.embed(model), batch_size=64)
.apply(post_proc)
)
```
=> feat(types): support lambda function in parallel mixin

docs/fundamentals/flow/remarks.md
Debugging Executor methods can be a bit of a pain (printing everything). I think mentioning `epdb` can be quite helpful.
=> docs: add breakpoint hint to debug flows

jina/executors/__init__.py, jina/jaml/__init__.py, jina/peapods/runtimes/request_handlers/data_request_handler.py, tests/unit/executors/test_executor.py, tests/unit/flow-construct/test_flow_yaml_parser.py
=> feat(hubio): allow uses_ override args in executors from_hub

tests/unit/types/arrays/mixins/test_parallel.py
update the test case for `apply()`
=> test: modify unit test case for apply

jina/hubble/helper.py, jina/hubble/hubio.py, tests/integration/hub_usage/test_hub_usage.py, tests/unit/hubble/test_helper.py, tests/unit/hubble/test_hubio.py
Now, `fetch_meta` is called twice when `force=True`. This would pollute the count of pulls of each executor in Hubble system. 
In this PR, the decorator `disk_cache_offline` is revised to return a tuple consisting of *returned value* and *bool value* (indicate whether the value is get from cache).
=> fix(hub): disk_cache_offline to return chached mark

jina/__init__.py
Python 3.10 has been released. Loose restriction a little bit.
=> fix: remove upper bound of python version

jina/flow/base.py, jina/peapods/networking.py, jina/peapods/runtimes/head/__init__.py
Fix https://github.com/jina-ai/internal-tasks/issues/346
There is a bug when a Flow is used in K8s without the K8sGrpcConnectionPool, but just with the static GrpcConnectionPool.
There are two things wrong:
1. The Gateway is configured to send to the worker deployments, not to the head deployment
2. The Head is not configuring its static worker addresses correctly, because the shard_id is interpreted as a string, but it should be an integer.
This was surfaced by a failing K8s test, this test should work now in this PR
=> fix(k8s): fix static cluster address config

jina/peapods/peas/factory.py, jina/peapods/pods/__init__.py, jina/peapods/runtimes/head/__init__.py, tests/integration/external_pod/test_external_pod.py, tests/integration/reduce/test_reduce.py, tests/integration/v2_api/test_func_routing.py, tests/unit/flow-orchestrate/test_flow_routing.py
Before this change we are always reducing if there is no uses_before.
With this PR we also check for `uses` and dont reduce if a meaningful `uses` exists.
I've adjusted some tests, there might be some more tests I need to adjust for this changed design.
=> fix: dont reduce if uses exist

cli/autocomplete.py, docs/fundamentals/flow/topology.md, jina/flow/base.py, jina/parsers/peapods/base.py, jina/parsers/peapods/runtimes/head.py, jina/peapods/runtimes/head/__init__.py, tests/unit/flow-construct/test_flow.py, tests/unit/flow-orchestrate/test_flow_routing.py, tests/unit/peapods/pods/test_pods.py, tests/unit/peapods/runtimes/head/test_head_runtime.py
Will close https://github.com/jina-ai/internal-tasks/issues/359
This PR unifies the arguments for polling. With this PR there is only the `polling` option exposed to the user.
This can be used as before (just put any/all) or it can be used as a dict defining polling per endpoint. If used as a dict, the user does not need to provide a complete dict. There is also the wildcard `*`. This wildcard will match all endpoints, except /index, /search and the endpoints explicitly named in the dict.
Equivalent are the following definitions:
polling = 'any' and polling = {'*': 'any'}
=> feat(polling): unify polling args

README.md
Based on analytics data, a [major source of traffic for our docs is our repo](https://jinaai.slack.com/archives/C018JCT47PV/p1641389346181900?thread_ts=1641389018.181100&cid=C018JCT47PV). This PR adds the learning portal to the readme to hopefully drive similar engagement. It also explains what each property offers to make it clear to user.
=> docs(readme): add link to learning portal, disambiguate difference with docs

daemon/api/dependencies.py, daemon/models/ports.py, daemon/stores/partial.py, jina/flow/base.py, jina/peapods/networking.py, jina/peapods/pods/__init__.py, jina/peapods/runtimes/worker/__init__.py, tests/daemon/unit/models/test_ports.py, tests/jinahub/test_integration.sh
* Add a check in the Pod when sending activate to use the correct address (localhost or host.docker.internal depending on the circumstances)
* Prevent exposing the `port_in` in the partial daemon containers if that starts a separate docker container
* Update pea args on overwriting the `workspace` in the Flow. This was breaking some JinaD assumptions.
* Remove usage of port_out  in some test (this was not breaking anything, but its not necessary anymore)
=> fix: several issues for jinad pods

extra-requirements.txt, jina/resources/extra-requirements.txt
not needed anymore with removing zmq
=> chore: remove tornado

jina/peapods/pods/__init__.py, tests/integration/runtimes/test_runtimes.py
Closes https://github.com/jina-ai/internal-tasks/issues/370
We had both head_args and the head itself in the ReplicaSet. Both is redundant. We need the head so I removed the head_args and get them from the head instead
=> refactor: clean up replica set

jina/peapods/peas/__init__.py, tests/unit/peapods/peas/test_pea.py
It can happen that a Pod closes a Pea before it was started (meaning its worker process has not yet been started). We should not wait for its termination then.
=> fix: close peas correctly

tests/distributed/test_remote_peas/test_remote_peas.py, tests/unit/peapods/peas/test_jinad.py
Thread backend for a runtime worker does not work well with containers. Dont test it in jinad
=> fix: dont test thread backend in jinad

.github/workflows/cd.yml
we should rather build test-pip in CD and not pull from the registry (its outdated)
=> fix: build test pip in cd

docs/advanced/experimental/docker-compose.md, docs/advanced/experimental/kubernetes.md
closes: https://github.com/jina-ai/jina/issues/4155
Since star routing is still not released, to perform the validation I did the following steps:
* build jinaai/jina:test-pip based on latest master
* build new encoder image from jinaai/jina:test-pip
* modify pqlite to rely on jina (latest master) and build new pqlite indexer from jinaai/jina:test-pip
* push all 3 images to a registry
* create config files and make sure to use the built images
=> docs: fix Jina on Kubernetes/docker-compose section

jina/peapods/networking.py
The `GrpcConnectionPool` cannot work with http and https proxy
related discussion: https://github.com/jina-ai/jina/pull/1348#discussion_r530721752
=> fix(runtime): worker grpc proxy env

.github/workflows/ci.yml, tests/k8s/test-executor/debug_executor.py, tests/k8s/test_k8s.py
closes: https://github.com/jina-ai/jina/issues/4147
=> test: add kubernetes test on connection pool behaviour

setup.py
This closes https://github.com/jina-ai/jina/issues/4194
Upgrading from Jina 2.x to 3.x is broken because pip will install first the new `docarray` pip package and then remove the old docarray package (which was part of jina repo). Because both are installed in the same folder, this will leave the new `docarray` package in some invalid state.
This change to the setup introduces a hack to rescue those cases: My code is checking if `docarray` can be imported correctly (by checking access to the version, this fails for master now). If this fails `docarray` is reinstalled via pip.
In non upgrading cases we will not enter the exception handler and my hack will not do anything (when installing jina in a new venv).
=> fix: rescue docarray in setup

jina/__init__.py
Issue https://github.com/jina-ai/jina/issues/4194 was meant to be fixed by https://github.com/jina-ai/jina/pull/4203
Unfortunately it did not, because the post install trigger is not happening when installing Jina as a wheel.
I dont see a proper way of working around it, so I changed at least the error message to something more meaningful
=> fix: add meaningful error on docarray issue

tests/integration/container_runtime_args/replica-exec/__init__.py, tests/integration/scale/scale-executor/__init__.py, tests/integration/scale/test_scale.py
the hack to retrieve the container id was too unreliable. I replaced it with some simple uid mechanism. No need to get the actual container id.
=> fix: replace docker id with uids

setup.py
This reverts commit 20d28a8b28533f45bef0dd21a4eda4b48265ae1b.
Fix does not help for the interesting cases and may have undesirable side effects
=> Revert "fix: rescue docarray in setup"

jina/orchestrate/flow/base.py, jina/orchestrate/pods/config/k8s.py, tests/k8s/conftest.py, tests/k8s/test_k8s.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py, tests/unit/orchestrate/pods/config/test_k8s_pod_config.py
This closes https://github.com/jina-ai/jina/issues/4145
This PR adds the possibility to use external Pods from a Flow in K8s. Before this PR, we would always generate K8s yaml files for the external Pods.
With this change those yamls for the external Pod are no longer generated. Also the Gateway pod address list logic is updated to cater for those external Pods. External Pods always need to be announced to the Gateway. It does not matter if the K8sConnectionPool is used or not. The gateway will always communicate to the head of the external Pod via a fixed address, configured in the Flow.
=> feat: use external pods from k8s

jina/clients/mixin.py, jina/serve/runtimes/request_handlers/data_request_handler.py, tests/integration/reduce/test_reduce.py, tests/unit/orchestrate/flow/flow-construct/test_flow.py
follow up on this [PR](https://github.com/jina-ai/jina/pull/4224) which is somehow broken on the github side
=> feat: change the way parameters are returned from Executors

jina/excepts.py, jina/orchestrate/deployments/config/docker_compose.py, jina/orchestrate/deployments/config/helper.py, jina/orchestrate/deployments/config/k8s.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_docker_compose_yaml.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
=> fix: improve error message

jina/orchestrate/flow/base.py
`docker compose -f file.yaml up` instead of `docker compose  up -f file.yaml`
=> fix: instruction is now docker compose -f file up

cli/autocomplete.py, jina/hubble/hubio.py, jina/parsers/hubble/push.py, tests/unit/parsers/hubble/test_pushpull.py
Close: https://github.com/jina-ai/hubble/issues/203
=> feat(hub): add `--verbose` option to "jina hub push" CLI

docs/fundamentals/flow/flow-api.md
This adds the section about extending the HTTP API again to the docs. It is more or less a copy of the old version
=> docs: add section for extending the http api

docs/fundamentals/clean-code.md, docs/fundamentals/executor/hub/use-hub-executor.md, docs/fundamentals/executor/repository-structure.md, docs/fundamentals/flow/create-flow.md, docs/fundamentals/flow/flow-api.md, docs/fundamentals/flow/index.md, docs/get-started/migrate.md, docs/how-to/kubernetes.md, docs/how-to/sandbox.md
unify all imports, not including `datatype`, `tutorial`.
=> docs: unify docarray import

.github/workflows/force-release.yml
=> chore: remove the legacy docaary GA script

.pre-commit-config.yaml
Automatically calling [blacken docs](https://github.com/asottile/blacken-docs) in pre-commit hook
=> feat: add blacken docs to precommit

jina/hubble/hubio.py
=> feat: add sandbox after push

docs/get-started/migrate.md
docs: migrate from memmap to sqlite
=> docs: migrate from memmap to sqlite

docs/fundamentals/executor/executor-api.md, docs/fundamentals/executor/executor-in-flow.md
=> docs: add explain on return

README.md
I think we should create the DA necessary for the example directly here. Otherwise the user needs to look this up in the previous example, which is awkward.
=> docs: complete containerization example

jina/hubble/helper.py
This PR aims to address the following error during `jina hub push ...`:
```
HubIO@48228[E]:Please report this session_id: 58edbc16-8faf-11ec-801d-6a44b164189a to https://github.com/jina-ai/jina/issues’
AttributeError(“‘PosixPath’ object has no attribute ‘startswith’“)
Traceback (most recent call last):
File “/Users/jemfu/opt/anaconda3/bin/jina”, line 8, in <module>
sys.exit(main())
File “/Users/jemfu/opt/anaconda3/lib/python3.9/site-packages/cli/__init__.py”, line 116, in main
getattr(api, args.cli.replace(‘-’, ‘_’))(args)
File “/Users/jemfu/opt/anaconda3/lib/python3.9/site-packages/cli/api.py”, line 226, in hub
getattr(HubIO(args), args.hub)()
File “/Users/jemfu/opt/anaconda3/lib/python3.9/site-packages/jina/hubble/hubio.py”, line 448, in push
raise e
File …
```
=> fix(hubble): pathspec match

docs/fundamentals/clean-code.md, docs/fundamentals/executor/executor-api.md
This is an improvement on the existing Executor API page.
This is part of the action points of the documentation training.
Part of building a selection of "Gold Standard" docs pages
done with @samsja @JohannesMessner
=> docs: improve quality of Executor API page

jina/enums.py, jina/serve/executors/__init__.py
`force_register` is legacy codes used to force ExecutorType to register an executor type. This is only used when we maintain the various executors within the jina codes with the legacy importing mechanism. This is part of the Jina 1.X
=> chore: remove the legacy codes for force register

docs/get-started/migrate.md
Migration guide described wrong behavior of `.post()` and its return type.
=> docs: fix migration guide

docs/index.md
This adds a link to the [old Jina 2 documentation](https://docs2.jina.ai/) in the "Developer Reference" section. This might be useful for people to maintain and migrate old projects written for version 2.
=> docs: add link to Jina 2 docs

extra-requirements.txt, jina/__init__.py, jina/resources/extra-requirements.txt
clean up the legacy dependency.
=> chore: clean up extra-requirements

CHANGELOG.md, README.md, docs/fundamentals/flow/client.md, docs/fundamentals/flow/create-flow.md, docs/fundamentals/flow/flow-api.md, docs/fundamentals/flow/index.md, docs/how-to/docker-compose.md, docs/how-to/external-executor.md, docs/how-to/kubernetes.md
This changes the arguments `port-expose` and `port-in` in the documentation to just `port` as changed in the code [here](https://github.com/jina-ai/jina/pull/4382). 
As the docs are not versioned, only merge and deploy this change AFTER THE NEXT RELEASE.
Closes https://github.com/jina-ai/jina/issues/4367
=> docs: adjust port args

.pre-commit-config.yaml
Add isort and flake8 to pre-commit.
* Isort : automatic import sorting https://github.com/PyCQA/isort
* We check flake8 in the CI so it might be usefull to check it in the precommit as well
=> feat: add isort and flake8 

jina/hubble/__init__.py, jina/hubble/hubapi.py, jina/hubble/hubio.py, tests/unit/hubble/test_hubapi.py
`sn` no longer exists instead now we use commits to manage the executor version.
Closes https://github.com/jina-ai/hubble/issues/299
=> fix(hubble): use commit id instead of serial number

docs/fundamentals/executor/executor-api.md, jina/serve/executors/__init__.py, tests/unit/serve/executors/test_executor.py
on developing remote Executor, I have to quickly make an Executor "served", I hope there is a shortcut for doing the following work:
```python
f = Flow(port=12345).add(uses=MyExec)
with f:
f.block()
```
so now I can:
```python
from jina import Executor
class MyExec(Executor):
...
MyExec().serve()
```
Please improve doc or whatever needs. I wont have time to revisit this PR, hope to see it merge soon.
=> feat(executor): add serve function

cli/__init__.py, jina/clients/base/__init__.py
e.g. adding test if needed. 
usage: `.post(..., total_docs=100000)`
rational: 
it is possible that user input is an iterator for saving memory but they know its length, e.g. if i want to load all `iglob('**/*.jpg')` i would easily know the length of the iterator in advance
yet, i would still construct it as an iterator (with no-length) as it is more memory friendly
=> feat(client): add total_docs to client post kwargs

jina/clients/__init__.py, jina/clients/base/__init__.py, jina/helper.py, tests/integration/gateway_clients/test_host_scheme.py
Fix the issue where the client type was always grpc because the args were not parsed soon enough, i.e they were parsed in the `BaseClient` but the client type was define before in the `Client` function where the args were not parsed yet.
=> fix: client args are now parse in the client function

.github/workflows/cd.yml
I noticed that I forgot to[ install linkerd](https://github.com/jina-ai/jina/blob/master/.github/workflows/ci.yml#L193) in the CD pipeline as well so the[ k8s tests are failing there](https://github.com/jina-ai/jina/runs/5718721397?check_suite_focus=true)
=> fix: install linkerd in cd pipeline

jina/serve/runtimes/worker/__init__.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py
We need to start the DataRequestHandler before the grpc Server. We may have Executors which are slow to init (downloading models etc) and we should not indicate to ready before the DataRequestHandler has been started.
This works atm with STATUS requests, but on K8s we are just doing plain TCP connects to the gRPC server to check if the pod is ready. These connects should fail while the Excutor is still initializing.
Closes #4570 ([issue](https://github.com/jina-ai/jina/issues/4570))
=> fix: start DataRequestHandler before grpc server

.github/workflows/cd.yml
Recently CD have been flaky. It seems that random tests timeout. I checked and the pytest timeout is actually set to 15 minutes only. [In CI it is 30 minutes](https://github.com/jina-ai/jina/blob/master/.github/workflows/ci.yml#L292), so we should set the same value here.
=> fix: increase pytest timeout to 30

jina/jaml/__init__.py, jina/jaml/helper.py, jina/jaml/parsers/base.py, jina/jaml/parsers/default/v1.py, jina/jaml/parsers/executor/legacy.py, jina/jaml/parsers/flow/v1.py, jina/serve/runtimes/request_handlers/data_request_handler.py, tests/unit/serve/executors/test_runtime_args.py
done with @alaeddine-13 
The `JinaLoader` now allow to pass `runtime_args` to the init of the Executor without parsing them to a yaml before
=> fix(executor): runtime args are now passed directly without any parsing

docs/fundamentals/executor/executor-in-flow.md, docs/fundamentals/flow/create-flow.md, docs/get-started/create-app.md
- Adds references to `replicas` and `shards` so that developers can better understand their purpose.
- Corrects one sentence in `get started` section.
=> docs(executor): add references to replicas and shards

cli/__init__.py, cli/known_plugins.json, cli/known_plugins.py
**TODO**
**Adding a Jina project to the core CLI as a plugin**
Basic usage:
- The project defines its own CLI and command
- The command associated with the project need to look like `jina-whatever`. If it does, and it is installed on the user's system, then `jina whatever` will also work automatically, **no need to configure anything, no need to wait for a core release**
- Any changes to the plugin CLI will be reflected automatically in the core CLI
Slightly-more-advanced stuff:
- For these features, the new **project's name, pip-package,  and plugin sub-command must be added to a json** on the Jina master branch. This way this info is always accessible and not tied to core release cycles.
- When the user uses the plugin, the core CLI automatically checks if the plugin has a newer version …
=> feat: add support for cli plugins

docs/get-started/install/troubleshooting.md
Using insights from [Issue 4422](https://github.com/jina-ai/jina/issues/4422#issuecomment-1057663345) to update install instructions for Mac M1.
=> Update M1 Install Documentation

docs/how-to/external-executor.md, extra-requirements.txt, jina/orchestrate/flow/base.py, jina/resources/extra-requirements.txt, jina/serve/networking.py, jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/grpc/__init__.py, jina/serve/runtimes/head/__init__.py, jina/serve/runtimes/worker/__init__.py, tests/integration/external_deployment/test_external_deployment.py, tests/integration/runtimes/test_runtimes.py, tests/unit/orchestrate/flow/flow-orchestrate/test_flow_complex_topology.py, tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py, tests/unit/serve/runtimes/head/test_head_runtime.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py, tests/unit/serve/test_networking.py
This PR allows external Executor to be fronted by our gRPC Gateway. This enables us to deploy external Executors together with a Gateway (as `Executor.serve()` is doing.). In theory this also allows us to integrate complete Flows as external Executors into another Flow. See the tests for some examples.
Implementation details:
I've added support for gRPC reflection with this PR. When we add a new connection, we first check the available gRPC endpoints using reflection. This way we can figure out automatically if the GrpcConnctionPool is used to target a Worker/Head or Gateway. This is necessary because they have different gRPC interfaces (streaming and non streaming). There is no configuration necessary to enable this. The reflection call is done lazily before the first request is send to …
=> feat: add grpc reflection support

docs/how-to/sandbox.md
Fixed a typo in the description of the sandbox lifecycle.
=> docs: fixed typo in sandbox lifecycle

docs/fundamentals/executor/executor-api.md, docs/how-to/external-executor.md, jina/orchestrate/flow/base.py, jina/serve/executors/__init__.py, tests/unit/serve/executors/test_executor.py
This adds  `to_k8s_yaml()` and `to_docker_compose_yaml()` for the Executors. It works similar to `serve()` in the sense that it creates a `Flow` behind the scenes and uses its existing methods to provide a similar user experience.
These features are also added to the docs and some basic tests have been added.
Closes [# (4502)](https://github.com/jina-ai/jina/issues/4502)
=> feat: Expose Executors as first class citizens

jina/orchestrate/flow/base.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
In K8s all Pods should use 8080 as the default port (expect monitoring and uses_before/uses_after). At the moment the Gateway is using a random port though unless specified otherwise.
The expected behavior is to respect user provided ports for the Gateway and use 8080 if there was no port specified.
My change fixes this in the Flow. Its fairly hacky/ugly, but I don't know how to do it differently really without breaking the parser. The main problem is that --port defaults to a random port, so its hard to check if the value was user set or just defaulted to. Thus I am using the `kwargs` in the Flow.
=> fix: 8080 as default gateway port in k8s

jina/serve/networking.py, tests/integration/sandbox/test_sandbox.py, tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py, tests/unit/serve/runtimes/head/test_head_runtime.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py
gRPC reflection is not respecting the TLS setttings. This makes all encrypted gRPC connections fail. This happens e.g. for sandbox.
This PR changes the logic so that we just reuse the existing channel for the reflection. This way I don't have to worry about the settings
=> fix: sandbox tls

docs/fundamentals/flow/flow-yaml.md
Updated docs such that property and method name of the executor differ
=> docs: renamed method to be named differently from property

jina/serve/networking.py, jina/serve/runtimes/worker/__init__.py
This PR renamed the two current Prometheus metrics implemented in jina and add `jina` as a namespace to follow the prometheus naming guidelines https://prometheus.io/docs/practices/naming/
new metrics name:
`receiving_request_seconds` -> `jina_receiving_request_seconds`
`sending_request_seconds` -> `jina_sending_request_seconds`
=> refactor(monitoring): add jina namespace to current metrics

jina/serve/executors/__init__.py, jina/serve/executors/decorators.py, jina/serve/runtimes/worker/__init__.py, tests/integration/monitoring/test_monitoring.py
Add `process_request_seconds` (on requests method) as a prometheus metrics to the Executor.
The goal of this metric is to monitor how much time each method decorated with the `@requests` takes to be processed
The metrics name is the same for all of the decorated method but there is a label for filtering.
=> feat: add process request seconds for executor

jina/helper.py, jina/serve/executors/__init__.py, tests/unit/serve/executors/test_executor.py
This PR disables the `ThreadPool` at Request level.
By having a threadpool with `num_workers` to 1, the benefit of having the `ThreadPool` is really minimal and can have some unwanted consequences.
=> refactor: avoid threadpool

.github/workflows/cd.yml, .github/workflows/ci.yml, jina/serve/executors/__init__.py, jina/serve/executors/decorators.py, jina/serve/networking.py, jina/serve/runtimes/gateway/request_handling.py, jina/serve/runtimes/head/__init__.py, jina/serve/runtimes/monitoring.py, jina/serve/runtimes/worker/__init__.py
We want to be able to remove prometheus from core dependency if needed. Therefore we need to remove the import from the top of the file
=> fix: remove prometheus import from the top of the files

jina/serve/runtimes/head/__init__.py, tests/unit/orchestrate/flow/flow-construct/test_flow_except.py, tests/unit/serve/runtimes/head/test_head_runtime.py
This makes error that occur in the head behave the same way as error that occur in the worker, which increases clarity.
**Before and after**
<details>
<summary>Before</summary>
````
executor0/head@39887[E]:NotImplementedError('Intentional error')
add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
File "/home/johannes/Documents/jina/jina/jina/serve/runtimes/head/__init__.py", line 182, in process_data
response, metadata = await self._handle_data_request(requests, endpoint)
File "/home/johannes/Documents/jina/jina/jina/serve/runtimes/head/__init__.py", line 241, in _handle_data_request
DataRequestHandler.merge_routes(requests)
File "/home/johannes/Documents/jina/jina/tests/unit/orchestrate/flow/flow-construct/test_flow_except.py", line 274, in fail …
```
=> fix: better reporting of errors in the head

tests/unit/serve/executors/test_executor.py
CI being slow made the blocking exec test [fail occassionally](https://github.com/jina-ai/jina/runs/6109701525?check_suite_focus=true)
This PR relaxes the asserted execution time constraint a bit. Its a magic number, but I think assuming that it should take less than 2 times the expected time should be fair
=> fix: relax time constraint in block exec test

jina/jaml/__init__.py
The `extra_search_paths` in the following example is not considered:
```
f = Flow.load_config('clip.yml', extra_search_paths=['/path/to/folder'])
```
```
jtype: Flow
version: '1'
with:
port: 51000
executors:
- name: clip_t
uses:
jtype: CLIPEncoder
metas:
py_modules:
- executors/clip_torch.py
```
Closes [# (issue)](https://github.com/jina-ai/clip-as-service/issues/682)
=> fix: pass extra search paths 

jina/orchestrate/flow/base.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_docker_compose_yaml.py, tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
We don't include the protocol part in the deployment addresses for K8s/Docker-Compose config files. This makes sandbox unusable from those environments. In docker-compose we actually had external executors never working before as well. Those issues are fixed in this PR. 
Closes 4664 ([issue](https://github.com/jina-ai/jina/issues/4664))
=> fix: sandbox usage from k8s/docker-compose

docs/fundamentals/flow/remarks.md
There were so mixed up between the multiprocessing things and the do and don't. I reordered the file but did not touch the content
=> docs: reorder correctly the remark page

extra-requirements.txt, jina/__init__.py, jina/resources/extra-requirements.txt
Failed to set the multiprocessing start_method `spawn` via `JINA_MP_START_METHOD`
```python
if __name__ == '__main__':
with Flow().add() as f:
f.block()
```
Start the flow service
```
JINA_MP_START_METHOD=spawn python example.py
```
it raises the following error
```
RuntimeError: context has already been set
```
=> fix: set the multiprocessing start_method spawn

docs/fundamentals/flow/flow-api.md
Fixed different typos in docs on limiting outstanding requests.
=> docs: fixed typos in limiting outstanding requests

jina/serve/runtimes/request_handlers/data_request_handler.py, tests/unit/orchestrate/flow/flow-construct/test_flow_except.py
**ToDo:**
**Worker:**
Don't throw our ExecutorFailedToLoad exception, instead only show the actual cause of the problem to the user.
<details>
<summary>Before</summary>
````
Traceback (most recent call last):
File "/home/johannes/Documents/jina/jina/jina/serve/runtimes/request_handlers/data_request_handler.py", line 48, in _load_executor
self._executor: BaseExecutor = BaseExecutor.load_config(
File "/home/johannes/Documents/jina/jina/jina/jaml/__init__.py", line 753, in load_config
return JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)
File "/home/johannes/Documents/jina/jina/jina/jaml/__init__.py", line 175, in load
r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
File "/home/johannes/Documents/jina/githubeverything/lib/python3.8/site-packages/yaml/ …
```
=> fix: better error messages when flow fails to start

extra-requirements.txt, jina/resources/extra-requirements.txt
Prometheus client should be a core dependency otherwise we can't monitor executor running in k8s
=> fix(dependency): prometheus client should be a core dependency

jina/orchestrate/flow/base.py, jina/serve/networking.py, tests/docker_compose/test_docker_compose.py
Goals:
Problem when using `to_docker_compose` of a Flow, the gateway deployment addresses to the Executor replicas is not properly set.
This PR fixes it.
Logic is:
- Local and Docker-compose: Gateway connects directly to each replicas doing the load balancing
- K8s: Gateway connects to a single address corresponding to the LinkerD or lstio load balancer
=> fix: fix configuration of addresses in docker compose

jina/orchestrate/pods/__init__.py, tests/integration/runtimes/test_runtimes.py
Goals:
The Pod does not set the runtime process as `daemon` so that `Executors` can leverage inner multiprocessing
=> fix: pod does not start runtime process as daemon

jina/serve/networking.py, jina/serve/runtimes/worker/__init__.py, tests/k8s/test_graceful_request_handling.py
This PR makes the termination of a Pod in Kubernetes Graceful. I also enabled the tests, which were failing before. With this PR there will be no requests lost if a Kubernetes Pod is terminated. Outside of Kubernetes this does not work, because we have no way of removing the dead replica.
The change is actually simple: When a Pod is terminated, its outstanding grpc calls will be cancelled by the server. This is a specific gRPC error. This error is caught now and the request is retried. The retry will then hit one of the remaining Pods. 
This closes [4626](https://github.com/jina-ai/jina/issues/4626)
=> feat: graceful shutdown

jina/hubble/helper.py, jina/hubble/requirements.py, tests/unit/hubble/test_helper.py
Goals:
To allow the following URI or VCS requirements can be parsed correctly:
```
git+https://github.com/huggingface/transformers.git
git+https://github.com/patil-suraj/vqgan-jax.git
git+https://github.com/borisdayma/dalle-mini.git
```
=> fix: parsing requirements of executor

extra-requirements.txt, jina/resources/extra-requirements.txt
Goals:
Fix the conda recipe building
=> fix: fix grpcio-reflection version

cli/autocomplete.py, docs/fundamentals/executor/hub/push-executor.md, jina/hubble/hubio.py, jina/parsers/hubble/push.py
Goals:
- Allow user to push executor with immutable tags to Jina Hub using the --immutable-tag option.
- Document this new feature inside the docs
Tested locally.
Code changed by this pr is not covered in automated tests.
Initially suggested by @deepankarm via https://github.com/jina-ai/hubble/issues/371
https://jinaai.slack.com/archives/C023A7RAPGR/p1649245281097999
=> feat: immutable tags for executors

jina/orchestrate/flow/base.py, tests/integration/monitoring/test_monitoring.py, tests/unit/orchestrate/flow/flow-construct/test_flow_monitoring.py
Right  now ( jina 3.3.18) when doing 
```python
Flow(monitoring=True).add(uses='jinahub//SimpleIndexer')
```
the monitoring is not enable on the executor
to enable it we need to to :
```python
Flow(monitoring=True).add(uses='jinahub//SimpleIndexer',monitoring=True)
```
it should be the other way around, we monitoring is set to True on the Flow level all of the executor should inherit from it unless we precisely disable it by doing
```python
Flow(monitoring=True).add(uses='jinahub//SimpleIndexer',monitoring=False)
```
=> feat: inherit monitoring arg from Flow

docs/_static/source-in-links.js, docs/conf.py
Goals:
- find referrals from docs website to other sites in jina ecosystem
=> docs(tracking): update refer links to other docs with utm_source

jina/__init__.py, jina/serve/executors/__init__.py, jina/serve/executors/decorators.py, tests/integration/monitoring/test_executor.py, tests/integration/monitoring/test_monitoring.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py
Follow up of https://github.com/jina-ai/clip-as-service/pull/674
Goal:
Having an decorator to monitor internal method of an Executor
```python
class DummyExecutor(Executor):
@requests(on='/foo')
def foo(self, docs, **kwargs):
self._proces(docs)
self.proces_2(docs)
@monitor(name='metrics_name',  documentation='metrics description')
def _proces(self, docs):
...
@monitor()
def proces_2(self, docs):
...
```
=> feat: add a decoratator for monitoring method

jina/serve/executors/__init__.py, jina/serve/runtimes/gateway/grpc/__init__.py, jina/serve/runtimes/gateway/http/app.py, jina/serve/runtimes/gateway/request_handling.py, jina/serve/runtimes/gateway/websocket/app.py, jina/serve/runtimes/head/__init__.py, jina/serve/runtimes/request_handlers/data_request_handler.py, jina/serve/runtimes/worker/__init__.py, tests/integration/monitoring/test_executor.py, tests/integration/monitoring/test_monitoring.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py
We need a specific name on each endpoint so that we can differentiate them. For example we need to differentiate the metrics coming from the executors from the one coming from the gateway.
Therefore we need to add a common label on every endpoint with the name of the pod.#
=> feat: add runtime name as label for monitoring

jina/jaml/__init__.py, tests/unit/jaml/invalid.yml, tests/unit/jaml/test_type_parse.py
Fixes silent error when invalid YAML is passed as an Executor
=> fix: add check that jaml parses to correct class

jina/serve/runtimes/gateway/request_handling.py
The current implementation of the `receiving_request_seconds` metrics on the gateway introduce a memory leak.
We store the time when sending a request in a dict but we never release this info.
This pr fixed it by poping the value instend of accessing it
=> fix: pop the init time instead of normal access

docs/_templates/page.html
Goals:
Add a template to prevent the qabot slot elements from showing on the docs pages.
=> fix(qabot): hide the slot elements on the docs page

cli/__init__.py, jina/helper.py
=> fix: unsetenv not existing on Windows

jina/hubble/helper.py
Goals:
- `api.jina.ai` is unstable sometimes, remove this layer to get better quality. We need to maintain the old domain even we move to new domain anyway, so no worries about writing domain down directly. 
Related to: https://github.com/jina-ai/hubble/issues/434
=> feat(hubble): use fixed domain for hubble api

jina/orchestrate/flow/base.py, tests/integration/issues/github_4773/config.yaml, tests/integration/issues/github_4773/test_load_config.py, tests/integration/override_config_params/worker/test_override_config_params.py, tests/unit/parsers/test_warnings.py
fixing https://github.com/jina-ai/jina/issues/4773
Now when doing 
```python
Flow().load_config('config.yaml')
```
you got this warning 
```
UserWarning: Calling load_config from a Flow instance will override all of its initial parameters. You should probably use `Flow.load_config(...)` instead
```
=> fix: warn user when calling load config from flow instance

docs/fundamentals/flow/monitoring-flow.md, jina/serve/runtimes/gateway/request_handling.py, jina/serve/runtimes/request_handlers/data_request_handler.py, tests/integration/monitoring/test_monitoring.py
linked to https://github.com/jina-ai/jina/issues/4731
add new metrics
SKIP
=> feat: add additional metrics

jina/excepts.py, jina/serve/networking.py, jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/request_handling.py, tests/integration/runtimes/test_network_failures.py
Right now, when a replica fails (on local), the gateway will stubbornly retry to connect to that same replica, instead of trying its luck with one of the other replicas. This PR changes that, applying round robing scheduling also for retries, not just successful calls.
**ToDo:**
=> feat: smart replica retry

docs/fundamentals/executor/index.md, docs/fundamentals/executor/yaml-spec.md, docs/fundamentals/flow/index.md, docs/fundamentals/flow/yaml-spec.md
=> docs: add specification of executor and flow yaml

jina/serve/runtimes/worker/__init__.py
In the worker runtime, some of the monitoring metrics were define **after** starting the grpc server. It should be the other way around the grpc server should be launch at the end when everything is ready.
=> fix: define metrics in worker before grpc server

extra-requirements.txt, jina/resources/extra-requirements.txt
recent release in protobuf causes the following problem:
```text
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be 
regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
```
As a quick fix, we fix the protobuf version to less than 4.21
The best solution would be to regenerate proto with protoc >= 3.19.0
=> fix: fix protobuf dependency

jina/jaml/__init__.py, tests/unit/jaml/test_type_parse.py
The output of `f.save_config()` should not include `!Flow` since it is deprecated syntax and not compatible with jcloud.
=> fix: remove tag from save config yaml

jina/serve/runtimes/gateway/websocket/__init__.py, jina/serve/runtimes/gateway/websocket/app.py, tests/unit/serve/runtimes/gateway/http/test_app.py
**Goal**
Even though AWS ALB supports Websocket traffic, it can't do health checks for WebSocket. It can do health checks with HTTP protocol though -  I'm enabling the same to add WebSocket gateway support in JCloud. Now, it throws bunch of 404s since the endpoint actually doesn't exist.
This PR adds an HTTP endpoint `GET /` for `WebsocketGateway` like for `HTTPGateway` (since both are FastAPI apps on Uvicorn server). I'm not sure whether this would help other load balancers, though.
=> feat(websocket): http healthcheck endpoint

README.md
Currently, Jina NOW can not be found by our users. We should get some attention by mentioning it in the readme.
=> docs: add jina now

cli/autocomplete.py, jina/orchestrate/deployments/__init__.py, jina/orchestrate/flow/base.py, jina/parsers/orchestrate/deployment.py
Right now tls is ignored without any warning when added the a deployment
```python
from docarray import DocumentArray
f = Flow().add(tls=True, host='host.wolf.jina.ai', external=True)
```
It means than no encryption is used when using external executor even if the user thinks it is used.
With this pr the `tls` argument is correctly passed to the deployment.
It fix the issue with wolf external deployment https://github.com/jina-ai/jina/issues/4838.
=> fix: pass tls to the deployment

docs/fundamentals/executor/monitoring-executor.md, jina/serve/executors/__init__.py, jina/serve/executors/decorators.py, tests/integration/monitoring/test_executor.py, tests/unit/serve/runtimes/worker/test_worker_runtime.py
having only the possibility to monitor custom part of Executor with a decorator is a limitation. We need to have a context manager as well. See full issue here : https://github.com/jina-ai/jina/issues/4876
This pr allow developer of Executor to use custom metrics with a context manager
example:
```python
from jina import requests, Executor
from docarray import DocumentArray
def preprocessing(self, docs: DocumentArray):
...
def model_inference(self, tensor):
...
class MyExecutor(Executor):
@requests
def encode(self, docs: DocumentArray, **kwargs):
with self.monitor('preprocessing_seconds', 'Time preprocessing the requests'):
docs.tensors = preprocessing(docs)
with self.monitor('model_inference_seconds', 'Time doing inference the requests'):
docs.embedding = model_inference(docs.tensors) …
```
=> feat: custom monitoring with context manager

docs/_templates/page.html
The github social icon leads to docarray right now. It should lead to the jina repository instead.
This PR corrects the link.
=> chore: correct template link to github

docs/requirements.txt
This should un-break local docs build
=> chore: update requirement to successfully build docs on local

docs/fundamentals/jcloud/advanced.md
Goals:
- Add jcloud version related docs.
Preview: 
https://github.com/jina-ai/jina/blob/jcloud-version/docs/fundamentals/jcloud/advanced.md
=> docs: add jcloud version doc

docs/api-rst.rst
Goals:
The links in the sidebar of the API reference page were broken. This removes the sidebar until we figure out a way to fix it properly.
=> docs: remove broken api sidebar

jina/clients/base/grpc.py, jina/clients/base/helper.py, jina/clients/base/http.py, jina/clients/base/websocket.py, jina/clients/mixin.py, tests/integration/clients_extra_kwargs/test_clients_post_extra_kwargs.py, tests/unit/clients/python/test_client.py, tests/unit/clients/python/test_on_err.py, tests/unit/clients/test_helper.py
Goals:
Allow the Client to send `header` and any other `auth` information to the server to be captured by some Proxy service
=> feat: expose kwargs to Clients

jina/orchestrate/flow/base.py
In the UI the `port_monitoring` of the replicas are not shown. 
Fix the behavior and iterate over the pods to show the replicas `port_monitoring`
```python
with Flow(monitoring=True).add(name='hello', port_monitoring=9090, replicas=2) as f:
f.block()
```
Before
After
=> fix: handle replicas in ui monitoring

extra-requirements.txt, jina/resources/extra-requirements.txt
Goals:
Issue from community installing jina because of this dependency, but seems not to be used anywhere anymore
=> chore: remove lz4 reqs

docs/fundamentals/executor/hub/push-executor.md, jina/hubble/hubio.py
Goals:
Hubble API changed to respect/use secret if logged in user provided it explicitly.
And returns warning message if it happens. So with this PR, user will see warning like below:
Related https://github.com/jina-ai/hubble/pull/476, https://github.com/jina-ai/hubble/issues/431
=> fix: use secret if logged in user provided it explicitly

jina/hubble/hubio.py, tests/unit/hubble/test_hubio.py
Fix the way to generate executor name of the func hub pull
Close: https://github.com/jina-ai/hubble/issues/475
=> fix(hubble): fix the way to generate executor name of the func hub pull

docs/fundamentals/flow/add-executors.md, jina/serve/executors/__init__.py, tests/integration/v2_api/test_override_requests.py
Goals: enable mapping different endpoints to the same executor func. 
```python
from jina import Flow, requests, Executor, Document, DocumentArray, Client
class MyExec(Executor):
@requests(on='/foo')
def foo(self, docs, **kwargs):
for d in docs:
d.text = 'foo'
f = Flow().add(uses=MyExec, uses_requests={'/index': 'foo', '/search': 'foo'})
with f:
req = Client(port=f.port).post(
'/index', Document()
)
print(req[0].text)
```
raises:
```
CRITI… executor0/rep-0@76726 can not load the executor from  [07/14/22 15:35:16]
MyExec                                                                   
ERROR  executor0/rep-0@76726 KeyError('/foo') during <class  [07/14/22 15:35:16]
'jina.serve.runtimes.worker.WorkerRuntime'>                              
initialization …
```
=> fix: map multiple endpoints to same func

jina/jaml/helper.py, tests/unit/serve/executors/dummy_executor.py, tests/unit/serve/executors/metas_executors.py, tests/unit/serve/executors/test_executor.py, tests/unit/serve/executors/test_set_metas.py
Goals:
To fix the issue when using python module path in the meta `py_modules`, such as:
```python
from jina import Flow, Document
f = Flow().add(uses='!CLIPEncoder', uses_meta={'py_modules': ['clip_server.executors.clip_torch']})
with f:
r = f.post(on='/', inputs=Document(text='hello world'))
print(r.embeddings)
```
raise the following error:
```
CRITI… executor0/rep-0@26144 can not load the executor from  [07/15/22 16:09:18]
CLIPEncoder                                                              
ERROR  executor0/rep-0@26144 TypeError('stat: path should be [07/15/22 16:09:18]
string, bytes, os.PathLike or integer, not NoneType')                    
during <class                                                            
'jina.serve.runtimes.worker.WorkerRuntime'> …
```
=> fix: use python module path in pymodules

docs/fundamentals/jcloud/advanced.md
Goals:
Documentation for CPU support in jCloud.
=> docs: add jcloud cpu docs

jina/clients/base/http.py, jina/clients/base/websocket.py, jina/serve/bff.py, jina/serve/runtimes/gateway/__init__.py, jina/serve/runtimes/gateway/grpc/__init__.py, jina/serve/runtimes/gateway/http/__init__.py, jina/serve/runtimes/gateway/http/app.py, jina/serve/runtimes/gateway/websocket/__init__.py, jina/serve/runtimes/gateway/websocket/app.py, jina/serve/stream/__init__.py, tests/integration/bff/test_gateway_bff.py, tests/integration/clients_extra_kwargs/test_clients_post_extra_kwargs.py, tests/integration/gateway_bff/test_gateway_bff.py, tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py, tests/unit/serve/runtimes/gateway/http/test_app.py, tests/unit/serve/stream/test_stream.py
Goals:
First conversation starter to have an `object` that can be used by community that hides the `complexity` from `TopologyGraph` and `ConnectionPool`.
Conditions of the design:
Things to do:
=> refactor: hide tgraph, cpool and streaming under new usable api

jina/clients/base/grpc.py, jina/clients/base/http.py
Similar to https://github.com/jina-ai/jina/pull/5008, I'm adding the logging also for GRPC dry run. 
Also I'm changing the two logs from `DEBUG` to `ERROR` as they contain information that reveals non-transient issue (see below screenshot) which is critical for debugging. I figured it's more appropriate.
With log line used:
=> fix: add more logging in grpc dry run

jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/request_handling.py, jina/serve/runtimes/helper.py, tests/integration/container_runtime_args/test_container_get_args.py, tests/integration/high_order_matches/test_document.py, tests/integration/inspect_deployments_flow/test_inspect_deployments_flow.py, tests/integration/override_config_params/container/test_override_config_params.py, tests/integration/override_config_params/worker/test_override_config_params.py, tests/integration/override_executor_specific_params/test_specific_params.py, tests/integration/reduce/test_reduce.py, tests/integration/specific_executor_params/test_specific_params.py, tests/unit/orchestrate/flow/flow-orchestrate/test_flow_docarray_return.py
Solves an issue with `executor specific parameters` per Executor.
Original problem is that `request` is concurrently altered and there are issues on how they are updated before they are sent.
This problem is now solved by deepcopying the request before sending, but we have to analyze if this is the right approach since it can imply performance degradation. To solve this I added some optimizations in the code to detect when it is actually needed
Here I just want to validate this functionality would work, specially if the `__results__` handling is correct
=> fix: fix specific params problem with branches

jina/serve/runtimes/gateway/request_handling.py, tests/integration/external_deployment/test_external_deployment.py
Goals:
Fix problem trying to connect to `CaS` as External Executor with `target_executor` parameter.
Since it is a Gateway-Gateway communication, you are actually passing the target_executor also to the second gateway, and in the external Flow, the executor may not be called the same and then it does not match any and returns the Docs unchanged.
The fix is to remove target_executor from the request once it is extracte
=> fix: do not send target_executor to Executors

docs/fundamentals/client/client.md, docs/fundamentals/client/third-party-client.md, docs/fundamentals/flow/client.md, docs/index.md, docs/proto/docs.md
Right now the docs to use grpc from an other language are really shallow. 
docs to check for review : 
* https://docs-improve-client--jina-docs.netlify.app/fundamentals/client/client/ 
* https://docs-improve-client--jina-docs.netlify.app/fundamentals/client/third-party-client/
=> docs: improve grpc third party client documentation

docs/fundamentals/jcloud/resources.md
**Goals:**
Remove the undesired `Example` section from JCloud docs.
**Before**
**After**
=> docs(jcloud): fix formatting

jina/__init__.py, jina/hubble/helper.py, jina/hubble/hubapi.py, jina/hubble/hubio.py, jina/orchestrate/helper.py, jina/serve/executors/decorators.py, tests/unit/hubble/test_hubapi.py, tests/unit/hubble/test_hubio.py
Goal:
as https://jina-ai.slack.com/archives/C01UFNWG9E0/p1660213590270149 
we'd like to unify all default jina-specific directory to `~/.cache/jina`
=> refactor: unify temp path to dot cache jina

extra-requirements.txt, jina/hubble/helper.py, jina/hubble/hubio.py, jina/parsers/__init__.py, jina/resources/extra-requirements.txt, jina_cli/autocomplete.py, tests/unit/hubble/test_hubio.py, tests/unit/test_helper.py
Goals:
- refactor the hubble auth part by removing all existing related code and use `jina-hubble-sdk` as the single source of truth
- add `jina auth` to CLI
- add `jina-hubble-sdk` as one of the `core` dependency
=> refactor(hub): use hubble sdk

jina/orchestrate/flow/base.py, jina/resources/logging.default.yml, jina/resources/logging.docker.yml
Goals:
- #5055
- #5044
- Logger dependent like JCloud should create their own logger YAML config and use it via `--log-config my.yml` to avoid UX change.
- In general, the user will not expect `logger.info` supports rich markup, hence we should not turn on markup by default
=> fix: #5055

jina/serve/executors/__init__.py, tests/unit/serve/executors/test_executor.py
Goals:
Enable setting of Executor workspace directly in the Executor init:
```python
e = MyExec(workspace='/test')
```
=> fix: set workspace in executor init method

docs/fundamentals/jcloud/index.md
**Goals:**
Now that we made `monitoring` enabled by default (and enforced) for JCloud deployed Flows, we need to adjust the docs around that.
Code changes on JCloud side:
https://github.com/jina-ai/wolf/pull/309
=> docs: adjust jcloud monitoring docs

.github/workflows/cd.yml, .github/workflows/ci.yml, tests/k8s/conftest.py, tests/k8s/test_graceful_request_handling.py
closes: https://github.com/jina-ai/jina/issues/5089
after the new release in linkerd (12.2.0), it is required to do `linkerd install --crds`.
This PR adds this extra step in order to fix the failing CI tests
UPDATE:
according to [linkerd 2.12 upgrade notice](https://linkerd.io/2.12/tasks/upgrade/#upgrade-notice-stable-2-12-0), kubernetes 1.21 is required
Since we depend on pytest-kind and it can only install kuberentes 1.20, we decide to downgrade linkerd instead.
=> ci: downgrade linkerd version in CI

docs/fundamentals/flow/monitoring-flow.md
Fix failed and successful request count metric names in the documentation
=> docs: fix metrics names

tests/integration/monitoring/test_manual_flow.py, tests/integration/monitoring/test_monitoring.py
This PR aim at fixing the flakyness of the CI in the `tests/integration/monitoring` folder. Indeed some test seems to be hanging. Flakyness as been probably introduce (or discover) with this PR https://github.com/jina-ai/jina/pull/5079 because of one test using process.
=> fix: remove flakyness of monitoring integration tests in CI

tests/unit/orchestrate/flow/flow-async/test_asyncflow.py
This PR fixes a test that asserts async flow and an async task run in parallel and optimize timing
However, the test also measures the flow construction and deconstruction which might exceed the 10s threshhold.
This PR excludes the construction and deconstruction from the measurements and lowers the threshhold.
closes: https://github.com/jina-ai/jina/issues/5113
=> test: fix test  concurrent async flow

docs/fundamentals/jcloud/index.md
The linking to `jc status` is broken, this PR is to fix it.
=> docs(jcloud): fix jc status link

extra-requirements.txt, jina/resources/extra-requirements.txt
Following latest grpc release (1.48.1), [CI tests start to hang forever and fail](https://github.com/grpc/grpc/issues/30843).
This appears to be related with pytest, multiprocessing since the latest release introduces [changes to forking](https://github.com/grpc/grpc/pull/30605).
This PR will cap grpcio version until compatibility is fixed.
=> fix: cap grpc version

tests/k8s/test_graceful_request_handling.py, tests/k8s/test_k8s.py, tests/k8s/test_k8s_failures.py
Fixes CI problems with K8s. When the `return_responses` param was deprecated these tests were not properly adapted
=> test: fix k8s tests return responses params

extra-requirements.txt, jina/resources/extra-requirements.txt
Fix docarray version in order to pass `graphql` tests
=> fix: set minimal docarray dependency

jina/hubble/hubio.py
`jina hub new` and selecting `torch-gpu` as Dockerfile template will remove the line that install jina (this [line](https://github.com/jina-ai/jina/blob/1df9b45919b5d24cd0d61dbcaec633c43c2e02bc/jina/resources/executor-template/torch.Dockerfile#L12)) 
This is because of this [line](https://github.com/jina-ai/jina/blob/1df9b45919b5d24cd0d61dbcaec633c43c2e02bc/jina/hubble/hubio.py#L217) in hubble parsing
=> fix: gpu dockerfile template include now jina install

extra-requirements.txt, jina/resources/extra-requirements.txt
in protobuf==3.19.5 the following fails:
```shell
python -c "from google.protobuf.pyext.cpp_message import GeneratedProtocolMessageType"
```
```text
ImportError: cannot import name '_message' from 'google.protobuf.pyext'
```
Thus, we increase min protobuf version due to incompatibility
=> fix: increase minimum protobuf version

extra-requirements.txt, jina/resources/extra-requirements.txt
Pin docarray version so that new column syntax is accepted by default
=> fix: pin docarray version for new column syntax

docs/fundamentals/flow/when-things-go-wrong.md
**Goals:**
- resolves #5168
- Add section to explain the usage of the `exit_on_exceptions` argument for automatically restarting k8s Executor deployments on exceptions.
=> docs: add section for exit_on_exceptions argument

docs/fundamentals/executor/executor-methods.md
ATM the documentation on the __return__ behavior is not clear
small documentation improvement
=> docs: clarify __return__ behavior in parameters

docs/fundamentals/client/client.md
closes: https://github.com/jina-ai/jina/issues/5192
Currently it's not clear to users that the GRPC Client cannot be used in multi-threaded environment like http servers or so.
This pr  mentions that the client can only be used in a single thread and users either have to use 1 thread (use multi processing for servers instead) or use another protocol like http.
=> docs: document grpc client limitation

jina/logging/logger.py, jina/resources/logging.json.yml
**Goals:**
Resolves #5186 - Enable structured logging (JSON) for Executors & Gateway. 
- Since in K8S, we essentially run commands, 1st 2 will be relevant for JCloud. I used the [default keys with `JsonFormatter`](https://github.com/jina-ai/jina/blob/60e9b8de6f5a6f8927ac16ff67d05d66ebf21a23/jina/logging/formatter.py#L26-L40), we should customize them according to the alerting needs @tarrantro. 
- The Flow example demonstrates, stack traces are tracked properly.
- The table with args & values can easily be removed by skipping `console.print(param_str)` if `JINA_LOG_NO_COLOR` is set, but there's no way to check what args are passed.
https://github.com/jina-ai/jina/blob/9c6740ce4dfea5f02233f3455d098233648547a3/jina_cli/__init__.py#L61-L63
```bash
$ export JINA_LOG_CONFIG=json …
```
=> feat(logs): enable json logging

docs/fundamentals/gateway/index.md
**Goals**
Clarify confusion between HTTP endpoints and Executor endpoints
=> docs: clarify exec endpoint usage in http

jina/serve/runtimes/gateway/http/models.py
Fix compatibility with python backend in protobuf.
In our code base, we depend directly on cpp or udp implementation for protobuf and python backend is not supported
=> fix: fix compatibility with protobuf python backend

jina/serve/runtimes/asyncio.py, jina/serve/runtimes/gateway/__init__.py
Currently, we only define readiness check in AsyncNewLoopRuntime which just applies a grpc health check test.
However, the GatewayRuntime which can also be an http or websocket server, does not override this behavior.
We override this and refactor code in AsyncNewLoopRuntime in order to correctly re-use this function
=> refactor: separate gateway and asyncio runtime readiness checks

jina/resources/logging.default.yml
original issue : https://github.com/jina-ai/jina/issues/5241
Atm the rich formatter invoke the rich traceback with a limited width which make it difficult to read traceback coming from Executor:
ex 
<details>
```bash
ERROR  executor0/rep-0@183551 ZeroDivisionError('division by [10/05/22 11:26:23]
zero')                                                                   
add "--quiet-error" to suppress the exception                           
details                                                                  
╭──────── Traceback (most recent call last) ────────╮                    
│ /home/sami/Documents/workspace/Jina/jina/jina/se… │                    
│ in process_data                                   │                    
│                                                   │ …
```
=> fix: disable rich traceback in logging

jina/logging/logger.py
**Goals:**
lambda functions cannot be pickled so is not convenient to have them as part of `logger`.
=> fix: avoid having a lambda in logger

docs/fundamentals/flow/add-executors.md, docs/fundamentals/flow/create-flow.md, docs/fundamentals/flow/health-check.md, docs/fundamentals/flow/index.md, docs/fundamentals/flow/monitoring-flow.md, docs/fundamentals/flow/topologies.md, docs/fundamentals/flow/when-things-go-wrong.md, docs/fundamentals/flow/yaml-spec.md
Clean up of docs, including spelling, grammar, clarity, consistency, etc.
- docs(flow): rm outdated video, clean up
- docs(flow): clean up
=> docs(flow): clean up

.github/workflows/force-docker-build.yml, .github/workflows/force-release.yml, scripts/release.sh
1. Allow release to be made by any branch in order to enable hot fixes from the past.
2. Push docker images for pre releases
closes: #5266
1. create a branch "in the past", implement your hotfix on that branch
3. in `jina./__init__.py` set the version number that you wish to release
4. run the action `manual release` from your hotfix branch, using the dropdown menu. A relase will be made, tag will be created, and version will be bumped. 
5. merge your hotfix branch back into master.
This modified action can be tried out (without actually releasing anything) here: https://github.com/jina-ai/jina-test-ci
We already push to docker hub for every merge on master, now we also provide a separate tag for every such pre-release.
You can try out the script that produces these tags, by running this …
=> ci: allow release from any branch

docs/how-to/flow-switch.md
In #5287 I mangled some restructuredtext syntax. This PR fixes that
**Goals:**
- Fix my past mistake and beg forgiveness
=> docs(flow-switch): fix broken restructuredtext syntax

.github/workflows/build-old-docs.yml, .github/workflows/force-docs-build.yml, .github/workflows/tag.yml, docs/_templates/sidebar/brand.html, docs/_versions.json, scripts/prepend_version_json.py, scripts/release.sh
Goals:
Docs Changes:
- Added a version selector to the sidebar in `docs/_templates/sidebar/brand.html`.
CI changes:
- Updates the `Manual Docs Build` workflow (`.github/workflows/force-docs-build.yml`).
- This can be run whenever the docs are updated.
- Changed some steps to be compatible with the new folder structure introduced by versioned docs
- Increased modularity of steps to increase separation of concerns as well as increase visibility on time taken for each concern.
- Decreased time taken to fetch code by changing fetches to shallow (depth 1)
- Added the `Build old docs` workflow (`.github/workflows/build-old-docs.yml`)
- This should be run when a new release is created (because there will be a new old release)
- The workflow will build the docs for all the versions specified in …
=> docs: add versioned docs

.github/workflows/force-docs-build.yml
**Goals:**
- Resolves https://github.com/jina-ai/jina/actions/runs/3330903483/jobs/5509997880#step:8:14
- Bash somehow doesn't evaluate the previous syntax correctly. It works on zsh, just not bash.
=> ci: fix move docs that did not exist

.github/workflows/force-docker-build.yml
Docker build/push is failing right now, this should fix it by properly separating the different tags that we want to push
=> ci: fix docker build and push

jina/clients/base/grpc.py
=> fix: nicer error message for rpc errors

jina/serve/runtimes/request_handlers/worker_request_handler.py
Pure refactoring PR, pulling the metrics collection for Prometheus into separate methods.
=> refactor: put metric collection in helper methods

jina/serve/instrumentation/__init__.py
**Goals:**
- Fix bad practice when using defaults in function
Non-constants should not be used as defaults in python methods. This is because they are passed by reference, leading to synced mutation of any objects created under the default. The code snippet below illustrates this effect:
Code:
```python
from typing import Dict 
class Meow:
def __init__(self, arg: Dict[str, str] = {}) -> None:
self.arg = arg
def __repr__(self) -> str:
return f"{self.__class__.__name__}(arg={self.arg})"
a = Meow()
b = Meow()
a.arg['Dog'] = "Woof"
print(a)
print(b)
b.arg['Pig'] = "Oink"
print(a)
print(b)
```
Output:
```terminal
Meow(arg={'Dog': 'Woof'})
Meow(arg={'Dog': 'Woof'})
Meow(arg={'Dog': 'Woof', 'Pig': 'Oink'})
Meow(arg={'Dog': 'Woof', 'Pig': 'Oink'})
```
As you can see, the two objects have their …
=> fix: metric timer initialization with bad default

jina/serve/instrumentation/__init__.py, tests/unit/serve/instrumentation/test_instrumentation.py
**Goals:**
The current decorator behaviour for MetricsTimer does not correctly save the labels assigned to the histogram.
This PR fixes this.
An example of the problem is in the tests.
The previous implementation would fail on the line:
```python
assert labels == histogram_metric['data']['data_points'][0]['attributes']
```
=> fix: new timer should keep labels

jina/proto/build-proto.sh
=> chore: update docker image tags and info to build locally

extra-requirements.txt, jina/resources/extra-requirements.txt
**Goals:**
Recent changes to `hubble.login()` un-intentionally removed the functionality of automatically opening the browser during the login process. The latest release of hubble sdk fixes that (https://github.com/jina-ai/jina-hubble-sdk/pull/103)
- resolves https://github.com/jina-ai/jina-hubble-sdk/issues/101
- automatically opens the browser during the login process where possible
=> chore: bump hubble sdk

jina/serve/networking.py, tests/unit/serve/instrumentation/conftest.py, tests/unit/serve/instrumentation/test_gateway_metric_labels.py, tests/unit/serve/instrumentation/test_networking_histograms.py
=> feat: add deployment label in grpc stub metrics

jina/serve/networking.py, jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/head/__init__.py, jina/serve/runtimes/request_handlers/worker_request_handler.py, tests/integration/runtimes/test_runtimes.py
**Goals:**
- resolves #5336
- ~[ ] add the total number of shards and the number of failed shards to the metadata~. Client side communication needs to be implemented as part of https://github.com/jina-ai/jina/issues/5349.
=> feat: capture shard failures in the head runtime

extra-requirements.txt, jina/resources/extra-requirements.txt
minimum prometheus client version is 0.12.0
prior to that, `pytest tests/integration/monitoring/test_request_size.py::test_request_size_increasing` will fail
=> fix: add minimum prometheus client version

docs/fundamentals/flow/remarks.md
**Goals:**
This PR adds tips for using multiprocessing fork in macOS.
Basically, Apple has changed the usage of `fork()` and `exec()` of Objective-C since MacOS 10.13. [Read here](http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html).
This may cause Flow to hang at starting stage.
This PR add a fix to the issue by setting `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
=> docs: add tips for using multiprocessing fork in macos

jina/serve/networking.py, jina/serve/runtimes/head/request_handling.py
In case of some Exceptions, the count of pending requests and some stats related were not properly decremented
=> fix: decrement requests count in case of exception inside HeadRuntime

jina/orchestrate/deployments/config/docker_compose.py, jina/orchestrate/deployments/config/k8s.py, tests/docker_compose/test_docker_compose.py, tests/k8s/test_k8s.py
When dumping a flow to docker compose or k8s, the uses_with parameter is ignored because it's in the taboo list.
This PR ensures the uses_with param actually is dumped and tests this behavior
=> fix: dump uses_with for gateway in k8s and docker compose

jina/clients/base/grpc.py, tests/unit/clients/python/test_client.py
When using max_attempts parameter in the client, the grpc retry configuration is configured with wthe wrong format of the multiplier parameter.
This PR fixes this behavior.
=> fix: fix multiplier format when using max attempts

docs/fundamentals/client/client.md, jina/clients/base/grpc.py, jina/clients/base/helper.py, jina/clients/base/http.py, jina/clients/base/websocket.py, jina/clients/mixin.py, jina/serve/runtimes/gateway/grpc/gateway.py, jina/serve/runtimes/gateway/http/__init__.py, jina/serve/runtimes/gateway/http/app.py, jina/serve/stream/__init__.py, jina/serve/streamer.py, jina/types/request/data.py, tests/integration/gateway_streamer/test_gateway_streamer.py, tests/integration/test_return_order/test_return_order.py, tests/unit/serve/stream/test_stream.py
**Goals:**
Try returning in the order of requests from Streamer
=> feat: add option to return in order in client and streamer

extra-requirements.txt, jina/resources/extra-requirements.txt
Docarray 0.19.0 need hubble sdk >= 0.24 and jina neeed ==0.24 lets unpin it.
This pr followed up the PR that was merge to do the hotfix https://github.com/jina-ai/jina/pull/5411
=> fix: unpin hubble sdk version

jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/request_handling.py
**Goals:**
Protect for the case where the deployment is not in the endpoint dictionary
=> fix: protect when deployment not in gathering endpoints dictionary

jina/orchestrate/flow/base.py, tests/unit/orchestrate/flow/flow-construct/test_flow.py, tests/unit/orchestrate/flow/flow-construct/test_flow_multiprotocol.py
Prior to this PR, using plural aliases for port and protocol doesn't work properly (mainly not correctly returned in Flow API)
This PR fixes the behavior and adds tests
=> fix: fix multi protocol gateway when using ports and protocols aliases

jina/orchestrate/pods/container.py
The port mapping for gateway is wrongly generated. This bug is hidden because net mode host is usually used.
However, under certain environments where the net mode is disabled, the port mapping is generated and the gateway cannot be started.
This PR takes the new multi protocol format in consideration when generating the port mapping for the gateway.
=> fix: fix custom gateway container port

.github/workflows/ci.yml, .github/workflows/nightly-tests.yml
Signed-off-by: Sami Jaghouar <sami.jaghouar@hotmail.fr>
It might happen that jina docarray hubble-sdk and jcloud are in conflict on the dependency. This is not intended and we should check before it happen
Add a test in CI to install the current commit with all of the latest version
=> chore: add install ecosystem latest version test to ci

jina/checker.py, jina_cli/__init__.py, tests/unit/test_cli.py
**Goals:**
- resolves #5474 
- remove jina logo printing for the `ping` command
- move some network check logging to debug logging.
=> feat: silence or minimize output of jina ping command

extra-requirements.txt, jina/orchestrate/deployments/__init__.py, jina/resources/extra-requirements.txt
**Goals:**
Use hubble-sdk to determine if a uses URI is in docker in sandbox ... etc ...
=> feat: update hubble-sdk

.github/workflows/force-docker-build.yml, RELEASE.md, docs/get-started/install/troubleshooting.md
build python 3.10 and 3.11 as default jina docker images and make 3.8 the default jina docker image
=> ci: build python 3.10 and 3.11 as default jina docker images and make 3.8 the default jina docker image

docs/fundamentals/flow/remarks.md, docs/get-started/install/troubleshooting.md, setup.py
Egg info setup mode does not have a post install command associated with it in setup.py (unlike `install` and `develop`).
This means, jina post install commands will not be executed in some cases (includes autocompletes, setting needed environment variables,...).
This PR adds an egg info post install command to handle this case.
=> fix: add egg info post install command for egg info setup mode

jina/serve/runtimes/gateway/http/app.py, jina/serve/runtimes/gateway/http/fastapi.py
fix: suppress warning for http gateway about health check
After introducing automatic health check installation for fast api gateways, we added a warning in case the health check endpoint already exists. The HTTPGateway was not updated to leave the health check for automatic installation. Thus a warning is always raised.
This PR fixes this issue by removing the health check in http gateway
=> fix: suppress warning for http gateway about health check

jina/serve/runtimes/asyncio.py, jina/serve/runtimes/gateway/__init__.py
This PR makes the GatewayRuntime send a special telemetry event for gateway.
An event with name `start_gateway` is sent along with the gateway class and the protocol used.
**Note:**
A more efficient way would be to send information from gateway runtime only once but this means moving send_telemetry_event from init to async_setup
=> chore: send telemetry event before starting gateway object

tests/unit/serve/instrumentation/test_networking_histograms.py
Recent release (https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.15.0) from open telemetry sdk introduces a small breaking change which breaks our CI.
This PR adapts the existing test.
I believe the test should be just removed
=> test: fix histograms monitoring test

docs/redirects.txt
URLs on Jina AI Cloud currently point to deprecated URLs and cause 404s. This adds redirects to fix that.
=> fix: jina ai cloud redirects

jina/serve/stream/__init__.py, jina/serve/stream/helper.py, tests/unit/serve/stream/test_stream.py
**Goals:**
Refactor do not use run_in_executor
=> refactor: avoid run in executor creating threads

jina/serve/gateway.py, jina/serve/runtimes/gateway/grpc/gateway.py
**Goals:**
Make the `GRPCGateway` be the one implementing the methods, so that we can have the CustomGateway developer inherit from it
=> refactor: make server link to gateway so that custom gateway can inherit

Dockerfiles/debianx.Dockerfile
fix: install build essentials before pip install for py 3.11 on docker
=> fix: install build essentials before pip install for python 3.11 docker image

Dockerfiles/debianx.Dockerfile
fix: fix installing build essentials for python 3.11
=> fix: fix installing build essentials for python 3.11

jina/serve/runtimes/head/request_handling.py, jina/serve/runtimes/worker/request_handling.py
**Goals:**
Why does it need to be reversed?
=> refactor: simplify get docs from requests

jina/helper.py, jina/serve/runtimes/gateway/composite/gateway.py, tests/unit/orchestrate/flow/flow-construct/test_flow_multiprotocol.py
=> fix: multi protocol gateway supports monitoring

docs/concepts/jcloud/yaml-spec.md
**Goals:**
- documents the `retain` `jcloud` argument
=> docs(jcloud): added documentation for retain

docs/concepts/executor/serve.md, jina/orchestrate/deployments/__init__.py, tests/integration/deployments/test_deployment.py, tests/integration/reload/test_deployments_reload.py
based on: https://github.com/jina-ai/jina/pull/5574
closes: https://github.com/jina-ai/jina/issues/5551
=> feat: add client to deployment

jina/parsers/__init__.py, jina/parsers/orchestrate/pod.py
chore: use hubble pull mixin parser
There are 2 imports of `mixin_hub_pull_options_parser` the first comes from jina and the other comes from hubble.
However, as isort's behavior changes from machine to machine, the order might change and therefore the used parser changes. This results in arguments like `prefer_platform` appearing and disappearing from PR to PR.
This PR keeps only one parser mixin
=> chore: use hubble pull mixin parser

jina/clients/base/grpc.py, jina/serve/networking.py, jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/http/app.py, jina/serve/runtimes/head/__init__.py, tests/integration/runtimes/test_network_failures.py
Signed-off-by: Johannes Messner <messnerjo@gmail.com>
**Goals:**
When an external Executor/Flow is behind an API Gateway (which is the case for JCloud), but is down, then DNS resolution succeeds but a "resource" (the Exec/Flow) cannot be found, resulting in a gRPC error with `NOT_FOUND` code.
This error case was not properly handled **before,** giving output like the following:
The user had no way of knowing what part of the Flow failed.
**After** this PR, the affected deployment and its address will be displayed:
```console
ERROR  gateway/rep-0/GatewayRuntime@123711 Error while       [01/23/23 12:35:15]
getting responses from deployments: no Route matched                     
with those values                                                        
trailing_metadata=Metadata((('date', …
```
=> fix: add proper error message to not-found errors

docs/concepts/jcloud/yaml-spec.md
Ref: https://jinaai.slack.com/archives/C03434J5BND/p1674562487625879?thread_ts=1674560596.701899&cid=C03434J5BND
Signed-off-by: Alex C-G <alexcg@outlook.com>
**Goals:**
- ...
- ...
- ...
- ...
=> docs(jcloud): use 1 gpu in example bc thats more stable

.github/workflows/ci.yml, jina/clients/base/__init__.py, jina/orchestrate/flow/base.py
**Goals:**
- resolves #5545 
- Add instrumentation teardown method to `BaseClient` so that the relevant tracer and metrics provider are correctly cleaned up.
- This is required because the tracer/metrics exporter starts a daemon thread to export metrics data in batches.
- The daemon thread is cleaned up using the `shutdown` method or if the program exits using the `atexit` module.
- The client teardown method is required especially for the test suite because every Flow that is started, creates a client on every `post` method which in turn instantiates a unique tracer/meter provider. The Flow context manager is not cleaning up the instrumentation resources created by the client which would leave open a lot of daemon threads until the test execution completes. 
- The Flow now lazily creates …
=> fix: clean up open telemetry resources in the Flow context manager exit procedure

jina/helper.py, jina/orchestrate/flow/base.py, jina/orchestrate/orchestrator.py
**Goals:**
Task from rich local in the thread stack
=> refactor: small refactor in threads for waiting Flow readiness

jina/orchestrate/pods/container.py, tests/unit/orchestrate/pods/container/custom-gateway/dummy_gateway.py, tests/unit/orchestrate/pods/container/test_container_pod.py
In case a custom gateway is started using the container pod, Jina will not pass some arguments to the container entrypoint (due to differences between a normal pod and a gateway pod).
This means that if a Gateway implementation needs to know its protocol (for instance, the composite gateway), the overridden protocol will not reach the runtime.
This PR fixes this issue and adds coverage in the tests
=> fix: pass extra arguments to gateway runtime with container pod

docs/concepts/jcloud/yaml-spec.md
**Goals:**
- add documentation for jcloud executor availability
=> docs: add jcloud executor availability parameters

jina/orchestrate/deployments/__init__.py, jina_cli/autocomplete.py, tests/integration/rr_cuda/test_rr_cuda.py
**Goals:**
What is promised in this documentation section (https://docs.jina.ai/concepts/flow/scale-out/#replicate-on-multiple-gpus) does not work when CUDA_VISIBLE_DEVICES env var is not provided in env args
Should solve #5653  and perhaps #5652
=> fix: fix usage with CUDA_VISIBLE_DEVICES

docs/concepts/gateway/customization.md, jina/excepts.py, jina/serve/runtimes/gateway/grpc/gateway.py, jina/serve/runtimes/gateway/http/app.py, jina/serve/runtimes/gateway/websocket/app.py, jina/serve/streamer.py, tests/integration/gateway_streamer/test_gateway_streamer.py, tests/unit/exceptions/test_exceptions.py, tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py, tests/unit/yaml/dummy_fastapi_gateway.py
**Goals:**
- resolves #5646 
- rename existing `stream` method that implements the gRPC Call stream method to `rpc_stream`.
- create a new `stream` method that accepts an request iterator and yields a tuple of response and the underlying Executor error.
- The `ExecutorError` class is used to wrap the `jina_pb2.StatusProto.ExceptionProto` information so that the user can raise the exception if necessary.  
- The new `stream` method doesn't catch all types of exceptions. Exceptions from the`stream` method will be raised.
=> feat: refactor streamer.stream method to yield reponse and executor error

jina/serve/executors/__init__.py
remove warning with this code :
```python
from typing import Optional
from jina import Executor, Flow, requests
from docarray import DocumentArray, Document
class MyExec(Executor):
@requests
def foo(self, docs: DocumentArray, **kwargs):
return docs
with Flow().add(uses=MyExec) as f:
f.post('/', inputs=Document())
```
=> fix: remove warning when return type hint is none in exec

jina/serve/executors/__init__.py
fix warning typo
`itas` -> `it as`
=> fix: fix warning typo

jina/exporter.py, jina/orchestrate/deployments/__init__.py, jina/parsers/export.py, jina_cli/api.py
**Goals:**
Align CLI of Flow and Deployment
closes: https://github.com/jina-ai/jina/issues/5671
=> feat: changes in CLI for Deployment

docs/cloud-nativeness/opentelemetry.md
since jcloud supports opentelemetry tracing (https://github.com/jina-ai/jina/pull/5688/), it doesn't make sense to state open telemetry is not support in jcloud
=> chore: remove stale section about opentelemetry

jina/orchestrate/pods/container.py
When an Executor container image is executed and the image does not support AMD architecture while the host machine uses MacOS (Darwin), the following warning will appear to the user:
=> chore: add warning when architectures do not match

README.md
In [Slack](https://jinaai.slack.com/archives/C0392P55FMZ/p1677161554788019?thread_ts=1677160828.660709&cid=C0392P55FMZ) it was mentioned that distinction between Flow and Deployment is confusing. I'm attempting to clear that up.
**Goals:**
- Make difference between Deployment and Flow clearer
=> docs(readme): make flow and deployment difference clearer

jina/serve/gateway.py, jina/serve/runtimes/gateway/composite/gateway.py, jina/serve/runtimes/gateway/request_handling.py, jina_cli/api.py, tests/integration/instrumentation/test_flow_instrumentation.py, tests/unit/orchestrate/flow/flow-construct/test_flow_multiprotocol.py
fix: composite gateway tracing support
before the PR, doing `jina gateway --protocol HTTP GRPC --port 8081 8085 --tracing` should result in an error
```grpc._cython.cygrpc.Channel.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__```
=> fix: composite gateway tracing support

jina/logging/logger.py, scripts/get-openapi-schemas.py, tests/unit/logging/test_logging.py
**Goals:**
- enable root logging always to allow DEBUG logging of other dependencies.
The current JINA_LOG_LEVEL controls the log level of the `JinaLogger`. Debug logging of other dependencies like urllib3 can be enabled by adding `logging.get_logger('urllib3').setLevel(logging.DEBUG)` at start of the Flow when running locally. This of course has limitations when deploying Gateway & Executors to the cloud.
=> fix: enable root logging always

README.md
Notebook link for building pipeline was previously broken. This PR:
- Sends user to the correct URL
- Sends user to the Flow-specific part of the notebook
=> fix(readme): pipeline notebook url

README.md
Replaced the correct links to the documentation in the scalability chapter
- resolves link issue in README
=> fix: link issues in scalability chapter

.gitignore
Every time we build the docs, we dynamically generate [the Protobuf documentation](https://docs.jina.ai/proto/docs/) in markdown (via `docs/Makefile`). It gets stored in the filesystem and it's easy to accidentally stage and push in git.
Since it's dynamically generated each time, we don't want/need it in the repo
**Goals:**
- Avoid accidentally committing unnecessary files.
=> chore: ignore dynamically generated protobuf docs

jina/orchestrate/pods/container.py, tests/unit/orchestrate/pods/container/test_container_pod.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: use container STOP so that containers running CUDA can be killed

jina/clients/base/helper.py
When querying a POST route we always try to retrive a json format from the response. It happens that we sometimes receive a plain html format, in case the json cannot be decoded, ended up in a raise of the following error: `Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8`. Adding this type of Exception in the catch allow to perform a retry.
=> feat: catch ContentTypeError for retry in POST requests

docs/concepts/jcloud/configuration.md
**Goals:**
- Fixes naming for components in `jcloud`
- Adds missing `storage` section
- Fixes description of `target` in autoscaling
=> docs(jcloud): add storage section

setup.py
**Goals:**
Set platform specific dependency on [uvloop](https://github.com/MagicStack/uvloop) in [a better way](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies), to avoid unintended and unexpected failure when being installed on platform Windows by [poetry](https://github.com/python-poetry/poetry) other than [pip](https://github.com/pypa/pip).
- resolves [langchain-issue-3260](https://github.com/hwchase17/langchain/issues/3260).
=> fix: set platform specific dependency to uvloop in a better way.

jina/clients/base/helper.py
`response.text` is a function and needs to be awaited to get the value. Error message now looks something like
**Goals:**
- ...
- ...
- ...
- ...
=> fix: return awaited text in content type

README.md
Codecov dropped I believe becasue of Stateful and golang code, no time to dig into how to hide those, so better hide the badge
=> chore: hide codecov

.github/getting-started/notebook.ipynb
The notebook was crashing due to a pinned version of protobuf (that we initially used as a workaround for a different bug).
That caused it to crash with the current version of Jina. Removing the pinned version fixes that crash
=> fix: remove outdated protobuf that caused notebook crash

README.md
Correct code snippets to use `text` field rather than storing prompt in `tags`
=> fix(readme): text not tags in code snippets

CHANGELOG.md, jina/serve/runtimes/worker/request_handling.py, tests/integration/docarray_v2/test_v2.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: monitoring validation error

jina/serve/runtimes/asyncio.py, jina/serve/runtimes/servers/grpc.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: unset http proxy

.github/workflows/cd.yml, .github/workflows/ci.yml, jina/clients/mixin.py, jina/clients/request/__init__.py, jina/serve/executors/__init__.py, jina/serve/executors/decorators.py, jina/serve/runtimes/gateway/async_request_response_handling.py, jina/serve/runtimes/gateway/graph/topology_graph.py, jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py, jina/serve/runtimes/helper.py, jina/serve/runtimes/worker/http_fastapi_app.py, jina/serve/runtimes/worker/request_handling.py, jina/serve/stream/__init__.py, jina/types/request/data.py, tests/integration/docarray_v2/test_parameters_as_pydantic.py
**Goals:**
- ...
- ...
- ...
- ...
=> feat: parameters can be described as Pydantic model for rich schema

README.md, docs/concepts/serving/executor/add-endpoints.md
docs: do not use tokenizer in client for llm streaming example
=> docs: do not use tokenizer in client for llm streaming example

.github/workflows/label-pr.yml, README.md, docs/jina-ai-cloud/login.md, docs/makedoc.sh, docs/requirements.txt
**Goals:**
- ...
- ...
- ...
- ...
=> docs: thumbnails fix

jina/orchestrate/deployments/config/k8s.py, jina/orchestrate/deployments/config/k8slib/kubernetes_deployment.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix weird host assignemnt in k8s yaml

jina/serve/consensus/run.go
**Goals:**
- ...
- ...
- ...
- ...
=> fix(consensus): free allocated CStrings

jina/serve/runtimes/gateway/graph/topology_graph.py, tests/integration/docarray_v2/test_v2.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix topology schema validation

jina/serve/runtimes/worker/batch_queue.py, jina/serve/runtimes/worker/request_handling.py, tests/unit/serve/dynamic_batching/test_batch_queue.py
This PR fixes the behavior of dynamic batching.
- It makes sure that no batch larger than preferred batch size gets into the Executor.
- It allows the requests to be returned to the client as they are processed without waiting for other requests to be ready, this should improve the average latency of the system.
=> feat: change the logic to handle dynamic batching

docs/concepts/serving/executor/dynamic-batching.md
**Goals:**
- ...
- ...
- ...
- ...
=> docs: fix dynamic batching documentation

jina/serve/runtimes/worker/batch_queue.py, tests/unit/serve/dynamic_batching/test_batch_queue.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix start timer before getting data lock

docs/tutorials/gpu-executor.md
Typo inside docs/tutorials/gpu-executor.md has been fixed.
=> docs: fix typo inside docs/tutorials

docs/concepts/client/third-party-clients.md, docs/concepts/jcloud/index.md, docs/concepts/serving/executor/hot-reload.md, docs/concepts/serving/gateway/customization.md, docs/concepts/serving/gateway/customize-http-endpoints.md
Multiple typos inside docs/concepts directory has been fixed.
=> fix typos inside docs/concepts directory

docs/cloud-nativeness/docker-compose.md, docs/cloud-nativeness/k8s.md, docs/cloud-nativeness/kubernetes.md
This PR fixes multiple typos inside of docs/cloud-nativeness directory.
=> fix: typos inside docs/cloud-nativeness

jina/serve/runtimes/gateway/graph/topology_graph.py, tests/integration/docarray_v2/test_issues.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix check graph compatibility nested types

docs/concepts/client/third-party-clients.md, docs/concepts/orchestration/yaml-spec.md, jina/schemas/__init__.py, scripts/get-openapi-schemas.py
**Goals:**
- ...
- ...
- ...
- ...
=> chore: change to schemas.jina.ai

jina/importer.py
improved cyclomatic difficulty from level C to level A in importer.py __exit__ (checked with radon)
=> refactor: simplify code in module importer

docs/concepts/serving/executor/add-endpoints.md, jina/clients/base/helper.py, jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py, jina/serve/runtimes/worker/http_fastapi_app.py, tests/integration/docarray_v2/test_issues.py, tests/integration/docarray_v2/test_streaming.py
Making a new PR that follows conventions to replace https://github.com/jina-ai/jina/pull/6091
Http streaming breaks when the input doc schema has fields which are not str, int, or float. This includes dicts, bools, and nested objects (See [Issue 6090](https://github.com/jina-ai/jina/issues/6090)). In addition it caps the input size to 2000 characters (Much less when you factor in URL encoding)
This PR changes the get endpoints to post endpoints. Not sure if we want to keep the get endpoints for backwards compatibility.
**Goals:**
- resolves [Issue 6090](https://github.com/jina-ai/jina/issues/6090)
=> fix: add and use post endpoint for streaming

extra-requirements.txt
**Goals:**
- ...
- ...
- ...
- ...
=> test: fix pytest-asyncio version

jina/serve/runtimes/worker/batch_queue.py, tests/integration/deployments/test_deployment.py, tests/integration/docarray_v2/test_v2.py, tests/integration/dynamic_batching/test_dynamic_batching.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: do not assign results if Exception

extra-requirements.txt, jina/serve/helper.py, jina/serve/runtimes/helper.py, tests/integration/docarray_v2/issues/github_6137/test_issue.py, tests/integration/issues/github_6137/test_issue.py, tests/unit/serve/runtimes/test_helper.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix subclass with DocList

jina/serve/runtimes/worker/http_csp_app.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix usage of input model

jina/clients/base/http.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: pass header kwargs to get openapi endpoints

jina/serve/executors/decorators.py, jina/serve/runtimes/worker/batch_queue.py, jina/serve/runtimes/worker/http_fastapi_app.py, tests/integration/dynamic_batching/test_dynamic_batching.py, tests/unit/serve/dynamic_batching/test_batch_queue.py, tests/unit/serve/executors/test_executor.py
Allow `flush-all` option to dynamic batching
=> feat: add flush all option to dynamic batching configuration

jina/clients/base/http.py, jina/clients/mixin.py, jina/serve/runtimes/worker/http_fastapi_app.py, jina/serve/runtimes/worker/request_handling.py, jina/types/request/data.py, tests/integration/dynamic_batching/test_dynamic_batching.py, tests/integration/inspect_deployments_flow/test_inspect_deployments_flow.py, tests/unit/serve/dynamic_batching/test_batch_queue.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: small optimization in HTTP server and client

jina/serve/runtimes/worker/batch_queue.py, jina/serve/runtimes/worker/request_handling.py, tests/integration/docarray_v2/test_v2.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: fix optim issue with optimization

jina/orchestrate/deployments/__init__.py, jina/orchestrate/flow/base.py, jina/serve/runtimes/worker/request_handling.py, tests/conftest.py, tests/docker_compose/conftest.py, tests/integration/instrumentation/conftest.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: pass allow_concurrent to runtime_args

jina/clients/base/helper.py
**Goals:**
- ...
- ...
- ...
- ...
=> refactor: handle async context manager in clientlet

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/force-release.yml, jina/clients/base/helper.py, jina/clients/base/http.py, tests/unit/clients/test_helper.py
**Goals:**
- ...
- ...
- ...
- ...
=> refactor: do not return response object

jina/clients/__init__.py, jina/clients/base/__init__.py, jina/clients/base/helper.py, jina/clients/base/http.py, jina/clients/http.py, jina/orchestrate/flow/base.py, jina/parsers/client.py, jina_cli/autocomplete.py, tests/integration/concurrent_clients/test_concurrent_clients.py, tests/integration/docarray_v2/test_singleton.py, tests/integration/streaming/test_streaming.py, tests/unit/clients/python/test_client.py, tests/unit/clients/test_helper.py, tests/unit/orchestrate/flow/flow-async/test_asyncflow.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: reuse session

jina/serve/runtimes/worker/request_handling.py, tests/integration/dynamic_batching/test_dynamic_batching.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: dyn batching configs

tests/integration/dynamic_batching/test_dynamic_batching.py
**Goals:**
- ...
- ...
- ...
- ...
=> test: add extra test for dyn batching

jina/clients/base/helper.py, jina/serve/stream/__init__.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: enrich logs

jina/clients/base/__init__.py, jina/clients/base/grpc.py, jina/clients/base/http.py, jina/clients/base/websocket.py
**Goals:**
- ...
- ...
- ...
- ...
=> fix: remove inputs state from client
